### ISSUE TITLE
Shoudn't "Check .well-known on the identity hostname" should follow redirect?

### ISSUE THREAD

**Issue by nodje** [spantaleev/matrix-docker-ansible-deploy#101]
I happen to have set the .well-known folder on an Nginx `server` directive that redirect to another server. (
So the `--tags=self-check` task chokes on the `Check .well-known on the identity hostname` task because it doesn't follow redirect.
```
- name: Check .well-known on the identity hostname
  uri:
    url: "{{ well_known_url_identity }}"
    follow_redirects: false
    return_content: true
  register: result_well_known_identity
  ignore_errors: true
```
simply making `follow_redirects: true` makes the whole of `self-check` works with my setup.

**Comment by spantaleev** [comment]
I've made some changes in 25bdc106174e23bf9.

Looks like the [Client-Server spec](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#server-discovery) doesn't mention if we should follow redirects, so I haven't enabled following for it.

For the `/.well-known/matrix/server` file, the [Server spec](https://matrix.org/docs/spec/server_server/r0.1.0.html#server-discovery) says that redirects should be followed, so we now do it.

It could be that redirects are okay for both, but since it's not in the spec, I'm reluctant to have the playbook say it's OK.

**Comment by abeluck** [comment]
@spantaleev  Not sure if I should open a new issue or just comment here.. playing it safe and commenting here.

This issue is biting us because the only sane way we could implement the client `.well-known` is with a 301 redirect. It works fine in all matrix clients we use. 

I understand not wanting to make that the default, but could you at least paramaterize it?

`roles/matrix-nginx-proxy/tasks/self_check_well_known.yml`  has

```yml
- name: Determine well-known files to check (Matrix)
  set_fact:
    well_known_file_checks:
      - path: /.well-known/matrix/client
        purpose: Client Discovery
        cors: true
        follow_redirects: none
        validate_certs: "{{ matrix_nginx_proxy_self_check_validate_certificates }}"
```

If we could introduce a `matrix_nginx_proxy_well_known_follow_redirects_override` variable, that would be super helpful, and we wouldn't have to maintain a patch.
