### ISSUE TITLE
Ma1sd not working if Nginx proxy disabled

### ISSUE THREAD

**Issue by enekonieto** [spantaleev/matrix-docker-ansible-deploy#1047]
If you set `matrix_nginx_proxy_enabled: false` searching user directory fails with `An internal server error occurred. Contact your administrator with reference Transaction #1620677698179`.

Peeking Ma1sd's logs I saw the reason:
```
(May 10 22:14:58 fosil matrix-ma1sd[1903298]: [XNIO-1 task-5] INFO io.kamax.mxisd.directory.DirectoryManager - Querying HS at http://matrix-nginx-proxy:12080/_matrix/client/r0/user_directory/search
May 10 22:14:58 fosil matrix-ma1sd[1903298]: [XNIO-1 task-5] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Transaction #1620677698179 - Unable to query the HS: I/O error: matrix-nginx-proxy: Name does not resolve)
```

Ma1sd tries to contact `matrix-nginx-proxy` but that host doesn't exist. `/matrix/ma1sd/config/ma1sd.yaml` has:
```
dns:
    overwrite:
        homeserver:
            client:
            -   name: matrix.fosil.eu
                value: http://matrix-nginx-proxy:12080
```

Fixed adding:
```
matrix_ma1sd_dns_overwrite_enabled: true
matrix_ma1sd_dns_overwrite_homeserver_client_value: "http://matrix-synapse:8008"
```
