### ISSUE TITLE
Configuration does not work well with Element Android client

### ISSUE THREAD

**Issue by kgraaf** [spantaleev/matrix-docker-ansible-deploy#1063]
When I do a fresh install of the playbook I end up with an install of synapse that works just fine on the desktop client, the web client, and FluffyChat, but Element for Android is just miserable. I've included pictures of what I see.

1. Signing in takes often 10 minutes at least
2. Once sign in has gotten to the next window, syncing can take another 5
3. Worst of all, once I'm signed in 'syncing' (the green bar) will occur constantly/randomly making actually chatting basically impossible in practice.

None of these issues occur with my matrix.org account. [This issue](https://github.com/vector-im/element-android/issues/983) seemed to be resolved by fixing configuration, so I was curious if that was the issue here. All of these problems occur on a fresh install with just one or two users and a single local (i.e. non-federated) channel. 

Element Android is v1.1.6 and the ansible playbook is the most recent version. I'm deploying on a fresh install of Debian 10 on a vultr VPS with 2GB of RAM. My hosts file is:

    [matrix_servers]
    matrix.<hostname> ansible_host=<ip_addr> ansible_port=<port> ansible_ssh_user=<sudo_user> become=true become_user=root ansible_python_interpreter=/usr/bin/python3

My vars.yaml file is:

```
matrix_domain: <base_domain>
matrix_ssl_lets_encrypt_support_email: <email>
matrix_coturn_turn_static_auth_secret: <password>
matrix_synapse_macaroon_secret_key: <password>
matrix_postgres_connection_password: <password>
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_registration_enabled: true
matrix_registration_admin_secret: <password>
matrix_ma1sd_enabled: false
matrix_mailer_enabled: false
matrix_synapse_configuration_extension_yaml: |
  limit_remote_rooms:
    enabled: true
    complexity: 1.0
```

![issues](https://user-images.githubusercontent.com/82181542/118797966-1d72b400-b86b-11eb-9feb-0f9857cd804d.jpeg)
