### ISSUE TITLE
Support for Ansible 4

### ISSUE THREAD

**Issue by theCalcaholic** [spantaleev/matrix-docker-ansible-deploy#1066]
## Description

When using the playbook with Ansible 4, there are some yaml parsing errors, e.g.:

```
TASK [matrix-bridge-mautrix-signal : Ensure mautrix-signal config.yaml installed] *******************************************************************************************************************
task path: /home/<redacted>/private/projects/matrix-docker-ansible-deploy/roles/matrix-bridge-mautrix-signal/tasks/setup_install.yml:50
fatal: [HOST_URL REDACTED]: FAILED! => 
  msg: |-
    An unhandled exception occurred while templating '{{ matrix_mautrix_signal_configuration_yaml|from_yaml|combine(matrix_mautrix_signal_configuration_extension, recursive=True) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ matrix_mautrix_signal_configuration_extension_yaml|from_yaml if matrix_mautrix_signal_configuration_extension_yaml|from_yaml is mapping else {} }}'. Error was a <class 'yaml.parser.ParserError'>, original message: while parsing a block mapping
      in "<unicode string>", line 1, column 1:
        bridge:
        ^
    expected <block end>, but found '<block mapping start>'
      in "<unicode string>", line 9, column 3:
          double_puppet_allow_discovery: true
```

## How to reproduce

1. Configure any mautrix bridge in your host vars
2. Make sure, to specify something in `matrix_mautrix_signal_configuration_extension_yaml`
3. Try to deploy using ansible 4

## Workaround/Fix

These errors can be worked around by downgrading ansible (tested with 2.10, since that's been used in my working setup on another machine) or by setting the `matrix_mautrix_*configuration` variables in multiple steps, e.g.:

```yaml
- set_fact:
    part_1: "{{ matrix_mautrix_signal_configuration_yaml|from_yaml }}"
- set_fact:
    part_2: "{{ matrix_mautrix_signal_configuration_extension_yaml|from_yaml }}"

- set_fact:
    matrix_mautrix_signal_configuration: "{{ part_1|combine(part_2, recursive=True) }}"
```

For the sake of completeness, here is the relevant section in the `defaults/main.yml` of `matrix-bridge-mautrix-signal`:

```yaml
matrix_mautrix_signal_configuration_yaml: "{{ lookup('template', 'templates/config.yaml.j2') }}"

matrix_mautrix_signal_configuration_extension_yaml: |
  # Your custom YAML configuration goes here.
  # This configuration extends the default starting configuration (`matrix_mautrix_signal_configuration_yaml`).
  #
  # You can override individual variables from the default configuration, or introduce new ones.
  #
  # If you need something more special, you can take full control by
  # completely redefining `matrix_mautrix_signal_configuration_yaml`.

matrix_mautrix_signal_configuration_extension: "{{ matrix_mautrix_signal_configuration_extension_yaml|from_yaml if matrix_mautrix_signal_configuration_extension_yaml|from_yaml is mapping else {} }}"

# Holds the final configuration (a combination of the default and its extension).
# You most likely don't need to touch this variable. Instead, see `matrix_mautrix_signal_configuration_yaml`.
matrix_mautrix_signal_configuration: "{{ matrix_mautrix_signal_configuration_yaml|from_yaml|combine(matrix_mautrix_signal_configuration_extension, recursive=True) }}"
```
