### ISSUE TITLE
Unable to disable user_directory

### ISSUE THREAD

**Issue by prostheboss** [spantaleev/matrix-docker-ansible-deploy#1115]
After adding

```
matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: true
    search_all_users: false
```

Element will still display every user on the server in the user directory, which I do not want to do.

I have looked inside the running container and I can confirm that **/data/homeserver.yaml** has indeed added the lines to the bottom, but I have no idea why I can still see the user directory, even if I set it to **enabled:false**

This is after a clean setup with no errors.
