### ISSUE TITLE
OIDC Login not working

### ISSUE THREAD

**Issue by Sirius-KiH** [spantaleev/matrix-docker-ansible-deploy#1132]
I am trying to get OIDC login working, using a self-hosted keycloak instance as identity provider following these guides:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1e46785a0d213d17524dfd4657d08a2785147f60/docs/configuring-playbook-synapse.md#synapse--openid-connect-for-single-sign-on

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1fb54a37cba126235b1688bb5e96226a65b4fe80/docs/configuring-playbook-nginx.md#synapse--openid-connect-for-single-sign-on

https://matrix-org.github.io/synapse/develop/openid.html

However, trying to login or register with keycloak redirects me to` /_matrix/client/r0/login/sso/redirect/oidc-keycloak?redirectUrl=https%3A%2F%2Fapp.element.io%2F`, which does not correctly redirect to keycloak, but redirects unto itself so that it ends up failing with too many redirects.

Is there some configuration that I missed?

**Comment by plank-tools** [comment]
Can you post your var.yaml here after replacing secrets and other confidential information?

**Comment by Sirius-KiH** [comment]
Here it is:

```
matrix_domain: "{{ vault_matrix_domain }}"
matrix_base_data_path: "{{ vault_matrix_base_data_path }}"

matrix_docker_network: "{{ vault_matrix_docker_network }}"
matrix_docker_installation_enabled: false

matrix_common_after_systemd_service_start_wait_for_timeout_seconds: 30


# SYNAPSE
matrix_synapse_enabled: true
matrix_synapse_docker_image: "matrixdotorg/synapse:v1.36.0"
matrix_synapse_max_upload_size_mb: 8
matrix_synapse_enable_registration: true
matrix_synapse_federation_enabled: false
matrix_synapse_macaroon_secret_key: "{{ vault_matrix_synapse_macaroon_secret_key }}"
matrix_synapse_user_ips_max_age: 1d
matrix_synapse_allow_guest_access: false
matrix_synapse_configuration_extension_yaml: |
  retention:
    enabled: true
#  oidc_providers:
#    - idp_id: keycloak
#      idp_name: "Keycloak SSO"
#      issuer: "https://{{ vault_keycloak_domain }}/auth/realms/{{ vault_keycloak_realm }}"
#      client_id: "synapse"
#      client_secret: "{{ vault_matrix_synapse_keycloak_client_secret }}"
#      scopes: ["openid", "profile"]
#      authorization_endpoint: "https://{{ vault_keycloak_domain }}/auth/realms/{{ vault_keycloak_realm }}/protocol/openid-connect/auth"
#      token_endpoint: "https://{{ vault_keycloak_domain }}/auth/realms/{{ vault_keycloak_realm }}/protocol/openid-connect/token"
#      userinfo_endpoint: "https://{{ vault_keycloak_domain }}/auth/realms/{{ vault_keycloak_realm }}/protocol/openid-connect/userinfo"
#      user_mapping_provider:
#        config:
#          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
#          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
#          email_template: "{% raw %}{{ user.email }}{% endraw %}"



matrix_synapse_rc_login:
  address:
    per_second: 50
    burst_count: 300
  account:
    per_second: 0.17
    burst_count: 3
  failed_attempts:
    per_second: 0.17
    burst_count: 3

matrix_synapse_database_host: "{{ vault_matrix_postres_connection_hostname }}"
matrix_synapse_database_user: "{{ vault_matrix_postres_connection_username }}"
matrix_synapse_database_password: "{{ vault_matrix_synapse_database_password }}"
matrix_synapse_database_database: "synapse"


# SYNAPSE THIRD PARTY
matrix_synapse_custom_third_party_enabled: false


# SYNAPSE ADMIN
matrix_synapse_admin_enabled: true
matrix_synapse_admin_container_self_build: false
matrix_synapse_admin_docker_image: "awesometechnologies/synapse-admin:latest"

# ELEMENT
matrix_client_element_enabled: true
matrix_client_element_docker_image: "vectorim/element-web:v1.7.31"
matrix_client_element_registration_enabled: true
matrix_client_element_roomdir_servers: []
matrix_client_element_configuration_extension_json: |
  {
  "disable_3pid_login": true,
  "defaultCountryCode": "DE",
  "settingDefaults":
    {
      "language": "de"
    },
  "disable_login_language_selector": true,
  "features":
    {
    "feature_pinning": "enable",
    "feature_presence_in_room_list": "enable",
    "feature_groups": "labs"
    }
  }

# HYDROGEN
matrix_client_hydrogen_enabled: true
matrix_client_hydrogen_version: v0.1.53

# POSTGRES
matrix_postgres_enabled: true
matrix_postgres_connection_hostname: "{{ vault_matrix_postres_connection_hostname }}"
matrix_postgres_connection_username: "{{ vault_matrix_postres_connection_username }}"
matrix_postgres_connection_password: "{{ vault_matrix_postgres_connection_password }}"
matrix_postgres_db_name: "matrix"


# SSL
matrix_ssl_retrieval_method: none


# Etherpad
matrix_etherpad_enabled: true


# NGINX
matrix_nginx_proxy_enabled: true
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_access_log_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: ''
matrix_nginx_proxy_container_federation_host_bind_port: ''
matrix_nginx_proxy_container_extra_arguments:
  - '--label "traefik.enable=true"'
  - '--label "traefik.http.routers.matrix-nginx-proxy.rule=Host(`{{ matrix_server_fqn_matrix }}`,`{{ matrix_server_fqn_element }}`,`{{ matrix_server_fqn_dimension }}`,`{{ matrix_server_fqn_jitsi }}`,`{{ matrix_server_fqn_hydrogen }}`)"'
  - '--label "traefik.http.routers.matrix-nginx-proxy.entrypoints=webs"'
  - '--label "traefik.http.services.matrix-nginx-proxy.loadbalancer.server.port=8080"'
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true


# COTURN
matrix_coturn_enabled: true
matrix_coturn_tls_enabled: false
matrix_coturn_turn_static_auth_secret: "{{ vault_matrix_coturn_turn_static_auth_secret }}"


# DIMENSION
matrix_dimension_enabled: true
matrix_dimension_access_token: "{{ vault_matrix_dimension_access_token }}"



# JITSI
matrix_jitsi_enabled: true
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_jicofo_component_secret: "{{ vault_matrix_jitsi_jicofo_component_secret }}"
matrix_jitsi_jicofo_auth_password: "{{ vault_matrix_jitsi_jicofo_auth_password }}"
matrix_jitsi_jvb_auth_password: "{{ vault_matrix_jitsi_jvb_auth_password }}"
matrix_jitsi_jibri_recorder_password: "{{ vault_matrix_jitsi_jibri_recorder_password }}"
matrix_jitsi_jibri_xmpp_password: "{{ vault_matrix_jitsi_jibri_xmpp_password }}"
matrix_jitsi_web_config_start_video_muted_after_nth_participant: 0

# MJOLNIR
matrix_bot_mjolnir_enabled: false
matrix_bot_mjolnir_access_token: "{{ vault_matrix_bot_mjolnir_access_token }}"
matrix_bot_mjolnir_management_room: "{{ matrix_bot_mjolnir_management_room }}"
```

**Comment by hungrymonkey** [comment]
@Sirius-KiH ,  A few things, you do not need to set `authorization_endpoint`, `token_endpoint`, `userinfo_endpoint`, when the endpoint is already openid. `issuer` url already contain the information
```
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
    - idp_id: keycloak
      idp_name: "Keycloak SSO"
      issuer: "https://{{ vault_keycloak_domain }}/auth/realms/{{ vault_keycloak_realm }}"
      client_id: "synapse"
      client_secret: "{{ vault_matrix_synapse_keycloak_client_secret }}"
      scopes: ["openid", "profile"]
      user_mapping_provider:
        config:
          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
          email_template: "{% raw %}{{ user.email }}{% endraw %}"
```

Did you setup your webserver properly? Your bug seems similar to the bug below.

https://github.com/matrix-org/synapse/issues/9680

**Comment by xXTim97Xx** [comment]
@Sirius-KiH did you managed to solve that issue? 
I've got the same issue as you and would like to know what you've done to solve that.

**Comment by Sirius-KiH** [comment]
Unfortunately, I have not found a solution yet.

The webserver config seems to be correct as far as I can tell

```
        location ~* ^(/_matrix|/_synapse/client|/_synapse/oidc|/_synapse/admin) {
                        resolver 127.0.0.11 valid=5s;
                        set $backend "matrix-nginx-proxy:12080";
                        proxy_pass http://$backend;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;

                client_body_buffer_size 25M;
                client_max_body_size 8M;
                proxy_max_temp_file_size 0;
        }
```

**Comment by plank-tools** [comment]
I couldn't get it working either. However, I was able to workaround this by directly editing `roles/matrix-synapse/templates/synapse/homeserver.yaml.j2` file. 

Here are my oidc settings

```yaml+
oidc_providers:
  - idp_id: keycloak
    idp_name: "My Keycloak Server"
    issuer: "https://my-keycloak-hostname/auth/realms/my-realm"
    client_id: "element"
    client_secret: "my-client-secret"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
        display_name_template: "{% raw %}{{ user.firstname }}{% endraw %} {% raw %}{{ user.lastname }}{% endraw %}"
        email_template: "{% raw %}{{ user.email }}{% endraw %}"

```

**Comment by nogweii** [comment]
I'm also running into the same issue; here is the applicable part of my host variables:

```
# configure Keycloak as my OIDC SSO
matrix_synapse_configuration_extension_yaml: |
  suppress_key_server_warning: true
  oidc_providers:
    - idp_id: keycloak
      idp_name: "Keycloak"
      issuer: "https://keycloak.example.com/auth/realms/master"
      client_id: "matrix-chat"
      client_secret: "{{ keycloak_matrix_oidc_secret }}"
      scopes: ["openid", "profile"]
      user_mapping_provider:
        config:
          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
          email_template: "{% raw %}{{ user.email }}{% endraw %}"
```

I'm getting log messages (after bumping `matrix_synapse_log_level` to _INFO_) like the following:

```
Sep 21 17:56:11 matrix-server matrix-synapse[33931]: 2021-09-22 00:56:11,176 - synapse.rest.client.login - 511 - INFO - GET-126 - Requested URI http://matrix.example.com/_matrix/client/r0/login/sso/redirect/oidc-keycloak is not canonical: redirecting to https://matrix.example.com/_matrix/client/r0/login/sso/redirect/oidc-keycloak
Sep 21 17:56:11 matrix-server matrix-synapse[33931]: 2021-09-22 00:56:11,177 - synapse.access.http.8008 - 389 - INFO - GET-126 - 100.111.235.75 - 8008 - {None} Processed request: 0.001sec/-0.000sec (0.003sec, 0.000sec) (0.000sec/0.000sec/0) 0B 302 "GET /_matrix/client/r0/login/sso/redirect/oidc-keycloak HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" [0 dbevts]
```

Something is causing the protocol information to be lost, to not make it's way to synapse.
