### ISSUE TITLE
Running behind a separate NGINX Reverse Proxy - trouble with ssl through the proxy

### ISSUE THREAD

**Issue by HeneryH** [spantaleev/matrix-docker-ansible-deploy#1136]
Can we get an ansible config for the NGINX reverse proxy described here https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md#nginx

You all got me hooked on deploying my NGINX Reverse proxy through ansible now and I can't figure out the ansible playbook for my proxy to get it to work with Matrix.

Do I do the ssl in the proxy or leave it in Matrix the way my default install had it?

If I assume the ssl will stay in matrix and then I want my proxy to just pass the 443 port data through untouched to matrix then I must have something wrong in my nginx playbook because I get sls cert errors when browsing.

This is what the /etc/nginx/sites-enabled/* config is showing in these instructions:
```
server {
    listen 443 ssl http2;   <-- how do I do the equivalent of "ssl http2" in ansible?
    listen [::]:443 ssl http2;

    # For the federation port
    listen 8448 ssl http2 default_server;   <-- I think putting two ports fails in ansible
    listen [::]:8448 ssl http2 default_server;

    server_name matrix.example.com;

    location ~* ^(\/_matrix|\/_synapse\/client) {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 50M;
    }
}
```

And this is what I am trying (and failing with) in my ansible version of above
```
---
- hosts: ansible-nginx-rp.localdomain
  become: yes
  collections:
    - nginxinc.nginx_core                           # For the open source NGINX
  roles:
    - role: nginx                                   # Installation role
    - role: nginx_config                            # Configuration role
      vars:
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          app:
            template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              matrix:
                listen:
                  listen_localhost:
                    port: 443
                server_name: matrix.me.us stats.me.us dimension.me.us element.me.us goneb.me.us hydrogen.me.us jitsi.me.us stats.me.us sygnal.me.us
                access_log:
                  - name: main
                    location: /var/log/nginx/matrix_access.log
                reverse_proxy:
                  locations:
                    main:
                   #  location: "~* ^(\/_matrix|\/_synapse\/client)"  <-- this fails
                      location: /
                      proxy_pass: http://192.168.50.54/
                      client_max_body_size: "50M"
                      proxy_set_header:
                        header_host:
                          name: Host
                          value: $host
                        X-Forwarded-Proto:
                          name: Proto
                          value: $scheme
                        X-Forwarded-For:
                          name: FwdFor
                          value: $remote_addr
```
