### ISSUE TITLE
DDNS config fails

### ISSUE THREAD

**Issue by sliwik** [spantaleev/matrix-docker-ansible-deploy#1138]
Hello,
My setup fails at Dynamic DNS config with following message:
```
TASK [matrix-dynamic-dns : Fail if no configurations specified] ************************************************************************************
fatal: [matrix.debian-lachatlondon.ddnsfree.com]: FAILED! => 
  msg: |-
    The conditional check 'matrix_dynamic_dns_domain_configurations|length == 0' failed. The error was: error while evaluating conditional (matrix_dynamic_dns_domain_configurations|length == 0): [{'provider': 'api.dynu.com', 'protocol': 'dyndns2', 'username': 'my_username', 'password': 'pASSw^0rd%', 'domain': '{{ debian-lachatlondon.ddnsfree.com }}'}]: 'debian' is undefined
  
    The error appears to be in '/Users/sliwik/Ansible/Playbooks/matrix-docker-ansible-deploy/roles/matrix-dynamic-dns/tasks/validate_config.yml': line 3, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Fail if no configurations specified
      ^ here

```

My vars.yml includes the following:
```
# DYNAMIC DNS
matrix_dynamic_dns_enabled: true

matrix_dynamic_dns_domain_configurations:
  - provider: api.dynu.com
    protocol: dyndns2
    username: my_username
    password: pASSw^0rd%
    domain: "{{ debian-lachatlondon.ddnsfree.com }}"

```

I can't really find the reason for this error. Can you please help?
Thank you.
