### ISSUE TITLE
Matrix Synapse won't start

### ISSUE THREAD

**Issue by xXTim97Xx** [spantaleev/matrix-docker-ansible-deploy#1167]
I've got a Problem starting the matrix-synapse Server.
When I'm running it with the parameters "start", synapse seems to exit every time.

This is what journalctl -fu shows me:

> sudo journalctl -fu matrix-synapse.service                                                                 
-- Logs begin at Wed 2021-06-16 05:04:10 CEST. --
Jul 07 14:14:31 *.de matrix-synapse[978563]:     self.invoke_all(
Jul 07 14:14:31 *.de matrix-synapse[978563]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 375, in invoke_all
Jul 07 14:14:31 *.de matrix-synapse[978563]:     res[name] = getattr(config, func_name)(*args, **kwargs)
Jul 07 14:14:31 *.de matrix-synapse[978563]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/oidc.py", line 40, in read_config
Jul 07 14:14:31 *.de matrix-synapse[978563]:     self.oidc_providers = tuple(_parse_oidc_provider_configs(config))
Jul 07 14:14:31 *.de matrix-synapse[978563]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/oidc.py", line 386, in _parse_oidc_provider_configs
Jul 07 14:14:31 *.de matrix-synapse[978563]:     yield _parse_oidc_config_dict(p, ("oidc_providers", "<item %i>" % (i,)))
Jul 07 14:14:31 *.de matrix-synapse[978563]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/oidc.py", line 408, in _parse_oidc_config_dict
Jul 07 14:14:31 *.de matrix-synapse[978563]:     ump_config.setdefault("module", DEFAULT_USER_MAPPING_PROVIDER)
Jul 07 14:14:31 *.de matrix-synapse[978563]: AttributeError: 'NoneType' object has no attribute 'setdefault'
Jul 07 14:14:32 *.de systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Jul 07 14:14:32 *.de systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.

It seems to be a OIDC Problem?

**Comment by aaronraimist** [comment]
What commit of the playbook are you using?

**Comment by xXTim97Xx** [comment]
I'm at commit 935967f3a60bfb499ea422d1594292d5ee0ce6f6

**Comment by aaronraimist** [comment]
I asked because the final error message looks like some old Synapse issues but I guess the rest of the traceback does not match so it is a different bug.

It does like like an OIDC problem. Can you share your `vars.yml` config file that shows your OIDC configuration? Make sure to redact the secret keys.

**Comment by xXTim97Xx** [comment]
This here is my `vars.yml`:

```

matrix_domain: example.de

matrix_ssl_lets_encrypt_support_email: 'tim@example.com'

matrix_coturn_turn_static_auth_secret: '*'

matrix_synapse_macaroon_secret_key: '*'

matrix_postgres_connection_password: '*'

matrix_jitsi_enabled: true 

matrix_jitsi_jicofo_component_secret: *
matrix_jitsi_jicofo_auth_password: *
matrix_jitsi_jvb_auth_password: *
matrix_jitsi_jibri_recorder_password: *
matrix_jitsi_jibri_xmpp_password: *

matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_jvb_container_extra_arguments:
  - '--env "DOCKER_HOST_ADDRESS=<10.0.20.20>"'

matrix_prometheus_enabled: true

matrix_prometheus_node_exporter_enabled: true

matrix_grafana_enabled: true

matrix_grafana_anonymous_access: false

matrix_grafana_default_admin_user: "th"

matrix_grafana_default_admin_password: "*"

matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true

matrix_synapse_storage_path: /opt/synapse_media_storage

matrix_synapse_ext_spam_checker_mjolnir_antispam_enabled: true


matrix_client_hydrogen_enabled: false

matrix_registration_enabled: true

matrix_registration_admin_secret: "*"


matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_signal_enabled: true

matrix_synapse_enable_registration_captcha: true
matrix_synapse_recaptcha_public_key: '*'
matrix_synapse_recaptcha_private_key: '*'


matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_synapse_configuration_extension_yaml: |
    oidc_providers:
    - idp_id: auth0
      idp_name: "Auth0"
      issuer: "*" # TO BE FILLED
      client_id: "*" # TO BE FILLED
      client_secret: "*" # TO BE FILLED
      scopes: ["openid", "profile"]
      user_mapping_provider:
      config:
        localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
        display_name_template: "{% raw %}{{ user.name }}{% endraw %}"


```
