### ISSUE TITLE
TLS not working for CoTurn

### ISSUE THREAD

**Issue by elgatosefue** [spantaleev/matrix-docker-ansible-deploy#1245]
Hi,
I am a noob setting this up but,
My vars.yml has the following variables:
!-----------------------------------------------------------------------!
matrix_coturn_tls_enabled: true
matrix_coturn_container_stun_plain_host_bind_port: ''
matrix_coturn_container_stun_tls_host_bind_port: '5349'
matrix_coturn_tls_cert_path: "/matrix/ssl/config/archive/turn.DOMAIN/fullchain1.pem"
matrix_coturn_tls_key_path: "/matrix/ssl/config/archive/turn.DOMAIN/privkey1.pem"
!-----------------------------------------------------------------------!

My turnserver.conf variables for TLS are also pointing to the same "fullchain1.pem" and "privkey1.pem" yet, when I do video-calling/voice-calling I can see the server run "3478" and not "5349" at all. 
Even though "3478" is not being at all configured within the Docker. 

Is there anything else I can share to be helped with troubleshooting?

Thank you

**Comment by elgatosefue** [comment]
Anyone available to help?

**Comment by shreyasajj** [comment]
Do you add the pem file to as an external volume as such
```
matrix_coturn_container_additional_volumes:
- src: /home/user/cert/fullchain.pem
  dst: /cert/fullchain.pem
  options: ro
- src: /home/user/cert/privkey.pem
  dst: /cert/privkey.pem
  options: ro
```
