### ISSUE TITLE
OIDC configuration in vars.yml has no effect in synapse

### ISSUE THREAD

**Issue by chThie** [spantaleev/matrix-docker-ansible-deploy#1278]
I am trying to setup OpenID Connect via my own Keycloak (as identity provider for synapse) with the playbook.
To register the running keycloak (https://auth.mydomain.com) in synapse I added the following lines to my inventory/host_vars/mydomain.com/vars.yml file:
```
matrix_synapse_configuration_extension_yaml: |
oidc_providers:
  - idp_id: keycloak
    idp_name: "Keycloak"
    issuer: "https://auth.mydomain.com/auth/realms/MyRealm"
    client_id: "synapse"
    client_secret: "a19c197a-e35c-4418-8167-de51c89d4f12"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.name }}"
```

I run the playbook with the "setup-all" and then "start" tag and then look into the matrix-synapse container.
The generated synapse config file seems to be /data/homeserver.yml.
This contains "oidc_providers: null" instead of my configuration.

So **somehow my configuration in the playbook inventory** host_vars file **does not get it's way to synapse**.

**Is this a bug or do I do something wrong?**

I was finally able to get it running by hardcoding my configuration into roles/matrix-synapse/templates/synapse/homeserver.yaml.j2, after finding this comment: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1132#issuecomment-896034255
 But that's not how it should work, right? 🙃

**Comment by aaronraimist** [comment]
@chThie Everything you want included in the configuration extension variable needs to be indented

So it should look like this:

```
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
    - idp_id: keycloak
      idp_name: "Keycloak"
      issuer: "https://auth.mydomain.com/auth/realms/MyRealm"
      client_id: "synapse"
      client_secret: "a19c197a-e35c-4418-8167-de51c89d4f12"
      scopes: ["openid", "profile"]
      user_mapping_provider:
        config:
          localpart_template: "{{ user.preferred_username }}"
          display_name_template: "{{ user.name }}"
```
