### ISSUE TITLE
Copy app service config files to Docker conf dir

### ISSUE THREAD

**Issue by wilkis3** [spantaleev/matrix-docker-ansible-deploy#133]
Hi,

If I want to use app_service_config_files I got this error:
```
Apr 10 11:15:24 HOSTNAME docker[26488]: 2019-04-10 09:15:24,086 - synapse.config.appservice - 94 - ERROR - None - Failed to load appservice from 'appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml'
Apr 10 11:15:24 HOSTNAME docker[26488]: 2019-04-10 09:15:24,087 - synapse.config.appservice - 95 - ERROR - None - [Errno 2] No such file or directory: 'appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml'
```
My host vars contains:
```
matrix_synapse_app_service_config_files: '
        - "appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml"'
```
and my hostserver.yaml file contains:
```
app_service_config_files:
- "appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml"
```

The app service config file exist and located below /opt/matrix/synapse/config.

Synapse also use the Docker OverlayFS and below /var/lib/docker/overlay2/wer234LONG2893eh/diff/conf is no other app service config file.
 It's possible to automatically copy the app service config files inside the OverlayFS conf directory.

**Comment by spantaleev** [comment]
You need to use `matrix_synapse_container_additional_volumes` to make the local file (from `/opt/matrix/synapse/config`) available in the container.

Also, make sure the path specified in `matrix_synapse_app_service_config_files` is an absolute path. We can't be sure how Synapse would resolve relative paths.

----------

You'd need configuration like this:

```yaml
# These are in-container paths.
# Any files referenced here need to be mounted into the container.
# See `matrix_synapse_container_additional_volumes`
matrix_synapse_app_service_config_files:
- /appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml

# This is how we mount the local file (`/opt/matrix/synapse/config/appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml`)
# into the container at `/appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml`
matrix_synapse_container_additional_volumes:
- src: /opt/matrix/synapse/config/appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml
  dst: /appservice-dimension-eguiefrgiphRANDOM89ui4h5tr.yaml
  options: ro
```
