### ISSUE TITLE
matrix-nginx-proxy spam really fills up systemd journal

### ISSUE THREAD

**Issue by skepticalwaves** [spantaleev/matrix-docker-ansible-deploy#1373]
it appears that matrix-nginx-proxy is logging every single HTTP query to the journal, 
```
Nov 02 16:18:07 matrix matrix-nginx-proxy[1121]: <IP>- - [02/Nov/2021:16:18:07 +0000] "GET /_matrix/client/r0/sync?filter=0......
```

this causes a few issues
1. The main log is very hard to get anything useful out of
2. It fills the disk pretty rapidly
3. This is bad for privacy

Is it possible to adjust the defaults for nginx logging to be a bit less chatty?

**Comment by spantaleev** [comment]
I think we currently do double-logging for requests going to `matrix.DOMAIN`, which makes things worse. First it goes to `roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2`, which then proxies to `roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2`, which then proxies to Synapse.

We do it in 2 tiers like that, because it allows more flexibility as to where the requests go. User-initiated requests (from outside) go through these 2 tiers (the 1st one of which potentially reroutes traffic through `matrix-corporal` before bringing it to Synapse). Internal requests (those generated by various bots and bridges) go to Synapse directly.

---------

We currently define some default logging in `roles/matrix-nginx-proxy/templates/nginx/nginx.conf.j2`: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7b8b595e81f9f49b233ece86f0d9b254d5b9411d/roles/matrix-nginx-proxy/templates/nginx/nginx.conf.j2#L40-L44

You can use the `matrix_nginx_proxy_access_log_enabled` variable to disable logging for all virtual hosts.

We can have some `access_log` statements in each `server{}` block tied to various variables, so that we can disable logging for each one. Their default values can be tied to the main `matrix_nginx_proxy_access_log_enabled` variable.

Example:

```yaml
# For matrix-domain.conf
matrix_nginx_proxy_proxy_matrix_access_log_enabled: "{{ matrix_nginx_proxy_access_log_enabled }}"

# For matrix-synapse.conf
matrix_nginx_proxy_proxy_synapse_access_log_enabled: "{{ matrix_nginx_proxy_access_log_enabled }}"

# ... more variables (one for each virtual host) ..
```

And likely something like this in each virtual host configuration (if explicitly disabled, turn logging off; if enabled, don't include an `access_log` statement at that level and use the main one):

```nginx
	{% if not matrix_nginx_proxy_proxy_synapse_access_log_enabled %}
	access_log off;
	{% endif %}
```
