### ISSUE TITLE
can't disable user_directory

### ISSUE THREAD

**Issue by felixx9** [spantaleev/matrix-docker-ansible-deploy#1381]
Hej

I installed my first synapse via this ansible project. Great help! Thx!

Due to privacy reasons I want to disable the user_directory:
```
matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: false
    search_all_users: false
```
so that's the other-way-around-problem as described in #919 

Federation is not active, yet.
With two brand new users on a brand new install: As soon I enter the "@"-sign, I get suggestions:

![Screenshot from 2021-11-06 02-14-55](https://user-images.githubusercontent.com/51174875/140593054-5e9f8aff-337a-460e-90d1-448b17bbea1d.png)

On my existing "standard" deploy that's not the case:
```
# User Directory configuration
#
# 'enabled' defines whether users can search the user directory. If
# false then empty responses are returned to all queries. Defaults to
# true.
#
# 'search_all_users' defines whether to search all users visible to your HS
# when searching the user directory, rather than limiting to users visible
# in public rooms.  Defaults to false.  If you set it True, you'll have to
# rebuild the user_directory search indexes, see
# https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md
#
user_directory:
  enabled: false
  search_all_users: false
```

![Screenshot from 2021-11-06 02-19-41](https://user-images.githubusercontent.com/51174875/140593097-08fd2b9c-9f20-4807-b868-d6d2b6fc92d0.png)

**Comment by felixx9** [comment]
by the way - I tried to set both values to true. Same results.

**Comment by aaronraimist** [comment]
I cannot reproduce. Did you run the `setup-all` and `start` tags after adding

```
matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: false
    search_all_users: false
```

to your `vars.yml` file?

**Comment by felixx9** [comment]
Yes I did.
By now, federation is activated, too. 
This is my vars.yml (sripped comments & empty lines)

```
matrix_domain: duesen.chat
matrix_ssl_lets_encrypt_support_email: 'the@email.de'
matrix_coturn_turn_static_auth_secret: 'a_secret'
matrix_synapse_macaroon_secret_key: 'another_secret'
matrix_postgres_connection_password: 'yet_another_secret'
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_synapse_admin_enabled: true
matrix_synapse_enable_registration: true
matrix_synapse_allow_public_rooms_over_federation: true
matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: false
    search_all_users: false

matrix_postgres_backup_enabled: true
```

**Comment by aaronraimist** [comment]
Hmm. If you look at `/matrix/synapse/config/homeserver.yaml` on the server, does it include

```
user_directory:
    enabled: false
    search_all_users: false
```

**Comment by felixx9** [comment]
yes it does
![Screenshot from 2021-11-06 02-57-09](https://user-images.githubusercontent.com/51174875/140594028-769c6d97-cebc-4e80-ad6a-854964f44745.png)

**Comment by aaronraimist** [comment]
Hmm. What does `sudo systemctl status matrix-synapse` show as the last time it was started?

Also what version of Synapse is running?

**Comment by felixx9** [comment]
what about this setting?
`limit_profile_requests_to_users_who_share_rooms: false`

**Comment by felixx9** [comment]
> Hmm. What does `sudo systemctl status matrix-synapse` show as the last time it was started?
15 minutes ago - all fine.

> Also what version of Synapse is running?
```
$ systemctl status matrix-synapse
● matrix-synapse.service - Synapse server
     Loaded: loaded (/etc/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-11-06 02:53:37 CET; 17min ago
    Process: 50008 ExecStartPre=/usr/bin/env sh -c /usr/bin/env docker kill matrix-synapse 2>/dev/null (code=exited, status=1/FAILURE)
    Process: 50018 ExecStartPre=/usr/bin/env sh -c /usr/bin/env docker rm matrix-synapse 2>/dev/null (code=exited, status=1/FAILURE)
   Main PID: 50030 (docker)
      Tasks: 6 (limit: 2341)
     Memory: 15.9M
        CPU: 139ms
     CGroup: /system.slice/matrix-synapse.service
             └─50030 docker run --rm --name matrix-synapse --log-driver=none --user=998:1001 --env=UID=998 --env=GID=1001 --cap-drop=ALL --read-only --tmpfs=/tmp:rw,noexec,nosuid,size=2500m --network=matrix --mount type=bind,src=/matrix/>
```

**Comment by felixx9** [comment]
failures process 50008 and 50018?

> what about this setting? `limit_profile_requests_to_users_who_share_rooms: false`
on my "regular" server, this is set to true. tried. no difference

hmm

**Comment by felixx9** [comment]
https://matrix.duesen.chat/_synapse/admin/v1/server_version
{"server_version":"1.46.0","python_version":"3.8.12"}

**Comment by aaronraimist** [comment]
I'm out of ideas. It seems like a Synapse bug to me.

> failures process 50008 and 50018?

That's normal.

**Comment by felixx9** [comment]
```
matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: false
    search_all_users: false
  limit_profile_requests_to_users_who_share_rooms: true
  include_profile_data_on_invite: false
```
does not work...
I filed an issue here : https://github.com/matrix-org/synapse/issues/11266
