### ISSUE TITLE
Data Retention Configuration not working

### ISSUE THREAD

**Issue by GammaG** [spantaleev/matrix-docker-ansible-deploy#1410]
The configurations that are described for the playbook configuration for vars.yml does not actually set the parameters in the homeserver.yaml.j2

`#Retention
matrix_synapse_retention_enabled: true
matrix_synapse_retention_default_policy_min_lifetime: 1d
matrix_synapse_retention_default_policy_max_lifetime: 3d`

The only solution is to manually add the retention configurations into "roles/matrix-synapse/templates/synapse/homeserver.yaml.j2"

Can this please also come from the vars.yml?

**Comment by aaronraimist** [comment]
None of those variables you have written (`matrix_synapse_retention_enabled`, `matrix_synapse_retention_default_policy_min_lifetime` or `matrix_synapse_retention_default_policy_max_lifetime`) exist. I'm not sure where you got them from.

You can change things that don't have variables by using the configuration extension.

For example:
```
matrix_synapse_configuration_extension_yaml: |
  retention:
    # The message retention policies feature is disabled by default. Uncomment the
    # following line to enable it.
    #
    enabled: true

    # Default retention policy. If set, Synapse will apply it to rooms that lack the
    # 'm.room.retention' state event. Currently, the value of 'min_lifetime' doesn't
    # matter much because Synapse doesn't take it into account yet.
    #
    default_policy:
      min_lifetime: 1d
      max_lifetime: 1y
```
