### ISSUE TITLE
Issue: Vars file ignoring some Synapse configuration options, probably user error?

### ISSUE THREAD

**Issue by AnonyPla** [spantaleev/matrix-docker-ansible-deploy#1424]
Hi,

I'm trying to have the following configuration set in the ansible vars.yaml

```
matrix_synapse_configuration_extension_yaml: |
  limit_remote_rooms:
    enabled: true
    complexity: 1.0
  retention:
  enabled: true
  default_policy:
    min_lifetime: 1s
    max_lifetime: 7d
  allowed_lifetime_min: 1s
  allowed_lifetime_max: 7d
  purge_jobs:
    - longest_max_lifetime: 7d
      interval: 12h
    - shortest_max_lifetime: 7d
      interval: 12h
```

Yet this is always ignored and the final homeserver.yaml resulting in `retention: null`

Am I doing something wrong? 

Any help would be appreciated
