### ISSUE TITLE
Suggestions for certbot crontab

### ISSUE THREAD

**Issue by tvo6** [spantaleev/matrix-docker-ansible-deploy#146]
Hello,

I'd like to suggest for the file `/etc/cron.d/matrix-ssl-lets-encrypt`:

- run the tasks every day
- postpone the nginx reload (my renewal takes more than 5 minutes), eg:
  ```45 4 * * *  root /bin/systemctl reload matrix-nginx-proxy.service```

I didn't see it in config files, but some variable to fix the time before renewal (sorry if I missed it) would be very convenient.

Thanks for all the fish :)

**Comment by spantaleev** [comment]
Thanks for the suggestions! :+1:  I've just implemented them!

-----------

As for making the time configurable, I guess it would be possible, even though a little complicated.

The current time is defined in `roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_lets_encrypt.yml` and it's spread out into multiple arguments to the Ansible [cron](https://docs.ansible.com/ansible/2.7/modules/cron_module.html) module.

Example:

```yml
  - name: Ensure periodic SSL renewal cronjob configured (matrix-ssl-lets-encrypt-certificates-renew)
    cron:
      user: root
      cron_file: matrix-ssl-lets-encrypt
      name: matrix-ssl-lets-encrypt-certificates-renew
      state: present
      hour: 4
      minute: 15
      day: "*"
      job: /usr/local/bin/matrix-ssl-lets-encrypt-certificates-renew
```

We either need to define a separate variable for each (hour; minute; day) or use variable arguments in Ansible. See:
- https://github.com/ansible/ansible/pull/41295
- https://github.com/ansible/ansible/pull/43798

Variable args for Ansible modules seems to be a newish feature only supported in Ansible 2.7.
We're currently targeting older versions down to Ansible 2.5, so using it is not possible.

I guess that leads us back to using multiple variables.. or better yet, avoiding such a feature if possible.

----------

I wonder, what is your use case for controlling the time?

Renewing and reloading services is not invasive (no system load increase or service downtime), so it shouldn't matter at what point in time it happens.
