### ISSUE TITLE
Mautrix Whatsapp fails to set-relay: 'Relay mode is not enabled on this instance of the bridge'

### ISSUE THREAD

**Issue by leofabri** [spantaleev/matrix-docker-ansible-deploy#1503]
Hello,
I want some element users to chat to a WhatsApp group without them being effectively registered to WA.
I am trying to use a relay for the first time, but I've not managed to do that yet.

This is the configuration of my mautrix WhatsApp bridge:
```
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml: |
  bridge:
    history_sync:
      backfill: true
  permissions:
    "{{ matrix_mautrix_whatsapp_homeserver_domain }}": user
    "@myuser:{{ matrix_domain }}": admin
    "@myuser:{{ matrix_domain }}": relay
  relay:
    enabled: true
  encryption:
    default: true
    allow: true
```
I don't know if the permissions bit is correct (and necessary). I keep getting "**Relay mode is not enabled on this instance of the bridge**". What am I missing?

**Comment by leofabri** [comment]
My bad. It's a dumb indentation problem 😓

## Solution
It should look more like this instead:
```
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml: |
  bridge:
    history_sync:
      backfill: true
    permissions:
      "{{ matrix_mautrix_whatsapp_homeserver_domain }}": user
      "@myuser:{{ matrix_domain }}": admin
      "@myuser:{{ matrix_domain }}": relay
    relay:
      enabled: true
    encryption:
      default: true
      allow: true
```
