### ISSUE TITLE
Configure Jitsi authentication and guests mode gives an error

### ISSUE THREAD

**Issue by razerrazer** [spantaleev/matrix-docker-ansible-deploy#1578]
Hello,

I try to get my matrix-home server to working without any guest autentication for jiitsi, and that you need to login to gain access.

Anyway, I following the guide and added these settings to my vars.yml : https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md

```
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_prosody_auth_internal_accounts:
  - username: "jitsi-moderator"
    password: "secret-password"
  - username: "another-user"
    password: "another-password"
```

But when i running the playbook i get an error (I have also try to change the password and also using everything default). My playbook are working without any problems except of this setting.

This is the error output i get from ansible:
```
TASK [matrix-jitsi : Ensure Jitsi internal authentication users are configured] **************************************************************************************************
failed: [matrix.hostlocal.local] (item={'username': 'jitsi-moderator', 'password': 'secret-password'}) => changed=true 
  ansible_loop_var: item
  cmd: docker exec matrix-jitsi-prosody prosodyctl --config /config/prosody.cfg.lua register jitsi-moderator meet.jitsi 'secret-password'
  delta: '0:00:00.555089'
  end: '2022-01-27 12:46:40.387604'
  item:
    password: secret-password
    username: jitsi-moderator
  msg: non-zero return code
  rc: 1
  start: '2022-01-27 12:46:39.832515'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |2-
  
  
    **************************
    Prosody was unable to find the configuration file.
    We looked for: /etc/prosody//config/prosody.cfg.lua
    A sample config file is included in the Prosody download called prosody.cfg.lua.dist
    Copy or rename it to prosody.cfg.lua and edit as necessary.
    More help on configuring Prosody can be found at https://prosody.im/doc/configure
    Good luck!
    **************************
  stdout_lines: <omitted>
changed: [matrix.hostlocal.local] => (item={'username': 'another-user', 'password': 'another-password'})

```

Let me know if you need more information.
Thanks!
