### ISSUE TITLE
Issue with Synapse Simple Anti-Spam Module Configuration Generation

### ISSUE THREAD

**Issue by AnonyPla** [spantaleev/matrix-docker-ansible-deploy#1582]
On the following documentation:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-synapse-simple-antispam.md

The instructions are as follows:

```
matrix_synapse_ext_spam_checker_synapse_simple_antispam_enabled: true
matrix_synapse_ext_spam_checker_synapse_simple_antispam_config_blocked_homeservers:
- example.com
- another.com
```

And I noticed that this will generate the following in the actual config file:

```
modules:
-   config:
        blocked_homeservers:
       - example.com
       - another.com
    module: synapse_simple_antispam.AntiSpamInvites
```

But shouldn't it be (as documented here https://github.com/t2bot/synapse-simple-antispam) as the following instead? 

```
modules:
-   module: "synapse_simple_antispam.AntiSpamInvites"
     config:
        blocked_homeservers:
         - example.com
         - another.com
```
