### ISSUE TITLE
matrix_encryption_disabler support

### ISSUE THREAD

**Issue by spantaleev** [spantaleev/matrix-docker-ansible-deploy#1621]
[matrix_encryption_disabler](https://github.com/digitalentity/matrix_encryption_disabler) allows homeserver administrators to force-disable E2EE for rooms hosted on their server.

Related to https://github.com/matrix-org/synapse/issues/4401

**Comment by digitalentity** [comment]
https://github.com/digitalentity/matrix_encryption_disabler/issues/1 has been fixed, the plugin now supports new Synapse Module API.

**Comment by spantaleev** [comment]
Thanks! We can now easily install your plugin and auto-enable it for the homeserver domain with a single configuration line:

```yaml
matrix_synapse_ext_encryption_disabler_enabled: true

# We apply these defaults, but users can customize these settings too.
# matrix_synapse_ext_encryption_disabler_deny_encryption_for_users_of: ["{{ matrix_domain }}"]
# matrix_synapse_ext_encryption_disabler_deny_encryption_for_rooms_of: ["{{ matrix_domain }}"]
```

----

I've tested it and it seems to **work well**! It prevents enabling encryption both during initial room creation and with a subsequent attempt to encrypt the room. Thank you for creating this plugin! :bow: 

Until now, I've been using [matrix-corporal](https://github.com/devture/matrix-corporal) to deny encryption creation attempts with the following configuration:

```yaml
# When matrix-corporal is acting as the primary authentication provider,
# you need to set up the REST authentication password provider module
# to make Interactive User Authentication work.
# This is necessary for certain user actions (like E2EE, device management, etc).
#
# See configuring-playbook-rest-auth.md
matrix_synapse_ext_password_provider_rest_auth_enabled: true
matrix_synapse_ext_password_provider_rest_auth_endpoint: "http://matrix-corporal:41080/_matrix/corporal"

matrix_corporal_enabled: true

# See matrix_aux_file_definitions
matrix_corporal_policy_provider_config: |
  {
    "Type": "static_file",
    "Path": "/etc/matrix-corporal/policy.json"
  }

# If you need to change matrix-corporal's user id from the default (matrix-corporal).
# In any case, you need to make sure this Matrix user is created on your server.
matrix_corporal_corporal_user_id_local_part: "matrix-corporal"

matrix_aux_file_definitions:
  - dest: "{{ matrix_corporal_config_dir_path }}/policy.json"
    content: |
      {
        "schemaVersion": 1,
        "identificationStamp": "stamp-1",
        "flags": {
          "allowCustomUserDisplayNames": false,
          "allowCustomUserAvatars": false,
          "forbidRoomCreation": false,
          "forbidEncryptedRoomCreation": true,
          "forbidUnencryptedRoomCreation": false,
          "allowCustomPassthroughUserPasswords": true,
          "allowUnauthenticatedPasswordResets": false,
          "allow3pidLogin": false
        },
        "managedCommunityIds": [],
        "managedRoomIds": [],
        "users": []
      }
```

This is more complicated, but also worked well for denying `/createRoom` requests and subsequent attempts to enable encryption.

What `matrix_encryption_disabler` does better than `matrix-corporal` with regards to this is that:

- `/createRoom` requests that try to enable encryption are not denied, but rather modified so that the encryption part is stripped away. This works around clients like [Fluffychat](https://fluffychat.im/), which try to [force you into using encryption and don't let you avoid it](https://gitlab.com/famedly/fluffychat/-/issues/648)
- using a Synapse plugin is a simpler and more lightweight solution for disabling encryption than installing a gateway/firewalling system like matrix-corporal
