### ISSUE TITLE
dendrite has replaced naffka with nats.

### ISSUE THREAD

**Issue by corburn** [spantaleev/matrix-docker-ansible-deploy#1625]
https://github.com/matrix-org/dendrite/blob/9ac27cabc5f624938264ddccf5500478d7d38bf3/CHANGES.md#dendrite-060-2022-01-28

**Comment by spantaleev** [comment]
We know, it's the reason #1599 didn't get merged. We need to adapt the configuration and test it out.

**Comment by Xemorph** [comment]
``Hello all,
for a first time installation it is relatively easy to customize the configurations, but for existing installations it might be difficult to upgrade. I refer here to a text section from the link of the first comment:

> Consolidated the federation API, federation sender and signing key server into a single component
If multiple databases are used, tables for the federation sender and signing key server should be merged into the federation API database (table names have not changed)

With version 0.6.x some databases were removed and replaced by a new one. In the config file `dendrite-config.yaml` the new database is titled as `federationapi`. During the upgrade the following should happen:
- Transfer table/s from DB `dendrite_federationsender` to the new DB `dendrite_federationapi`
- Transfer table/s from DB `dendrite_sigingkeyserver` to the new DB `dendrite_federationapi`
- Delete the following databases: `dendrite_naffka`, `dendrite_federationsender`, `dendrite_sigingkeyserver`, `dendrite_device`

**Note:** I don't know where the data from the database `dendrite_device` are migrated to!

---

Subsequently, other things would have to be adjusted, including the configuration file for Dendrite, the Docker command must be extended. The command could then look something like this:
```
ExecStart={{ matrix_host_command_docker }} run --rm --name matrix-dendrite \
			--log-driver=none \
			--user={{ matrix_user_uid }}:{{ matrix_user_gid }} \
			--cap-drop=ALL \
			--read-only \
			--tmpfs=/tmp:rw,noexec,nosuid,size={{ matrix_dendrite_tmp_directory_size_mb }}m \
			--network={{ matrix_docker_network }} \
			{% if matrix_dendrite_container_http_host_bind_address and matrix_dendrite_http_bind_port %}
			-p {{ matrix_dendrite_container_http_host_bind_address }}:{{ matrix_dendrite_http_bind_port }} \
			{% endif %}
			{% if matrix_dendrite_container_https_host_bind_address and matrix_dendrite_https_bind_port %}
			-p {{ matrix_dendrite_container_https_host_bind_address }}:{{ matrix_dendrite_https_bind_port }} \
			{% endif %}
			--mount type=bind,src={{ matrix_dendrite_config_dir_path }},dst=/data,ro \
			--mount type=bind,src={{ matrix_dendrite_storage_path }},dst=/matrix-media-store-parent,bind-propagation=slave \
			--mount type=bind,src={{ matrix_dendrite_storage_path }},dst=/matrix-jetstream-parent,bind-propagation=slave \
			{% for volume in matrix_dendrite_container_additional_volumes %}
			-v {{ volume.src }}:{{ volume.dst }}:{{ volume.options }} \
			{% endfor %}
			{% for arg in matrix_dendrite_container_extra_arguments %}
			{{ arg }} \
			{% endfor %}
			{{ matrix_dendrite_docker_image }} \
			-config /data/dendrite.yaml \
			{% if matrix_dendrite_http_bind_address %}
			-http-bind-address {{ matrix_dendrite_http_bind_address }}
			{% endif %}
			{% if matrix_dendrite_https_bind_address %}
			-https-bind-address {{ matrix_dendrite_https_bind_address }}
			{% endif %}
			{{ matrix_dendrite_process_extra_arguments|join(' ') }}
```
I have added another `--mount` parameter to allow NATS JetStream to permanently store its data.
If you wonder why another `--mount` is necessary, take a look at the configuration of NATS JetStream (copied from the following file: [dendrite-config.yaml](https://github.com/matrix-org/dendrite/blob/v0.6.5/dendrite-config.yaml)). JetStream needs a path to be able to store its data, so I used the `media-store` as a guide.
```yaml
# Configuration for NATS JetStream
  jetstream:
    # A list of NATS Server addresses to connect to. If none are specified, an
    # internal NATS server will be started automatically when running Dendrite
    # in monolith mode. It is required to specify the address of at least one
    # NATS Server node if running in polylith mode.
    addresses:
    # - localhost:4222

    # Keep all NATS streams in memory, rather than persisting it to the storage
    # path below. This option is present primarily for integration testing and
    # should not be used on a real world Dendrite deployment.
    in_memory: false

    # Persistent directory to store JetStream streams in. This directory
    # should be preserved across Dendrite restarts.
    storage_path: ./

    # The prefix to use for stream names for this homeserver - really only
    # useful if running more than one Dendrite on the same NATS deployment.
    topic_prefix: Dendrite
```

---

There is definitely a lot to do. I could document my changes here in the course of the week, whether they are good is another question, because my time is also very limited.
