### ISSUE TITLE
matrix_mautrix_signal_bridge_permissions not written to server

### ISSUE THREAD

**Issue by fcnjd** [spantaleev/matrix-docker-ansible-deploy#1658]
Title mostly tells the problem: When I set the variable in my vars.yml file and re-run the playbook, the corresponding config is not written to the server. The relevant part of the file looks like this (anonymized):

```yaml
# bridges
# signal
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true
# Permissions for using the bridge.
# Permitted values:
#      relay - Allowed to be relayed through the bridge, no access to commands.
#       user - Use the bridge with puppeting.
#      admin - Use and administrate the bridge.
# Permitted keys:
#        * - All Matrix users
#   domain - All users on that homeserver
#     mxid - Specific user
matrix_mautrix_signal_bridge_permissions: |
  '*': relay
  '{{ matrix_mautrix_signal_homeserver_domain }}': user
  '@xxx:matrix.org': user
```

I think this is probably a bug because I can't explain it differently why the variable is not written in the config. Of course there is a workaround: setting the configuration_extension manually, and so I'd consider it low priority. Anyway, I'd very happy if you could somehow fix that, since it breaks the convention of beeing able to override playbook variables.
