### ISSUE TITLE
 Mautrix Twitter broken

### ISSUE THREAD

**Issue by shalzz** [spantaleev/matrix-docker-ansible-deploy#1682]
**Describe the bug**
Enabling mautrix twitter breaks the playbook

**To Reproduce**
Enable mautrix twitter

```yaml
matrix_mautrix_twitter_enabled: true
```

I get the following error:
```
fatal: [matrix.redacted]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: {{ matrix_mautrix_twitter_configuration_yaml|from_yaml|combine(matrix_mautrix_twitter_configuration_extension, recursive=True) }}: {{ lookup('template', 'templates/config.yaml.j2') }}: {{ { 'postgres': matrix_mautrix_twitter_database_connection_string, }[matrix_mautrix_twitter_database_engine] }}: 'dict object' has no attribute ''

    The error appears to be in '/home/shalzz/builds/network/matrix-docker-ansible-deploy/roles/matrix-bridge-mautrix-twitter/tasks/setup_install.yml': line 56, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: Ensure mautrix-twitter config.yaml installed
      ^ here
```

**Expected behavior**
Mautrix twitter bridge should be configured and installed.

**Comment by shalzz** [comment]
Okay I see that we need to manually set the `matrix_mautrix_twitter_database_*` variables which is not described in the docs.
I would have thought the already specified database variables for synapse would be re-used here, but I guess it's not trivial to automatically create a new postgres database on an existing db server.

**Comment by shalzz** [comment]
Okay, even after setting the `matrix_mautrix_twitter_database_*` variables I'm still seeing the same error.

**Comment by spantaleev** [comment]
Perhaps you haven't defined `matrix_mautrix_twitter_database_engine: postgres` in your `vars.yml` file?

I don't think it's enough to have the following custom configuration to reproduce the bug:

```yaml
matrix_mautrix_twitter_enabled: true
```

You're **probably using an external Postgres server as well** (`matrix_postgres_enabled: false`), which is causing all the trouble (manual work you need to do). Such a setup is not so well supported (something https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1679 is aiming to address through documentation.. although.. things are not so simple).

-----

The way `group_vars/matrix_servers` was configured, you'd end up with `matrix_mautrix_twitter_database_engine: ''` here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1bea072484fda284c91ba4e8fbf29b40a07b9220/group_vars/matrix_servers#L12-L18

.. which should have told you to define this empty `matrix_mautrix_twitter_database_engine` variable via this check: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1bea072484fda284c91ba4e8fbf29b40a07b9220/roles/matrix-bridge-mautrix-twitter/tasks/validate_config.yml#L12-L18

Perhaps this validation check did not work well and `matrix_mautrix_twitter_database_engine` still remains empty for you?

-------

In 8c25ade9fb6d, I've reworked how these variables work a bit. You should try and see if you have more success with that.

If you're using an external Postgres server, you'll need to define this additional `vars.yml` configuration:

```yaml
matrix_mautrix_twitter_enabled: true

# Define your Postgres server credentials here (defaults are taken from roles/matrix-bridge-mautrix-twitter/defaults/main.yml)
matrix_mautrix_twitter_database_username: 'matrix_mautrix_twitter'
matrix_mautrix_twitter_database_password: ''
matrix_mautrix_twitter_database_hostname: ''
matrix_mautrix_twitter_database_port: 5432
matrix_mautrix_twitter_database_name: 'matrix_mautrix_twitter'
```
