### ISSUE TITLE
Dimension can't contact home server in non-standard federation setup

### ISSUE THREAD

**Issue by Natrocx** [spantaleev/matrix-docker-ansible-deploy#1690]
**Describe the bug**
The dimension integration manager successfully starts and can be contacted by the client but dimensions fails to reach the synapse homeservers. The server successfully federates with matrix.org and devture.com (no others tested).

The log (`journalctl -fu matrix-dimension`) output for requesting dimension from Element ("Edit widgets, bridges and bots") looks something like:
```
Mar 11 11:17:05 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:05 GMT [INFO] [Webserver] Incoming request: POST /api/v1/scalar/register?v=1.1
Mar 11 11:17:05 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:05 GMT [DEBUG] [matrix] Cached federation URL for natrocx.win is http://matrix-nginx-proxy:12088
Mar 11 11:17:05 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:05 GMT [ERROR] [matrix] Error calling /_matrix/federation/v1/openid/userinfo
Mar 11 11:17:05 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:05 GMT [ERROR] [matrix] Error: connect ECONNREFUSED 172.18.0.16:12088
Mar 11 11:17:05 matrix matrix-dimension[2990904]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
Mar 11 11:17:05 matrix matrix-dimension[2990904]:   errno: -111,
Mar 11 11:17:05 matrix matrix-dimension[2990904]:   code: 'ECONNREFUSED',
Mar 11 11:17:05 matrix matrix-dimension[2990904]:   syscall: 'connect',
Mar 11 11:17:05 matrix matrix-dimension[2990904]:   address: '172.18.0.16',
Mar 11 11:17:05 matrix matrix-dimension[2990904]:   port: 12088
Mar 11 11:17:05 matrix matrix-dimension[2990904]: }
Mar 11 11:17:05 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:05 GMT [INFO] [matrix] Doing federated API call: http://matrix-nginx-proxy:12088/_matrix/federation/v1/openid/userinfo
Mar 11 11:17:05 matrix matrix-dimension[2990904]: Error: connect ECONNREFUSED 172.18.0.16:12088
Mar 11 11:17:05 matrix matrix-dimension[2990904]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
Mar 11 11:17:09 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:09 GMT [DEBUG] [MatrixClientLite] Received sync. Next token: s...
Mar 11 11:17:09 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:09 GMT [DEBUG] [MatrixClientLite] Performing sync with token s...
Mar 11 11:17:09 matrix matrix-dimension[2990904]: Fri, 11 Mar 2022 11:17:09 GMT [DEBUG] [MatrixHttpClient (REQ-623)] GET http://matrix-nginx-proxy:12080/_matrix/client/r0/sync
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: natrocx.win

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: ''

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'natrocx@protonmail.ch'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: ''

# use system docker to safe some trouble
matrix_docker_installation_enabled: true

# enable multi-processing:
matrix_synapse_workers_enabled: true

# We want a proper certificate to safe us trouble with federation
matrix_ssl_retrieval_method: lets-encrypt

# we will be sitting behind cloduflare; activate TLSv1.3
matrix_nginx_proxy_ssl_preset: modern

matrix_nginx_proxy_hsts_preload_enabled: true

matrix_synapse_password_config_localdb_enabled: true # shared auth documentation is missing

#performance optimisation
matrix_nginx_proxy_access_log_enabled: false

matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    #These lines will be included in the nginx configuration.
    #This is at the top level of the file, so you will need to define all of the `server { ... }` blocks.
    #
    ## Git letsencrypt
    server {
        listen 8080;
        listen [::]:8080;


        server_name git.natrocx.win;

        server_tokens off;
        root /dev/null;

                location /.well-known/acme-challenge {
                                resolver 127.0.0.11 valid=5s;
                                set $backend "matrix-certbot:8080";
                                proxy_pass http://$backend;
                }

                location / {
                        return 301 https://$http_host$request_uri;
                }
    }

    server {
        listen 8443 ssl http2;
        listen [::]:8443 ssl http2;
       

        server_name git.natrocx.win;

        server_tokens off;
        root /dev/null;

        ssl_certificate /matrix/ssl/config/live/git.natrocx.win/fullchain.pem;
        ssl_certificate_key /matrix/ssl/config/live/git.natrocx.win/privkey.pem;

        ssl_protocols TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_session_tickets off;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_timeout 1d;

        gzip on;
        gzip_types text/plain application/json application/javascript text/css image/x-icon font/ttf image/gif;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Frame-Options SAMEORIGIN;
        add_header Content-Security-Policy "frame-ancestors 'self'";

        add_header Permissions-Policy interest-cohort=() always;

        location / {

            client_max_body_size 150m;
                        resolver 127.0.0.11 valid=5s;
                        set $backend "172.17.0.1:3000";
                        proxy_pass http://$backend;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
        }


    }
 

# as of right now there are no other hosted services:
matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_client_element_disable_custom_urls: false

matrix_client_element_themes_enabled: true
matrix_client_element_themes_repository_url: https://github.com/aaronraimist/element-themes # default

# Controls the default theme
matrix_client_element_default_theme: 'dark'

matrix_client_hydrogen_enabled: false
matrix_client_cinny_enabled: false


# enable admin gui
matrix_synapse_admin_enabled: true

# enable gated registration
matrix_registration_enabled: false  # currently broken
matrix_registration_admin_secret: ""

# simple spam filter - reenable after everything works?
matrix_synapse_ext_spam_checker_synapse_simple_antispam_enabled: false
matrix_synapse_ext_spam_checker_synapse_simple_antispam_config_blocked_homeservers: []

matrix_architecture: arm64

matrix_dimension_enabled: true

matrix_dimension_admins:
  - "@dimension:{{ matrix_domain }}"

matrix_dimension_access_token: syt_...

## Stats
matrix_prometheus_enabled: true

matrix_prometheus_node_exporter_enabled: true

matrix_grafana_enabled: true

matrix_grafana_anonymous_access: false

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
matrix_grafana_default_admin_user: "grafanaadmin"

# Changing the password subsequently won't work.
matrix_grafana_default_admin_password: 

## Bridging

# Discord - currently has some issues
matrix_mx_puppet_discord_enabled: true

# Matrix reminder - imma need that :3
matrix_bot_matrix_reminder_bot_enabled: true

# Adjust this to whatever password you chose when registering the bot user
matrix_bot_matrix_reminder_bot_matrix_user_password: 

# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/Berlin

matrix_synapse_http_listener_resource_names: ["client","federation"]
# Set to a cloud-flare supported port
matrix_federation_public_port: 443
matrix_synapse_federation_port_enabled: false

# Whether dynamic dns is enabled
matrix_dynamic_dns_enabled: false

matrix_etherpad_enabled: false # no arm64 support as of now
```

Since Cloudflare will not proxy 8448 I have moved the federation port to the standard https port. This shouldn't really influence the internal routing.

**Expected behavior**
Dimension connects to the home server

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture: arm64
(Oracle Cloud arm instance)

**Additional context**
The dimension checker widget shows the following:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/17322576/157858769-1aa800c7-69ce-49dd-bd3f-595848a66b40.png">

The server does not filter requests except into Oracles network. The firewall/filtering is done by Oracle Cloud + Cloudflare.

Note that TLSv1.3 only is active on the ngninx proxy (see ssl preset).
