### ISSUE TITLE
Beeper-maintained bridges fail to build

### ISSUE THREAD

**Issue by myned** [spantaleev/matrix-docker-ansible-deploy#1719]
**Describe the bug**
Beeper-maintained bridges (at least Discord and Slack) fail to build due to GitHub's [deprecation](https://github.blog/2021-09-01-improving-git-protocol-security-github/) of `git://` and `ssh://` protocols. The docker images are likely unaffected.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_mx_puppet_discord_enabled: true
matrix_mx_puppet_discord_container_image_self_build: true
```

**Expected behavior**
Bridges build successfully.

**Actual behavior**
Build fails with error:
```
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn && cd packages/mx-puppet-discord && yarn build' returned a non-zero code: 128
```

**Matrix Server:**
 - OS: Arch Linux
 - Architecture: arm64

**Ansible:**
The problem lies with the upstream [monorepo](https://gitlab.com/beeper/mx-puppet-monorepo).

**Client:**
N/A

**Additional context**
I have submitted upstream MR [!35](https://gitlab.com/beeper/mx-puppet-monorepo/-/merge_requests/35) a week ago, which would also close the related [issue](https://gitlab.com/beeper/mx-puppet-monorepo/-/issues/2). My [fork](https://gitlab.com/Myned/mx-puppet-monorepo) can be used as follows until it is resolved. The only difference between the fork and upstream is a dirty fix to replace the unauthenticated protocols with `git+https://` in relevant lock files. I will attempt to merge any changes made upstream until building is fixed. If this is an acceptable interim solution, I would be happy to open a PR.

For Discord (tested on arm64):
```yaml
matrix_mx_puppet_discord_enabled: true
matrix_mx_puppet_discord_container_image_self_build: true
matrix_mx_puppet_discord_container_image_self_build_repo: "https://gitlab.com/Myned/mx-puppet-monorepo"
```
For Slack (untested):
```yaml
matrix_mx_puppet_slack_enabled: true
matrix_mx_puppet_slack_container_image_self_build: true
matrix_mx_puppet_slack_container_image_self_build_repo: "https://gitlab.com/Myned/mx-puppet-monorepo"
```
