### ISSUE TITLE
Self-checks fails on "Parse JSON for well-known payload at the identity hostname"

### ISSUE THREAD

**Issue by soletan** [spantaleev/matrix-docker-ansible-deploy#1735]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: mydomain.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '64 random letters'
matrix_ssl_lets_encrypt_support_email: ssladmin@mydomain.com
matrix_postgres_connection_password: 'secret-with-special-characters'
matrix_synapse_admin_enabled: true
```

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture: x86_64

**Ansible:**

Ansible version 2.12.2 runs on a separate remote server which in turn runs Ubuntu 20.04 as well. No docker involved.

**Problem description**:

Tried setup-all, start and self-check in a row multiple times. self-check keeps failing:

```
TASK [matrix-nginx-proxy : Parse JSON for well-known payload at the identity hostname] ******************************
fatal: [matrix.mydomain.com -> 127.0.0.1]: FAILED! =>
  msg: |-
    the field 'args' has an invalid value ({'well_known_identity_payload': '{{ result_well_known_identity.content|from_json }}'}), and could not be converted to an dict.The error was: Expecting value: line 1 column 1 (char 0)

    The error appears to be in '/root/playbooks/matrix-docker-ansible-deploy/roles/matrix-nginx-proxy/tasks/self_check_well_known_file.yml': line 56, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: Parse JSON for well-known payload at the identity hostname
      ^ here
```

* I can open https://element.mydomain.com in the browser. 
* I can log in. 
* I can create public rooms via element webclient. 
* I can log in via synapse-admin addressing my homeserver on login.
* There are no event reports logged in synapse-admin.

**Client (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10 Pro 21H2
 - Browser: Firefox
 - Version: 98.0.2

**Additional context**

Working off cloned repository in branch master. Had pulled latest changes right before trying to run setup-all, start, self-check recently.
