### ISSUE TITLE
playbook do not create container goofys

### ISSUE THREAD

**Issue by Seele-Vollerei32** [spantaleev/matrix-docker-ansible-deploy#1740]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: atunemic.cn

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'SECRET_KEY'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'we123445@outlook.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: 'PASSWORD'

matrix_synapse_enable_registration: true
matrix_synapse_registrations_require_3pid: 'email'

matrix_prometheus_enabled: true

matrix_prometheus_node_exporter_enabled: true

matrix_grafana_enabled: true

matrix_grafana_anonymous_access: false

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
matrix_grafana_default_admin_user: "kevin"

# Changing the password subsequently won't work.
matrix_grafana_default_admin_password: "PASSWORD"

matrix_synapse_admin_enabled: true

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: TOKEN

matrix_bot_mjolnir_enabled: true
matrix_bot_mjolnir_access_token: "TOKEN"
matrix_bot_mjolnir_management_room: "!ROOM:atunemic.cn"
matrix_synapse_ext_spam_checker_mjolnir_antispam_enabled: true
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_invites: true
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_messages: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_usernames: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_ban_lists: []

matrix_dimension_enabled: true
matrix_dimension_access_token: "TOKEN"
matrix_dimension_admins:
  - "@kevin:{{ matrix_domain }}"

matrix_s3_media_store_enabled: true
matrix_s3_media_store_bucket_name: "matrix-APPID
matrix_s3_media_store_aws_access_key: "AKID98rKWS7VcS1II2VhcGdjY6OQBgtpUszp"
matrix_s3_media_store_aws_secret_key: "SECRET_KEY"
matrix_s3_media_store_custom_endpoint_enabled: true
# Example: "https://storage.googleapis.com"
matrix_s3_media_store_custom_endpoint: "https://matrix-APPID.cos.ap-shanghai.myqcloud.com"
```

**Matrix Server:**
 - OS: CentOS 7
 - Architecture: amd64

**Problem description**:

This problem appeared after I added Tencent Cloud COS

**Additional context**
> journalctl -fu matrix-goofys.service

```

Apr 10 15:14:04 VM-16-3-centos systemd[1]: matrix-goofys.service holdoff time over, scheduling restart.
Apr 10 15:14:04 VM-16-3-centos systemd[1]: Stopped Matrix Goofys media store.
Apr 10 15:14:04 VM-16-3-centos systemd[1]: Starting Matrix Goofys media store...
Apr 10 15:14:04 VM-16-3-centos matrix-goofys[12238]: Error response from daemon: Cannot kill container: matrix- goofys.service: No such container: matrix-goofys.service
Apr 10 15:14:04 VM-16-3-centos matrix-goofys[12244]: Error: No such container: matrix-goofys.service
Apr 10 15:14:04 VM-16-3-centos systemd[1]: Started Matrix Goofys media store.
Apr 10 15:14:05 VM-16-3-centos matrix-goofys[12253]: 2022/04/10 07:14:05.402478 main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1
Apr 10 15:14:05 VM-16-3-centos matrix-goofys[12253]: stderr:
Apr 10 15:14:05 VM-16-3-centos matrix-goofys[12253]: fusermount: mountpoint is not empty
Apr 10 15:14:05 VM-16-3-centos matrix-goofys[12253]: fusermount: if you are sure this is safe, use the 'nonempty' mount option
Apr 10 15:14:05 VM-16-3-centos systemd[1]: matrix-goofys.service: main process exited, code=exited, status=1/FAILURE
Apr 10 15:14:05 VM-16-3-centos systemd[1]: Unit matrix-goofys.service entered failed state.
Apr 10 15:14:05 VM-16-3-centos systemd[1]: matrix-goofys.service failed.

```

> systemctl status matrix-goofys.service
```

● matrix-goofys.service - Matrix Goofys media store
   Loaded: loaded (/etc/systemd/system/matrix-goofys.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2022-04-10 15:17:41 CST; 663ms ago
  Process: 17563 ExecStart=/usr/bin/env docker run --rm --name %n --log-driver=none --user=995:1001 --mount type=bind,src=/etc/passwd,dst=/etc/passwd,ro --mount type=bind,src=/etc/group,dst=/etc/group,ro --mount type=bind,src=/matrix/synapse/storage/media-store,dst=/s3,bind-propagation=shared --security-opt apparmor:unconfined --cap-add mknod --cap-add sys_admin --device=/dev/fuse --env-file=/matrix/synapse/config/env-goofys --entrypoint /bin/sh ewoutp/goofys:latest -c goofys -f --endpoint=https://matrix-APPID.cos.ap-shanghai.myqcloud.com --region eu-central-1 --stat-cache-ttl 60m0s --type-cache-ttl 60m0s --dir-mode 0700 --file-mode 0700 matrix-APPID /s3 (code=exited, status=1/FAILURE)
  Process: 17555 ExecStartPre=/usr/bin/env docker rm %n (code=exited, status=1/FAILURE)
  Process: 17548 ExecStartPre=/usr/bin/env docker kill %n (code=exited, status=1/FAILURE)
 Main PID: 17563 (code=exited, status=1/FAILURE)


```
