### ISSUE TITLE
FAILED - While Update Matrix Docker on Matrix Mailer

### ISSUE THREAD

**Issue by corincorvus** [spantaleev/matrix-docker-ansible-deploy#1751]
**Describe the bug**
Today i tried to upgrade my Matrix Server.
With git pull i update the Playbook, checked new Settings (Dendryte and Synapse settings i added in the vars.yml)

i start the Setup and get this Error:
```

TASK [matrix-mailer : Ensure mailer environment variables file created] *******************
ok: [matrix.server.tld]

TASK [matrix-mailer : Ensure exim-relay repository is present on self-build] **************
skipping: [matrix.server.tld]

TASK [matrix-mailer : Ensure exim-relay Docker image is built] ****************************
skipping: [matrix.server.tld]

TASK [matrix-mailer : Ensure exim-relay image is pulled] **********************************
fatal: [matrix.server.tld]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: {{ matrix_mailer_docker_image_name_prefix }}devture/exim-relay:{{ matrix_mailer_version }}: {{ 'localhost/' if matrix_mailer_container_image_self_build else matrix_container_global_registry_prefix }}: 'matrix_container_global_registry_prefix' is undefined
  
    The error appears to be in '/opt/github/matrix-docker-ansible-deploy/roles/matrix-mailer/tasks/setup_mailer.yml': line 47, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Ensure exim-relay image is pulled
      ^ here


```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml

### Base
matrix_domain: matrix.server.tld
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: ''
matrix_ssl_lets_encrypt_support_email: 'admin@server.tld'
matrix_synapse_macaroon_secret_key: ''
matrix_postgres_connection_password: ''

matrix_synapse_trusted_key_servers:
  - server_name: "matrix.org"

### Registration
matrix_synapse_enable_registration: false
matrix_synapse_allow_guest_access: false

### Upload Size
matrix_synapse_max_upload_size_mb: 1024

### Federation
matrix_synapse_federation_enabled: true
matrix_synapse_allow_public_rooms_over_federation: true
#matrix_synapse_federation_domain_whitelist:
matrix_synapse_tls_federation_listener_enabled: false

### Public Rooms
matrix_synapse_enable_room_list_search: true

### Auto Rooms
matrix_synapse_autocreate_auto_join_rooms: true
matrix_synapse_auto_join_rooms:
- '#ankuendigungen:matrix.server.tld'
- '#spaces:matrix.server.tld'

# Nginx
matrix_ssl_retrieval_method: ntld
matrix_well_known_matrix_server_enabled: false
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: '0.0.0.0:81'
matrix_nginx_proxy_container_federation_host_bind_port: '0.0.0.0:8449'

matrix_nginx_proxy_trust_forwarded_proto: true
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate: /matrix/ssl/config/live/matrix.server.tld/fullchain.pem
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate_key: /matrix/ssl/config/live/matrix.server.tld/privkey.pem
matrix_nginx_proxy_access_log_enabled: false
matrix_nginx_proxy_proxy_matrix_nginx_status_allowed_addresses:
- 1.1.1.1
- 1.0.0.1

# Mail
matrix_mailer_sender_address: "noreply@server.tld"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "Mailserver"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "noreply@server.tld"
matrix_mailer_relay_auth_password: ""

# Coturn
matrix_coturn_enabled: false
matrix_synapse_turn_shared_secret: ""
matrix_synapse_turn_uris:
- turns:turn.server.tld?transport=udp
- turns:turn.server.tld?transport=tcp
- turn:turn.server.tld?transport=udp
- turn:turn.server.tld?transport=tcp

# Ldap
matrix_synapse_ext_password_provider_ldap_enabled: true
matrix_synapse_ext_password_provider_ldap_uri: "ldap://IP:7389"
matrix_synapse_ext_password_provider_ldap_start_tls: false
matrix_synapse_ext_password_provider_ldap_base: "dc=server,dc=tld"
matrix_synapse_ext_password_provider_ldap_attributes_uid: "uid"
matrix_synapse_ext_password_provider_ldap_attributes_mail: "mailPrimaryAddress"
matrix_synapse_ext_password_provider_ldap_attributes_name: "displayname"
matrix_synapse_ext_password_provider_ldap_bind_dn: "uid=ldaplogin,cn=users,dc=server,dc=tld"
matrix_synapse_ext_password_provider_ldap_bind_password: ""
matrix_synapse_ext_password_provider_ldap_filter: "(|(memberof=cn=grp-intern-matrix,cn=groups,dc=server,dc=tld))"

# Adminweb
matrix_synapse_admin_enabled: true

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: ""
matrix_synapse_password_config_localdb_enabled: false

###############################################################################################
### Element ###
# Element
matrix_client_element_disable_guests: true

# Registration Element
matrix_registration_enabled: false
matrix_registration_admin_secret: ""

###############################################################################################
### Bridges ###

# Signal
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true

permissions:
  '*': relay
  YOUR_DOMAIN: user

# Discord
matrix_mx_puppet_discord_enabled: true
matrix_appservice_discord_enabled: false

# Twitter
matrix_mx_puppet_twitter_enabled: true
matrix_mx_puppet_twitter_consumer_key: ''
matrix_mx_puppet_twitter_consumer_secret: ''
matrix_mx_puppet_twitter_access_token: ''
matrix_mx_puppet_twitter_access_token_secret: ''
matrix_mx_puppet_twitter_environment: ''

# Steam
matrix_mx_puppet_steam_enabled: true

# Instagram
matrix_mautrix_instagram_enabled: true

# Whatsapp
matrix_mautrix_whatsapp_enabled: true
matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true

# Reminder
matrix_bot_matrix_reminder_bot_enabled: true

# Adjust this to whatever password you chose when registering the bot user
matrix_bot_matrix_reminder_bot_matrix_user_password: 

# Adjust this to your timeztld
matrix_bot_matrix_reminder_bot_reminders_timeztld: Europe/Berlin


### Deaktivierte Bridges ###
# Slack
matrix_mx_puppet_slack_enabled: false

```

Download new playbook on existing playbook system
upgrade System

**Expected behavior**
The Playbook update all Container and services

**Matrix Server:**
 - OS: Debian 11 64 Bit
 - Architecture amd64

**Additional**
i tried to pull the exim-relay manually. Not worked.
Last Upgrade of Playbook and Services was ~4 month ago, before dendrite added in the playbook.
