### ISSUE TITLE
jitsi component start up issue

### ISSUE THREAD

**Issue by XiotSamuel** [spantaleev/matrix-docker-ansible-deploy#1797]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: msgtest.ooguy.com

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '*************************************'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: '*************8@************.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: 'matrix'

matrix_architecture: 'arm64'

matrix_jitsi_enabled: true

# Run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
# or define your own strong passwords manually.
matrix_jitsi_jicofo_auth_password: "*******"
matrix_jitsi_jvb_auth_password: "******"
matrix_jitsi_jibri_recorder_password: "******"
matrix_jitsi_jibri_xmpp_password: "******"

matrix_synapse_admin_enabled: true
matrix_synapse_enable_registration_without_verification: true
matrix_synapse_enable_registration: true
```

**Matrix Server:**
 - OS:  Ubuntu 21.04
 - Architecture arm64 with raspPi 4

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

Implementing jitsi in rasppi, but all jitsi service cannot start.

`failed: [matrix.msgtest.ooguy.com] (item=matrix-jitsi-web.service) => changed=false 
  ansible_loop_var: item
  item: matrix-jitsi-web.service
  msg: matrix-jitsi-web.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-jitsi-web.service` and `journalctl -fu matrix-jitsi-web.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.
failed: [matrix.msgtest.ooguy.com] (item=matrix-jitsi-prosody.service) => changed=false 
  ansible_loop_var: item
  item: matrix-jitsi-prosody.service
  msg: matrix-jitsi-prosody.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-jitsi-prosody.service` and `journalctl -fu matrix-jitsi-prosody.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.
failed: [matrix.msgtest.ooguy.com] (item=matrix-jitsi-jicofo.service) => changed=false 
  ansible_loop_var: item
  item: matrix-jitsi-jicofo.service
  msg: matrix-jitsi-jicofo.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-jitsi-jicofo.service` and `journalctl -fu matrix-jitsi-jicofo.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.
failed: [matrix.msgtest.ooguy.com] (item=matrix-jitsi-jvb.service) => changed=false 
  ansible_loop_var: item
  item: matrix-jitsi-jvb.service
  msg: matrix-jitsi-jvb.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-jitsi-jvb.service` and `journalctl -fu matrix-jitsi-jvb.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.`

**Client (please complete the following information):**
 - Device: macos
 - OS: apple
 - Browser chrome

**Additional context**
