### ISSUE TITLE
systemd timers not triggering

### ISSUE THREAD

**Issue by lemmy04** [spantaleev/matrix-docker-ansible-deploy#1805]
I have a matrix homeserver installed with this play, the systemd timers installed by it did not fire.
See this screenshot: https://paste.pics/GVQKL

**To Reproduce**
My `vars.yml` file looks like this with the sensitive stuff stripped out:

```yaml
matrix_domain: eregion.de
matrix_ssl_lets_encrypt_support_email: 'admin@eregion.de'
matrix_nginx_proxy_base_domain_serving_enabled: false
matrix_coturn_turn_external_ip_address: 89.58.34.47
matrix_mailer_sender_address: "admin@eregion.de"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "*.*.de"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_synapse_report_stats: true
matrix_synapse_admin_enabled: true
matrix_registration_enabled: true
matrix_dimension_enabled: false
matrix_jitsi_enabled: false
matrix_prometheus_enabled: true
matrix_prometheus_node_exporter_enabled: true
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: false
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
```

**Expected behavior**
The letsencrypt certificate is supposed to get renewed automatically by the systemd timers.

**Matrix Server:**
 - OS: Ubuntu 20.04.4 LTS
 - Architecture X86_64

**Additional context**
Just a wild guess here:
I ran the play just the day before the certificates expired, to upgrade my server to the latest versions.
maybe that re-installed those timers, so they didn't run before the expiry time?
