### ISSUE TITLE
Get Error The error was: 'matrix_geturl_retries_delay' is undefined

### ISSUE THREAD

**Issue by corincorvus** [spantaleev/matrix-docker-ansible-deploy#1819]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# Example value: example.com
matrix_domain: matrix.domain.tld

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'KEY'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'info@domain.tld'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: 'KEY'

matrix_synapse_trusted_key_servers:
  - server_name: "matrix.org"

### Upload Size
matrix_synapse_max_upload_size_mb: 1024


```

**Matrix Server:**
Debian 11
AMD64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:
While i start with fresh downloaded Playbook (Today): ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start --ask-pass 
```
 TASK [matrix-synapse : set_fact] **************************************************************************************************************************************************************************************************************************
skipping: [matrix.domain.tld]

TASK [matrix-synapse : Ensure matrix-synapse-rest-auth doesn't exist] *************************************************************************************************************************************************************************************
ok: [matrix.domain.tld]

TASK [matrix-synapse : Fail if Shared Secret Auth secret not set] *****************************************************************************************************************************************************************************************
skipping: [matrix.domain.tld]

TASK [matrix-synapse : Fail if no Shared Secret Auth login types enabled] *********************************************************************************************************************************************************************************
skipping: [matrix.domain.tld]

TASK [matrix-synapse : Download matrix-synapse-shared-secret-auth] ****************************************************************************************************************************************************************************************
fatal: [matrix.domain.tld]: FAILED! => 
  msg: |-
    The field 'delay' has an invalid value, which includes an undefined variable. The error was: 'matrix_geturl_retries_delay' is undefined
  
    The error appears to be in '/opt/github/matrix-docker-ansible-deploy/roles/matrix-synapse/tasks/ext/shared-secret-auth/setup_install.yml': line 13, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Download matrix-synapse-shared-secret-auth
      ^ here


```

**Additional context**
