### ISSUE TITLE
Can't complete admin using the API

### ISSUE THREAD

**Issue by BettyNutz** [spantaleev/matrix-docker-ansible-deploy#1846]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: ******.*******

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '******************'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: '*******@*************.******'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: '**********'

# This is where you access Jitsi.
matrix_server_fqn_jitsi: 'jitsi.***********.******'

#This is setting the serves the base domain from the Matrix server -- the federation can find the matrix server
matrix_nginx_proxy_base_domain_serving_enabled: true

#Jetsi stuff copied form https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md
#matrix_jitsi_enabled: true

#Synapse's Admin API exposed to the internet
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true
```

**Matrix Server:**
 - OS: Debian11 - AWS
 - Architecture amd64

**Ansible:**
Working fine

**Problem description**:

Installed the server via the playbook. All good. I need to get the admin api working but its not. Tried the following commands with ' & " in various locations: 

sudo curl -H "Authorization: Bearer syt_***************" http://localhost:8008/_synapse/admin/v1/room/\!LXxm**********sHphYK:**************.com/media

sudo curl -H "Authorization: Bearer syt_***************" http://localhost:8448/_synapse/admin/v1/room/\!LXxm**********sHphYK:**************.com/media

sudo docker exec matrix-synapse curl -H "Authorization: Bearer syt_***************" http://localhost:8008/_synapse/admin/v1/room/\!LXxm**********sHphYK:**************.com/media

sudo docker exec matrix-synapse curl -H "Authorization: Bearer syt_***************" http://localhost:8448/_synapse/admin/v1/room/\!LXxm**********sHphYK:**************.com/media

sudo docker exec matrix-synapse curl -H "Authorization: Bearer syt_***************" http://mydominname.com:8448/_synapse/admin/v1/room/\!LXxm**********sHphYK:**************.com/media

Do i need to call api from inside the container?

Do i need to use iptables to route from 127.0.0.11 to the backend DNS resolver in the Docker Engine?

I even tied installing [synadm](https://github.com/JOJ0/synadm). Same issue

Can someone give me an example of an api command.. im not sure if im using the correct commands and there are no real word examples in the doc.

**Client (please complete the following information):**
 - Device: Terminal via ssh to server

**Additional context**

Getting the following errors (out of synadm) and nothing out of the server with the api:

reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Server: nginx
header: Date: Sat, 21 May 2022 03:14:40 GMT
header: Content-Type: text/html
header: Content-Length: 248
header: Connection: close
WARNING Synapse returned status code 400
ERROR JSONDecodeError while querying Synapse: Expecting value: line 1 column 1 (char 0)
Media list could not be fetched.

These are the ports i have open:

netstat -tnlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:3478            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:8448            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:5349            0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::80                   :::*                    LISTEN      -                   
tcp6       0      0 :::3478                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::443                  :::*                    LISTEN      -                   
tcp6       0      0 :::8448                 :::*                    LISTEN      -                   
tcp6       0      0 :::5349                 :::*                    LISTEN      -
