### ISSUE TITLE
Postgres: too many idle processes (cp_min / cp_max)

### ISSUE THREAD

**Issue by roughnecks** [spantaleev/matrix-docker-ansible-deploy#1854]
**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64

**Ansible:**
I'm running Ansible on the Matrix server
 `ansible --version`: 2.10.8

**Problem description**:

OK, so, my VPS has got only 2GB RAM and I use Matrix just for myself, with a few bridges (mautrix) and a reminder bot. My issue is that I'm almost out of memory already and I found out that there are many idle postgres processes which takes quite a lot memory.. I wanted to reduce their number to say like, 3 min and 5 max, instead of default 10 max.
I asked in the Ansible channel on Matrix and they told me to adjust "cp_min" and "cp_max" vars but I couldn't find them in this playbook and trying to do this, everything failed:

```yaml
# Postgres
matrix_postgres_process_extra_arguments: [
  "-c max_connections=75",
  "-c shared_buffers=96MB",
  "-c cp_min=3",
  "-c cp_max=5",
]
```

$ ps aux |grep postgre
matrix    834608  0.0  4.8 164668 95784 ?        Ss   May25   0:07 postgres: synapse synapse 172.18.0.6(39296) idle
matrix    834615  0.0  4.7 164720 95028 ?        Ss   May25   0:12 postgres: synapse synapse 172.18.0.6(39298) idle
matrix    834619  0.0  4.8 164640 96572 ?        Ss   May25   0:13 postgres: synapse synapse 172.18.0.6(39300) idle
matrix    834665  0.0  4.4 164560 88424 ?        Ss   May25   0:04 postgres: synapse synapse 172.18.0.6(39302) idle
matrix    834666  0.0  4.9 164632 99076 ?        Ss   May25   0:11 postgres: synapse synapse 172.18.0.6(39304) idle
matrix    834670  0.0  4.6 164720 93220 ?        Ss   May25   0:08 postgres: synapse synapse 172.18.0.6(39306) idle
matrix    834671  0.0  4.8 164592 96412 ?        Ss   May25   0:06 postgres: synapse synapse 172.18.0.6(39308) idle
matrix    834672  0.0  4.8 164632 97200 ?        Ss   May25   0:14 postgres: synapse synapse 172.18.0.6(39310) idle
matrix    834868  0.0  4.6 164648 92760 ?        Ss   May25   0:07 postgres: synapse synapse 172.18.0.6(39512) idle
matrix    834869  0.0  4.2 164396 85204 ?        Ss   May25   0:04 postgres: synapse synapse 172.18.0.6(39514) idle

So, is there another way to achieve the same result and lower memory consumption by postgres service?
Thanks

**Comment by spantaleev** [comment]
`cp_min` and `cp_max` are Synapse settings for the database connection. See `roles/matrix-synapse/templates/synapse/homeserver.yaml.j2`

These are not configurable using a dedicated variable right now, but you can:

- use `matrix_synapse_configuration_extension_yaml` to change them
- submit a PR that makes them configurable in an easier way

**Comment by roughnecks** [comment]
Thanks for your answer.

This is my original conf:

```yaml
matrix_synapse_configuration_extension_yaml: |
  retention:
    # The message retention policies feature is disabled by default. Uncomment the
    # following line to enable it.
    #
    enabled: true
    # Default retention policy. If set, Synapse will apply it to rooms that lack the
    # 'm.room.retention' state event. Currently, the value of 'min_lifetime' doesn't
    # matter much because Synapse doesn't take it into account yet.
    #
    default_policy:
      min_lifetime: 1d
      max_lifetime: 90d
```

Can I add these bits only and make it like this?

```yaml
matrix_synapse_configuration_extension_yaml: |
  retention:
    # The message retention policies feature is disabled by default. Uncomment the
    # following line to enable it.
    #
    enabled: true
    # Default retention policy. If set, Synapse will apply it to rooms that lack the
    # 'm.room.retention' state event. Currently, the value of 'min_lifetime' doesn't
    # matter much because Synapse doesn't take it into account yet.
    #
    default_policy:
      min_lifetime: 1d
      max_lifetime: 90d

  database:
    args:
      cp_min: 3
      cp_max: 5
```
