### ISSUE TITLE
TASK [matrix-base : Fail if matrix_homeserver_generic_secret_key is undefined]

### ISSUE THREAD

**Issue by Seldos** [spantaleev/matrix-docker-ansible-deploy#1856]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: elementtesting.com

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'deleted but in my File i have actually defined it'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: ''

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: ''

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: ""

matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: ""
matrix_mautrix_telegram_api_hash: ""

matrix_mautrix_whatsapp_enabled: true

matrix_mautrix_instagram_enabled: true

matrix_mautrix_twitter_enabled: true

matrix_mautrix_signal_enabled: true

matrix_appservice_discord_enabled: true
matrix_appservice_discord_client_id: ""
matrix_appservice_discord_bot_token: ""

```

**Matrix Server:**
 - OS: [Raspberry Pi OS - latest version]
 - Architecture [arm64]

**Ansible:**
If your problem appears to be with Ansible, tell us:
Running on the Matrix Server itself
Raspberry Pi OS - latest version
Version: 3.9.2
standard installation

**Problem description**:

`TASK [matrix-base : Fail if matrix_homeserver_generic_secret_key is undefined] ***
fatal: [matrix.elementtesting.com]: FAILED! => changed=false 
  msg: |-
    The `matrix_homeserver_generic_secret_key` variable must be defined and have a non-null and non-empty value.
  
    If you're observing this error on a new installation, you should ensure that the `matrix_homeserver_generic_secret_key` is defined.
  
    If you're observing this error on an existing homeserver installation, you can fix it easily and in a backward-compatible way by adding
    `matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"`
    to your `vars.yml` file. Using another secret value for the new variable is also possible and shouldn't cause any trouble.
`
Im getting this Error all the time, i read in another issue here on github that some other fixed it by naming his matrix.your-domain folder correctly but i dont know how it is named correctly

i named it "matrix.elementtesting.com", "matrix.elementtesting", "elementtesting", "elementtesting.com"

i tried chaning up the variable "matrix_domain" in the Vars.yml to "elementtesting.com", "elementtesting", "matrix.elementtesting.com", "matrix.elementtesting"

and it does not seem to fix the issue

**Additional context**
i currently don't own the domain, but it does not seem to be the problem here in my opinion
