### ISSUE TITLE
matrix-registration.service fail to start

### ISSUE THREAD

**Issue by cosmin-vasu** [spantaleev/matrix-docker-ansible-deploy#1864]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: domain

matrix_homeserver_implementation: synapse

matrix_homeserver_generic_secret_key: 'secret key'

matrix_ssl_lets_encrypt_support_email: 'email'

matrix_postgres_connection_password: 'password'

matrix_architecture: 'arm64'

matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_coturn_turn_external_ip_address: IP

matrix_mx_puppet_discord_enabled: true

matrix_registration_enabled: true

# Generate a strong secret using: `pwgen -s 64 1`.
matrix_registration_admin_secret: "admin key"

```

**Matrix Server:**
 - OS: Ubuntu 20.04.3 LTS
 - Architecture arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
Ansible is running on a different machine (alpinelinux)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:

Just trying to add matrix-registration (the server is running OK otherwise)

but matrix-registration.service fails to start

TASK [matrix-common-after : Fail if service isn't detected to be running] ******
failed: [domain] (item=matrix-registration.service) => changed=false 
  ansible_loop_var: item
  item: matrix-registration.service
  msg: matrix-registration.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-registration.service` and `journalctl -fu matrix-registration.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.

user@server:/$ systemctl status matrix-registration.service
● matrix-registration.service - matrix-registration
     Loaded: loaded (/etc/systemd/system/matrix-registration.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-05-31 10:22:02 UTC; 3s ago
    Process: 87909 ExecStartPre=/usr/bin/env sh -c /usr/bin/env docker kill matrix-registration 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 87918 ExecStartPre=/usr/bin/env sh -c /usr/bin/env docker rm matrix-registration 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 87928 ExecStart=/usr/bin/env docker run --rm --name matrix-registration --log-driver=none --user=997:1002 --cap-drop=ALL --network=matrix --mount type=bind,src=/matrix/matrix-registration/config,dst=/config,ro --mount type=b
   Main PID: 87928 (code=exited, status=1/FAILURE)

tried to run it manually to see the errors:
 
user@server:/$ sudo docker run --name matrix-registration --log-driver=none --user=997:1002 --cap-drop=ALL --network=matrix --mount type=bind,src=/matrix/matrix-registration/config,dst=/config,ro --mount type=bind,src=/matrix/matrix-registration/data,dst=/data localhost/zeratax/matrix-registration:v0.7.2 serve
Traceback (most recent call last):
  File "/usr/local/bin/matrix-registration", line 5, in <module>
    from matrix_registration.app import cli
  File "/usr/local/lib/python3.8/site-packages/matrix_registration/__init__.py", line 1, in <module>
    from . import api
  File "/usr/local/lib/python3.8/site-packages/matrix_registration/api.py", line 9, in <module>
    from flask import (
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)

**Client (please complete the following information):**

**Additional context**
