### ISSUE TITLE
Nginx-proxy not installed on arm64/dendrite

### ISSUE THREAD

**Issue by oscarcarlsson** [spantaleev/matrix-docker-ansible-deploy#1868]
**Describe the bug**
It seems Nginx-proxy isn't installed when trying to run the latest code on arm64 and using dendrite. Fresh install, Ubuntu 22.04 and latest source from this repository.

The playbook fails when it's trying to fetch certificates from lets encrypt, but the Nginx container isn't even running:

```sh
# systemctl status matrix-nginx-proxy.service
Unit matrix-nginx-proxy.service could not be found.
# docker ps -a
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS      NAMES
116f272edf4c   postgres:14.3-alpine   "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes   5432/tcp   matrix-postgres
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
matrix_domain: foo.bar
matrix_architecture: arm64
matrix_homeserver_implementation: dendrite
matrix_homeserver_generic_secret_key: 'secret'
matrix_ssl_lets_encrypt_support_email: 'oscar@foo.bar'
matrix_postgres_connection_password: 'secret'
```

Running this command (several times):

```sh
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all
```

I also tried to run just `tags=setup-nginx-proxy` but no difference.

**Expected behavior**
Nginx installed and running.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture arm64
 - Homeserver: Dendrite

**Ansible:**
Running Ansible from a FreeBSD 13.0-RELEASE jail, running Ansible 5.5.0 / core 2.12.4
