### ISSUE TITLE
Dimension log level

### ISSUE THREAD

**Issue by demontefacto** [spantaleev/matrix-docker-ansible-deploy#1879]
Hello.

It is possible to decrease log level for dimension integration? It fullfill the log with many debug and info messages by default. I cant find "variable" for change this

**Comment by spantaleev** [comment]
We could **previously** do this:

```yaml
matrix_dimension_configuration_extension_yaml: |
  logging:
    consoleLevel: verbose # Change this to one of: trace, debug, info, warn, error
```

.. but [since this change](https://github.com/turt2live/matrix-dimension/commit/123a45bb217126875a5a9aaabbe22c5f8f66727a) in Dimension, this `logging` configuration has been removed. I have also removed it from the playbook in 95ca182ab50b.

-----

As 95ca182ab50b says, I'm not sure how one can influence Dimension's logging configuration. You may wish to ask about this in [turt2live/matrix-dimension](https://github.com/turt2live/matrix-dimension).
