### ISSUE TITLE
mautrix-telegram: Support setting device properties

### ISSUE THREAD

**Issue by ndarilek** [spantaleev/matrix-docker-ansible-deploy#1924]
**Is your feature request related to a problem? Please describe.**
Some users of the Telegram bridge are having all their devices [forceably disconnected](https://github.com/mautrix/telegram/issues/733) when this bridge connects.

**Describe the solution you'd like**
Apparently, [setting these device properties](https://github.com/mautrix/telegram/issues/733#issuecomment-1175267044) may eliminate the kicks. The parameters appear hard-coded in the templated J2 config, however.

I don't know much more about this issue other than that I was one of the kicked users, and have never gotten this bridge working. If setting these device parameters makes it work, I'd appreciate the ability to set them with these playbooks.

Thanks!

**Comment by th0mcat** [comment]
@ndarilek, I've never used ansible before, but based on [the documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-telegram.md), copy the following to `/<path>/matrix-docker-ansible-deploy/roles/matrix-bridge-mautrix-telegram/defaults/main.yml`:

```
matrix_mautrix_telegram_configuration_extension_yaml: |
  telegram:
    device_info:
        device_model: GooglePixel 6
        system_version: SDK 32
        app_version: 8.7.4 (26367)
        lang_code: en
        system_lang_code: en
```

That could be the wrong file to insert this into, I don't know, like I said I've never used ansible.  I'm very curious to know if that works, though!
