### ISSUE TITLE
Error with maubot

### ISSUE THREAD

**Issue by mcaponong** [spantaleev/matrix-docker-ansible-deploy#1965]
When doing a git pull then an install sudo ansible-playbook -i inventory/hosts setup.yml -vvvv --tags=setup-all,start I get the following error

ERROR! couldn't resolve module/action 'community.docker.docker_image'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ubuntu/matrix-docker-ansible-deploy/roles/matrix-bot-maubot/tasks/setup_install.yml': line 28, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Ensure maubot image is pulled
  ^ here
**To Reproduce**
git pull 
sudo ansible-playbook -i inventory/hosts setup.yml -vvvv --tags=setup-all,start

```yaml
Paste your vars.yml file here.# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: xxx.xxx.com

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxx

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'admin@xxxxxxxx.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: xxxxxxxxxxxxxxxxx

matrix_architecture: arm64
matrix_synapse_federation_enabled: true
matrix_mautrix_googlechat_enabled: true
matrix_mautrix_signal_enabled: true
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_appservice_discord_enabled: false
#matrix_appservice_discord_client_id: xxxxxxxxxxxxxxxxxxxxxxxx
#matrix_appservice_discord_bot_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: xxxxxxxxxxxx
matrix_mautrix_telegram_api_hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
matrix_client_element_themes_enabled: true
matrix_nginx_proxy_base_domain_homepage_enabled: false
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: xxxxxxxxxxxxxxxxxxxxxxxx
matrix_mx_puppet_discord_enabled: true
matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@XXXXXX:{{ matrix_domain }}"
matrix_dimension_access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
matrix_synapse_admin_enabled: false
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true


matrix_appservice_irc_enabled: true

matrix_appservice_irc_ircService_servers:
  irc.xxx.org:
    name: "xxx"
    port: 6697
    ssl: true
    sasl: true
    allowExpiredCerts: false
    sendConnectionMessages: true
    botConfig:
      enabled: true
      nick: "xxx"
      joinChannelsIfNoUsers: true
    privateMessages:
      enabled: true
      federate: true
    dynamicChannels:
      enabled: true
      createAlias: true
      published: true
      joinRule: public
      groupId: +myircnetwork:localhost
      federate: true
      aliasTemplate: "#irc_$CHANNEL"
    membershipLists:
      enabled: false
      floodDelayMs: 10000
      global:
        ircToMatrix:
          initial: false
          incremental: false
        matrixToIrc:
          initial: false
          incremental: false
    matrixClients:
      userTemplate: "@irc_$NICK"
      displayName: "$NICK (IRC)"
      joinAttempts: -1
    ircClients:
      nickTemplate: "$DISPLAY[m]"
      allowNickChanges: true
      maxClients: 30
      idleTimeout: 86400
      reconnectIntervalMs: 5000
      concurrentReconnectLimit: 50
      lineLimit: 3
Make sure to remove any secret values before posting your vars.yml file publicly.
```

**Expected behavior**
The server to update and reload all services

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Client:**

**Additional context**
