### ISSUE TITLE
matrix-go-skype-bridge does not like postgres

### ISSUE THREAD

**Issue by ToeiRei** [spantaleev/matrix-docker-ansible-deploy#1972]
**Describe the bug**
The go-skype-bridge reports 
```
Jul 21 23:33:01 matrix systemd[1]: Started Matrix Go Skype Bridge bridge.
Jul 21 23:34:15 matrix matrix-go-skype-bridge[152947]: loadDBPortal1
Jul 21 23:34:15 matrix matrix-go-skype-bridge[152947]: loadDBPortal:  <nil>
Jul 21 23:34:15 matrix matrix-go-skype-bridge[152947]: loadDBPortal1
Jul 21 23:34:15 matrix matrix-go-skype-bridge[152947]: loadDBPortal:  <nil>
```

**To Reproduce**
My `vars.yml` file looks like this:

```
matrix_go_skype_bridge_enabled: true
matrix_go_skype_bridge_database_engine: 'postgres'
matrix_go_skype_bridge_database_username: 'some_database'
matrix_go_skype_bridge_database_password: 'some_password'
matrix_go_skype_bridge_database_hostname: 'external.postgres.server.ip'
matrix_go_skype_bridge_database_port: 5432
matrix_go_skype_bridge_database_name: 'matrix_skype'
```

To me this looks like a problem with the container itself as the config.yml in /matrix/go-skype-bridge/config/config.yml clearly has the database set. 

**Expected behavior**
I'd expect that thing not to write a sqlite db when it's instructed to use the postgreSQL server

**Matrix Server:**
 - OS: Debian 10 on KVM/QEMU
 - Architecture: amd64

**Additional context**

**Comment by spantaleev** [comment]
What is `/matrix/go-skype-bridge/config/config.yml` like?

You can paste it here, or open an upstream issue with that configuration.

**Comment by ToeiRei** [comment]
There you go:
```
root@matrix:~# cat /matrix/go-skype-bridge/config/config.yaml
appservice:
  address: http://matrix-go-skype-bridge:8080
  as_token: XXXXXX
  bot:
    avatar: mxc://matrix.org/kGQUDQyPiwbRXPFkjoBrPyhC
    displayname: Skype bridge bot
    username: skypebridgebot
  database:
    max_idle_conns: 2
    max_open_conns: 20
    type: postgres
    uri: postgresql://user:pass@dbhost:5432/matrix_skype?sslmode=disable
  hostname: 0.0.0.0
  hs_token: XXXXXX
  id: skype
  port: 8080
  provisioning:
    prefix: /_matrix/provision/v1
    shared_secret: disable
bridge:
  Skype_thumbnail: false
  allow_user_invite: false
  call_notices:
    end: true
    start: true
  chat_list_wait: 30
  command_prefix: '!skype'
  community_template: skype-{{.Localpart}}={{.Server}}
  connection_retry_delay: -1
  connection_timeout: 20
  delivery_receipts: false
  displayname_template: '{{if .DisplayName}}{{.DisplayName}}{{else}}{{.PersonId}}{{end}} (Skype)'
  double_puppet_allow_discovery: false
  double_puppet_server_map:
    some.domain: http://matrix-synapse:8008
  encryption:
    allow: false
    default: false
    puppet_id:
      allow: false
      key: 12dsf323
      username_template_prefix: skype-
  fetch_message_on_timeout: false
  initial_chat_sync_count: 10
  initial_history_disable_notifications: false
  initial_history_fill_count: 20
  invite_own_puppet_for_backfilling: true
  login_qr_regen_count: 2
  login_shared_secret_map:
    some.domain: secret_key_here
  max_connection_attempts: 3
  permissions:
    '@me:some.domain': admin
    some.domain: user
  portal_sync_wait: 600
  private_chat_portal_meta: true
  recovery_chat_sync_limit: -1
  recovery_history_backfill: true
  relaybot:
    enabled: false
    invites: []
    management: '!foo:example.com'
    message_formats:
      m.audio: '<b>{{ .Sender.Displayname }}</b>: sent an audio file'
      m.emote: '* <b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.file: '<b>{{ .Sender.Displayname }}</b>: sent a file'
      m.image: '<b>{{ .Sender.Displayname }}</b>: sent an image'
      m.location: '<b>{{ .Sender.Displayname }}</b>: sent a location'
      m.notice: '<b>{{ .Sender.Displayname }}</b>:: {{ .Message }}'
      m.text: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.video: '<b>{{ .Sender.Displayname }}</b>: sent a video'
  report_connection_retry: true
  sync_contact: false
  sync_max_chat_age: 259200
  sync_with_custom_puppets: true
  username_template: skype-{{.}}
homeserver:
  address: http://matrix-synapse:8008
  domain: stargazer.at
  server_name: matrix.to
logging:
  directory: ./logs
  file_date_format: '2006-01-02'
  file_mode: 384
  file_name_format: null
  print_level: warn
  timestamp_format: Jan _2, 2006 15:04:05

```
