### ISSUE TITLE
Borg backup complains about external postgreSQL server being too old

### ISSUE THREAD

**Issue by ToeiRei** [spantaleev/matrix-docker-ansible-deploy#1982]
**Describe the bug**
Despite matrix_backup_borg_supported_postgres_versions are ['12', '13', '14'], the script complains about my server being too old.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
# Postgres Config
matrix_postgres_enabled: false
matrix_synapse_database_host: "1.2.3.4"
matrix_synapse_database_user: "matrix"
matrix_synapse_database_password: "some pw"
matrix_synapse_database_database: "matrix"


# Borg Backup
matrix_backup_borg_enabled: true
matrix_backup_borg_location_repositories:
 - backup@nasIP:/mnt/MyPool/Backup/matrix
matrix_backup_borg_storage_encryption_passphrase: "super secret passphrase here"
matrix_backup_borg_ssh_key_private: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  ...
  -----END OPENSSH PRIVATE KEY-----
matrix_backup_borg_postgresql_enabled: true
matrix_backup_borg_postgresql_databases: ['matrix']
matrix_backup_borg_postgresql_databases_hostname: "1.2.3.4"
matrix_backup_borg_postgresql_databases_username: "matrix"
matrix_backup_borg_postgresql_databases_password: "some pw"
matrix_backup_borg_postgresql_databases_port: 5432

```

```
TASK [matrix-backup-borg : Fail if detected Postgres version is unsupported] ***********************************************************************************************
fatal: [matrix.domain.com]: FAILED! => changed=false
  msg: 'You cannot use borg backup with such an old version () of Postgres. Consider upgrading - link to docs for upgrading Postgres: docs/maintenance-postgres.md#upgrading-postgresql'
```

**Expected behavior**
I'd expect it to work - or at least acknowledge that my database isn't outdated.

**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- on the Matrix server itself
- what version of Ansible you're running -- ansible 2.10.8

**Additional context**

External postgreSQL server was at 12, got upgraded to 13 - same message
