### ISSUE TITLE
Unknown Module after git pull

### ISSUE THREAD

**Issue by felixhopfauf** [spantaleev/matrix-docker-ansible-deploy#1991]
**Describe the bug**

I did an update with git pull to get the latest version of the playbook.
The download runs successfully but after that i am not able to update my installation.

I get the following message that there is a task with no action in

/root/matrix-docker-ansible-deploy/roles/matrix-base/tasks/main.yml

![2022-08-01 10_26_47-Remote Desktop Manager  e-vsrv01](https://user-images.githubusercontent.com/53529059/182107453-05b91325-5cf7-4a42-a680-1b6f17111da3.png)

**To Reproduce**

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# Example value: example.com
matrix_domain: example.info

matrix_synapse_max_upload_size_mb: 1000
matrix_postgres_connection_password: 'xxx'
# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: stuff@example.info

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "xxx"

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "xxx"


matrix_client_element_themes_enabled: true

matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_synapse_log_level: "INFO"
matrix_synapse_storage_sql_log_level: "INFO"
matrix_synapse_root_log_level: "INFO"
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"

```

Run: ansible-playbook -i inventory/hosts setup.yml --tags=setup-all 

**Expected behavior**
I expect to run the playbook with the Tag "--setup-all"

**Matrix Server:**
 - OS: Debian 10
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible: on the server itself directly in the root folder of the playbook
- what version of Ansible you're running: 2.7.7 (with python 3.7.3)
