### ISSUE TITLE
borg backup service fails to start

### ISSUE THREAD

**Issue by DatanoiseTV** [spantaleev/matrix-docker-ansible-deploy#2015]
```
Aug 11 10:57:31 zorro systemd[1]: matrix-backup-borg.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit matrix-backup-borg.service has entered the 'failed' state with result 'exit-code'.
Aug 11 10:57:31 zorro systemd[1]: Failed to start Matrix Borg Backup.
-- Subject: A start job for unit matrix-backup-borg.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit matrix-backup-borg.service has finished with a failure.
-- 
-- The job identifier is 1276939 and the job result is failed.
Aug 11 10:57:35 zorro matrix-nginx-proxy[967160]: 172.18.0.8 - - [11/Aug/2022:10:57:35 +0000] "GET /_matrix/client/v3/sync
``` 

My yaml looks like this:

```yaml
matrix_backup_borg_enabled: true
matrix_backup_borg_location_repositories:
 - XXXXXXXXXXXX@XXXXXXXXXXXX.your-storagebox.de:XXXXXXXXXXXX
matrix_backup_borg_storage_encryption_passphrase: "XXXXXXXXXXXX"
matrix_backup_borg_ssh_key_private: |
  ---- BEGIN SSH2 PUBLIC KEY ----
  XXXXXXXXXXXX
  ---- END SSH2 PUBLIC KEY ----

```
