### ISSUE TITLE
ma1sd fails to build when architecture is ARM64

### ISSUE THREAD

**Issue by chavinlo** [spantaleev/matrix-docker-ansible-deploy#2066]
ma1sd fails to build when the architecture is set to ARM64. It first throws "detected dubious ownership in repository" when checking the folder, then when #2008 is done (both `git config --global --add safe.directory /matrix/docker-src/dimension` & [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#compatibility-break-changes-to-docker-src-permissions-necessitating-manual-action)), it thinks its pulled but then fails on ["Ensure ma1sd Docker image is tagged correctly"](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1fb54a37cba126235b1688bb5e96226a65b4fe80/roles/matrix-ma1sd/tasks/setup_install.yml#L91).

**To Reproduce**

Enable ma1sd module on an ARM64 based server

My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.tld
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'redacted'
matrix_ssl_lets_encrypt_support_email: 'example@example.tld'
matrix_postgres_connection_password: 'redacted'
matrix_architecture: arm64
matrix_synapse_admin_enabled: true
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_ma1sd_enabled: true
matrix_ma1sd_matrixorg_forwarding_enabled: true
```

**Expected behavior**
ma1sd should build with no errors

**Matrix Server:**
 - Oracle Cloud Platform, Sao Pablo
 - OS: Ubuntu 22.04.1 LTS aarch64 provided by Oracle
 - Architecture: arm64

**Additional context**

This issue has already been mentioned with a fix on #1440, I did that, cleaned the docker build folders (`find /matrix -maxdepth 2 -name 'docker-src' | xargs rm -rf`), re-run the main script again, and it worked. (not built???? this ansible thing is confusing)
