### ISSUE TITLE
Document how to setup conduit

### ISSUE THREAD

**Issue by meenzen** [spantaleev/matrix-docker-ansible-deploy#2076]
**There is currently no documentation on how to properly setup conduit.**

Conduit support is experimental but we should at least provide some basic documentation.

**Proposal: Add documentation for the most common tasks**

This is what i've come up with so far:

# Configuring Conduit (optional, experimental)

To use Conduit instead of Synapse enable it in `vars.yml`:

```yaml
matrix_homeserver_implementation: conduit
```

## Creating the admin account

Conduit automatically makes the first user an admin. To create the account, simply register using a matrix client like Element.

## Disabling registration

By default anyone can create an account on your homeserver. After creating the admin account you can disable it in `vars.yml`:

```yaml
matrix_conduit_allow_registration: false
```

You can still create users using the admin command [conduit docs not available yet]

## Configuring bridges / appservices

Automatic appservice setup is currently unsupported when using conduit. After setting up the service as usual you may notice that it is unable to start.

You will have to manually register it using the the [register-appservice](https://gitlab.com/famedly/conduit/-/blob/next/APPSERVICES.md) command.

Find the `registration.yaml` in the `/matrix` directory, for example `/matrix/mautrix-signal/bridge/registration.yaml`, then pass the content to conduit:

    @conduit:your.server.name: register-appservice
    ```
    as_token: <token>
    de.sorunome.msc2409.push_ephemeral: true
    hs_token: <token>
    id: signal
    namespaces:
      aliases:
      - exclusive: true
        regex: ^#signal_.+:example\.org$
      users:
      - exclusive: true
        regex: ^@signal_.+:example\.org$
      - exclusive: true
        regex: ^@signalbot:example\.org$
    rate_limited: false
    sender_localpart: _bot_signalbot
    url: http://matrix-mautrix-signal:29328
    ```
