### ISSUE TITLE
Nginx cannot start after reboot server

### ISSUE THREAD

**Issue by Seele-Vollerei32** [spantaleev/matrix-docker-ansible-deploy#2077]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: atunemic.cn

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: dendrite

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '***'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'we123445@outlook.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: '***'

matrix_synapse_enable_registration: true
matrix_synapse_registration_requires_token: true
matrix_synapse_registrations_require_3pid: 'email'

matrix_prometheus_enabled: false

matrix_prometheus_node_exporter_enabled: false

matrix_grafana_enabled: false

matrix_grafana_anonymous_access: false

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
matrix_grafana_default_admin_user: "kevin"

# Changing the password subsequently won't work.
matrix_grafana_default_admin_password: "***"

matrix_synapse_admin_enabled: flase

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: false
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: ***

matrix_bot_mjolnir_enabled: true
matrix_bot_mjolnir_access_token: "***"
matrix_bot_mjolnir_management_room: "!AVjqHyfcl6BsDRTO:atunemic.cn"
matrix_synapse_ext_spam_checker_mjolnir_antispam_enabled: true
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_invites: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_messages: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_usernames: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_ban_lists: []

matrix_mautrix_telegram_enabled: false
matrix_mautrix_telegram_api_id: 9609852
matrix_mautrix_telegram_api_hash: ***
matrix_mautrix_telegram_bot_token: ***
matrix_mautrix_telegram_configuration_extension_yaml: |
  bridge:
    permissions:
      '*': relaybot
      '@kevin_liu:atunemic.cn': admin


matrix_dimension_enabled: true
matrix_dimension_access_token: "***"
matrix_dimension_admins:
  - "@kevin_liu:{{ matrix_domain }}"

matrix_s3_media_store_enabled: false
matrix_s3_media_store_bucket_name: "matrix-1302020253"
matrix_s3_media_store_aws_access_key: "***"
matrix_s3_media_store_aws_secret_key: "***"
matrix_s3_media_store_custom_endpoint_enabled: true
# Example: "https://storage.googleapis.com"
matrix_s3_media_store_custom_endpoint: "***"

matrix_bot_matrix_registration_bot_enabled: true
# Token obtained via logging into the bot account (see above)
matrix_bot_matrix_registration_bot_bot_access_token: "***"

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true

matrix_ma1sd_enabled: true

matrix_synapse_log_level: "INFO"
matrix_synapse_storage_sql_log_level: "INFO"
matrix_synapse_root_log_level: "INFO"

```

**Matrix Server:**
 - OS: archlinux 
 - Architecture: amd64

**Problem description**:

Before I reboot my server, the webui is unable to open. I reboot the server because I thought the load of the server is too heavy for the server to run. But after reboot, it still can't open.

**Additional context**
`journalctl -fu matrix-nginx-proxy.service
```
Aug 30 16:40:57 archlinux systemd[1]: matrix-nginx-proxy.service: Scheduled restart job, restart counter is at 71.
Aug 30 16:40:57 archlinux systemd[1]: Stopped Matrix nginx-proxy server.
Aug 30 16:40:57 archlinux systemd[1]: Starting Matrix nginx-proxy server...
Aug 30 16:40:57 archlinux systemd[1]: Started Matrix nginx-proxy server.
Aug 30 16:40:57 archlinux matrix-nginx-proxy[22486]: docker: Error response from daemon: driver failed programming external connectivity on endpoint matrix-nginx-proxy (87aad82eee715c36c5c704e9b17f295b0e7f3fff8ef4ebceb9705197d88cb30d): Bind for 0.0.0.0:8448 failed: port is already allocated.
Aug 30 16:40:57 archlinux systemd[1]: matrix-nginx-proxy.service: Main process exited, code=exited, status=125/n/a
Aug 30 16:40:57 archlinux systemd[1]: matrix-nginx-proxy.service: Failed with result 'exit-code'.

```
in this cycle.
