### ISSUE TITLE
Multiple instances of mjolnir

### ISSUE THREAD

**Issue by MichaelSasser** [spantaleev/matrix-docker-ansible-deploy#2115]
**Is your feature request related to a problem? Please describe.**
Since mjolnir is exclusive to one "community" (one control room, that applies to one set of rooms), it would be nice if the playbook supports running multiple instances of mjolnir to deal with any number of communities.

**Describe the solution you'd like**
We could change the configuration to something like this:
 
```yaml
matrix_bot_mjolnir_instances:
  - name: foo  # can be used as suffix, alternatively, we could number the instances
    # maybe one for every instance and one global to disable all instances of mjolnir, 
    # which overwrites all of those switches
    enabled: true
    access_token: "<token 1>"
    management_room: "!foo:domain.tld"
    configuration_extension_yaml: |
      [...]
    [...]
  - name: bar
    enabled: true
    access_token: "<token 2>"
    management_room: "!bar:domain.tld"
    configuration_extension_yaml: |
      [...]
    [...]
```
The image and non-instance specific configuration can still be "global".
Only instance specific configuration would be added to `matrix_bot_mjolnir_instances`.
This can be used like the example below for the `setup_install.yml` from `main.yml`:

```yaml
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  with_items: "{{ matrix_bot_mjolnir_instances }}"
  loop_control:
      loop_var: outer_item  # arbitrary name
  when: "run_setup | bool and matrix_bot_mjolnir_enabled | bool"
  tags:
    - setup-all
    - setup-bot-mjolnir
```

In `{{ role_path }}/tasks/setup_install.yml`, variables, which aren't moved to `matrix_bot_mjolnir_instances` can be used, just like before. Everything inside `matrix_bot_mjolnir_instances` would be addressed with `outer_item.` e.g `"{{ outer_item.name }}"` (or any other variable name specified as `loop_control.loop_var`).

**Describe alternatives you've considered**
Write another role, which basically does the same thing.

**Additional context**
None
