### ISSUE TITLE
Use `matrix_coturn_turn_static_auth_secret` for external turn server

### ISSUE THREAD

**Issue by Samonitari** [spantaleev/matrix-docker-ansible-deploy#2119]
**Describe the bug**
The supplied turn shared secret is not used for synapse (or denrite) config, if external coturn server is used instead of the playbook's one.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_coturn_turn_static_auth_secret: "my_shared_secret"
matrix_coturn_enabled: false
matrix_synapse_turn_uris:
- turn:my.turn.server?transport=tcp
- turn:my.turn.server?transport=udp
```

**Expected behavior**
The `matrix_coturn_turn_static_auth_secret` variable gets inserted into homeserver.yml as `turn_shared_secret`
