### ISSUE TITLE
Failure using method, value must be a string

### ISSUE THREAD

**Issue by ebcoop** [spantaleev/matrix-docker-ansible-deploy#2125]
I'm running Ansible 2.9.21 on Python 3.8.10 on my Fedora laptop. 

This setup previously completely deployed OK, but it was a couple of months ago. I'm now doing a clean install.

A test clean ansible playbook I made to test has a similar issue. 
"Unexpected templating type error occurred, a string or stream input is required"

```
- name: test
  hosts: localhost
  become: no

  vars: 
    string_input: " { foo: 0 } "

    testvar0: "{{ \" { foo: 0 } \" | from_yaml }}"

    testvar1: "{{ ' { foo: 0 } ' | from_yaml }}"

    testvar2: "{{ string_input | from_yaml }}"

  tasks:

  - name: Debug issues 1
    ansible.builtin.debug:
      msg: "{{ testvar0 }}"
  
  - name: Debug issues 2
    ansible.builtin.debug:
      msg: "{{ testvar1 }}"

  - name: Debug issues 3
    ansible.builtin.debug:
      msg: "{{ testvar2 }}"

  - name: Debug issues 4
    ansible.builtin.debug:
      msg: "{{ testvar0 | to_nice_yaml | from_yaml }}"

  - name: Debug issues 5
    ansible.builtin.debug:
      msg: "{{ testvar1 | to_nice_yaml | from_yaml | to_nice_yaml}}"
```

Tests 1, 2, 4, and 5 are all fine, but 3 throws the following error

`fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ string_input | from_yaml }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ string_input | from_yaml }}): a string or stream input is required"}
`

I'm new to Ansible, but I played with all combinations of quotes and brackets and I'm pretty sure it's broken. Is this something I should report to Ansible as well?

In case anyone else is having similar issues, putting some lines like this in my vars.yml to override each problem variable seems to be making progress.

`matrix_mautrix_facebook_configuration_extension: "{{ {} }}"
matrix_synapse_configuration_extension: "{{ {} }}"
matrix_ma1sd_configuration_extension: "{{ {} }}"
`
