### ISSUE TITLE
matrix-postgres-backup image haven't been refreshed

### ISSUE THREAD

**Issue by hooger** [spantaleev/matrix-docker-ansible-deploy#2191]
I encountered the problem when backups in the folder `/matrix/postgres-backup/last` are not cleaned up. After a long debugging session it turned out that my postgres-backup image was 6 months old. `docker pull prodrigestivill/postgres-backup-local:14-alpine` seems to solve it, but that still means a bug in the playbook infrastructure (I run it every week).

```sh
~$ docker image history prodrigestivill/postgres-backup-local:14-alpine
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
ba136cf02839   7 months ago    HEALTHCHECK &{["CMD-SHELL" "curl -f \"http:/_   0B        buildkit.dockerfile.v0
<missing>      7 months ago    CMD ["exec /usr/local/bin/go-cron -s \"$SCHE_   0B        buildkit.dockerfile.v0
<missing>      7 months ago    ENTRYPOINT ["/bin/sh" "-c"]                     0B        buildkit.dockerfile.v0
<missing>      7 months ago    VOLUME [/backups]                               0B        buildkit.dockerfile.v0
<missing>      7 months ago    COPY backup.sh /backup.sh # buildkit            4.71kB    buildkit.dockerfile.v0
<missing>      7 months ago    ENV POSTGRES_DB=**None** POSTGRES_DB_FILE=**_   0B        buildkit.dockerfile.v0
<missing>      7 months ago    RUN |3 GOCRONVER=v0.0.10 TARGETOS=linux TARG_   11.1MB    buildkit.dockerfile.v0
<missing>      7 months ago    ARG TARGETARCH                                  0B        buildkit.dockerfile.v0
<missing>      7 months ago    ARG TARGETOS                                    0B        buildkit.dockerfile.v0
<missing>      7 months ago    ARG GOCRONVER=v0.0.10                           0B        buildkit.dockerfile.v0
<missing>      8 months ago    /bin/sh -c #(nop)  CMD ["postgres"]             0B        
<missing>      8 months ago    /bin/sh -c #(nop)  EXPOSE 5432                  0B        
<missing>      8 months ago    /bin/sh -c #(nop)  STOPSIGNAL SIGINT            0B        
<missing>      8 months ago    /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry_   0B        
<missing>      8 months ago    /bin/sh -c #(nop) COPY file:17f02a384c69f25a_   12kB      
<missing>      8 months ago    /bin/sh -c #(nop)  VOLUME [/var/lib/postgres_   0B        
<missing>      8 months ago    /bin/sh -c mkdir -p "$PGDATA" && chown -R po_   0B        
<missing>      8 months ago    /bin/sh -c #(nop)  ENV PGDATA=/var/lib/postg_   0B        
<missing>      8 months ago    /bin/sh -c mkdir -p /var/run/postgresql && c_   0B        
<missing>      8 months ago    /bin/sh -c set -eux;  cp -v /usr/local/share_   57.4kB    
<missing>      8 months ago    /bin/sh -c set -eux;   wget -O postgresql.ta_   207MB     
<missing>      8 months ago    /bin/sh -c #(nop)  ENV PG_SHA256=2cf78b2e468_   0B        
<missing>      8 months ago    /bin/sh -c #(nop)  ENV PG_VERSION=14.2          0B        
<missing>      10 months ago   /bin/sh -c #(nop)  ENV PG_MAJOR=14              0B        
<missing>      10 months ago   /bin/sh -c mkdir /docker-entrypoint-initdb.d    0B        
<missing>      10 months ago   /bin/sh -c #(nop)  ENV LANG=en_US.utf8          0B        
<missing>      10 months ago   /bin/sh -c set -eux;  addgroup -g 70 -S post_   4.71kB    
<missing>      11 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      11 months ago   /bin/sh -c #(nop) ADD file:9233f6f2237d79659_   5.59MB    
```

My vars file looks like this (comments and passwords removed):

```yaml
matrix_domain: horvath.club

matrix_coturn_enabled: true

matrix_postgres_connection_password: ...
matrix_postgres_backup_enabled: true
matrix_postgres_process_extra_arguments: [
  "-c 'max_connections=200'"
]

matrix_synapse_max_upload_size_mb: 100
matrix_synapse_workers_enabled: true

matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_ssl_lets_encrypt_support_email: ...

matrix_coturn_turn_static_auth_secret: ...

matrix_synapse_macaroon_secret_key: ...

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: ...

matrix_synapse_configuration_extension_yaml: |
  retention:
    enabled: true
    default_policy:
      min_lifetime: 1w
      max_lifetime: 2y
  experimental_features:
    msc2716_enabled: true

matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"

# disable riot
matrix_riot_web_enabled: false
matrix_client_element_enabled: false

# bridges
matrix_mautrix_googlechat_enabled: true
matrix_mautrix_googlechat_configuration_extension_yaml: {bridge: {backfill: {initial_limit: 200}, initial_chat_sync: 5, invite_own_puppet_to_pm: true}}

matrix_mautrix_facebook_enabled: true
matrix_mautrix_facebook_configuration_extension_yaml: {bridge: {sync_direct_chat_list: true, backfill: {initial_limit: 200}, periodic_reconnect: {interval: 6*60*60}, initial_chat_sync: 10, refresh_on_reconnection_fail: true, invite_own_puppet_to_pm: true}}

matrix_mx_puppet_slack_enabled: true
matrix_mx_puppet_slack_configuration_extension_yaml: {namePatterns: {user: ":name (Slack-:team)", room: ":name", group: ":name"}}

matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true

matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: ....
matrix_mautrix_telegram_api_hash: ...
matrix_mautrix_telegram_configuration_extension_yaml: |
  telegram:
    device_info:
        device_model: GooglePixel 6
        system_version: SDK 32
        app_version: 8.7.4 (26367)
        lang_code: en
        system_lang_code: en

matrix_mautrix_signal_enabled: true

matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_database_engine: 'postgres'
matrix_mautrix_discord_database_username: '{{ matrix_postgres_connection_username }}'
matrix_mautrix_discord_database_password: '{{ matrix_postgres_connection_password }}'
matrix_mautrix_discord_database_hostname: 'matrix-postgres'
```
