### ISSUE TITLE
ERROR! the role 'galaxy/com.devture.ansible.role.playbook_help' was not found

### ISSUE THREAD

**Issue by zevlee** [spantaleev/matrix-docker-ansible-deploy#2242]
**Describe the bug**
There appears to be an error with Ansible Galaxy in the playbook.
```
ERROR! the role 'galaxy/com.devture.ansible.role.playbook_help' was not found in /home/ubuntu/matrix-docker-ansible-deploy/roles:/home/ubuntu/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ubuntu/matrix-docker-ansible-deploy

The error appears to be in '/home/ubuntu/matrix-docker-ansible-deploy/setup.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Most of the roles below are not distributed with the playbook, but downloaded separately using `ansible-galaxy` via the `make roles` command (see `Makefile`).
    - role: galaxy/com.devture.ansible.role.playbook_help
      ^ here
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: zevlee.me
matrix_ssl_lets_encrypt_support_email: "**REMOVED SENSITIVE VALUE**"
matrix_coturn_turn_static_auth_secret: "**REMOVED SENSITIVE VALUE**"
matrix_synapse_macaroon_secret_key: "**REMOVED SENSITIVE VALUE**"
matrix_homeserver_generic_secret_key: "**REMOVED SENSITIVE VALUE**"
matrix_nginx_proxy_enabled: false
matrix_ssl_retrieval_method: manually-managed
matrix_ssl_config_dir_path: /etc/letsencrypt
matrix_client_element_enabled: false
matrix_ma1sd_enabled: false
matrix_mailer_enabled: false
matrix_coturn_enabled: true
matrix_coturn_tls_enabled: true
matrix_coturn_tls_cert_path: /etc/letsencrypt/live/matrix.zevlee.me/fullchain.pem
matrix_coturn_tls_key_path: /etc/letsencrypt/live/matrix.zevlee.me/privkey.pem
matrix_architecture: "arm64"
matrix_container_images_self_build: true
matrix_coturn_container_image_self_build_repo_version: "master"
matrix_registration_enabled: false
matrix_synapse_presence_enabled: false
matrix_synapse_configuration_extension_yaml: |
  encryption_enabled_by_default_for_room_type: all
matrix_synapse_max_upload_size_mb: 10000
matrix_postgres_connection_password: "**REMOVED SENSITIVE VALUE**"
matrix_synapse_admin_enabled: false
```

While in the project directory, run `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all`

**Expected behavior**

**Matrix Server:**
Ubuntu Server 22.04, arm64
