### ISSUE TITLE
Syntax error in ansible script

### ISSUE THREAD

**Issue by neonknight** [spantaleev/matrix-docker-ansible-deploy#2253]
**Describe the bug**
when running arbitrary script accounts, e.g.
`ansible-playbook -i inventory/hosts setup.yml --tags=list-matrix-registration-tokens`

I get the following error output:
```
ERROR! the role 'galaxy/com.devture.ansible.role.playbook_state_preserver' was not found in /path/to/matrix-docker-ansible-deploy/roles:/home/lukas/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/path/to/matrix-docker-ansible-deploy

The error appears to be in '/path/to/matrix-docker-ansible-deploy/setup.yml': line 90, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # See: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2217#issuecomment-1301487601
    - when: devture_playbook_state_preserver_enabled | bool
      ^ here
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: "example.com"
matrix_ssl_lets_encrypt_support_email: 'user@example.com'
matrix_coturn_turn_static_auth_secret: '{{ vault_matrix_coturn_turn_static_auth_secret }}'
matrix_synapse_macaroon_secret_key: '{{ vault_matrix_synapse_macaroon_secret_key }}'
matrix_postgres_connection_password: '{{ vault_matrix_postgres_connection_password }}'
matrix_nginx_proxy_base_domain_serving_enabled: false
matrix_common_after_systemd_service_start_wait_for_timeout_seconds: 40
matrix_postgres_backup_enabled: true
matrix_registration_enabled: true
matrix_registration_admin_secret: "{{ vault_matrix_registration_admin_secret }}"
matrix_synapse_configuration_extension_yaml: |
  old_signing_keys:
    "ed25519:asdfasdf": { key: "asdfasdf", expired_ts: 123123 }
matrix_synapse_url_preview_enabled: false
matrix_bot_matrix_reminder_bot_enabled: true
matrix_bot_matrix_reminder_bot_matrix_user_password: "{{ vault_matrix_bot_matrix_reminder_bot_matrix_user_password }}"
matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/Zurich
matrix_dimension_enabled: true
matrix_dimension_access_token: "{{ vault_matrix_dimension_access_token }}"
matrix_dimension_admins:
  - "@admin1:{{ matrix_domain }}"
  - "@admin2:{{ matrix_domain }}"
matrix_bot_go_neb_enabled: false 
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_mailer_sender_address: "matrix@example.com"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "mail.example.com"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "matrix@example.com"
matrix_mailer_relay_auth_password: "{{ vault_matrix_mailer_relay_auth_password }}"
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "{{ vault_synapse_ext_password_provider_shared_secret_auth_shared_secret }}"
matrix_well_known_matrix_client_configuration_extension_json: |
  {
    "m.tile_server": {
      "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=asdfasdf"
    }
  }
matrix_client_element_configuration_extension_json: |
  {
      "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=asdfasdf"
  }

```

**Expected behavior**
ansible script runs and presents understandable green success output, not a red syntax error

**Matrix Server:**
 - OS: Debian 11
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible: local computer with debian 11
- what version of Ansible you're running: ansible 2.10.8
