### ISSUE TITLE
[custom/matrix-synapse : Check Matrix Client API] fails

### ISSUE THREAD

**Issue by makoeppel** [spantaleev/matrix-docker-ansible-deploy#2267]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: "matrix.MYDOMAIN"
matrix_server_fqn_matrix: "matrix.MYDOMAIN"
matrix_server_fqn_element: "element.MYDOMAIN"
matrix_server_fqn_dimension: "dimension.MYDOMAIN"
matrix_server_fqn_jitsi: "jitsi.MYDOMAIN"

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'MYKEY'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'MYMAIL'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: 'MYPW'

matrix_jitsi_enabled: true

# Run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
# or define your own strong passwords manually.
matrix_jitsi_jicofo_auth_password: "MYPW"
matrix_jitsi_jvb_auth_password: "MYPW"
matrix_jitsi_jibri_recorder_password: "MYPW"
matrix_jitsi_jibri_xmpp_password: "MYPW"

matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true

matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@dimension:matrix.MYDOMAIN"
matrix_dimension_access_token: "MYTOKEN"

matrix_bot_postmoogle_enabled: false
# matrix_bot_postmoogle_login: postmoogle
matrix_bot_postmoogle_password: "MYPW"
```

**Matrix Server:**
 - OS: Ubuntu 21.04

**Problem description**:
Hi all,

as you can see I setup my server using matrix_domain as matrix.MYDOMAIN since I do have another service running on MYDOMAIN. The proxy (NGINX) on MYDOMAIN is set to:
```
# config for matrix proxy
server {
  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
  ssl_ecdh_curve X25519:X448:secp384r1:secp256k1;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;
  index index.php index.html;
  client_max_body_size 0;
  root /web;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  server_name MYDOMAIN;
  server_tokens off;

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }

  if ($scheme = http) {
    return 301 https://$host$request_uri;
  }

  location /.well-known/matrix {
    proxy_pass https://matrix.MYDOMAIN/.well-known/matrix;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}
```
With this its also possible to see the the response of https://MYDOMAIN.well-known/matrix/server: 

```json
m.server | "matrix.MYDOMAIN:8448"
```

However running `ansible-playbook -i inventory/hosts setup.yml --tags=self-check` results in the error:

```
fatal: [matrix.MYDOMAIN]: FAILED! => changed=false                                                                                                                                                                                                                                                                               
  msg: 'Failed checking Matrix Client API is up at `matrix.MYDOMAIN` (checked endpoint: `https://matrix.MYDOMAIN/_matrix/client/versions`). Is Synapse running? Is port 443 open in your firewall? Full error: {''redirected'': False, ''url'': ''https://matrix.MYDOMAIN/_matrix/client/versions'', ''status'': 502, '
'server'': ''nginx'', ''date'': ''Tue, 15 Nov 2022 19:36:04 GMT'', ''content_type'': ''text/html'', ''content_length'': ''150'', ''connection'': ''close'', ''permissions_policy'': ''interest-cohort=()'', ''strict_transport_security'': ''max-age=31536000; includeSubDomains'', ''elapsed'': 0, ''changed'': False, ''failed'': Tr
ue, ''msg'': ''Status code was 502 and not [200]: HTTP Error 502: Bad Gateway''}
```
Connecting to element.MYDOMAIN gives me: connection to homeserver failed. Also https://federationtester.matrix.org/ gives me an 502 error.

With changing the `vars.yml` file to:
```yaml
matrix_domain: "matrix.MYDOMAIN"
#matrix_server_fqn_matrix: "matrix.MYDOMAIN"
#matrix_server_fqn_element: "element.MYDOMAIN"
#matrix_server_fqn_dimension: "dimension.MYDOMAIN"
#matrix_server_fqn_jitsi: "jitsi.MYDOMAIN"
...
```
I am able to connect to the server but I can't join any other matrix rooms. I am a bit lost at the moment and don't really know how to resolve the issue.

Best regards,
Marius
