### ISSUE TITLE
Setup/Upgrade fails with grafana enabled

### ISSUE THREAD

**Issue by lemmy04** [spantaleev/matrix-docker-ansible-deploy#2288]
**Describe the bug**
I'm running the play (git checkout as of a couple minutes ago) with --tags=setup-all and it fails to pull grafana:

TASK [custom/matrix-grafana : Ensure matrix-grafana image is pulled] *************************************************************************************
FAILED - RETRYING: [matrix.eregion.de]: Ensure matrix-grafana image is pulled (10 retries left).
FAILED - RETRYING: [matrix.eregion.de]: Ensure matrix-grafana image is pulled (9 retries left).

**To Reproduce**
My `vars.yml` file looks like this: (only grafana parts)

```yaml
lemmy@kumiko:~/Work/matrix.eregion.de/matrix-docker-ansible-deploy/inventory/host_vars> grep -i grafa matrix.eregion.de/*
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: false
matrix_grafana_default_admin_user: "xxx"
matrix_grafana_default_admin_password: "xxx"
```

I'm running the play as usual:
``ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start``

**Expected behavior**
Last time I re-ran the play it still worked... now it doesn't.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture X86_64

**Workaround:**
disable grafana in vars.yml, that way I at least have my matrix server up and running ;)
