### ISSUE TITLE
Postmoogle bot with new multi-domain config

### ISSUE THREAD

**Issue by Gregivy** [spantaleev/matrix-docker-ansible-deploy#2292]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_bot_postmoogle_enabled: true
matrix_bot_postmoogle_password: "***"
matrix_bot_postmoogle_domains:
  - "my.domain"
  - "{{ matrix_server_fqn_matrix }}"
```

**Problem description**:

I have added second level domain `my.domain` at the beginning of the list, and updated my DNS:
```
TXT  _dmarc.matrix  v=DMARC1; p=quarantine;
TXT  _dmarc  v=DMARC1; p=quarantine;
TXT  matrix  v=spf1 ip4:myip -all
TXT  @  v=spf1 ip4:myip -all
TXT  postmoogle._domainkey  dkimkey
TXT  postmoogle._domainkey.matrix  dkimkey

MX  @  my.domain
MX  matrix  matrix.my.domain
```

The bot seems to recognise this setting as it shows 2 mailboxes (one for _my.domain_, the other for _matrix.my.domain_). I am able to send emails via the bot from both of these domains, however I receive only from _matrix.my.domain_. Messages sent to _my.domain_ don't show up inside the matrix room.

@etkecc I will be grateful if you could check this.
