### ISSUE TITLE
Systemd service manager blocks playbook run

### ISSUE THREAD

**Issue by throny** [spantaleev/matrix-docker-ansible-deploy#2295]
**Describe the bug**
```
TASK [galaxy/com.devture.ansible.role.systemd_service_manager : Ensure systemd services are stopped] ***************************************************************************************************************************************
fatal: [matrix.X.X]: FAILED! => 
  msg: '''dict object'' has no attribute ''priority,name'''
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: 'X.X'
matrix_server_fqn_matrix: 'matrix.X.X'
matrix_server_fqn_element: 'chat.X.X'
matrix_homeserver_implementation: synapse
matrix_playbook_docker_installation_enabled: false
matrix_homeserver_generic_secret_key: 'X'
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: ''
matrix_nginx_proxy_container_federation_host_bind_port: ''
matrix_nginx_proxy_trust_forwarded_proto: true
matrix_nginx_proxy_x_forwarded_for: '$proxy_add_x_forwarded_for'
matrix_coturn_enabled: false
matrix_docker_network: 'https-proxy'
matrix_nginx_proxy_container_extra_arguments:
  - '--env "VIRTUAL_HOST={{ matrix_server_fqn_matrix }},{{ matrix_server_fqn_element }},{{ matrix_server_fqn_jitsi }},{{ matrix_server_fqn_dimension }}"'
  - '--env "VIRTUAL_PORT=8080"'
  - '--env "LETSENCRYPT_HOST={{ matrix_server_fqn_matrix }},{{ matrix_server_fqn_element }},{{ matrix_server_fqn_jitsi }},{{ matrix_server_fqn_dimension }}"'
matrix_synapse_http_listener_resource_names: ["client","federation","openid"]
matrix_federation_public_port: 443
matrix_synapse_federation_port_enabled: false
matrix_postgres_connection_password: 'X'
matrix_mailer_sender_address: "matrix@X.X"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "mail.X.X"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "matrix@X.X"
matrix_mailer_relay_auth_password: "X"
devture_systemd_service_manager_up_verification_delay_seconds: 60
matrix_dimension_enabled: true
matrix_server_fqn_dimension: 'dimension.X.X'
matrix_dimension_admins:
  - "@X:{{ matrix_domain }}"
matrix_dimension_access_token: "X"
matrix_dimension_database_engine: 'postgres'
matrix_dimension_database_password: 'X'
matrix_dimension_container_extra_arguments:
  - '--env "VIRTUAL_HOST={{ matrix_server_fqn_dimension }}"'
  - '--env "VIRTUAL_PORT=8184"'
  - '--env "LETSENCRYPT_HOST={{ matrix_server_fqn_dimension }}"'
matrix_dimension_homeserver_federationUrl: "https://matrix.X.X/"
matrix_synapse_admin_enabled: true
matrix_synapse_admin_container_extra_arguments:
  - '--env "VIRTUAL_HOST=X.X.X"'
  - '--env "VIRTUAL_PORT=80"'
  - '--env "LETSENCRYPT_HOST=X.X.X"'
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'X'
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_bridge_encryption_allow: true
matrix_mautrix_whatsapp_database_engine: 'postgres'
matrix_mautrix_whatsapp_database_password: 'X'
matrix_synapse_presence_enabled: false
matrix_postgres_process_extra_arguments: [
  "-c max_connections=100",
  "-c shared_buffers=8GB",
  "-c checkpoint_completion_target=0.9",
  "-c wal_buffers=16MB",
  "-c default_statistics_target=100",
  "-c random_page_cost=4",
  "-c effective_io_concurrency=2",
  "-c work_mem=10485kB",
  "-c min_wal_size=1GB",
  "-c max_wal_size=4GB",
  "-c max_worker_processes=8",
  "-c max_parallel_workers_per_gather=4",
  "-c max_parallel_workers=8",
  "-c max_parallel_maintenance_workers=4",
  "-c effective_cache_size=24GB",
  "-c maintenance_work_mem=2GB",
]

```

**Expected behavior**
Starting the Matrix Services.

**Matrix Server:**
 - OS: Ubuntu 20.04.5 LTS
 - Architecture amd64

**Ansible:**
Running locally: ansible [core 2.12.10]
