### ISSUE TITLE
matrix-synapse service fails to start

### ISSUE THREAD

**Issue by drwahl** [spantaleev/matrix-docker-ansible-deploy#2325]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: drwahl.me
matrix_ssl_lets_encrypt_support_email: <redacted>
matrix_coturn_turn_static_auth_secret:  <redacted>
matrix_synapse_macaroon_secret_key:  <redacted>
devture_postgres_connection_password: <redacted>
matrix_prometheus_enabled: true
matrix_prometheus_node_exporter_enabled: true
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: false
matrix_grafana_default_admin_user: <redacted>
matrix_grafana_default_admin_password: <redacted>
matrix_synapse_admin_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: <redacted>
matrix_registration_enabled: true
matrix_registration_admin_secret: <redacted>
matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@<redacted>:{{ matrix_domain }}"
matrix_dimension_access_token: <redacted>
matrix_mautrix_whatsapp_version: latest
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_googlechat_enabled: true
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true
matrix_mx_puppet_discord_enabled: false
matrix_mx_puppet_slack_enabled: true
matrix_appservice_webhooks_enabled: true
matrix_appservice_webhooks_api_secret: <redacted>
matrix_appservice_webhooks_log_level: 'info'
matrix_mx_puppet_instagram_enabled: true
matrix_mx_puppet_steam_enabled: true
matrix_bot_matrix_reminder_bot_enabled: true
matrix_bot_matrix_reminder_bot_matrix_user_password: <redacted>
matrix_bot_matrix_reminder_bot_reminders_timezone: MST
matrix_s3_media_store_enabled: true
matrix_s3_media_store_bucket_name: "drwahl-matrix"
matrix_s3_media_store_aws_access_key: <redacted>
matrix_s3_media_store_aws_secret_key: <redacted>
matrix_s3_media_store_region: "us-east-1"
matrix_s3_media_store_custom_endpoint_enabled: true
matrix_s3_media_store_custom_endpoint: <redacted>
matrix_jitsi_enabled: true
matrix_jitsi_jicofo_auth_password: <redacted>
matrix_jitsi_jvb_auth_password: <redacted>
matrix_jitsi_jibri_recorder_password: <redacted>
matrix_jitsi_jibri_xmpp_password: <redacted>
matrix_jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
  config.disableAudioLevels = false;
  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 4;
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_mautrix_facebook_enabled: true
matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
    community_template: "unofficial/facebook_{localpart}={server}"
matrix_synapse_configuration_extension_yaml: |
  enable_group_creation: true
  group_creation_prefix: "unofficial/"
matrix_etherpad_enabled: true
matrix_hookshot_enabled: true
matrix_hookshot_gitlab_enabled: true
matrix_hookshot_gitlab_instances:
  git.drwahl.me:
    url: https://git.drwahl.me
matrix_hookshot_gitlab_webhook_secret: <redacted>
matrix_synapse_log_level: "INFO"
matrix_synapse_storage_sql_log_level: "INFO"
matrix_synapse_root_log_level: "INFO"
```

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture: amd64

**Problem description**:

After deploying matrix with `setup.yaml`, the `matrix-synapse` service/container fails to start. When running with `service matrix-synapse start`, systemd continuously restarts the docker container with very little in the logs (simply saying it's starting, then says stopped, then starting again). If I copy the command out of the systemd service file and paste it into my shell, the container launches successfully works as expected, so this seems specific to systemd somehow.

**Additional context**
This deployment was working for quite some time. At some point within the last 6 months or so, I started to notice this behaviour. My workaround has just been to run the launch command from a root shell, which launches the container and everything "just works" at that point.
