### ISSUE TITLE
Do not want the server name to be matrix.{domain-name.com}, how do I change 'matrix' to 'chat'?

### ISSUE THREAD

**Issue by sobriant74** [spantaleev/matrix-docker-ansible-deploy#2331]
I want it to be chat.domain.com but I cant seem to get the ansible playbook to stop defaulting to matrix.domain.com
Anyone know where the setting is in the defaults to make that change?
My DNS is correct, I've successfully used letsencrypt on my test servers and been running Element against the test server for a week.
Just need to know where I need to change in this wonderful playbook, so it doesnt pre-pend "matrix".
error while running playbook with command: ansible-playbook -i inventory/hosts setup.yml --tags=install-all,ensure-matrix-users-created,start
Error:
 Requesting a certificate for matrix.domain.com

    Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
      Domain: matrix.domain.com
      Type:   unauthorized
      Detail: 50.57.29.53: Invalid response from http://matrix.domain.com/.well-known/acme-challenge/EVwysdqZqVtfiE7d7shRJAzQREAD469cHhN-830M71Y: 404

hosts file: [matrix_servers]
chat.{domainnameredacted}.com ansible_host={localIP for internal matrix server} ansible_ssh_user=root ansible_connection=local

**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: redacteddomain.com

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'itsasecret'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'sysadmins@domain.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'password'
#sets up synapse admin to allow online administration
matrix_synapse_admin_enabled: true

matrix_prometheus_enabled: true

# You can remove this, if unnecessary.
matrix_prometheus_node_exporter_enabled: true

# You can remove this, if unnecessary.
matrix_prometheus_postgres_exporter_enabled: true

# You can remove this, if unnecessary.
matrix_prometheus_nginxlog_exporter_enabled: true
matrix_grafana_enabled: true

matrix_grafana_anonymous_access: false

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
matrix_grafana_default_admin_user: "statsadmin"

# Changing the password subsequently won't work.
matrix_grafana_default_admin_password: "password"
#ldap
matrix_synapse_ext_password_provider_ldap_enabled: true
matrix_synapse_ext_password_provider_ldap_mode: "search"
matrix_synapse_ext_password_provider_ldap_uri: "ldap://domain.local:389"
matrix_synapse_ext_password_provider_ldap_base: "OU=Users,DC=domain,DC=local"
matrix_synapse_ext_password_provider_ldap_active_directory: true
matrix_synapse_ext_password_provider_ldap_default_domain: "domain.local"
matrix_synapse_ext_password_provider_ldap_attributes_uid: "userPrincipalName"
matrix_synapse_ext_password_provider_ldap_attributes_mail: "mail"
matrix_synapse_ext_password_provider_ldap_attributes_name: "givenName"
matrix_synapse_ext_password_provider_ldap_bind_dn: "CN=Matrix Synapse Svc Account,OU=System Maintenance Users,OU=Users,DC=domain,DC=local"
matrix_synapse_ext_password_provider_ldap_bind_password: "password"
```

**Matrix Server:**
 - Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- on the server its installing to
- what version of Ansible you're running (see `ansible --version`)
ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

I'm setting up an internal Matrix server, had a couple of ones I setup successfully to run synapse from a docker, now I want to get one in production using the Ansible playbook and installing with all the bells and whistles including grafana and synapse_admin. I want it to be chat.domain.com but I cant seem to get the ansible playbook to stop defaulting to matrix.domain.com
