### ISSUE TITLE
Cannot get jitsi to install: "device or resource busy"

### ISSUE THREAD

**Issue by briankendall** [spantaleev/matrix-docker-ansible-deploy#2368]
**Playbook Configuration**:

The relevant excerpt from my `vars.yml` file:

```yaml

matrix_domain: mydomain.com
matrix_homeserver_generic_secret_key: '[redacted]'
matrix_coturn_turn_static_auth_secret: '[redacted]'
matrix_synapse_macaroon_secret_key: '[redacted]'
devture_postgres_connection_password: '[redacted]'
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: ''
matrix_nginx_proxy_container_federation_host_bind_port: ''
matrix_coturn_enabled: false
matrix_nginx_proxy_container_additional_networks: ['webservers']
matrix_nginx_proxy_trust_forwarded_proto: true
matrix_nginx_proxy_x_forwarded_for: '$proxy_add_x_forwarded_for'

matrix_jitsi_enabled: true
matrix_jitsi_jicofo_auth_password: "[redacted]"
matrix_jitsi_jvb_auth_password: "[redacted]"
matrix_jitsi_jibri_recorder_password: "[redacted]"
matrix_jitsi_jibri_xmpp_password: "[redacted]"
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_prosody_auth_internal_accounts:
  - username: "[redacted]"
    password: "[redacted]"
matrix_jitsi_jvb_container_extra_arguments:
  - '--env "DOCKER_HOST_ADDRESS=[server local IP]"'
  - '--env "ENABLE_XMPP_WEBSOCKET=1"'
matrix_jitsi_web_config_resolution_width_ideal_and_max: 1920
matrix_jitsi_web_config_resolution_width_min: 1920
matrix_jitsi_web_config_resolution_height_ideal_and_max: 1080
matrix_jitsi_web_config_resolution_height_min: 1080
matrix_jitsi_web_custom_config_extension: |
  config.desktopSharingFrameRate = { min: 30, max: 30 };
```

**Matrix Server:**
 - OS: Debian 11.2
 - Architecture amd64

**Ansible:**
- Running on macOS 10.14
- Ansible version: 2.13.1
- Python version: 3.10.8

**Problem description**:

Attempts at setting up and running jitsi fail with the following error:

```
TASK [custom/matrix-jitsi : Ensure matrix-jitsi-prosody container is running] ****************************************************************
fatal: [matrix.mydomain.com]: FAILED! => changed=false
  msg: 'Error loading unit file ''matrix-jitsi-prosody'': System.Error.EBUSY "Unit matrix-jitsi-prosody.service failed to load properly: Device or resource busy."'
```

**Additional context**
I'm attempting to completely reinstall Matrix after accidentally wrecking its database. I followed the manual uninstallation instructions to remove it, and then started again from scratch. I've got everything I wanted set up, with the exception of Jitsi. I tried resetting Jitsi [as suggested here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md#troubleshooting) but it didn't help.

I haven't changed anything Jitsi-related in my vars.yml from my last Matrix installation where it installed without issue, so I have no idea why it's failing now.

All of my matrix services are accessible via a separate reverse proxy that I manage myself (hence the use of `matrix_nginx_proxy_container_additional_networks`).
