### ISSUE TITLE
Dendrite: user registration via ansible playbook doesn't work

### ISSUE THREAD

**Issue by sensor-freak** [spantaleev/matrix-docker-ansible-deploy#2369]
**Describe the bug**
Trying to register a new Dendrite user with the playbook fails.

The error message from the playbook is:
```
TASK [custom/matrix-dendrite : Register user] ************************************************************************************************************
fatal: [inka-23]: FAILED! =>
  msg: 'template error while templating string: expected token '':'', got ''}''. String: {{ {{ matrix_dendrite_bin_path }} }}/create-account {{ username | quote }} {{ password | quote }} {{ ''1'' if admin == ''yes'' else ''0'' }}. expected token '':'', got ''}'''
```
The user is not yet created at this point

**To Reproduce**
Execute the following command:
```
ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=user password=password admin=no' --tags=register-user
```

**Expected behavior**
Executing the playbook succeeds and the user is created.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture amd64

**Ansible:**
- where you run Ansible: remote computer (Windows 11, WSL2, Kali Linux)
- what version of Ansible you're running: 2.14.1

**Client:**
n/a

**Additional context**
It seems to me that the problem is caused by doubled usage of `{{` and `}}` in file `roles\custom\matrix-dendrite\tasks\register_user.yml` (line 32):

```yaml
- name: Register user
  ansible.builtin.command:
    cmd: "{{ {{ matrix_dendrite_bin_path }} }}/create-account {{ username | quote }} {{ password | quote }} {{ '1' if admin == 'yes' else '0' }}"
  register: matrix_dendrite_register_user_result
  changed_when: matrix_dendrite_register_user_result.rc == 0
```

Changing the line starting with `cmd: ` seems to solve the problem:
```yaml
    cmd: "{{ matrix_dendrite_bin_path }}/create-account {{ username | quote }} {{ password | quote }} {{ '1' if admin == 'yes' else '0' }}"
```

(Sorry for not providing a pull request. I haven't created a fork from this repo yet.)
