### ISSUE TITLE
'user' is undefined

### ISSUE THREAD

**Issue by RobertDWhite** [spantaleev/matrix-docker-ansible-deploy#2374]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml

#
# Example value: example.com
matrix_domain: xxxxx.com

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'xxxxx'

matrix_ssl_lets_encrypt_support_email: 'xxxxx'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'xxxxx'

# Enable nginx proxy to serve base domain and .well-known
matrix_nginx_proxy_base_domain_serving_enabled: true

# Enable prometheus which is a time series database for
# holding metrics
matrix_prometheus_enabled: true

# Addon to prometheus that collects generic system
# information such as CPU, memory, filesystem, and even
# system temperatures
matrix_prometheus_node_exporter_enabled: true

# Addon to prometheus that collects metrics about postgres
matrix_prometheus_postgres_exporter_enabled: true

# Enables grafana web interface for viewing metrics in
# prometheus
matrix_grafana_enabled: true

# Disables anonymous access to grafana
matrix_grafana_anonymous_access: false

# Sets default credentials for grafana access
matrix_grafana_default_admin_user: "xxxxx"
matrix_grafana_default_admin_password: "xxxxx"

# Enable token and link based account registration
matrix_registration_enabled: true

# Set admin secret for generating tokens and links
matrix_registration_admin_secret: "xxxxx"

# Enable automatic postgres backups
devture_postgres_backup_enabled: true

# Setup what postgres backups to keep
devture_postgres_backup_keep_days: 3
devture_postgres_backup_keep_weeks: 0
devture_postgres_backup_keep_months: 0

# Set coturn auth secret
matrix_coturn_turn_static_auth_secret: 'xxxxx'

# Enable workers for better performance and use workers
# preset one-of-each
matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: one-of-each

# Turn off synapse open sign ups
matrix_synapse_enable_registration: true

# Set database transaction limit
matrix_synapse_database_txn_limit: 10000

# Set allowing public rooms over federation
matrix_synapse_allow_public_rooms_over_federation: true

# Turn off presense status for better performance
matrix_synapse_presence_enabled: false

# Enable synapse admin
matrix_synapse_admin_enabled: true

# Enable guest access
matrix_synapse_allow_guest_access: false

#Enable external password provider
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'xxxxx'

# Disable local identity server
matrix_ma1sd_enabled: false

# Add email based verification
matrix_synapse_registrations_require_3pid: ['email']
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true
matrix_mautrix_signal_enabled: true
matrix_mailer_sender_address: "matrix@xxxxx.com"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "10.100.3.10"
matrix_mailer_relay_host_port: 25
matrix_mailer_relay_auth: false
```

**Matrix Server:**
 - OS: Ubuntu 22.10 (also tried Ubuntu 21.04 and 20.04)
 - Architecture: amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- on another ansible server. Tried Ubuntu 20.04, 21.04, and 22.10. Standard installation
- what version of Ansible you're running: currently running 2.14.1. Same error on 2.13.x

**Problem description**:

Receiving the following error when deploying via
```
sudo ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start --ask-pass --ask-become-pass
```
Error:
```
fatal: [matrix.xxxxxxx.com]: FAILED! =>
msg: |-
    The task includes an option with an undefined variable. The error was: {{ matrix_synapse_configuration_yaml | from_yaml | combine(matrix_synapse_configuration_extension, recursive=True) }}: {{ lookup('template', 'templates/synapse/homeserver.yaml.j2') }}: 'user' is undefined

    The error appears to be in '/home/xxxxx/matrix-docker-ansible-deploy/roles/custom/matrix-synapse/tasks/synapse/setup_install.yml': line 111, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: Ensure Synapse homeserver config installed
      ^ here
```

**Additional context**
```make roles``` ran successfully. connections are fine. I am up to date with the Git repo. this is the only error I have at this point (everything else has been able to be relatively easily troubleshooted). this particular error has persisted across distro upgrades, ansible upgrades, etc.
