### ISSUE TITLE
Potential CORS issues in nginx with Etherpad, ma1sd, and jitsi

### ISSUE THREAD

**Issue by ctwelve** [spantaleev/matrix-docker-ansible-deploy#2397]
**Describe the bug**
On a clean install of the playbook in Amazon Web Services to a Debian VM, using existing data:

- Etherpad complains about embedding within the client (likely a CORS issue) but works fine with standalone URL
- Jitsi is having strange connection issues to nginx and is throwing weird log errors: `nginx: [emerg] host not found in upstream "etherpad.arkmuse.org" in /config/nginx/meet.conf:104`
- Because of this, jitsi refuses to start and this is breaking audio/video chat on my server
- Additionally, ma1sd seems totally unresponsive
- I think there is something fundamentally wrong with the generated nginx config but I'm not clever/experiened enough to deduce what it might be

**To Reproduce**
1. Save data. In my case, all file object data is safely in S3 and the database in Amazon RDS
2. Spin up new Debian VM, run `apt update && apt upgrade` and restart
3. Run the playbook on the new server and swing DNS to move production load to new server

If I do this, it will 100% of the time produce the errors above

```yaml
## BASE CONFIGURATION
matrix_domain: 'arkmuse.org'
matrix_base_data_path: '/srv/matrix'

matrix_synapse_workers_enabled: true
matrix_client_element_themes_enabled: true
matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_ssl_lets_encrypt_support_email: 'webmaster@arkmuse.org'

matrix_coturn_turn_external_ip_address: 54.162.34.150
matrix_coturn_turn_static_auth_secret: '$SEKRIT'

matrix_synapse_report_stats: true
matrix_synapse_admin_enabled: true
matrix_homeserver_generic_secret_key: '$SEKRIT'

# Enable self-registration and ID federation
matrix_synapse_enable_registration: true
matrix_synapse_enable_registration_captcha: true
matrix_synapse_registrations_require_3pid: 'msisdn'
matrix_synapse_recaptcha_public_key: '$SEKRIT'
matrix_synapse_recaptcha_private_key: '$SEKRIT'
matrix_synapse_allow_public_rooms_over_federation: true
matrix_synapse_auto_join_rooms:
  - '#arkmuse:arkmuse.org'
  - '#general:arkmuse.org'
  - '#tech-support:arkmuse.org'
  - '#memes:arkmuse.org'

# Enable 3PID manager
matrix_ma1sd_enabled: true
matrix_ma1sd_synapsesql_enabled: true
matrix_ma1sd_verbose_logging: true
matrix_ma1sd_matrixorg_forwarding_enabled: true
matrix_ma1sd_configuration_extension_yaml: |
  register:
    policy:
      allowed: true
      threepid:
        email:
          domain:
            blacklist: ~
            whitelist: ~
  threepid:
    medium:
      msisdn:
        connectors:
          twilio:
            account_sid: '$SEKRIT'
            auth_token: '$SEKRIT'
            number: '+$SEKRIT'

# Enable outbound email
matrix_mailer_sender_address: 'matrix@arkmuse.org'
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: 'email-smtp.us-east-1.amazonaws.com'
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: '$SEKRIT'
matrix_mailer_relay_auth_password: '$SEKRIT'

# Configure Dimension
matrix_dimension_enabled: true
matrix_dimension_admins:
  - '@$SEKRIT:{{ matrix_domain }}'
  - '@$SEKRIT:{{ matrix_domain }}'
matrix_dimension_access_token: '$SEKRIT'

# Etherpad
matrix_etherpad_enabled: true

# Statistics
matrix_prometheus_enabled: true
matrix_prometheus_node_exporter_enabled: true
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: true
matrix_grafana_default_admin_user: '$SEKRIT'
matrix_grafana_default_admin_password: '$SEKRIT'

# Multimedia conferencing
matrix_jitsi_enabled: true
matrix_jitsi_jicofo_component_secret: '$SEKRIT'
matrix_jitsi_jicofo_auth_password: '$SEKRIT'
matrix_jitsi_jvb_auth_password: '$SEKRIT'
matrix_jitsi_jibri_recorder_password: '$SEKRIT'
matrix_jitsi_jibri_xmpp_password: '$SEKRIT'

# Mjolnir
matrix_bot_mjolnir_enabled: true
matrix_bot_mjolnir_access_token: '$SEKRIT'
matrix_bot_mjolnir_management_room: '!$SEKRIT:arkmuse.org'

matrix_synapse_ext_spam_checker_mjolnir_antispam_enabled: true
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_invites: true
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_messages: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_block_usernames: false
matrix_synapse_ext_spam_checker_mjolnir_antispam_config_ban_lists: []

## DATABASE
devture_postgres_enabled: false
# matrix_synapse_connection_password: '$SEKRIT'
# matrix_synapse_connection_username: 'matrix'

# Synapse
matrix_synapse_database_host: 'ark-matrix.$SEKRIT.us-east-1.rds.amazonaws.com'
matrix_synapse_database_user: 'matrix_synapse'
matrix_synapse_database_password: '$SEKRIT'
matrix_synapse_database_database: 'matrix_synapse'

# Dimension
matrix_dimension_database_engine: 'postgres'
matrix_dimension_database_hostname: 'ark-matrix.$SEKRIT.us-east-1.rds.amazonaws.com'
matrix_dimension_database_username: 'matrix_dimension'
matrix_dimension_database_password: '$SEKRIT'
matrix_dimension_database_name: 'matrix_dimension'

# Etherpad
matrix_etherpad_database_engine: 'postgres'
matrix_etherpad_database_hostname: 'ark-matrix.$SEKRIT.us-east-1.rds.amazonaws.com'
matrix_etherpad_database_username: 'matrix_etherpad'
matrix_etherpad_database_password: '$SEKRIT'
matrix_etherpad_database_name: 'matrix_etherpad'

# ma1sd
matrix_ma1sd_database_engine: 'postgres'
matrix_ma1sd_database_hostname: 'ark-matrix.$SEKRIT.us-east-1.rds.amazonaws.com'
matrix_ma1sd_database_username: 'matrix_ma1sd'
matrix_ma1sd_database_password: '$SEKRIT'
matrix_ma1sd_database_name: 'matrix_ma1sd'

## AMAZON S3
matrix_synapse_ext_synapse_s3_storage_provider_enabled: true
matrix_synapse_ext_synapse_s3_storage_provider_config_bucket: ark-matrix
matrix_synapse_ext_synapse_s3_storage_provider_config_region_name: us-east-1
matrix_synapse_ext_synapse_s3_storage_provider_config_endpoint_url: https://s3.us-east-1.amazonaws.com # adjust this
matrix_synapse_ext_synapse_s3_storage_provider_config_access_key_id: '$SEKRIT'
matrix_synapse_ext_synapse_s3_storage_provider_config_secret_access_key: '$SEKRIT'
matrix_synapse_ext_synapse_s3_storage_provider_config_storage_class: STANDARD
```

**Expected behavior**
Obviously, I expect all these services to communicate correctly with each other on setup-all. Not even multiple runs of setup-all seems to address the issue.

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture: amd64
 - VM: `t3a.medium`

**Client:**
 - Device: Element standalone
 - OS: Multiple: macOS, Windows, Linux
 - Version: any current

**Additional context**
This was previously working, but due to hosting reasons I needed to move to AWS. It is only on constructing this new server from blank that this happens. I have not yet tested to see if this is specific to new servers on AWS, though that seems far-fetched.
