### ISSUE TITLE
Matrix-registration: 404 error when trying to generate token or open registration page

### ISSUE THREAD

**Issue by pekkalaaksonen** [spantaleev/matrix-docker-ansible-deploy#2400]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: example.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key:  'secret_key'
matrix_ssl_lets_encrypt_support_email: 'my.email@example.com'
devture_postgres_connection_password: 'secret_password'
matrix_nginx_proxy_enabled: false
matrix_synapse_reverse_proxy_companion_container_client_api_host_bind_port: '0.0.0.0:8008'
matrix_synapse_reverse_proxy_companion_container_federation_api_host_bind_port: '0.0.0.0:8048'
matrix_client_element_container_http_host_bind_port: "0.0.0.0:8765"
matrix_ssl_retrieval_method: none
matrix_registration_enabled: true
matrix_registration_admin_secret: "admin_secret"
```

**Matrix Server:**
 - OS: Ubuntu 22.04.1
 - Architecture amd64

**Problem description**:

I have enabled Matrix registration but I'm unable to generate tokens and I'm not able to navigate to registration page.

When trying to create token I'm getting following error: `msg: 'Status code was 404 and not [200]: HTTP Error 404: Not Found'`. 

```

$ ansible-playbook -i inventory/hosts setup.yml --tags=generate-matrix-registration-token --extra-vars="one_time=yes ex_date=2023-12-31"
.
.
.
TASK [custom/matrix-registration : Call matrix-registration token creation API] ************************************************************************************************************************************************************************************************
fatal: [matrix.example.com]: FAILED! => changed=false
  connection: close
  content_length: '146'
  content_type: text/html
  date: Wed, 18 Jan 2023 06:41:13 GMT
  elapsed: 0
  msg: 'Status code was 404 and not [200]: HTTP Error 404: Not Found'
  permissions_policy: interest-cohort=()
  redirected: false
  server: nginx
  status: 404
  strict_transport_security: max-age=31536000; includeSubDomains
  url: https://matrix.example.com/matrix-registration/token

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
matrix.example.com   : ok=6    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

```

When I try to navigate to `https://matrix.example.com/matrix-registration/register`I'm getting the same error: `404 Not Found`. I'm using my own Nginx web server and everything else works as expected. I can login to `element.example.com` etc.

I have ensured that matrix-registration docker container is running:

```
$ docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED        STATUS                  PORTS                                                                                                                                                                                                                                               NAMES
e55edf2334fa   zeratax/matrix-registration:v0.7.2   "matrix-registration…"   10 hours ago   Up 10 hours             127.0.0.1:8767->5000/tcp                                                                                                                                                                                                                            matrix-registration
a58cdd42a83d   vectorim/element-web:v1.11.17        "/docker-entrypoint.…"   10 hours ago   Up 10 hours             80/tcp, 0.0.0.0:8765->8080/tcp                                                                                                                                                                                                                      matrix-client-element
7bab9902b5c9   nginx:1.23.3-alpine                  "/docker-entrypoint.…"   10 hours ago   Up 10 hours             0.0.0.0:8008->8008/tcp, 80/tcp, 0.0.0.0:8048->8048/tcp                                                                                                                                                                                              matrix-synapse-reverse-proxy-companion
4089ff3cc7b6   devture/exim-relay:4.96-r1-0         "/sbin/tini -- exim …"   10 hours ago   Up 10 hours             8025/tcp                                                                                                                                                                                                                                            matrix-mailer
7e8e0738357a   coturn/coturn:4.6.1-r0-alpine        "turnserver -c /turn…"   10 hours ago   Up 10 hours             0.0.0.0:3478->3478/tcp, 0.0.0.0:3478->3478/udp, :::3478->3478/tcp, :::3478->3478/udp, 0.0.0.0:5349->5349/udp, :::5349->5349/udp, 0.0.0.0:5349->5349/tcp, 0.0.0.0:49152-49172->49152-49172/udp, :::5349->5349/tcp, :::49152-49172->49152-49172/udp   matrix-coturn
3cf93453d4b0   matrixdotorg/synapse:v1.74.0         "/start.py run -m sy…"   10 hours ago   Up 10 hours (healthy)   8008-8009/tcp, 8448/tcp                                                                                                                                                                                                                             matrix-synapse
309113fd2442   postgres:15.1-alpine                 "docker-entrypoint.s…"   10 hours ago   Up 10 hours             5432/tcp                                                                                                                                                                                                                                            matrix-postgres
```
