### ISSUE TITLE
Unable to start with custom OIDC config

### ISSUE THREAD

**Issue by Aeris1One** [spantaleev/matrix-docker-ansible-deploy#2410]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# OAuth2
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true
matrix_synapse_configuration_extension_yaml: |
    oidc_config:
        enabled: true
        discover: false
        issuer: "https://my.nextcloud.tld/"
        client_id: "redacted"
        client_secret: "obviously-redacted"
        authorization_endpoint: "https://my.nextcloud.tld/apps/oauth2/authorize"
        token_endpoint: "https://my.nextcloud.tld/apps/oauth2/api/v1/token"
        userinfo_endpoint: "https://my.nextcloud.tld/ocs/v2.php/cloud/user?format=json"
        skip_verification: false
        scopes: ["nc doesn't implement"]
        user_mapping_provider:
        config:
            subject_claim: "{{ user.ocs.data.id }}"
            localpart_template: "{{ user.login }}"
            display_name_template: "{{ user.name }}"
```

**Matrix Server:**
 - OS: Ubuntu 22.04 LTS
 - Architecture : arm64

**Problem description**:

When running `setup-all`, it returns the following error :
```
TASK [custom/matrix-synapse : (Deprecation) Catch and report renamed settings in matrix_synapse_configuration_extension_yaml] *****************************************fatal: [matrix.mydomain.tld]: FAILED! => 
  msg: |-
    The conditional check 'item.old in matrix_synapse_configuration_extension' failed. The error was: error while evaluating conditional (item.old in matrix_synapse_configuration_extension): {{ matrix_synapse_configuration_extension_yaml | from_yaml if matrix_synapse_configuration_extension_yaml | from_yaml is mapping else {} }}: oidc_config:
        enabled: true
        discover: false
        issuer: "https://my.nextcloud.tld/"
        client_id: "redacted"
        client_secret: "obviously-redacted"
        authorization_endpoint: "https://my.nextcloud.tld/apps/oauth2/authorize"
        token_endpoint: "https://my.nextcloud.tld/apps/oauth2/api/v1/token"
        userinfo_endpoint: "https://my.nextcloud.tld/ocs/v2.php/cloud/user?format=json"
        skip_verification: false
        scopes: ["nc doesn't implement"]
        user_mapping_provider:
        config:
            subject_claim: "{{ user.ocs.data.id }}"
            localpart_template: "{{ user.login }}"
            display_name_template: "{{ user.name }}"
    : 'user' is undefined
  
    The error appears to be in '/home/aeris/matrix-docker-ansible-deploy/roles/custom/matrix-synapse/tasks/validate_config.yml': line 67, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: (Deprecation) Catch and report renamed settings in matrix_synapse_configuration_extension_yaml
      ^ here
```

It isn't a deprecation notice, it seems like some error which shouldn't appear, my configuration seems correct and I copied it from https://github.com/matrix-org/synapse/issues/8511#issuecomment-1370929388

What should I edit in my config to make this work ?
