### ISSUE TITLE
After update, ansible fails to run due to prometheus_node_exporter

### ISSUE THREAD

**Issue by jgoerzen** [spantaleev/matrix-docker-ansible-deploy#2425]
**Describe the bug**

After a `git pull` that upgraded from 1abba4c9..29818aba, I now get this when running `ansible-playbook  -i inventory/hosts setup.yml --tags=setup-all,start`:

```
ERROR! the role 'galaxy/prometheus_node_exporter' was not found in /root/matrix-docker-ansible-deploy/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root/matrix-docker-ansible-deploy

The error appears to be in '/root/matrix-docker-ansible-deploy/setup.yml': line 89, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - custom/matrix-synapse-admin
    - galaxy/prometheus_node_exporter
      ^ here
```

Note that I do not now, nor have I ever, used the prometheus_node_exporter.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: [redacted]
matrix_synapse_admin_enabled: true
devture_postgres_connection_password: [redacted]
matrix_synapse_rust_synapse_compress_state_find_rooms_command_wait_time: 600
matrix_server_fqn_element: "riot.{{ matrix_domain }}"
matrix_ssl_lets_encrypt_support_email: [redacted]
matrix_coturn_turn_static_auth_secret: [redacted]
matrix_coturn_enabled: false
matrix_ma1sd_enabled: false
matrix_synapse_macaroon_secret_key: [redacted]
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"

matrix_synapse_configuration_extension_yaml: |
  retention:
    enabled: false
    default_policy:
      min_lifetime: 1w
      max_lifetime: 8w
    allowed_lifetime_min: 1w
    allowed_lifetime_max: 8w
matrix_synapse_presence_enabled: false
matrix_synapse_caches_global_factor: 0.7
matrix_mailer_relay_host_name: [redacted]
matrix_mailer_relay_host_port: 25
matrix_mailer_sender_address: [redacted]
matrix_mailer_relay_use: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: [redacted]

matrix_mautrix_facebook_enabled: true
matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    initial_chat_sync: 5

matrix_mx_puppet_twitter_enabled: false

matrix_mautrix_hangouts_enabled: true
matrix_mautrix_hangouts_configuration_extension_yaml: |
  bridge:
    initial_chat_sync: 5
matrix_mautrix_googlechat_enabled: true
matrix_appservice_discord_enabled: true
matrix_appservice_discord_client_id: [redacted]
matrix_appservice_discord_bot_token: [redacted]
matrix_appservice_discord_bridge_disablePresence: true
matrix_appservice_discord_configuration_extension_yaml: |
        ghosts:
                usernamePattern: :username

matrix_mx_puppet_slack_enabled: true
matrix_mx_puppet_slack_client_id: [redacted]
matrix_mx_puppet_slack_client_secret: [redacted]

matrix_heisenbridge_enabled: true
matrix_heisenbridge_owner: [redacted]
```

**Expected behavior**

Running the same command that I've always used to update shouldn't die with an error.

**Matrix Server:**
 - OS: Debian bullseye
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- on the matrix server itself
- what version of Ansible you're running -- 2.10.8

**Client:**
n/a

**Additional Info:**

Removing the prometheus_node_exporter line from setup.yml works around this problem.
