### ISSUE TITLE
problem upgrading pre-existing installation since galaxy and just changes

### ISSUE THREAD

**Issue by altsalt** [spantaleev/matrix-docker-ansible-deploy#2445]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: sal.td
matrix_ssl_lets_encrypt_support_email: '<redacted>'
matrix_coturn_turn_static_auth_secret: '<redacted>'
matrix_synapse_macaroon_secret_key: '<redacted>'
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
devture_postgres_connection_password: '<redacted>'
devture_postgres_process_extra_arguments:
  - "-c 'max_connections=200'"
  - "-c 'shared_buffers=768MB'"
  - "-c 'effective_cache_size=2304MB'"
  - "-c 'maintenance_work_mem=192MB'"
  - "-c 'checkpoint_completion_target=0.9'"
  - "-c 'wal_buffers=16MB'"
  - "-c 'default_statistics_target=100'"
  - "-c 'random_page_cost=1.1'"
  - "-c 'effective_io_concurrency=200'"
  - "-c 'work_mem=1966kB'"
  - "-c 'min_wal_size=1GB'"
  - "-c 'max_wal_size=4GB'"
  - "-c 'max_worker_processes=3'"
  - "-c 'max_parallel_workers_per_gather=2'"
  - "-c 'max_parallel_workers=3'"
  - "-c 'max_parallel_maintenance_workers=2'"
devture_postgres_backup_enabled: true
devture_postgres_backup_keep_days: 3
devture_postgres_backup_keep_weeks: 1
devture_postgres_backup_keep_months: 1
matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@salt:{{ matrix_domain }}"
matrix_dimension_access_token: "<redacted>"
matrix_synapse_presence_enabled: false
matrix_synapse_url_preview_enabled: false
matrix_client_element_enabled: true
matrix_coturn_enabled: false
matrix_synapse_report_stats: true
matrix_mailer_enabled: false
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: <redacted>
matrix_heisenbridge_enabled: true
matrix_heisenbridge_owner: "@salt:sal.td"
matrix_heisenbridge_identd_enabled: true
```

**Matrix Server:**
 - OS: Debian 11 (bullseye)
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible: on a separate computer running Debian 12 (bookworm), using these flags: `--ask-pass --become-user matrix_docker_ansible --become-method sudo`
- what version of Ansible: 2.14.2

**Problem description**:

I am attempting to upgrade my single-user synapse server that has been operating for years using `just setup-all`. The last upgrade was done in September or October, before the transition to external roles. I've tried a number of things to get through the setup-all process, to no avail.

An issue that repeatedly occurs relates to how I am gaining root permissions. The Ansible flags listed above used to work, but now errors are being thrown as though the permission is not being passed properly. One example can be seen in [this issue](https://github.com/geerlingguy/ansible-role-docker/issues/400) and another is below:
```
TASK [custom/matrix-base : Ensure Matrix base paths exists] *********************************************************************************************************************************************************************
ok: [matrix.sal.td] => (item=/matrix)
failed: [matrix.sal.td] (item=/matrix/bin) => changed=false 
  ansible_loop_var: item
  item: /matrix/bin
  msg: 'There was an issue creating /matrix/bin as requested: [Errno 13] Permission denied: b''/matrix/bin'''
  path: /matrix/bin
```
I have tried to work around these by manually changing permissions or relocating files, but have spent too much time to continue at the moment and would appreciate direction.
