### ISSUE TITLE
Fresh install of the ansible playbook fails with couldn't resolve module/action 'community.docker.docker_image'.

### ISSUE THREAD

**Issue by fierg** [spantaleev/matrix-docker-ansible-deploy#2450]
**Describe the bug**
Fresh install of the ansible playbook fails with
ERROR! couldn't resolve module/action 'community.docker.docker_image'.
in 
roles/custom/matrix-nginx-proxy/tasks/ssl/setup_ssl_lets_encrypt.yml

although ssl method is set to self-signed
`matrix_ssl_retrieval_method: self-signed`

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: duc-sd7scpbykhs.dev.u.agfahealthcare.com/

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'XXX'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: ''

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'XXX'

matrix_ssl_retrieval_method: self-signed

matrix_jitsi_enabled: true

# Run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
# or define your own strong passwords manually.
matrix_jitsi_jicofo_auth_password: "XXX"
matrix_jitsi_jvb_auth_password: "XXX"
matrix_jitsi_jibri_recorder_password: "XXX"
matrix_jitsi_jibri_xmpp_password: "XXX"

matrix_jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=XXX"'

```

**Expected behavior**
The ansible playbook runs through and installs a synapse home server
**Matrix Server:**
 - OS: [Fedora 37]
 - Architecture [amd64]

**Ansible:**
If your problem appears to be with Ansible, tell us:
- running on the Matrix server itself
- core 2.14.1

**Additional context**
Also configured to install the Jitsi bridge
