### ISSUE TITLE
Could not find the requested service devture-traefik.service: host

### ISSUE THREAD

**Issue by rdaries** [spantaleev/matrix-docker-ansible-deploy#2465]
**Describe the bug**
Could not find the requested service devture-traefik.service: host after git pull

**To Reproduce**
My `vars.yml` is not changed

```yaml
failed: [matrix.domain.tld] (item={'name': 'devture-traefik.service', 'priority': 3000, 'groups': ['matrix', 'traefik', 'reverse-proxies']}) => changed=false 
  ansible_loop_var: item
  item:
    groups:
    - matrix
    - traefik
    - reverse-proxies
    name: devture-traefik.service
    priority: 3000
  msg: 'Could not find the requested service devture-traefik.service: host'

PLAY RECAP ******************************************************************************************************************************************
matrix.domain.tld           : ok=574  changed=53   unreachable=0    failed=1    skipped=584  rescued=0    ignored=0  
```
