### ISSUE TITLE
ntfy.DOMAIN throws 404

### ISSUE THREAD

**Issue by felixx9** [spantaleev/matrix-docker-ansible-deploy#2529]
***Description*
Call ntfy.DOMAIN in Browser throws 404:  
`{"code":40401,"http":404,"error":"page not found"}`

**To Reproduce**
open `https://ntfy.DOMAIN` in browser.

```yaml
ntfy_enabled: true
matrix_server_fqn_ntfy: "ntfy.{{ matrix_domain }}"
ntfy_configuration_extension_yaml: |
  log_level: DEBUG
```

**Expected behavior**
Until somewhen earlier (before introducing Traefik?) a page like https://ntfy.sh/app was served under ntfy.DOMAIN
