### ISSUE TITLE
Traefik ignores X-Forwarded headers when running behind another reverse proxy, breaking SSO

### ISSUE THREAD

**Issue by davidmehren** [spantaleev/matrix-docker-ansible-deploy#2532]
**Describe the bug**
When using the playbook-managed traefik behind another reverse proxy which terminates TLS, all requests in traefiks access log come from the IP of the reverse-proxy. This also breaks SSO again, as services think they are accessed without TLS, like in https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1132

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '0.0.0.0:3000'

```
(like documented in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#fronting-the-integrated-reverse-proxy-webserver-with-another-reverse-proxy)

**Expected behavior**

I fixed the problem by bluntly overwriting the entrypoint definition like this:
```
devture_traefik_configuration_extension_yaml:
  entryPoints:
    web:
      address: ':80'
      forwardedHeaders:
        trustedIPs:
          - '172.28.48.1/32'
```
See https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers for docs.

This playbook should in the best case generate an appropriate entrypoint config, like `forwardedHeaders.insecure = true` when it is set up to be fronted with another reverse-proxy.
Alternatively, it could provide knobs to add custom config to the default `web` entrypoint (so that one does not have to redefine it completely) and document that.

**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64

**Comment by spantaleev** [comment]
I think that the way configuration gets merged, you don't need to repeat the `address` field.. So it can be like this:

```yaml
devture_traefik_configuration_extension_yaml:
  entryPoints:
    web:
      forwardedHeaders:
        trustedIPs:
          - '172.28.48.1/32'
```

-------

In any case, I've added dedicated variables for this and you could shorten the whole thing down to:

If your reverse-proxy is on the same machine:

```yaml
# Other stuff ...

devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
```

Or.. If your reverse-proxy is on another machine:

```yaml
# Other stuff ...

devture_traefik_container_web_host_bind_port: 81

devture_traefik_config_entrypoint_web_forwardedHeaders_trustedIPs: ['172.28.48.1/32']
```
