### ISSUE TITLE
[BUG] traefik config for synapse is missing

### ISSUE THREAD

**Issue by Ramblurr** [spantaleev/matrix-docker-ansible-deploy#2543]
**Describe the bug**

I run (/ran/) this playbook with the builtin nginx-proxy, but in the mode where my own local nginx reverse-proxied the builtin nginx-proxy.

I saw today that there were similar instructions for traefik, that is, I could run with `matrix_playbook_reverse_proxy_type: playbook-managed-traefik` and proxy traefik with my own nginx.. So I decided to go ahead with the migration.

After setting up the config and running `setup-all` and `start-all` I am left with a situation where:

* traefik is running
* synapse is running and reachable over its local container IP (I test with `curl IP:PORT/_matrix/client/versions`
* however, synapse is not reachable via traefik
  * it is also not reachable via my nginx, but that makes sense since I can't even reach it via traefik
  * also the traefik /dashboard/ is not working, despite the relevant config, though I'm not sure if that is related.
* Notably `synapse-admin` and element are reachable through traefik.
  *  this leads me to believe that:
    1. traefik is working fine and the docker socket proxy is also working
    2. My nginx reverse-proxy config is also working fine
    3. BUT the traefik configuration so it will proxy synapse is missing (see Analysis below)

When I say "not reachable" what I mean is that traefik is returning 404 errors with the body text `404 page not found`

Example:
```
# use docker inspect to get matrix-synapse container ip: 172.18.0.4
$ curl http://172.18.0.4:8008/_matrix/client/versions
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0","r0.6.1","v1.1","v1.2","v1.3","v1.4","v1.5"],"
....snip...

# use docker inspect to get traefik container ip: 172.29.0.3
$  curl http://172.29.0.3:80/_matrix/client/versions
404 page not found
# just for kicks, try the local port that is forwarded to the traefik container:
$ curl http://127.0.0.1:81/_matrix/client/versions
404 page not found
```

**Analysis**
Looking at the generated configuration in `/matrix` I do not see how traefik could be configured to proxy synapse.

* There are no labels on the `matrix-synapse` container
* There is no configuration in `/matrix/traefik/config/traefik.yml` that configures a service for traefik to route synapse traffic to. (there is a federation endpoint however).

*How is the traefik supposed to be configured to proxy for synapse??*

**To Reproduce**

```yaml
matrix_domain: mydomain.com
matrix_coturn_enabled: false
matrix_synapse_macaroon_secret_key: "redacted"
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_synapse_max_upload_size_mb: 2000
matrix_synapse_storage_path: "/mnt/box/matrix_streetnoise_at/storage"
matrix_synapse_media_store_path: "/mnt/box/matrix_streetnoise_at/media-store"
matrix_synapse_auto_join_rooms:
    - "#redacted:mydomain.com"
matrix_server_fqn_element: "chat.{{ matrix_domain }}"
matrix_client_element_brand: "redacted"
matrix_client_element_welcome_logo_link: "https://mydomain.com"
matrix_client_element_welcome_headline: "Welcome to redacted"
matrix_client_element_welcome_text: "redacted"
matrix_client_element_welcome_logo: "https://mydomain.com/redacted"
matrix_client_element_branding_welcomeBackgroundUrl: "https://mydomain.com/media/redacted"
matrix_client_element_branding_authFooterLinks:
    - text: Forum
      url: https://forum.mydomain.com

devture_postgres_enabled: true
devture_postgres_connection_password: "redacted"


matrix_synapse_configuration_extension_yaml: |
   password_config:
     enabled: false 
   sso:
     update_profile_information: false
     client_whitelist:
         - https://chat.mydomain.com/
         - element://element/
         - element://connect/
   oidc_providers:
       - idp_id: id.mydomain.com
         idp_name: redacted
         issuer: "https://id.mydomain.com/realms/redacted"
         client_id: matrix.mydomain.com
         client_secret: redacted
         scopes: ["openid", "profile"]
         user_mapping_provider:
           config:
             localpart_template: "{{ '{{' }} user.preferred_username {{ '}}' }}"
             display_name_template: "{{ '{{' }} user.name {{ '}}' }}"
         backchannel_logout_enabled: true
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true
matrix_synapse_container_extra_arguments: ["--mount type=bind,src={{ matrix_synapse_ext_path }}/nextcloud_oicd_mapping_provider.py,dst={{ matrix_synapse_in_container_python_packages_path }}/nextcloud_oicd_mapping_provider.py,ro"]

matrix_synapse_admin_enabled: true

matrix_synapse_federation_domain_whitelist:
  - redacted.com

matrix_synapse_federation_enabled: true
devture_postgres_backup_enabled: true

# these backup files are backed up by our borgmatic script which has its own retention settings
devture_postgres_backup_keep_days: 2
devture_postgres_backup_keep_weeks: 1
devture_postgres_backup_keep_months: 1

# NEW traefik migration vars
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
devture_traefik_container_web_host_bind_port: "127.0.0.1:81"
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_additional_entrypoints_auto:
  - name: matrix-federation
    port: 8449
    host_bind_port: "127.0.0.1:8449"
    config: {}
    
# enable traefik dashboard
devture_traefik_dashboard_enabled: true
devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
devture_traefik_dashboard_basicauth_enabled: true
devture_traefik_dashboard_basicauth_user: admin
devture_traefik_dashboard_basicauth_password: redacted
devture_traefik_config_log_level: DEBUG

# OLD nginx settings. possibly remove.
matrix_nginx_proxy_enabled: false
matrix_ssl_retrieval_method: none

```

**Expected behavior**

Synapse should be reachable through traefik

**Matrix Server:**
 - OS: Ubuntu 22.04.2 LTS
 - Architecture: x86_64

I ran the migration with this repo checked out to 30f10347670d2fcc3fafc3ac81659dcb6d909cdc
