### ISSUE TITLE
playbook-managed-traefik fails when fronted by apache2

### ISSUE THREAD

**Issue by xschlef** [spantaleev/matrix-docker-ansible-deploy#2544]
All requests result in 404 when using the recommended settings using current HEAD https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/2a872e95fcc171a0bb96317b4a811762957600e3

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#fronting-the-integrated-reverse-proxy-webserver-with-another-reverse-proxy

traefik has an error:
`Error while building configuration (for the first time): http cannot be a standalone element (type *dynamic.HTTPConfiguration)" providerName=file`

traefik configuration look rather empty, but I'm no expert on that.

```
/ # cat /config/provider.yml 

http:
  middlewares:

  routers:

/ # cat /config/traefik.yml 
accessLog: {}
api:
  dashboard: false
certificatesResolvers: null
entryPoints:
  matrix-federation:
    address: :8449
  web:
    address: :80
    forwardedHeaders:
      insecure: true
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
providers:
  docker:
    exposedByDefault: false
    network: traefik
  file:
    filename: /config/provider.yml
```

looks like traefic is not really routing anything?
