### ISSUE TITLE
Decryption Issue for all encrypted chats

### ISSUE THREAD

**Issue by gitayam** [spantaleev/matrix-docker-ansible-deploy#2546]
My `vars.yml` file looks like this:

```yaml

---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ('matrix.<matrix-domain>').
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com

matrix_domain: domain.tld

##
#load balancing : https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-synapse.md
#matrix_synapse_workers_enabled: true
matrix_base_data_path: "/datadrive/matrix"

## Server stuff
## auto join
## source : https://github.com/matrix-org/synapse/blob/e7b78dcc4a6bf8fdb71782640932da8dff7cc5ed/docs/sample_config.yaml#L1264-L1274
## line 1260
enable_set_displayname: true
# Homeserver admin contacts as per MSC 1929 https://github.com/matrix-org/matrix-spec-proposals/pull/1929
matrix_homeserver_admin_contacts:
  - matrix_id: "@username_here:domain.tld"
    email_address: username_here@domain.tld
    role: admin
  - email_address: security@domain.tld
    role: security

matrix_playbook_reverse_proxy_type: playbook-managed-nginx
matrix_homeserver_support_url: "https://domain.tld/support"
matrix_synapse_http_listener_resource_names: ["client","federation"]
matrix_federation_public_port: 443
matrix_synapse_federation_port_enabled: false
matrix_synapse_tls_federation_listener_enabled: false
##https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-matrix-registration.md
matrix_registration_enabled: true
# Generate a strong secret using: `pwgen -s 64 1`.
matrix_registration_admin_secret: "password_here"
# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'password_here'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'matrix@domain.tld'
#matrix_ssl_retrieval_method: none


# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'password_here'
### JITSI
matrix_jitsi_enabled: true
# Run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
# or define your own strong passwords manually.
matrix_jitsi_jicofo_auth_password: 'password_here'
matrix_jitsi_jvb_auth_password: 'password_here'
matrix_jitsi_jibri_recorder_password: 'password_here'
matrix_jitsi_jibri_xmpp_password: 'password_here'
#matrix_jitsi_enable_auth: true
#matrix_jitsi_enable_guests: true
matrix_jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;

  config.disableAudioLevels = true;

  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 4;

matrix_jitsi_web_config_resolution_width_ideal_and_max: 1080
matrix_jitsi_web_config_resolution_height_ideal_and_max: 720
###Etherpad
etherpad_enabled: true
# Variables configuring the etherpad
etherpad_title: Etherpad
etherpad_abiword: null
etherpad_soffice: /usr/bin/soffice
# Uncomment below if you'd like to install Etherpad on the Dimension domain (not recommended)
#etherpad_mode: dimension

#Uncomment below to enable the admin web UI
etherpad_admin_username: admin
etherpad_admin_password: password_here

### MSynapse
matrix_synapse_admin_enabled: true

# Enable generation of `/.well-known/matrix/support`.
# This needs to be enabled explicitly for now, because MSC 1929 is not yet accepted.
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_well_known_matrix_support_enabled: true


### BOTS

BOTSmatrix_bot_matrix_reminder_bot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
#matrix_bot_matrix_reminder_bot_matrix_user_id_localpart: reminder-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_reminder_bot_matrix_user_password:password_here
# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: America/New York


### Signal Bot
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true
matrix_mautrix_signal_login_shared_secret: 'password_here'
matrix_mautrix_signal_bridge_permissions: {"@username_here:domain.tld": "admin", "*": "user"}
# Enable bridge relay bot functionality
matrix_mautrix_signal_bridge_encryption_allow: true
###
# Discord bot
matrix_mautrix_discord_enabled: true
###
# Honoroit Bot

# Uncomment and adjust this part if you'd like to use a username different than the default
#matrix_bot_honoroit_login: honoroit_bot
# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
#matrix_bot_honoroit_password: password_here
# Adjust this to your room ID
#matrix_bot_honoroit_roomid: "!iIkQXgxGLQOkOhBDpn:domain.tld"
###
# Maubot
matrix_bot_maubot_enabled: false
matrix_bot_maubot_admins:
  - username_here: password_here

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: password_here

### Logging

matrix_synapse_log_level: "INFO"
matrix_synapse_storage_sql_log_level: "INFO"
matrix_synapse_root_log_level: "INFO"
### Retention Policy
#https://matrix-org.github.io/synapse/develop/message_retention_policies.html
#default_policy:
 # min_lifetime: 1d
 # max_lifetime: 1y
###OIDC
#roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
#matrix_synapse_configuration_extension_yaml: |

matrix_bot_chatgpt_enabled: true
# Obtain a new API key from https://platform.openai.com/account/api-keys
matrix_bot_chatgpt_openai_api_key: 'password_here'

# This is the default username
matrix_bot_chatgpt_matrix_bot_username_localpart: 'username_heregpt'

# Matrix access token (from bot user above)
# see: https://webapps.stackexchange.com/questions/131056/how-to-get-an-access-token-for-element-riot-matrix
matrix_bot_chatgpt_matrix_access_token: 'password_here'

devture_postgres_process_extra_arguments: [
  "-c max_connections=100",
  "-c shared_buffers=2GB",
  "-c effective_cache_size=6GB",
  "-c maintenance_work_mem=512MB",
  "-c checkpoint_completion_target=0.9",
  "-c wal_buffers=16MB",
  "-c default_statistics_target=100",
  "-c random_page_cost=1.1",
  "-c effective_io_concurrency=200",
  "-c work_mem=5242kB",
  "-c min_wal_size=1GB",
  "-c max_wal_size=4GB",
  "-c max_worker_processes=4",
  "-c max_parallel_workers_per_gather=2",
  "-c max_parallel_workers=4",
  "-c max_parallel_maintenance_workers=2",
]
```

**Matrix Server:**
 - OS: Linux matrix-server 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Ansible:**
ansible [core 2.14.1]

# **Problem description**:

## Decryption Issue for all encrypted chats and unable to sending images fail to upload
```Error
Open another device to load encrypted messages
This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.
```
This happened after the update to specifically add `matrix_playbook_reverse_proxy_type: playbook-managed-nginx`

**Additional context**

Issue persist on all clients (mobile, pc, and web) but is more severe on mobile.
