### ISSUE TITLE
Sliding sync proxy url not using https

### ISSUE THREAD

**Issue by meenzen** [spantaleev/matrix-docker-ansible-deploy#2547]
I just set up the sliding sync proxy by setting `matrix_sliding_sync_enabled: true` and my `.well-known` now looks like this:

```json
{
    "m.homeserver": {
        "base_url": "https://matrix.meenzen.net"
    },
    "org.matrix.msc3575.proxy": {
        "url": "http://matrix.meenzen.net/sliding-sync"
    }
}
```

I don't think that's intended.

I am running the services behind another reverse proxy, so traefik is configured like this:

```yml
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '0.0.0.0:81'
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
devture_traefik_additional_entrypoints_auto:
  - name: matrix-federation
    port: 8449
    host_bind_port: '0.0.0.0:8449'
    config:
      forwardedHeaders:
        insecure: true
```
