### ISSUE TITLE
Expose the port for admin api calls

### ISSUE THREAD

**Issue by Will-Zhao0** [spantaleev/matrix-docker-ansible-deploy#2549]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: xxxx.org

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'xxxx'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'xxxxxx'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: 'xxxx'

matrix_client_element_default_theme: 'dark'

# matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_nginx_proxy_enabled: true

matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true

matrix_synapse_admin_enabled: true
```

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture x86_64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- I'm running ansible from another linux machine Rocky Linux 8.7 (Green Obsidian)
- what version of Ansible you're running -- core 2.14.2

**Problem description**:

I'm trying to make admin api calls from outside the docker using python, but it seems not able to connect to the server when I run the python script, the program always hangs. I suppose there are some configuration I missed from `vars.yml`. Thank you!
