### ISSUE TITLE
.well-known/matrix/client 404 error with Traefik being fronted by nginx

### ISSUE THREAD

**Issue by Randshot** [spantaleev/matrix-docker-ansible-deploy#2550]
**Describe the bug**
I am using this playbook with the internal Traefik proxy being fronted by a server hosted nginx installation.
The self-check fails since it can't reach https://DOMAIN/.well-known/matrix/client (404 error). 
https://matrix.DOMAIN/.well-known/matrix/client is reachable though (checked with browser).
I fixed this by explicitly setting the host header in the nginx config: `proxy_set_header Host matrix.DOMAIN;`

**To Reproduce**
My `vars.yml` file looks like this (only relevant part):

```yaml
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '127.0.0.1:81'
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
devture_traefik_additional_entrypoints_auto:
  - name: matrix-federation
    port: 8449
    host_bind_port: '127.0.0.1:8449'
    config: {}
```

**Expected behavior**
Reachable .well-known/matrix files from base domain.

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture amd64

**Comment by Pippadi** [comment]
I get `418 I'm a teapot` errors, even without nginx in front of traefik.

I get my `.well-known/matrix/client` from `matrix.chat.domain.com`, but not `chat.domain.com`.

Here's my `vars.yml`.

```yml
matrix_domain: chat.domain.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'asecret'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: 'myemail@example.com'

# The base domain wasn't getting an LE cert automatically without this
devture_traefik_additional_domains_to_obtain_certificates_for: [ 'chat.domain.com' ]

devture_postgres_connection_password: 'aPassword'

matrix_architecture: 'arm64'
matrix_coturn_turn_external_ip_address: '1.2.3.4'

# Changelogs said that some nginx settings were used for traefik too.
# This one didn't seem to help, though.
matrix_nginx_proxy_base_domain_serving_enabled: true
```

I'm posting this mostly to stay updated on this thread's activity.
