### ISSUE TITLE
/_matrix/federation/v1/version 404 page not found (using SRV records instead of well-known)

### ISSUE THREAD

**Issue by sidewinder94** [spantaleev/matrix-docker-ansible-deploy#2555]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: zarrouk.eu

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '<key>'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: '<mail>'

matrix_ssl_additional_domains_to_obtain_certificates_for:
  - '{{ matrix_domain }}'

# Choosing the reverse proxy implementation
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: <mail>

matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_nginx_proxy_container_labels_traefik_proxy_base_domain_enabled: true
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate: /matrix/ssl/config/live/zarrouk.eu/fullchain.pem
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate_key: /matrix/ssl/config/live/zarrouk.eu/privkey.pem

# Experimental features
matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true

# Sliding proxy for MSC3575
matrix_sliding_sync_enabled: true

matrix_coturn_denied_peer_ips: []

# Jitsi
matrix_jitsi_enabled: true

matrix_jitsi_web_stun_servers:
 - stun:matrix.zarrouk.eu:5349

matrix_jitsi_jicofo_auth_password: <passwd>
matrix_jitsi_jvb_auth_password: <passwd>
matrix_jitsi_jibri_recorder_password: <passwd>
matrix_jitsi_jibri_xmpp_password: <passwd>

matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_prosody_auth_internal_accounts:
 - username: "jitsi-moderator"
   password: "<passwd>"
 - username: "another-user"
   password: "<passwd>"
 - username: "aazarrouk"
   password: "<passwd>"

matrix_jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=<local server ip>"'

matrix_jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;

  config.disableAudioLevels = false;

  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 6;

matrix_jitsi_web_config_resolution_width_ideal_and_max: 1920
matrix_jitsi_web_config_resolution_height_ideal_and_max: 1080

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: '<passwd>'

matrix_well_known_matrix_server_enabled: false

matrix_prometheus_enabled: true

prometheus_node_exporter_enabled: true

grafana_enabled: true

grafana_anonymous_access: false

matrix_synapse_admin_enabled: true

matrix_ma1sd_enabled: true

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
grafana_default_admin_user: "aazarrouk"

# Changing the password subsequently won't work.
grafana_default_admin_password: "<passwd>"

# Double puppetting

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: <passwd>

# Element conf override

matrix_client_element_configuration_extension_json: |
 {
  "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=<passwd>"
 }

# Bridges

## Matrix
matrix_mautrix_discord_enabled: true

matrix_mautrix_discord_configuration_extension_yaml: |
  bridge:
    delete_portal_on_channel_delete: true
    permissions:
      '@antoine-ali:zarrouk.eu': admin
      'zarrouk.eu': user

## Steam

matrix_mx_puppet_steam_enabled: true

## WhatsApp

matrix_mautrix_whatsapp_enabled: true

matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true

## Signal

matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true

matrix_mautrix_signal_configuration_extension_yaml: |
  bridge:
    permissions:
      '@antoine-ali:zarrouk.eu': admin
      'zarrouk.eu': user

## Facebook

matrix_mautrix_facebook_enabled: true

matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
  bridge:
    permissions:
      '@antoine-ali:zarrouk.eu': admin
      'zarrouk.eu': user
  
# Dimension (Integrations)

matrix_dimension_enabled: true

matrix_dimension_admins:
  - "@antoine-ali:{{ matrix_domain }}"

matrix_dimension_access_token: "<passwd>"

```

**Matrix Server:**
 - OS: Ubuntu 22.04.2 LTS
 - Architecture amd64

**Ansible:**
Problem don't seem to come from ansible.
But ansible is ran on the server itself (version 2.10.8)

**Problem description**:

Federation appears broken since switching to traefik as a reverse proxy.

When trying to join a room on another server, Element loads indefinitely.

The federation tester reports a 404 when trying to get the server version :

https://federationtester.matrix.org/api/report?server_name=zarrouk.eu 

returns : 
```json
{
  "WellKnownResult": {
    "m.server": "",
    "result": "No .well-known found",
    "CacheExpiresAt": 0
  },
  "DNSResult": {
    "SRVSkipped": false,
    "SRVCName": "_matrix._tcp.zarrouk.eu.",
    "SRVRecords": [
      {
        "Target": "matrix.zarrouk.eu.",
        "Port": 8448,
        "Priority": 10,
        "Weight": 0
      }
    ],
    "SRVError": null,
    "Hosts": {
      "matrix.zarrouk.eu.": {
        "CName": "matrix.zarrouk.eu.",
        "Addrs": [
          "82.64.244.51"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "82.64.244.51:8448"
    ]
  },
  "ConnectionReports": {},
  "ConnectionErrors": {
    "82.64.244.51:8448": {
      "Message": "Non-200 response 404 from remote server"
    }
  },
  "Version": {
    "error": "contents=[52 48 52 32 112 97 103 101 32 110 111 116 32 102 111 117 110 100 10] msg=Failed to GET JSON (hostname \"zarrouk.eu\" path \"/_matrix/federation/v1/version\"): 404 page not found\n code=404 wrapped="
  },
  "FederationOK": false
}
```

And `http://82.64.244.51:8448/_matrix/federation/v1/version` indeed returns a 404.
However, If I change the IP with the DNS name configured in the SRV record : https://matrix.zarrouk.eu:8448/_matrix/federation/v1/version

Then I get a valid answer :
 ```json
{"server":{"name":"Synapse","version":"1.78.0"}}
```

Thanks for the support !

**Comment by sidewinder94** [comment]
Documenting steps to try and federate again:

- Get a wildcard certificate from let's encrypt

1. edit /etc/systemd/system/matrix-traefik.service
Add environment vars configuration
```bash
--env CF_API_EMAIL=<cloudflare account mail> \
--env CF_ZONE_API_TOKEN=<read only zone API token> \
--env CF_DNS_API_TOKEN=<write zone dns API token> \
--env LEGO_DISABLE_CNAME_SUPPORT=true \ #needed for some reason
```

Planning to get the tokens out to some file once stabilized
This is because my DNS zone is hosted by cloudflare, and traefik supports ACME DNS challenges with that provider

2. Edit traefik conf
Edit /matrix/traefik/config/traefik.yml


Set up the ACME DNS Challenge as the default resolver

replace `certificateResolvers:default:acme` content with 
```yaml
email: antoine-ali@zarrouk.eu
dnsChallenge:
    provider: cloudflare
    resolvers: 
      - "1.1.1.1:53"
      - "8.8.8.8:53"
storage: /ssl/acme.json
```

Ask for a wildcard certificate in addition to the base domain one **Right now they are still separate, i'm still looking on how to get a single one**
Edit `/matrix/traefik/config/traefik.yml`

In the `http:routers:<base_domain>-dummy:tls` section add :
```yaml
domains:
    - main: "<base_domain>"
    - sans: "*.<base_domain>"
```

3. Make traefik use the wildcard certificate for the federation endpoint (which **should** also valid for the base domain) : 
Edit `/matrix/nginx-proxy/labels`

Comment out  the following lines : 

```yaml
#traefik.http.routers.matrix-nginx-proxy-matrix-client.tls.certResolver=default
#traefik.http.routers.matrix-nginx-proxy-matrix-federation.tls.certResolver=default
```

**Comment by sidewinder94** [comment]
```yaml
matrix_nginx_proxy_container_labels_additional_labels:
```
Could be used to add the two "domains" lines in the nginx-proxy labels file

**Comment by sidewinder94** [comment]
Bonus step disable the creation of `matrix-traefik-certs-dumper-wait-for-domain@matrix.domain.tld.service` since we won't have a `matrix.domain.tld` certificate (we'll have the wildcard one).

**Comment by sidewinder94** [comment]
I've got a mostly working config.

While federation and chat work with the following, this breaks the Coturn service. Since it is expecting a certificate from matrix-traefik-certs-dumper for the matrix.domain.tld, and we don't have one annymore (we only have the base domain and the wildcard).

```yaml
matrix_ssl_additional_domains_to_obtain_certificates_for:
  - '{{ matrix_domain }}'

# Choosing the reverse proxy implementation
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: redacted@zarrouk.eu

# Those might not be necessary anymore ?
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate: /matrix/ssl/config/live/zarrouk.eu/fullchain.pem
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate_key: /matrix/ssl/config/live/zarrouk.eu/privkey.pem

# To serve the federation from any domain, as long as the path match
matrix_nginx_proxy_container_labels_traefik_proxy_matrix_federation_rule: PathPrefix(`/_matrix`)

# To let traefik know which domains certificates to serve
matrix_nginx_proxy_container_labels_additional_labels: |
  traefik.http.routers.matrix-nginx-proxy-matrix-federation.tls.domains.main="zarrouk.eu"
  traefik.http.routers.matrix-nginx-proxy-matrix-federation.tls.domains.sans="*.zarrouk.eu"

# I need a DNS acme challenge, not the default http(s) one / this overrides the default ACME configuration without having to disable it, since it would have a wide range of side effects
devture_traefik_configuration_extension_yaml: |
  certificatesResolvers:
    default:
      acme:
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        email: {{ devture_traefik_config_certificatesResolvers_acme_email | to_json }}
        dnsChallenge:
          provider: cloudflare
          resolvers: 
            - "1.1.1.1:53"
            - "8.8.8.8:53"
        storage: {{ devture_traefik_config_certificatesResolvers_acme_storage | to_json }}

# Configure the environment variables needed by traefik to automate the ACME DNS CHallenge
devture_traefik_environment_variables: |
  CF_API_EMAIL=redacted
  CF_ZONE_API_TOKEN=redacted
  CF_DNS_API_TOKEN=redacted
  LEGO_DISABLE_CNAME_SUPPORT=true
```

So for those who don't need the Coturn / certificate exporter services, this is complete.

For me and the others, I'll be trying to solve that last issue.

**Comment by sidewinder94** [comment]
Another way could be to add a symbolink link between `/matrix/traefik-certs-dumper/dumped-certficates/*.domain.tld` and `/matrix/traefik-certs-dumper/dumped-certficates/matrix.domain.tld`

This would replace updating the path in the `ExecStart` directive of the previous comment.

**Comment by sidewinder94** [comment]
Two changes for coturn to test :

To define the certificate paths:
Change :
- matrix_coturn_tls_cert_path
- matrix_coturn_tls_key_path

To not wait on the certificates being dumped (⚠️ might not work on first install, will need the certificates to be exported before starting):
- Override `matrix_coturn_systemd_required_services_list` to only wait on docker

**Comment by sidewinder94** [comment]
Last part of needed config for coturn (to put in vars.yml) :
```yaml
matrix_coturn_systemd_required_services_list: ['docker.service']
matrix_coturn_container_additional_volumes: |
  {{
    (
      [
       {
         'src': (matrix_ssl_config_dir_path + '/live/*.' + matrix_domain + '/fullchain.pem'),
         'dst': '/fullchain.pem',
         'options': 'ro',
       },
       {
         'src': (matrix_ssl_config_dir_path + '/live/*.' + matrix_domain + '/privkey.pem'),
         'dst': '/privkey.pem',
         'options': 'ro',
       },
      ] if matrix_playbook_reverse_proxy_type in ['playbook-managed-nginx', 'other-nginx-non-container'] and matrix_coturn_tls_enabled else []
    )
    +
    (
      [
       {
         'src': (devture_traefik_certs_dumper_dumped_certificates_dir_path +  '/*.' + matrix_domain + '/certificate.crt'),
         'dst': '/certificate.crt',
         'options': 'ro',
       },
       {
         'src': (devture_traefik_certs_dumper_dumped_certificates_dir_path +  '/*.' + matrix_domain + '/privatekey.key'),
         'dst': '/privatekey.key',
         'options': 'ro',
       },
      ] if matrix_playbook_reverse_proxy_type in ['playbook-managed-traefik', 'other-traefik-container'] and devture_traefik_certs_dumper_enabled and matrix_coturn_tls_enabled else []
    )
  }}
```

This removes the dependency on the certificate exporter, and references the wildcard certificate we requested.

**Comment by sidewinder94** [comment]
Final working config : 
```yaml
matrix_ssl_additional_domains_to_obtain_certificates_for:
  - '{{ matrix_domain }}'

# Choosing the reverse proxy implementation
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: redacted@zarrouk.eu

# Those might not be necessary anymore ?
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate: /matrix/ssl/config/live/zarrouk.eu/fullchain.pem
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate_key: /matrix/ssl/config/live/zarrouk.eu/privkey.pem

# To serve the federation from any domain, as long as the path match
matrix_nginx_proxy_container_labels_traefik_proxy_matrix_federation_rule: PathPrefix(`/_matrix`)

# To let traefik know which domains certificates to serve
matrix_nginx_proxy_container_labels_additional_labels: |
  traefik.http.routers.matrix-nginx-proxy-matrix-federation.tls.domains.main="zarrouk.eu"
  traefik.http.routers.matrix-nginx-proxy-matrix-federation.tls.domains.sans="*.zarrouk.eu"

# I need a DNS acme challenge, not the default http(s) one / this overrides the default ACME configuration without having to disable it, since it would have a wide range of side effects
devture_traefik_configuration_extension_yaml: |
  certificatesResolvers:
    default:
      acme:
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        email: {{ devture_traefik_config_certificatesResolvers_acme_email | to_json }}
        dnsChallenge:
          provider: cloudflare
          resolvers: 
            - "1.1.1.1:53"
            - "8.8.8.8:53"
        storage: {{ devture_traefik_config_certificatesResolvers_acme_storage | to_json }}

# Configure the environment variables needed by traefik to automate the ACME DNS CHallenge
devture_traefik_environment_variables: |
  CF_API_EMAIL=redacted
  CF_ZONE_API_TOKEN=redacted
  CF_DNS_API_TOKEN=redacted
  LEGO_DISABLE_CNAME_SUPPORT=true

# Only depend on docker.service, this removes the dependency on the certificate exporter, might imply the need to manually restart coturn on the first installation once the certificates are obtained, afterwards, the reload service should handle things
matrix_coturn_systemd_required_services_list: ['docker.service']

# This changes the path of the loaded certificate, while maintaining the original functionality, we're now loading the wildcard certificate.
matrix_coturn_container_additional_volumes: |
  {{
    (
      [
       {
         'src': (matrix_ssl_config_dir_path + '/live/*.' + matrix_domain + '/fullchain.pem'),
         'dst': '/fullchain.pem',
         'options': 'ro',
       },
       {
         'src': (matrix_ssl_config_dir_path + '/live/*.' + matrix_domain + '/privkey.pem'),
         'dst': '/privkey.pem',
         'options': 'ro',
       },
      ] if matrix_playbook_reverse_proxy_type in ['playbook-managed-nginx', 'other-nginx-non-container'] and matrix_coturn_tls_enabled else []
    )
    +
    (
      [
       {
         'src': (devture_traefik_certs_dumper_dumped_certificates_dir_path +  '/*.' + matrix_domain + '/certificate.crt'),
         'dst': '/certificate.crt',
         'options': 'ro',
       },
       {
         'src': (devture_traefik_certs_dumper_dumped_certificates_dir_path +  '/*.' + matrix_domain + '/privatekey.key'),
         'dst': '/privatekey.key',
         'options': 'ro',
       },
      ] if matrix_playbook_reverse_proxy_type in ['playbook-managed-traefik', 'other-traefik-container'] and devture_traefik_certs_dumper_enabled and matrix_coturn_tls_enabled else []
    )
  }}
```
