### ISSUE TITLE
proxyHealthCheck error: Sliding-Sync tells the client the internal docker hostname http://matrix-nginx-proxy:12080

### ISSUE THREAD

**Issue by MichaelSasser** [spantaleev/matrix-docker-ansible-deploy#2572]
**Describe the bug**

Hey, I've wanted to try out syncv3. I've "switched" the reverse proxy to traefik with 
`matrix_playbook_reverse_proxy_type: playbook-managed-traefik`
and I've enabled sliding sync. After that, I wanted to try it out with element-web, where I got an error: `proxyHealthCheck: client using https://matrix.foo.bar but server is as http://matrix-nginx-proxy:12080`. Just to make sure, I gave it a domain `sliding-sync.foo.bar` with the root endpoint `/` and gave it another shot, but I got the same error message.

`https://sliding-sync.foo.bar/client/server.json` gives me the container hostname / docker DNS:
```json
{
  "server": "http://matrix-nginx-proxy:12080",
  "version": "0.99.1 (2f8e3313d8df1a6df39b3ea6e083992de7a8c5e3)"
}
```

In comparison, the client and server well-known endpoints:

`https://matrix.foo.bar/.well-known/matrix/server`:
```json
{
  "m.server": "matrix.foo.bar:8448"
}
```

```json
{
  "admins": [
    {
      "email_address": "info@foo.bar",
      "matrix_id": "@michael:foo.bar",
      "role": "admin"
    },
    {
      "email_address": "abuse@foo.bar",
      "role": "security"
    }
  ],
  "features": {
    "feature_html_topic": true,
    "feature_latex_maths": true,
    "feature_pinning": true,
    "feature_report_to_moderators": true,
    "feature_thread": true
  },
  "im.vector.riot.jitsi": {
    "preferredDomain": "jitsi.foo.bar"
  },
  "io.element.jitsi": {
    "preferredDomain": "jitsi.foo.bar"
  },
  "jitsi": {
    "preferred_domain": "jitsi.foo.bar"
  },
  "m.homeserver": {
    "base_url": "https://matrix.foo.bar"
  },
  "m.tile_server": {
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=MyKey"
  },
  "org.matrix.msc3488.tile_server": {
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=MyKey"
  },
  "org.matrix.msc3575.proxy": {
    "url": "https://sliding-sync.foo.bar"
  },
  "setting_defaults": {
    "MessageComposerInput.showStickersButton": false
  }
}
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---

docker_network_name: matrix
---

security_fail2ban_enabled: true
fail2ban_bantime: 604800
fail2ban_findtime: 86400
fail2ban_maxretry: 3
---

grafana_loki_upgrade: true
grafana_promtail_upgrade: true
---

matrix_synapse_auto_compressor_enabled: true
---
matrix_bot_honoroit_enabled: true
matrix_bot_honoroit_database_engine: "postgres"
matrix_bot_honoroit_database_password: ...

matrix_bot_honoroit_password: ...
matrix_bot_honoroit_login: helpdesk
matrix_bot_honoroit_roomid: "!...:{{ matrix_domain }}"

matrix_bot_honoroit_text_prefix_open: "[OPEN]"
matrix_bot_honoroit_text_prefix_done: "[CLOSED]"

matrix_bot_honoroit_text_noencryption: >-
  ...

matrix_bot_honoroit_text_greetings: >-
  ...

matrix_bot_honoroit_text_invite: >-
  ...

matrix_bot_honoroit_text_join: >-
  ...

matrix_bot_honoroit_text_leave: >-
  ...

matrix_bot_honoroit_text_error: >-
  ...

matrix_bot_honoroit_text_emptyroom: >-
  ...

matrix_bot_honoroit_text_done: >-
  ...

matrix_bot_honoroit_environment_variables_extension: >-
  ...
---

matrix_hookshot_enabled: true  # default
matrix_hookshot_gitlab_enabled: true
matrix_hookshot_widgets_addToAdminRooms: true
matrix_hookshot_permissions:
  # Allow all users to send commands to existing services
  - actor: "*"
    services:
      - service: gitlab
        level: commands
  - actor: "@..."
    services:
      - service: "*"
        level: admin
---

matrix_bot_mjolnir_enabled: true
matrix_bot_mjolnir_access_token: ...
matrix_bot_mjolnir_management_room: ...
matrix_bot_mjolnir_configuration_extension_yaml: |
  backgroundDelayMS: 50
  fasterMembershipChecks: true
  recordIgnoredInvites: true
  commands:
    additionalPrefixes:
        - mjolnir
        - bot
  automaticallyRedactForReasons:
    - ...
  protections:
    wordlist:
      words:
        - ...
      minutesBeforeTrusting: 1440
---

matrix_ssl_lets_encrypt_support_email: ...
---

matrix_client_cinny_enabled: false
matrix_server_fqn_cinny: "cinny.{{ matrix_domain }}"
---
matrix_client_element_version: v1.11.25-rc.3

matrix_client_element_registration_enabled: false
matrix_client_element_enable_presence_by_hs_url:
  ...

matrix_client_element_roomdir_servers:
  - matrix.org
  - ...

matrix_client_element_themes_enabled: false
matrix_client_element_default_theme: "dark"

matrix_client_element_configuration_extension_json: |
  {
     "sso_redirect_options": {
        "immediate": true
     }
  }

matrix_client_element_integrations_jitsi_widget_url: "https://jitsi.{{ matrix_domain }}/api/widgets/jitsi.html"
matrix_client_element_jitsi_preferredDomain: "jitsi.{{ matrix_domain }}"
matrix_client_hydrogen_enabled: true
---

grafana_enabled: true
grafana_anonymous_access: false
grafana_default_admin_user: ...
grafana_default_admin_password: ...

grafana_container_extra_arguments:
  - -e GF_AUTH_GENERIC_OAUTH_NAME="Single Sign-On"
  - -e GF_AUTH_GENERIC_OAUTH_ENABLED="true"
  - -e GF_AUTH_GENERIC_OAUTH_CLIENT_ID="matrix-grafana"
  - -e GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET="...."
  - -e GF_AUTH_GENERIC_OAUTH_SCOPES="openid"
  - -e GF_AUTH_GENERIC_OAUTH_AUTH_URL="..."
  - -e GF_AUTH_GENERIC_OAUTH_TOKEN_URL="..."
  - -e GF_AUTH_GENERIC_OAUTH_API_URL="..."
  - -e GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP="true"
  - -e GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH="contains(roles[*], 'Admin') && 'Admin' || contains(roles[*], 'Editor') && 'Editor' || contains(roles[*], 'Viewer') && 'Viewer'|| ''"
  - -e GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT="true"
  - -e GF_AUTH_DISABLE_LOGIN_FORM="true"
  - -e GF_AUTH_OAUTH_AUTO_LOGIN="true"
  - -e GF_AUTH_BASIC_ENABLED="false"

matrix_heimdall_appservice_token: "..."
matrix_heimdall_homeserver_token: "..."
matrix_heimdall_registration_yaml:
  id: heimdall
  url: http://...
  as_token: "{{ matrix_heimdall_appservice_token }}"
  hs_token: "{{ matrix_heimdall_homeserver_token }}"
  sender_localpart: heimdall
  namespaces:
    aliases:
      - regex: "#heimdall_.*"
        exclusive: true
      - regex: "#hdp_.*"
        exclusive: true
    rooms: []
    users:
      - regex: "@heimdall_.*"
        exclusive: true
  rate_limited: false
  protocols: []

# stuff before unneeded, copied file manually
matrix_synapse_container_extra_arguments:
  - --mount type=bind,src=/matrix/heimdall/registration.yaml,dst=/matrix-heimdall-registration.yaml,ro

matrix_synapse_app_service_config_files:
  - "/matrix-heimdall-registration.yaml"
---
# Jitsi
# TODO: Remove jitsi
matrix_jitsi_enabled: false
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_enable_lobby: true
matrix_jitsi_enable_recording: false
matrix_jitsi_enable_transcriptions: false
matrix_jitsi_jicofo_component_secret: ...
matrix_jitsi_jicofo_auth_password: ...
matrix_jitsi_jvb_auth_password: ...
matrix_jitsi_jibri_recorder_password: ...
matrix_jitsi_jibri_xmpp_password: ...

matrix_jitsi_web_config_resolution_width_ideal_and_max: 1920
matrix_jitsi_web_config_resolution_height_ideal_and_max: 1200
matrix_jitsi_web_config_resolution_width_min: 1280
matrix_jitsi_web_config_resolution_height_min: 720

matrix_jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
  config.disableAudioLevels = true;
  config.channelLastN = 4;
  config.disableSimulcast = true;

matrix_jitsi_web_custom_interface_config_extension: |
  interfaceConfig.SHOW_JITSI_WATERMARK = false;
  interfaceConfig.SHOW_BRAND_WATERMARK = false;
  interfaceConfig.SHOW_WATERMARK_FOR_GUESTS = true;
  interfaceConfig.GENERATE_ROOMNAMES_ON_WELCOME_PAGE = true;
  interfaceConfig.DISABLE_TRANSCRIPTION_SUBTITLES = false;

# LDAP Jitsi
matrix_jitsi_auth_type: "ldap"
matrix_jitsi_ldap_auth_method: "bind"
matrix_jitsi_ldap_version: "3"
matrix_jitsi_ldap_use_tls: false
matrix_jitsi_ldap_url: "..."
matrix_jitsi_ldap_base: "..."
matrix_jitsi_ldap_binddn: "..."
matrix_jitsi_ldap_bindpw: "..."
matrix_jitsi_ldap_filter: "...."
---

matrix_synapse_password_config_localdb_enabled: false # disable the internal password auth

matrix_mailer_sender_address: "..."
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "..."
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "..."
matrix_mailer_relay_auth_password: "...."
---

matrix_synapse_rust_synapse_compress_state_find_rooms_command_wait_time: 1200
matrix_synapse_rust_synapse_compress_state_compress_room_time: 68400 # 2.5h -> 5h
matrix_synapse_rust_synapse_compress_state_psql_import_time: 68400 # 2.5h -> 5h
---
devture_postgres_connection_password: "..."
devture_postgres_container_postgres_bind_port: 5432

devture_postgres_process_extra_arguments:
  [
    "-c max_connections=150",
    "-c shared_buffers=1GB",
    "-c effective_cache_size=3GB",
    "-c maintenance_work_mem=256MB",
    "-c checkpoint_completion_target=0.9",
    "-c wal_buffers=16MB",
    "-c default_statistics_target=100",
    "-c random_page_cost=1.1",
    "-c effective_io_concurrency=200",
    "-c work_mem=5242kB",
    "-c min_wal_size=1GB",
    "-c max_wal_size=4GB",
    "-c max_worker_processes=2",
    "-c max_parallel_workers_per_gather=1",
    "-c max_parallel_workers=2",
    "-c max_parallel_maintenance_workers=1",
  ]
---

# Prometheus
matrix_prometheus_enabled: true

# Postgres Exporter
prometheus_postgres_exporter_enabled: false
prometheus_postgres_exporter_database_username: "..."
prometheus_postgres_exporter_database_password: "..."

# Node Exporter
prometheus_node_exporter_enabled: true
prometheus_node_exporter_process_extra_arguments:
  - "--collector.disable-defaults"
  - "--collector.cpu"
  - "--collector.filesystem"
  - "--collector.os"
  - "--collector.stat"
  - "--collector.meminfo"
  - "--collector.loadavg"
  - "--collector.time"
  - "--collector.uname"  # Mandatory
---

matrix_sliding_sync_enabled: true

matrix_sliding_sync_hostname: "sliding-sync.foo.bar"
matrix_sliding_sync_path_prefix: /
---
matrix_synapse_federation_enabled: true
matrix_synapse_allow_public_rooms_over_federation: true
matrix_synapse_allow_public_rooms_without_auth: true
matrix_synapse_caches_global_factor: 1.5 # 0.5, is default
matrix_synapse_event_cache_size: "100K"
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true
matrix_synapse_configuration_extension_yaml: |
  suppress_key_server_warning: true  # defaults to matrix.org

  ####################
  # blacklist
  ####################
  ip_range_blacklist:
    - ...

  ####################
  # server notice
  ####################
  server_notices:
    system_mxid_localpart: server
    system_mxid_display_name: "Server Notices"
    system_mxid_avatar_url: "mxc://{{ matrix_domain }}/..."
    room_name: "Server Notices"

  ####################
  # Experimental Features
  ####################
  experimantal_features:
    msc3030_enabled: true

  ####################
  # OIDC
  ####################
  oidc_providers:
    - idp_id: keycloak
      idp_name: "Single Sign-On"
      issuer: "..."
      client_id: "..."
      client_secret: "..."
      scopes: ["openid", "profile"]
      allow_existing_users: true
      user_mapping_provider:
        config:
          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
      backchannel_logout_enabled: true

# Media retention
matrix_synapse_media_retention_local_media_lifetime: 8w
matrix_synapse_media_retention_remote_media_lifetime: 1w

# workers
matrix_synapse_workers_enabled: true

matrix_synapse_workers_preset: foo
matrix_synapse_workers_presets:
  foo:
    generic_workers_count: 1
    pusher_workers_count: 1
    federation_sender_workers_count: 1
    media_repository_workers_count: 1
    appservice_workers_count: 1
    user_dir_workers_count: 1
    background_workers_count: 1
    stream_writer_events_stream_workers_count: 0
    stream_writer_typing_stream_workers_count: 0
    stream_writer_to_device_stream_workers_count: 0
    stream_writer_account_data_stream_workers_count: 0
    stream_writer_receipts_stream_workers_count: 0
    stream_writer_presence_stream_workers_count: 0

matrix_synapse_macaroon_secret_key: "..."
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_synapse_max_upload_size_mb: 256

matrix_synapse_auto_join_rooms:
  - "#support:{{ matrix_domain }}"

# Shared Secret Provider
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: false # disabled to make sure no m.password authentication is available
matrix_synapse_ext_password_provider_shared_secret_auth_m_login_password_support_enabled: false # disabled to make sure no m.password authentication is available
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "..."
---
devture_timesync_ntpd_package: systemd-timesyncd
devture_timesync_ntpd_service: systemd-timesyncd

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: ...

##### KEEP NGINX VARIABLES #######
matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_nginx_proxy_connect_timeout: 120
matrix_nginx_proxy_send_timeout: 120
matrix_nginx_proxy_read_timeout: 120
matrix_nginx_send_timeout: 120

matrix_nginx_proxy_proxy_matrix_client_redirect_root_uri_to_domain: ""
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true
matrix_coturn_turn_static_auth_secret: "..."

---

# Enable location sharing
matrix_well_known_matrix_client_configuration_extension_json: |-
  {
    "jitsi": {
      "preferred_domain": "..."
    },
    "org.matrix.msc3488.tile_server": {
      "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=..."
    },
    "m.tile_server": {
      "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=..."
    },
    "setting_defaults": {
      "MessageComposerInput.showStickersButton": false
    },
    "features": {
      "feature_latex_maths": true,
      "feature_pinning": true,
      "feature_thread": true,
      "feature_report_to_moderators": true,
      "feature_html_topic": true
    },
    "admins": [{
      "matrix_id": "..",
      "email_address": "...",
      "role": "admin"
    },
    {
      "email_address": "...",
      "role": "security"
    }]
  }
---

security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"

---

swap_file_size_mb: "4069" # in MB
---
sysctl_vm_swappiness: 1
# sysctl_vm_overcommit_memory: 1
---

journald_journal:
  max_retention_sec: 2week
  max_file_sec: 1week
  system_max_use: 2G
---
# headscale ns: hnet

tailscale_login_server: "..."
tailscale_authkey: "..."
security_autoupdate_reboot: false
security_autoupdate_reboot_time: "04:00"
security_autoupdate_mail_to: "Michael@{{ domain }}"
security_autoupdate_mail_on_error: true
security_autoupdate_enabled: true
---

group_list:
  - name: ...
    state: present
  - name: docker
    gid: 998  # 998 Debian - 969 Arch
    system: true
    state: present

user_list:
  - name: ...
    group: ...
    createhome: true
    bootstrap: true
    comment: ...
    shell: /usr/bin/bash
    groups:
      - sudo
      - floppy
      - video
      - audio
      - games
      - disk
      - docker

---
# Python Interpreter
ansible_python_interpreter: "/usr/bin/python3"

domain: ...

matrix_domain: "{{ domain }}"

# hard limit: 30 sec
devture_systemd_service_manager_up_verification_delay_seconds: 28
---
wireguard_wg0_interface:
  ...

wireguard_wg0_peers:
  ...

```

**Expected behavior**
No error message, client adopts syncv3

**Matrix Server:**
 - OS: `Linux matrix 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`

**Client:**
 - Device: `Linux x1 6.2.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:23 +0000 x86_64 GNU/Linux`
 - Browser Mozilla Firefox 110.0.1 - Element Web v1.11.25-rc.3
