### ISSUE TITLE
Sliding Sync: Incorrect Server URL Environment Variable Value

### ISSUE THREAD

**Issue by Kab1r** [spantaleev/matrix-docker-ansible-deploy#2583]
**Describe the bug**
Sliding Sync Proxy uses an internal URL instead of the external one.
This prevents it from being usable from Element Web

**To Reproduce**
My `vars.yml` file looks roughly like this, but it's probably reproducible on x86 as well:

```yaml
matrix_architecture: arm64
matrix_sliding_sync_enabled: true
matrix_homeserver_implementation: synapse
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
```
Making the HTTP request, or looking at the devtools logs from element-web when setting the sliding sync URL, we see the following incorrect response and the URL being rejected .

```http
GET https://matrix.domain.tld/sliding-sync/client/server.json
```
```json
{"server":"http://matrix-nginx-proxy:12080","version":"0.99.1 (2f8e3313d8df1a6df39b3ea6e083992de7a8c5e3)"}
```

**Expected behavior**
```http
GET https://matrix.domain.tld/sliding-sync/client/server.json
```
```json
{"server":"http://matrix.domain.tld","version":"0.99.1 (2f8e3313d8df1a6df39b3ea6e083992de7a8c5e3)"}
```
**Matrix Server:**
 - OS: Ubuntu 22.04.2 LTS aarch64
 - Architecture: arm64

**Fix**
I can create a PR, but here's the basic patch
```patch
diff --git a/roles/custom/matrix-sliding-sync/defaults/main.yml b/roles/custom/matrix-sliding-sync/defaults/main.yml
index f66b3b61..fa6e65a4 100644
--- a/roles/custom/matrix-sliding-sync/defaults/main.yml
+++ b/roles/custom/matrix-sliding-sync/defaults/main.yml
@@ -76,7 +76,7 @@ matrix_sliding_sync_systemd_required_services_list: ["docker.service"]
 matrix_sliding_sync_systemd_wanted_services_list: []
 
 # Controls the SYNCV3_SERVER environment variable
-matrix_sliding_sync_environment_variable_syncv3_server: "{{ matrix_homeserver_container_url }}"
+matrix_sliding_sync_environment_variable_syncv3_server: "{{ matrix_homeserver_url }}"
 
 # Controls the SYNCV3_SECRET environment variable
 matrix_sliding_sync_environment_variable_syncv3_secret: ''
```

**Comment by spantaleev** [comment]
This is intentional. The container networks are meant to be connected and sliding sync should be able to connect to Synapse without going through the public network.

It works for me and for many others. If it doesn't work for you, your configuration may be more special somehow. You should look into that.

**Comment by Kab1r** [comment]
Hmm, is it possible that element received an update validating the URL? I am using the self-hosted role.

The error reads: `proxyHealthCheck: client using https://matrix.domain.tld but server is as http://matrix-nginx-proxy:12080`

**Comment by Kab1r** [comment]
Here is a larger portion of my configuration, but most of this is unrelated:
```yaml
---
matrix_architecture: arm64
matrix_domain: removed.tld
matrix_homeserver_implementation: synapse
matrix_synapse_report_stats: true
matrix_ssl_lets_encrypt_support_email: kabir+le@removed.tld
devture_traefik_config_certificatesResolvers_acme_email: kabir+le@removed.tld
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_postgres_connection_password: removed
matrix_homeserver_generic_secret_key: removed
matrix_synapse_ext_synapse_s3_storage_provider_enabled: true
matrix_synapse_ext_synapse_s3_storage_provider_config_bucket: synapse-media-store
matrix_synapse_ext_synapse_s3_storage_provider_config_region_name: auto
matrix_synapse_ext_synapse_s3_storage_provider_config_endpoint_url: removed
matrix_synapse_ext_synapse_s3_storage_provider_config_access_key_id: removed
matrix_synapse_ext_synapse_s3_storage_provider_config_secret_access_key: removed
matrix_synapse_ext_synapse_s3_storage_provider_config_storage_class: STANDARD

matrix_client_element_showLabsSettings: true
matrix_client_element_themes_enabled: true
matrix_client_element_default_theme: 'Dracula'
matrix_client_element_default_country_code: "US"
matrix_well_known_matrix_client_io_element_e2ee_default: true

matrix_jitsi_enabled: false
matrix_ma1sd_enabled: true
matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true
matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@kabir:{{ matrix_domain }}"
matrix_dimension_access_token: removed
matrix_mailer_sender_address: "matrix@{{ matrix_domain}}"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: removed
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: removed
matrix_mailer_relay_auth_password: removed
grafana_enabled: true
grafana_anonymous_access: false
grafana_default_admin_user: removed
grafana_default_admin_password: removed
matrix_prometheus_enabled: true
matrix_synapse_metrics_enabled: true
prometheus_node_exporter_enabled: true
prometheus_nginxlog_exporter_enabled: true
prometheus_postgres_exporter_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: removed
matrix_admin: "@kabir:{{ matrix_domain }}"
// a bunch of bridges configured here
matrix_sliding_sync_enabled: true
```
