### ISSUE TITLE
Jitsi doesn't assign moderator role to any user when internal auth is enabled

### ISSUE THREAD

**Issue by aine-etke** [spantaleev/matrix-docker-ansible-deploy#2589]
**Describe the bug**
Once you enable jitsi internal auth, no one can get moderator permissions anymore

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_jitsi_enabled: yes
matrix_jitsi_enable_auth: yes
matrix_jitsi_enable_guests: yes
matrix_jitsi_jvb_auth_password: REDACTED
matrix_jitsi_jibri_xmpp_password: REDACTED
matrix_jitsi_jibri_recorder_password: REDACTED
matrix_jitsi_jicofo_auth_password: REDACTED
matrix_jitsi_prosody_auth_internal_accounts:
 - username: REDACTED
   password: REDACTED
```

1. Enable jitsi internal auth (the config above)
2. Start a meeting
3. Login with the credentals from `matrix_jitsi_prosody_auth_internal_accounts`
4. Notice you are not moderator and you can't set meeting password anymore

**Expected behavior**
Once you login with the credentials from `matrix_jitsi_prosody_auth_internal_accounts`, you should have full access to moderator tools, the same way as it was before enabling jitsi internal auth

**Matrix Server:** Unrelated

**Ansible:** Unrelated

**Client:** Unrelated

**Additional context**
Moderator role assignment works without internal auth
