### ISSUE TITLE
Fresh install, traefik 404 and invalid certificate 

### ISSUE THREAD

**Issue by yousefamar** [spantaleev/matrix-docker-ansible-deploy#2591]
**Describe the bug**

Hi! Really scratching my head over this one, any help appreciated. When I start a fresh install with only some light customisation, it seems that traefik doesn't quite work, and I can't see why. The certificate is invalid (TRAEFIK DEFAULT CERT), and all requests return "404 page not found". I tried enabling the traefik dashboard to see what might be going on, but that 404s too. I can't seem to read the docker logs for `matrix-traefik` either. Any tips or info on somewhere I could check logs would be much appreciated!

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
matrix_domain: chat.amar.io
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: "{{ vault_matrix_homeserver_generic_secret_key }}"
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: 'yousef@amar.io'
devture_postgres_connection_password: "{{ vault_devture_postgres_connection_password }}"

# Cinny

matrix_client_cinny_enabled: true

# Bridges

matrix_mautrix_whatsapp_enabled: true
matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true

# Traefik

devture_traefik_dashboard_enabled: true
devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
devture_traefik_dashboard_basicauth_enabled: true
devture_traefik_dashboard_basicauth_user: amar
devture_traefik_dashboard_basicauth_password: "{{ vault_devture_traefik_dashboard_basicauth_password }}"

# Stats

matrix_prometheus_enabled: true
prometheus_node_exporter_enabled: true
prometheus_postgres_exporter_enabled: true
matrix_prometheus_nginxlog_exporter_enabled: true

grafana_enabled: true
grafana_anonymous_access: false
grafana_default_admin_user: "amar"
grafana_default_admin_password: "{{ vault_grafana_default_admin_password }}"
```

**Matrix Server:**
```
ubuntu@ip-172-31-20-51:~$ uname -a
Linux ip-172-31-20-51 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-20-51:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
