### ISSUE TITLE
Cant connect to a room outside my matrix homeserver (problem with Federation or well_known)

### ISSUE THREAD

**Issue by PottersGame** [spantaleev/matrix-docker-ansible-deploy#2605]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: potter.sk

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'key'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'fas@asfd'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'key'
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_coturn_turn_external_ip_address: fake.ip

matrix_mautrix_whatsapp_enabled: true
matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true
matrix_mautrix_facebook_enabled: true

matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true

matrix_mautrix_instagram_enabled: true
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true
matrix_mautrix_discord_enabled: true
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: 1*
matrix_mautrix_telegram_api_hash: *
matrix_synapse_admin_enabled: true


# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: *
matrix_architecture: arm64

matrix_bot_matrix_reminder_bot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_matrix_reminder_bot_matrix_user_id_localpart: bot.matrix-reminder-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_reminder_bot_matrix_user_password: key

# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/MyHome
# Enabling it is the only required setting
ntfy_enabled: true

# This is the default hostname.
# Uncomment the line below and change it, if you'd like.
# matrix_server_fqn_ntfy: "ntfy.{{ matrix_domain }}"

# Uncomment and change to inject additional configuration options.
# ntfy_configuration_extension_yaml: |
#   log_level: DEBUG

matrix_jitsi_enabled: true

# Run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
# or define your own strong passwords manually.
matrix_jitsi_jicofo_auth_password: "key"
matrix_jitsi_jvb_auth_password: "key"
matrix_jitsi_jibri_recorder_password: "key"
matrix_jitsi_jibri_xmpp_password: "key"
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: *@gmail.com


matrix_synapse_auto_compressor_enabled: true

matrix_synapse_allow_public_rooms_over_federation: true

matrix_nginx_proxy_base_domain_homepage_enabled: false


```

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture arm64

**Problem description**:
I have a problem that i cant connect to any room outside my homeserver and its probably because of federation. tried to fix it using previous bug reports but that does not seemed to work. I think i had this problem before treafik so i am not shure what it could be. 

this is my Federation json [https://federationtester.matrix.org/api/report?server_name=potter.sk](https://federationtester.matrix.org/api/report?server_name=potter.sk)
