### ISSUE TITLE
Poostmoogle service failed to start

### ISSUE THREAD

**Issue by Gregivy** [spantaleev/matrix-docker-ansible-deploy#2613]
**Describe the bug**
After upgrading to latest commit of this repo and switching to traefik postmoogle bot stopped working.

Here is the log from `journalctl -fu matrix-bot-postmoogle.service`:
```
Dependency failed for Matrix Postmoogle bot.
systemd[1]: matrix-bot-postmoogle.service: Job matrix-bot-postmoogle.service/start failed with result 'dependency'.
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_bot_postmoogle_enabled: true
# Adjust this to whatever password you chose when registering the bot user
matrix_bot_postmoogle_password: "..."
matrix_bot_postmoogle_domains:
  - "domain.ltd"
  - "{{ matrix_server_fqn_matrix }}"
```

**Expected behavior**
Bot should work as before.

**Matrix Server:**
 - OS: Ubuntu 22.04 LTS

**Ansible:**
I use ansible locally through a docker container, `ansible [core 2.13.0]`.

**Additional context**
I tried to set `matrix_bot_postmoogle_enabled` to `false` then to `true` and setup-all with ansible but no effect.
