### ISSUE TITLE
Prometheus metrics endpoint not found

### ISSUE THREAD

**Issue by ToeiRei** [spantaleev/matrix-docker-ansible-deploy#2619]
**Describe the bug**
I configured prometheus to feed the metrics into my (already existing) grafana instance. I would expect the metrics to be at /metrics but all I get is a "Sorry. No luck finding that resource."

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
#  Prometheus Monitoring
prometheus_enabled: true
prometheus_node_exporter_enabled: true

prometheus_nginxlog_exporter_enabled: true
prometheus_services_proxy_connect_prometheus_node_exporter_metrics_proxying_enabled: true

matrix_nginx_proxy_proxy_matrix_metrics_enabled: true
matrix_nginx_proxy_proxy_matrix_metrics_basic_auth_enabled: true
matrix_nginx_proxy_proxy_matrix_metrics_basic_auth_username: someuser
matrix_nginx_proxy_proxy_matrix_metrics_basic_auth_password: somepass
matrix_synapse_metrics_proxying_enabled: true

# No grafana here
grafana_enabled: false
grafana_anonymous_access: false

```

**Expected behavior**
Metrics?

**Matrix Server:**
 - OS: Debian 11
 - Architecture is amd64
