### ISSUE TITLE
Outdated documentation for deployment behind CDN proxy (Cloudflare, etc.) / Error when federating over port 443

### ISSUE THREAD

**Issue by Aeris1One** [spantaleev/matrix-docker-ansible-deploy#2634]
When deploying with federation port as 443 (through `matrix_federation_public_port: 443`), Traefik errors out because port is already bound to nginx (which is still used in front of Synapse).

The related [documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-federation.md#changing-the-federation-port-from-8448-to-a-different-port-to-use-a-cdn-that-only-accepts-44380-ports) which says to use the following config is then outdated.

```yaml
matrix_synapse_http_listener_resource_names: ["client","federation"]
matrix_federation_public_port: 443
matrix_synapse_federation_port_enabled: false
# eventually : matrix_synapse_tls_federation_listener_enabled: false
```
