### ISSUE TITLE
Traefik fronted with nginx returns "404 page not found" for matrix.<my-domain>

### ISSUE THREAD

**Issue by shade-belisar** [spantaleev/matrix-docker-ansible-deploy#2642]
**Describe the bug**
I followed this guide to setup my matrix server with nginx fronting for traefik.
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/examples/nginx/README.md
When accessing matrix.my-domain, I only get the text "404 page not found" (no actual 404 though). However, the web client on element.my-domain is delivered correctly, it just can't connect to the home server. Neither can my Element apps on Linux or Android.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: <my-domain>

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '<secret-key>'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: '<my-email>'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: '<postgres-password>'

matrix_nginx_proxy_enabled: false

matrix_ssl_retrieval_method: none

matrix_synapse_admin_enabled: true

matrix_registration_enabled: true

matrix_registration_admin_secret: "<admin-secret>"

matrix_coturn_turn_udp_max_port: 49200

# matrix_synapse_federation_enabled: false

matrix_ma1sd_enabled: true

matrix_synapse_auto_join_rooms: ["#main:<my-domain>"]

# Use traefik as the internal webserver for matrix
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# Ensure that public urls use https
matrix_playbook_ssl_enabled: true

# Disable the web-secure (port 443) endpoint, which also disables SSL certificate retrieval
devture_traefik_config_entrypoint_web_secure_enabled: false

# If your reverse-proxy runs on another machine, consider using `0.0.0.0:81`, just `81` or `SOME_IP_ADDRESS_OF_THIS_MACHINE:81`
devture_traefik_container_web_host_bind_port: '127.0.0.1:81'

devture_traefik_config_log_level: DEBUG

# We bind to `127.0.0.1` by default (see above), so trusting `X-Forwarded-*` headers from
# a reverse-proxy running on the local machine is safe enough.
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true

devture_traefik_additional_entrypoints_auto:
  - name: matrix-federation
    port: 8449
    host_bind_port: '127.0.0.1:8449'
    config: {}
```

My nginx config looks like this:
```
server {
	listen 8448 ssl http2 default_server;
	listen [::]:8448 ssl http2 default_server;

	server_name matrix.bielefeldt.berlin;

	location / {
		proxy_pass http://localhost:8449;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $host;

		access_log /var/log/nginx/matrix.access.log;
		error_log /var/log/nginx/matrix.error.log;

		client_max_body_size 50M;
	}

	ssl_certificate /etc/letsencrypt/live/bielefeldt.berlin/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/bielefeldt.berlin/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = element.bielefeldt.berlin) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = matrix.bielefeldt.berlin) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80;

	server_name matrix.bielefeldt.berlin element.bielefeldt.berlin;
    return 404; # managed by Certbot
}
```

I install matrix and setup nginx according to the guide, then try to access matrix.my-domain

**Expected behavior**
I would expect the home server to be accessible at the matrix subdomain.

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture amd64
