### ISSUE TITLE
Fronting the integrated reverse-proxy with another reverse-proxy results 502 error

### ISSUE THREAD

**Issue by NablaMetal** [spantaleev/matrix-docker-ansible-deploy#2651]
### Describe the bug:
I'm trying to deploy a matrix (synapse/element) server on an existing server.
I have already an nginx ([SWAG ](https://docs.linuxserver.io/general/swag)instance) installed on the server, so I'm trying to go for a solution where I keep the default traefik playbook-managed reverse proxy behind my host existing reverse proxy as described [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md).
Unfortunately I get 502 Bad Gateway Errors, when I try to connect to matrix.mydomain.com.
#### The (anonynmized) nginx error log:
`[error] 621#621: 2 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XXX.XX, server: matrix., request: "GET / HTTP/2.0", upstream: "http://172.25.0.10:81/502.html", host: "matrix.mydomain.com"`
the 172.25.0.10 ip address is the matrix-traefik container ip address (wich the nginx of the host is able to resolve).
#### The (anonynmized) vars.yml:
```
matrix_domain: mydomain.com 
matrix_homeserver_implementation: synapse 
matrix_homeserver_generic_secret_key: 'xxx'
devture_postgres_connection_password: 'yyy'
devture_playbook_state_preserver_commit_hash_preservation_enabled: false
matrix_playbook_docker_installation_enabled: false
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '127.0.0.1:81'
devture_traefik_additional_entrypoints_auto:
  - name: matrix-federation 
    port: "{{ matrix_federation_public_port }}"
    host_bind_port: "127.0.0.1:{{      matrix_federation_public_port }}"
    config: {}
```
#### My matrix.subdomain.conf in my host nginx conf folder:
I use a domain wildcard cert.
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name matrix.* element.*;
    include /config/nginx/ssl.conf; 

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        proxy_pass http://matrix-traefik:81;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 50M;
    }
}

# settings for matrix federation
server {
    listen 8448 ssl http2 default_server;
    listen [::]:8448 ssl http2 default_server;

    server_name matrix.*;
    include /config/nginx/ssl.conf; 

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        proxy_pass http://matrix-traefik:8449;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        client_max_body_size 50M;
    }
}

```
##### Matrix Server:
OS: Ubuntu 22.04
Architecture: x86_64
##### Ansible:
I'm using Ansible:2.13.6-r0-3 on docker from within the host according to the [documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md#running-ansible-in-a-container-on-the-matrix-server-itself).

I don't if it does matter or not, but the bare domain itself (mydomain.com) hosts a wordpress website, also behind the host nginx reverse proxy, which is accessible. All matrix containers are up and running.

I would highly appreciate any help, I spent two days trying various things but I can't get it working. Thank you!
