### ISSUE TITLE
Traefik Default Cert Published

### ISSUE THREAD

**Issue by recreational-grade** [spantaleev/matrix-docker-ansible-deploy#2657]
I use Let's Encrypt SSL by default and do not have any custom Traefik settings, the only thing in my YML is:  
```yml
# Traefik Reverse Proxy
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: [withheld]
```  
But there is a self-signed certificate that is published on the root IP of our matrix.\<my-domain\>: 
```
Issuer Name: TRAEFIK DEFAULT CERT
DNS Name: <some hash>.traefik.default
```  
Is there some configuration that needs to be added? Before using Traefik, I was using nginx but reconfigured for Traefik when that became preferred.
