### ISSUE TITLE
ChatGPT bot fails to install with api key

### ISSUE THREAD

**Issue by ZenKyma** [spantaleev/matrix-docker-ansible-deploy#2681]
**Describe the bug**

ChatGPT bot fails to install when following the documentation:

```TASK [custom/matrix-bot-chatgpt : Fail if required Chatgpt settings not defined] ************************************************************************************************************************************
failed: [matrix.synkosmos.org] (item={'name': 'matrix_bot_chatgpt_openai_email', 'when': True}) => changed=false 
  ansible_loop_var: item
  item:
    name: matrix_bot_chatgpt_openai_email
    when: true
  msg: You need to define a required configuration setting (`matrix_bot_chatgpt_openai_email`).
failed: [matrix.synkosmos.org] (item={'name': 'matrix_bot_chatgpt_openai_password', 'when': True}) => changed=false 
  ansible_loop_var: item
  item:
    name: matrix_bot_chatgpt_openai_password
    when: true
  msg: You need to define a required configuration setting (`matrix_bot_chatgpt_openai_password`).
skipping: [matrix.synkosmos.org] => (item={'name': 'matrix_bot_chatgpt_openai_login_type', 'when': True}) 
skipping: [matrix.synkosmos.org] => (item={'name': 'matrix_bot_chatgpt_matrix_bot_username', 'when': True}) 
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
# chatGPT

matrix_bot_chatgpt_enabled: true

# Obtain a new API key from https://platform.openai.com/account/api-keys
matrix_bot_chatgpt_openai_api_key: 'REDACTED'

# This is the default username
matrix_bot_chatgpt_matrix_bot_username_localpart: "chatgptbot"

# Matrix access token (from bot user above)
# see: https://webapps.stackexchange.com/questions/131056/how-to-get-an-access-token-for-element-riot-matrix
matrix_bot_chatgpt_matrix_access_token: "REDACTED"
```

Follow the documentation at https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bot-chatgpt.md.

**Expected behavior**
Expecting to set up chatGPT with the ap key.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

Ansible runs on the matrix server itself. ansible --version [core 2.13.5]

**Additional context**
I found the variable 'matrix_bot_chatgpt_openai_login_type' which could not find any reference to at:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-bot-chatgpt/tasks/validate_config.yml
