### ISSUE TITLE
Can't get Authentik OIDC working

### ISSUE THREAD

**Issue by bboyles303** [spantaleev/matrix-docker-ansible-deploy#2695]
So took a look at the docs and added the following to my vars.yml, using the Keycloak example as a template:

matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
    - idp_id: authentik
      idp_name: "Nimbus Nexus"
      discover: true
      issuer: "https://*my-authentic-url/application/o/nimbus-nexus-chat/"
      client_id: "*removed*"
      client_secret: "*removed*"
      scopes: ["openid", "profile", "email"]
      user_mapping_provider:
        config:
          localpart_template: "{{ user.preferred_username }}"
          display_name_template: "{{ user.name|capitalize }}"
      allow_existing_users: true # Optional
      backchannel_logout_enabled: true # Optional

matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true (as per docs, although could this be different with Traefik?)

When I look in /matrix/vars.yml on the matrix server I see the changes get pushed after I run the playbook, but looking in /matrix/synapse/config/homeserver.yaml I don't see the oidc block and still see the default oidc_providers: null

Of course when I got to my Element install, logging in with a known good Authentik user fails. 

Thoughts?

**Comment by sagat79** [comment]
Try it like this @bboyles303, it works for me without a problem

```yaml
oidc_providers:
    - idp_id: authentik
      idp_name: authentik
      discover: true
      issuer: "https://authentik.company/application/o/app-slug/"
      client_id: "*client id*"
      client_secret: "*client secret*"
      scopes: ["openid", "profile", "email"]
      user_mapping_provider:
          config:
              localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
              display_name_template: "{% raw %}{{ user.name|capitalize }}{% endraw %}"
              email_template: "{% raw %}{{ user.email }}{% endraw %}"
```
