### ISSUE TITLE
postmoogle certs_dumper error "no filter named 'split'

### ISSUE THREAD

**Issue by whowantsmybigdata** [spantaleev/matrix-docker-ansible-deploy#2728]
**Describe the bug**
Since I changed to `playbook-managed-traefik` (from `playbook-managed-nginx`) I get this error when trying to setup postmoogle:
```
TASK [custom/matrix-bot-postmoogle : Ensure matrix-bot-postmoogle.service installed] *****************************************************************************************************************************
fatal: [matrix.REDACTED]: FAILED! => changed=false
  msg: |-
    AnsibleError: An unhandled exception occurred while templating '{{
      ['docker.service']
      +
      ([devture_postgres_identifier ~ '.service'] if devture_postgres_enabled else [])
      +
      (['matrix-synapse.service'] if matrix_synapse_enabled else [])
      +
      (matrix_playbook_bot_postmoogle_traefik_certs_dumper_waiter_services | trim | split(' ') if matrix_playbook_reverse_proxy_type in ['playbook-managed-traefik', 'other-traefik-container'] and devture_traefik_certs_dumper_enabled else [])
    }}
    '. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no filter named 'split'. String: {{
      ['docker.service']
      +
      ([devture_postgres_identifier ~ '.service'] if devture_postgres_enabled else [])
      +
      (['matrix-synapse.service'] if matrix_synapse_enabled else [])
      +
      (matrix_playbook_bot_postmoogle_traefik_certs_dumper_waiter_services | trim | split(' ') if matrix_playbook_reverse_proxy_type in ['playbook-managed-traefik', 'other-traefik-container'] and devture_traefik_certs_dumper_enabled else [])
    }}
```

**To Reproduce**
My `vars.yml` file looks like this:
```
matrix_architecture: arm64

matrix_domain: REDACTED
matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_coturn_turn_static_auth_secret: REDACTED
matrix_coturn_turn_udp_max_port: 49372
matrix_synapse_turn_uris:
- turns:matrix.REDACTED?transport=udp
- turns:matrix.REDACTED?transport=tcp
- turn:matrix.REDACTED?transport=tcp
- turn:matrix.REDACTED?transport=udp

matrix_coturn_denied_peer_ips:
  - 0.0.0.0-0.255.255.255
  - 10.0.0.0-10.255.255.255
  - 100.64.0.0-100.127.255.255
  - 127.0.0.0-127.255.255.255
  - 169.254.0.0-169.254.255.255
  - 172.16.0.0-172.31.255.255
  - 192.0.0.0-192.0.0.255
  - 192.0.2.0-192.0.2.255
  - 192.88.99.0-192.88.99.255
#  - 192.168.0.0-192.168.255.255
  - 198.18.0.0-198.19.255.255
  - 198.51.100.0-198.51.100.255
  - 203.0.113.0-203.0.113.255
  - 240.0.0.0-255.255.255.255
  - ::1
  - 64:ff9b::-64:ff9b::ffff:ffff
  - ::ffff:0.0.0.0-::ffff:255.255.255.255
  - 100::-100::ffff:ffff:ffff:ffff
  - 2001::-2001:1ff:ffff:ffff:ffff:ffff:ffff:ffff
  - 2002::-2002:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  - fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  - fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff


matrix_synapse_macaroon_secret_key: REDACTED
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: REDACTED
matrix_synapse_max_upload_size_mb: 10000
matrix_synapse_url_preview_enabled: false

matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_enabled: false
devture_traefik_ssl_dir_enabled: true
devture_traefik_configuration_extension_yaml: |
  providers:
    file:
     filename: /config/certificates.yml
     watch: true
aux_file_definitions:
  - dest: "{{ devture_traefik_ssl_dir_path }}/privkey.pem"
    src: "/etc/letsencrypt/live/REDACTED/privkey.pem"

  - dest: "{{ devture_traefik_ssl_dir_path }}/cert.pem"
    src: "/etc/letsencrypt/live/REDACTED/fullchain.pem"

  - dest: "{{ devture_traefik_config_dir_path }}/certificates.yml"
    content: |
      tls:
        certificates:
          - certFile: /ssl/cert.pem
            keyFile: /ssl/privkey.pem
        stores:
          default:
            defaultCertificate:
              certFile: /ssl/cert.pem
              keyFile: /ssl/privkey.pem

devture_postgres_connection_password: REDACTED

matrix_registration_enabled: true
matrix_registration_admin_secret: REDACTED
matrix_registration_configuration_extension_yaml: |
   password:
     min_length: 12

matrix_synapse_admin_enabled: true

matrix_mailer_enabled: false

matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true
matrix_mautrix_signal_configuration_extension_yaml: |
  bridge:
    permissions:
      '@REDACTED:REDACTED': admin
    encryption:
      allow: true
      default: true

matrix_bot_postmoogle_enabled: true
matrix_bot_postmoogle_password: REDACTED
matrix_bot_postmoogle_ssl_path: "/etc/letsencrypt"
matrix_bot_postmoogle_tls_cert: "/ssl/live/REDACTED/fullchain.pem"
matrix_bot_postmoogle_tls_key: "/ssl/live/REDACTED/privkey.pem"
matrix_bot_postmoogle_tls_required: true
matrix_bot_postmoogle_admins:
  - "@REDACTED:{{ matrix_domain }}"

matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@REDACTED:{{ matrix_domain }}"
matrix_dimension_access_token: "REDACTED"
```

**Matrix Server:**
 - OS: Raspbian Bullseye 11, Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34)
 - Architecture: arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible: on the matrix-server itself
- what version:
```
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/REDACTED/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/REDACTED/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Additional context**
I also tried with commenting:
```
# matrix_bot_postmoogle_ssl_path: "/etc/letsencrypt"
# matrix_bot_postmoogle_tls_cert: "/ssl/live/REDACTED/fullchain.pem"
# matrix_bot_postmoogle_tls_key: "/ssl/live/REDACTED/privkey.pem"
# matrix_bot_postmoogle_tls_required: true
```
and putting `devture_traefik_certs_dumper_enabled: true`
And also with any combination of the given changes to my vars.yml - no luck.

I also tried it with commenting out 
```
aux_file_definitions:
  - dest: "{{ devture_traefik_ssl_dir_path }}/privkey.pem"
#    src: "/etc/letsencrypt/live/REDACTED/privkey.pem"

  - dest: "{{ devture_traefik_ssl_dir_path }}/cert.pem"
#    src: "/etc/letsencrypt/live/REDACTED/fullchain.pem"
```
and providing the certs manually with `content: |`
