### ISSUE TITLE
Task can't find vars.yml

### ISSUE THREAD

**Issue by Saik0Shinigami** [spantaleev/matrix-docker-ansible-deploy#2731]
**Describe the bug**
Installing from scratch on a clean LXC container I receive the following error.

```
TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Preserve vars.yml on the server for easily restoring if it gets lost later on] ******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [matrix.saik0.com]: FAILED! => changed=false 
  msg: |-
    Could not find or access '/root/matrix-docker-ansible-deploy/inventory/host_vars/matrix.saik0.com/vars.yml' on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
matrix_domain: saik0.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '***'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_postgres_connection_password: '***'
matrix_client_element_enabled: false
matrix_playbook_ssl_enabled: true
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '127.0.0.1:81'
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
devture_traefik_additional_entrypoints_auto:
  - name: matrix-federation
    port: 8449
    host_bind_port: '127.0.0.1:8449'
    #config: {}
    # If your reverse-proxy runs on another machine, remove the config above and use this config instead:
    config:
      forwardedHeaders:
        insecure: true
        trustedIPs: ['10.10.2.10']

matrix_coturn_enabled: false

matrix_synapse_allow_public_rooms_over_federation: true

matrix_mailer_sender_address: "***"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "***"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "***"
matrix_mailer_relay_auth_password: "***"

matrix_synapse_admin_enabled: true

matrix_mautrix_discord_enabled: true

matrix_mautrix_signal_enabled: true

matrix_synapse_auto_compressor_enabled: true
```

On a fresh LXC container, installing the pre-reqs and running the setup-all operation eventually runs and hits the above error. 

**Expected behavior**
The vars.yml is clearly accessible as all the setting selections are working just fine for the other several hundreds of selected options configured items.

```PLAY RECAP *******************************************************************************************************************************************************************************************************
matrix.saik0.com           : ok=333  changed=91   unreachable=0    failed=1    skipped=532  rescued=0    ignored=0  
```

**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64
 - LXC container on proxmox

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible --on the Matrix server itself installed from 
- what version of Ansible you're running:
```
ansible 2.10.8
  config file = /root/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```
