### ISSUE TITLE
Can't found how to bring back DB from `postgres_backup`

### ISSUE THREAD

**Issue by RoiArthurB** [spantaleev/matrix-docker-ansible-deploy#2777]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
[...]
devture_postgres_backup_enabled: true
devture_postgres_backup_schedule: '@weekly'
devture_postgres_backup_keep_weeks: 3
[...]
```

**Matrix Server:**
 - OS: Debian
 - Architecture arm64

**Problem description**:

My matrix server just had a disk error and I have to rebuild it all. Fortunatly, I did backup all my `/matrix` root folder and probably can bring back (except container's info, I'm aware) most of the server. Mainly, I do have all the db backup made with @prodrigestivill 's `devture_postgres_backup` role.

But I'm not really sure how to use those to bring everything back. Can anyone give me some extra informations ?
