### ISSUE TITLE
Invalid repository error with fresh BorgBase

### ISSUE THREAD

**Issue by altsalt** [spantaleev/matrix-docker-ansible-deploy#2813]
**Describe the bug**

journald throws an error `/srv/repos/BORGBASEREPO/repo is not a valid repository. Check repo config.` when trying to deploy backups via borg.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
backup_borg_enabled: true
backup_borg_location_repositories:
  - ssh://BORGBASEREPO@BORGBASEREPO.repo.borgbase.com/./repo
backup_borg_storage_encryption_passphrase: "REDACTED"
backup_borg_location_exclude_patterns:
  - "postgres-backup"
  - "./postgres-backup"
  - "/postgres-backup"
  - "/matrix/postgres-backup"
backup_borg_retention_keep_hourly: 0
backup_borg_retention_keep_daily: 1
backup_borg_retention_keep_weekly: 2
backup_borg_retention_keep_monthly: 2
backup_borg_retention_keep_yearly: 2
backup_borg_ssh_key_private: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  REDACTED
  -----END OPENSSH PRIVATE KEY-----
```

Running `systemctl start matrix-backup-borg` on the matrix server with a fresh BorgBase repository.

**Expected behavior**

A backup should be pushed to the BorgBase repository.

**Matrix Server:**
 - OS: Debian Bullseye
 - Architecture amd64

**Additional context**

I've also filed [an issue](https://github.com/borgbackup/borg/issues/7756) with borgbackup.
