### ISSUE TITLE
CORS Header not set

### ISSUE THREAD

**Issue by wuast94** [spantaleev/matrix-docker-ansible-deploy#2818]
When using a client that is not hosted on the same domain a CORS error is raised. Played around with Traefik and Nginx to find where to set this header but didnt find the right place.

On my local server (not the Ansible Matrix one) i use a Traefik middleware:
```
middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - PATCH
        accessControlMaxAge: 100
        addVaryHeader: true
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow"
          server: ""
          X-Forwarded-Proto: "https"
          Access-Control-Allow-Origin: "*"
```
I post the full one because its field tested over month now with nextcloud and many other sevices, but of course the relavnt one is Access-Control-Allow-Origin.

Dont know if its anyway a better idea to use some sort of middleware that could be easy extended or changed per Vars.yml.

Just throwing out what is in my mind for now, im open for diskussion and ideas.
