### ISSUE TITLE
Dimension integrations .well-known file has incorrect values

### ISSUE THREAD

**Issue by jacwib** [spantaleev/matrix-docker-ansible-deploy#282]
For whatever reason the dimension.my.domain/.well-known/matrix/integrations file looks like this:

`{"m.integrations_widget":{"url":"https://dimension.example.org/riot","data":{"api_url":"https://dimension.example.org/api/v1/scalar"}}}`

Note the _example.org_, when its supposed to have "my.domain" (or well, what my domain actually is, but you get the idea.)

My dns is set up correctly, and federation tester along with the self check says everything is okay.

This ends up causing an issue with every client but the self-hosted riot, where I can't set the integration to dimension as it gives an error, and im stuck using modular instead.

I tried hardcoding the url into vars.yml too, but that didnt help anything. It seems the ansible deploy just never touches those lines..?

**Comment by spantaleev** [comment]
I don't think the playbook installs a file to be served at `dimension.my.domain/.well-known/matrix/integrations`.

If there is such a file, it's served from Dimension itself.

Perhaps it's a configuration issue or a bug in Dimension, which causes the `/.well-known/matrix/integrations` to be off.

**Comment by GeneralUltra758** [comment]
Adding the following to the `inventory/host_vars/matrix.MY.DOMAIN/vars.yml`
sets the required variable for dimension that defines the URL in the .well-known
and thereby fixes this issue.
found that by looking at the recent commit to the default.yaml for dimension: https://github.com/turt2live/matrix-dimension/commit/915f1ebe4afd3a3070a6b1fcc759f4be8beb1acd
```yaml
matrix_dimension_configuration_extension_yaml: |
  # Your custom YAML configuration for Dimension goes here.
  # This configuration extends the default starting configuration 
  dimension:
    # This is where Dimension is accessible from clients. Be sure to set this
    # to your own Dimension instance.
    publicUrl: "https://dimension.MY.DOMAIN"
```
i assume the playbook is missing this variable?
