### ISSUE TITLE
Datasource ${DS_PROMETHEUS} was not found for synapse dashboard

### ISSUE THREAD

**Issue by e-g1gor** [spantaleev/matrix-docker-ansible-deploy#2834]
**Describe the bug**

Grafana synapse dashboard not work. Probably related to https://github.com/grafana/grafana/issues/10786#issuecomment-392377975 and https://github.com/grafana/grafana/issues/11018

Synapse dashboard settings in graphana UI

![json](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/29484330/933e4ac2-1706-4f8c-a2a6-321ffefc55b7)
![variables](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/29484330/a252dcaf-d1f4-4672-8d0c-beea21ea420f)

For comparison, working node-exporter settings

![variables](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/29484330/e7c8e172-3276-4377-9f71-4ed40454e65a)

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
ntfy_enabled: true
matrix_homeserver_implementation: "synapse"
matrix_playbook_reverse_proxy_type: "playbook-managed-traefik"

matrix_synapse_federation_enabled: false
matrix_synapse_federation_domain_whitelist: []
matrix_synapse_allow_public_rooms_over_federation: false
matrix_synapse_federation_port_enabled: false
matrix_nginx_proxy_proxy_matrix_federation_api_enabled: false
matrix_synapse_reverse_proxy_companion_federation_api_enabled: false
matrix_synapse_enable_registration: false
matrix_synapse_enable_registration: false
matrix_synapse_enable_registration_without_verification: false
matrix_synapse_report_stats: false
matrix_synapse_admin_enabled: true

devture_traefik_config_log_level: "DEBUG"
devture_traefik_dashboard_enabled: true
devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
devture_traefik_dashboard_basicauth_enabled: true

prometheus_enabled: true
prometheus_node_exporter_enabled: true
prometheus_postgres_exporter_enabled: true
matrix_prometheus_nginxlog_exporter_enabled: true

grafana_enabled: true
grafana_anonymous_access: false
```

Fresh install

**Expected behavior**

**Matrix Server:**
 - OS: Fedora
 - Architecture: x86_64
