### ISSUE TITLE
Checkout Prosody Auth Matrix User Verification Plugin Repo failes

### ISSUE THREAD

**Issue by ThomasHalwax** [spantaleev/matrix-docker-ansible-deploy#2839]
**Describe the bug**

I'm trying to enable matrix auth for jitsi and it fails with the following error:

```
TASK [galaxy/jitsi : Checkout Prosody Auth Matrix User Verification Plugin Repo] **************************************************************************************************************************************************************************
fatal: [matrix.trigonometry.digital]: FAILED! => changed=false
  module_stderr: |-
    sudo: unknown user: 998
    sudo: error initializing audit plugin sudoers_audit
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

Looks like the entries in the file `setup_jitsi_auth_uvs_install.yml` cause the error

```
  become: true
  become_user: "{{ jitsi_uid }}"
```

__After removing these entries I can successfully run the installation and I can successfully make voice and video calls.__

**To Reproduce**
My `vars.yml` file looks like this:
```yaml

---

matrix_domain: *redacted*.digital
matrix_homeserver_implementation: synapse

matrix_homeserver_generic_secret_key: '*redacted*'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: '*redacted*'
devture_postgres_connection_password: '*redacted*'

ntfy_enabled: true

matrix_synapse_federation_enabled: false
matrix_client_element_enabled: false

# serve .well-known files
matrix_nginx_proxy_base_domain_serving_enabled: true

# video conferences
jitsi_enabled: true
jitsi_enable_auth: true

jitsi_enable_guests: false
jitsi_auth_type: matrix
matrix_user_verification_service_enabled: true
## assigned to user "*redacted*" who MUST be an admin account
matrix_user_verification_service_uvs_access_token: '*redacted*'

```

Just run the playbook:
```bash
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
```

**Expected behavior**
I just want the services to be installed.

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture: x64

**Ansible:**

I run non-dockerized ansible on OSX Ventura (13.5):

```bash
ansible [core 2.13.3]
  config file = /Users/thomas/Development/KOSINUS/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/Users/thomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/thomas/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```
