### ISSUE TITLE
Unable to install because there is an error pulling an image

### ISSUE THREAD

**Issue by MidnightSlicer** [spantaleev/matrix-docker-ansible-deploy#2855]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: ******

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'Secret Key'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'Email'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'password'

###---!!! START OF CUSTOM CONFIG !!!---###

###Implement Traefik###
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: Email

###Implement Sliding Sync Proxy###
matrix_sliding_sync_enabled: true

###More Federation Settings###
matrix_synapse_allow_public_rooms_over_federation: true

###Shared Secret Auth###
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'Shared Secret

###CLIENTS###
matrix_client_hydrogen_enabled: true
matrix_client_cinny_cnabled: true

###DIMENSION###
matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@username"

matrix_dimension_access_token: "token"

###JITSI###
#Fix Jitsi!
jitsi_enabled: true

jitsi_jicofo_auth_password: "Password"
jitsi_jvb_auth_password: "Password"
jitsi_jibri_recorder_password: "Password"
jitsi_jibri_xmpp_password: "Password"

jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=LAN Address"'

jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;

  config.disableAudioLevels = true;

  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 4;

jitsi_web_config_resolution_width_ideal_and_max: 480
jitsi_web_config_resolution_height_ideal_and_max: 240

jitsi_prosody_max_participants: 50

```

**Matrix Server:**
 - Old OS: Ubuntu 21.04
 - New OS: Debian 12
 - Architecture: amd64

**Problem description**:

Hello! I am migrating from an old server to a new one. They both have the same architecture and they will have the exact same setup for now. I already copied the /matrix folder to the new server and made sure the other one was turned off, however, when I run 'ansible-playbook -i inventory/hosts setup.yml --tags=install-all' I get this error:

```
fatal: [matrix.domain]: FAILED! => changed=false 
  attempts: 10
  msg: 'Error pulling image docker.io/devture/exim-relay:4.96-r1-0 - 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.96-r1-0&fromImage=docker.io%2Fdevture%2Fexim-relay: Internal Server Error ("Get "https://registry-1.docker.io/v2/devture/exim-relay/manifests/sha256:6aeb52edd282561aeaaa41de5757ba714419b21eb3e1454d9658d2bd0313fe14": dial tcp [2600:1f18:2148:bc01:c4:4967:28eb:1824]:443: connect: network is unreachable")'
```

and the playbook stops. It pulled several other containers before it got to this point with no issues, and this server is basically fresh. I haven't done anything on it that would interfere other than install UFW, which I have configured to allow all the ports I need. It really seems like it is an issue on Docker's end, but I want to see if anyone else has ever seen this. Thank you in advance!
