### ISSUE TITLE
Error decrypting video with telegram messages

### ISSUE THREAD

**Issue by gouthamravee** [spantaleev/matrix-docker-ansible-deploy#2874]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: 

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 

#matrix_docker_installation_enabled: false
matrix_playbook_docker_installation_enabled: false
# Do not retrieve SSL certificates. This shall be managed by another webserver or other means.
#matrix_ssl_retrieval_method: none

# Do not try to serve HTTPS, since we have no SSL certificates.
# Disabling this also means services will be served on the HTTP port
# (`matrix_nginx_proxy_container_http_host_bind_port`).
#matrix_nginx_proxy_https_enabled: false

#matrix_nginx_proxy_enabled: false

# Do not listen for HTTP on port 80 globally (default), listen on the loopback interface.
# If you'd like, you can make it use the local network as well and reverse-proxy from another local machine.
#matrix_nginx_proxy_container_http_host_bind_port: '80'

# Likewise, expose the Matrix Federation port on the loopback interface.
# Since `matrix_nginx_proxy_https_enabled` is set to `false`, this federation port will serve HTTP traffic.
# If you'd like, you can make it use the local network as well and reverse-proxy from another local machine.
#
# You'd most likely need to expose it publicly on port 8448 (8449 was chosen for the local port to prevent overlap).
#matrix_nginx_proxy_container_federation_host_bind_port: '8448'

# Coturn relies on SSL certificates that have already been obtained.
# Since we don't obtain any certificates (`matrix_ssl_retrieval_method: none` above), it won't work by default.
# An alternative is to tweak some of: `matrix_coturn_tls_enabled`, `matrix_coturn_tls_cert_path` and `matrix_coturn_tls_key_path`.
matrix_coturn_enabled: false

# Trust the reverse proxy to send the correct `X-Forwarded-Proto` header as it is handling the SSL connection.
#matrix_nginx_proxy_trust_forwarded_proto: true

# Trust and use the other reverse proxy's `X-Forwarded-For` header.
#matrix_nginx_proxy_x_forwarded_for: '$proxy_add_x_forwarded_for'

matrix_synapse_admin_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 

# The easy way. The specified Matrix user ID will be made an admin of all bridges
matrix_admin: 

matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: 
matrix_mautrix_telegram_api_hash: 
matrix_mautrix_telegram_bridge_encryption_allow: true


matrix_bot_maubot_enabled: true
matrix_bot_maubot_admins:
  - 

matrix_registration_enabled: true
matrix_registration_admin_secret: 

matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_bridge_encryption_allow: true

matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_bridge_encryption_allow: true

matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_bridge_encryption_allow: true

matrix_mx_puppet_steam_enabled: true

matrix_synapse_configuration_extension_yaml: |
  limit_remote_rooms:
    enabled: true
    complexity: 1.0

matrix_synapse_media_retention_local_media_lifetime: 7d
matrix_synapse_media_retention_remote_media_lifetime: 3d

matrix_synapse_max_upload_size_mb: 2000

matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: one-of-each

matrix_dimension_enabled: false
matrix_dimension_admins:
  - 

matrix_dimension_access_token: 

matrix_mailer_sender_address: 
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "smtp.mailgun.org"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: 
matrix_mailer_relay_auth_password: 

matrix_mautrix_instagram_enabled: true
matrix_mautrix_instagram_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true

#matrix_beeper_linkedin_enabled: true
#matrix_beeper_linkedin_configuration_extension_yaml: |
#  bridge:
#    encryption:
#      allow: true
#      default: true
#    permissions:
#      

matrix_client_element_themes_enabled: true

#https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-synapse-auto-compressor.md
matrix_synapse_auto_compressor_enabled: true
#https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-sliding-sync-proxy.md
matrix_sliding_sync_enabled: true


matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# Ensure that public urls use https
matrix_playbook_ssl_enabled: true

# Disable the web-secure (port 443) endpoint, which also disables SSL certificate retrieval
devture_traefik_config_entrypoint_web_secure_enabled: false

# If your reverse-proxy runs on another machine, consider using `0.0.0.0:81`, just `81` or `SOME_IP_ADDRESS_OF_THIS_MACHINE:81`
devture_traefik_container_web_host_bind_port: '0.0.0.0:81'

# We bind to `127.0.0.1` by default (see above), so trusting `X-Forwarded-*` headers from
# a reverse-proxy running on the local machine is safe enough.
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true

# Or, if you're publishing the port (`devture_traefik_container_web_host_bind_port` above) to a public network interfaces:
# - remove the `devture_traefik_config_entrypoint_web_forwardedHeaders_insecure` variable definition above
# - uncomment and adjust the line below
# devture_traefik_config_entrypoint_web_forwardedHeaders_trustedIPs: ['IP-ADDRESS-OF-YOUR-REVERSE-PROXY']

# Likewise (to `devture_traefik_container_web_host_bind_port` above),
# if your reverse-proxy runs on another machine, consider changing the `host_bind_port` setting below.
#devture_traefik_additional_entrypoints_auto:
#  - name: matrix-federation
#    port: 8449
#    host_bind_port: '127.0.0.1:8449'
#    config: {}
# If your reverse-proxy runs on another machine, remove the config above and use this config instead:
config:
  forwardedHeaders:
    insecure: true
    trustedIPs: 

matrix_synapse_presence_enabled: false
matrix_synapse_caches_global_factor: 1.5

devture_postgres_process_extra_arguments: [
 "-c max_connections=400",
 "-c shared_buffers=2GB",
 "-c effective_cache_size=6GB",
 "-c maintenance_work_mem=512MB",
 "-c checkpoint_completion_target=0.9",
 "-c wal_buffers=16MB",
 "-c default_statistics_target=100",
 "-c random_page_cost=1.1",
 "-c effective_io_concurrency=200",
 "-c work_mem=655kB",
 "-c min_wal_size=1GB",
 "-c max_wal_size=4GB",
 "-c max_worker_processes=8",
 "-c max_parallel_workers_per_gather=4",
 "-c max_parallel_workers=8",
 "-c max_parallel_maintenance_workers=4",
]

```

**Matrix Server:**
 - OS: Debian Bookworm
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- Matrix server itself
- what version of Ansible you're running (see `ansible --version`)
```
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/home/dietpi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dietpi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Problem description**:

Only with Telegram, when someone sends a gif or mp4 through their telegram client, on my end with any element client I get the error "Error decrypting video" the logs show the content below

```
2023-08-21T15:18:38.436Z E Unable to download attachment to decrypt it:  MatrixError: [404] Not found [b'domain.org', b'pEjGlFLDGrCsmQFMWcYIuzoo'] (https://matrix.domain.org/_matrix/media/r0/download/domain.org/pEjGlFLDGrCsmQFMWcYIuzoo)
M_NOT_FOUND: MatrixError: [404] Not found [b'domain.org', b'pEjGlFLDGrCsmQFMWcYIuzoo'] (https://matrix.domain.org/_matrix/media/r0/download/domain.org/pEjGlFLDGrCsmQFMWcYIuzoo)
    at c (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:1355935)
    at u (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:1394613)
    at async s.getFn (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:1300202)
    at async Promise.all (index 0)
    at async P.downloadImage (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:2760248)
```

I don't see this issue with images, and with other bridges.
