### ISSUE TITLE
mx-puppet-steam won't respond to commands, 401 Unauthorized 

### ISSUE THREAD

**Issue by Virkkunen** [spantaleev/matrix-docker-ansible-deploy#2882]
**Describe the bug**
mx-puppet-steam bridge doesn't respond to any commands. The only log available when running journalctl is a 401 error: `matrix matrix-mx-puppet-steam[273606]: 172.18.0.4 - - [09/Sep/2023:09:17:47 +0000] "PUT /_matrix/app/v1/transactions/13779 HTTP/1.1" 401 57 "-" "Synapse/1.91.2"`

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
    matrix_domain: domain.tld
    matrix_homeserver_implementation: synapse
    matrix_homeserver_generic_secret_key: 'secret'
    matrix_playbook_reverse_proxy_type: other-traefik-container
    matrix_playbook_reverse_proxyable_services_additional_network: traefik
    devture_traefik_certs_dumper_ssl_dir_path: "/traefik/letsencrypt"
    matrix_playbook_docker_installation_enabled: false
    matrix_client_element_enabled: true
    matrix_ssl_lets_encrypt_support_email: 'email@domain.tld'
    devture_postgres_connection_password: 'secret'
    matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
    matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: secret
    matrix_mautrix_discord_enabled: true
    matrix_mautrix_telegram_enabled: true
    matrix_mautrix_telegram_api_id: id
    matrix_mautrix_telegram_api_hash:  secret
    matrix_mautrix_whatsapp_enabled: true
    matrix_synapse_configuration_extension_yaml: |
      experimental_features:
        msc2716_enabled: true
    matrix_mautrix_whatsapp_configuration_extension_yaml:
      bridge:
        history_sync:
          backfill: true
    matrix_mautrix_facebook_enabled: true
    matrix_mautrix_facebook_configuration_extension_yaml: |
      bridge:
         encryption:
           allow: true
           default: true
    matrix_mautrix_googlechat_enabled: false
    matrix_mautrix_instagram_enabled: true
    matrix_mautrix_twitter_enabled: false
    matrix_mautrix_signal_enabled: true
    matrix_beeper_linkedin_enabled: false
    matrix_heisenbridge_enabled: false
    matrix_mx_puppet_steam_enabled: true
    matrix_mx_puppet_steam_container_image_self_build: true # my server is arm64, without this tag it won't build because of missing platform (linux/arm64/v8)
    matrix_nginx_proxy_enabled: true
    matrix_client_element_themes_enabled: true
    matrix_client_element_themes_repository_url: 'https://github.com/aaronraimist/element-themes'
    matrix_client_element_themes_repository_version: master
    matrix_synapse_admin_enabled: true
    matrix_bot_matrix_reminder_bot_enabled: true
    matrix_bot_matrix_reminder_bot_matrix_user_password: secret
    matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/Berlin
    matrix_synapse_federation_enabled: true
    matrix_synapse_federation_port_enabled: true
    matrix_nginx_proxy_proxy_matrix_federation_api_enabled: true
    matrix_synapse_reverse_proxy_companion_federation_api_enabled: true
    matrix_synapse_http_listener_resource_names: ["client","federation"]
    matrix_federation_public_port: 8448
    matrix_synapse_tls_federation_listener_enabled: false
    matrix_sliding_sync_enabled: true
    matrix_synapse_auto_compressor_enabled: true
    matrix_admin: "@admin:domain.tld"
    matrix_bridges_encryption_enabled: true
    devture_traefik_dashboard_enabled: true
    devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
    devture_traefik_dashboard_basicauth_enabled: true
    devture_traefik_dashboard_basicauth_user: admin
    devture_traefik_dashboard_basicauth_password: 'secret'
```

**Expected behavior**
Steam bridge bot responds to command and logs in

**Matrix Server:**
 - OS: Debian 6.1.38-4 (2023-08-08)
 - Architecture: arm64

**Additional context**
mx-puppet-steam bridge doesn't respond to any commands. The only log available when running journalctl is a 401 error: 
`matrix matrix-mx-puppet-steam[273606]: 172.18.0.4 - - [09/Sep/2023:09:17:47 +0000] "PUT /_matrix/app/v1/transactions/13779 HTTP/1.1" 401 57 "-" "Synapse/1.91.2"`

A `docker ps -a` reports:
`78244275fbe1   localhost/icewind1991/mx-puppet-steam:latest   "/opt/mx-puppet-stea…"   24 hours ago   Up 24 hours   matrix-mx-puppet-steam`
  
The ansible install, setup and check commands report no error with the container/bridge.

A screenshot of the bot:
![](https://microbin.vrkknn.net/file/spider-emu-zebra)

Are there any other steps I can do to troubleshoot it?
I've also created an [issue on the bridge's repo](https://github.com/icewind1991/mx-puppet-steam/issues/44), in case this is an issue with the bridge itself and not its integration with this playbook
