### ISSUE TITLE
Issue setting an OIDC provider

### ISSUE THREAD

**Issue by paphiopedilum05** [spantaleev/matrix-docker-ansible-deploy#2887]
I'm trying to set my Synapse installation with an external IdP server. So I've added `oidc_providers` block. After installation playbook attempts to activate matrix-synapse.service but it fails.
Here's what journalctl shows:
```systemd[1]: Starting Synapse server...
 matrix-synapse[3600102]: 5e9b4cfa6c401f2ce4342d76ea684caa9168387ce5ee5b456ebf68d6fd69b5bc
 systemd[1]: Started Synapse server.
 matrix-synapse[3600111]: Starting synapse with args -m synapse.app.homeserver -c /data/homeserver.yaml
 matrix-synapse[3600111]: This server is configured to use 'matrix.org' as its trusted key server via the
 matrix-synapse[3600111]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
 matrix-synapse[3600111]: server since it is long-lived, stable and trusted. However, some admins may
 matrix-synapse[3600111]: wish to use another server for this purpose.
 matrix-synapse[3600111]: To suppress this warning and continue using 'matrix.org', admins should set
 matrix-synapse[3600111]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
 matrix-synapse[3600111]: --------------------------------------------------------------------------------
 matrix-synapse[3600111]: 2023-09-12 13:00:03,730 - root - 348 - WARNING - main - ***** STARTING SERVER *****
 matrix-synapse[3600111]: 2023-09-12 13:00:03,730 - root - 349 - WARNING - main - Server /usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py version 1.90.0
 matrix-synapse[3600111]: 2023-09-12 13:00:03,961 - synapse.app._base - 269 - CRITICAL - sentinel - Error during startup
 matrix-synapse[3600111]: Traceback (most recent call last):
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 140, in load_metadata
 matrix-synapse[3600111]:     await p.load_metadata()
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 588, in load_metadata
 matrix-synapse[3600111]:     return await self._provider_metadata.get()
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/cached_call.py", line 136, in get
 matrix-synapse[3600111]:     return await self._cachedcall.get()
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/cached_call.py", line 106, in get
 matrix-synapse[3600111]:     self._result.raiseException()
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 504, in raiseException
 matrix-synapse[3600111]:     raise self.value.with_traceback(self.tb)
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
 matrix-synapse[3600111]:     result = context.run(
 matrix-synapse[3600111]:              ^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
 matrix-synapse[3600111]:     return g.throw(self.type, self.value, self.tb)
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/cached_call.py", line 126, in _wrapper
 matrix-synapse[3600111]:     return await f()
 matrix-synapse[3600111]:            ^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 600, in _load_metadata
 matrix-synapse[3600111]:     metadata_response = await self._http_client.get_json(url)
 matrix-synapse[3600111]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 559, in get_json
 matrix-synapse[3600111]:     body = await self.get_raw(uri, args, headers=actual_headers)
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 644, in get_raw
 matrix-synapse[3600111]:     response = await self.request("GET", uri, headers=Headers(actual_headers))
 matrix-synapse[3600111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 411, in request
 matrix-synapse[3600111]:     response = await make_deferred_yieldable(request_deferred)
 matrix-synapse[3600111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
 matrix-synapse[3600111]:     current.result = callback(  # type: ignore[misc]
 matrix-synapse[3600111]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 952, in _timeout_to_request_timed_out_error
 matrix-synapse[3600111]:     raise RequestTimedOutError("Timeout waiting for response from remote server")
 matrix-synapse[3600111]: synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
 matrix-synapse[3600111]: The above exception was the direct cause of the following exception:
 matrix-synapse[3600111]: Traceback (most recent call last):
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/app/_base.py", line 254, in wrapper
 matrix-synapse[3600111]:     await cb(*args, **kwargs)
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 362, in start
 matrix-synapse[3600111]:     await oidc.load_metadata()
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 144, in load_metadata
 matrix-synapse[3600111]:     raise Exception(
 matrix-synapse[3600111]: Exception: Error while initialising OIDC provider 'oidc-adfs'
 matrix-synapse[3600111]: Error during startup:
 matrix-synapse[3600111]: Traceback (most recent call last):
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 140, in load_metadata
 matrix-synapse[3600111]:     await p.load_metadata()
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 588, in load_metadata
 matrix-synapse[3600111]:     return await self._provider_metadata.get()
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/cached_call.py", line 136, in get
 matrix-synapse[3600111]:     return await self._cachedcall.get()
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/cached_call.py", line 106, in get
 matrix-synapse[3600111]:     self._result.raiseException()
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 504, in raiseException
 matrix-synapse[3600111]:     raise self.value.with_traceback(self.tb)
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
 matrix-synapse[3600111]:     result = context.run(
 matrix-synapse[3600111]:              ^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
 matrix-synapse[3600111]:     return g.throw(self.type, self.value, self.tb)
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/cached_call.py", line 126, in _wrapper
 matrix-synapse[3600111]:     return await f()
 matrix-synapse[3600111]:            ^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 600, in _load_metadata
 matrix-synapse[3600111]:     metadata_response = await self._http_client.get_json(url)
 matrix-synapse[3600111]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 559, in get_json
 matrix-synapse[3600111]:     body = await self.get_raw(uri, args, headers=actual_headers)
 matrix-synapse[3600111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 644, in get_raw
 matrix-synapse[3600111]:     response = await self.request("GET", uri, headers=Headers(actual_headers))
 matrix-synapse[3600111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 411, in request
 matrix-synapse[3600111]:     response = await make_deferred_yieldable(request_deferred)
 matrix-synapse[3600111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
 matrix-synapse[3600111]:     current.result = callback(  # type: ignore[misc]
 matrix-synapse[3600111]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 952, in _timeout_to_request_timed_out_error
 matrix-synapse[3600111]:     raise RequestTimedOutError("Timeout waiting for response from remote server")
 matrix-synapse[3600111]: synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
 matrix-synapse[3600111]: The above exception was the direct cause of the following exception:
 matrix-synapse[3600111]: Traceback (most recent call last):
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/app/_base.py", line 254, in wrapper
 matrix-synapse[3600111]:     await cb(*args, **kwargs)
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 362, in start
 matrix-synapse[3600111]:     await oidc.load_metadata()
 matrix-synapse[3600111]:   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/oidc.py", line 144, in load_metadata
 matrix-synapse[3600111]:     raise Exception(
 matrix-synapse[3600111]: Exception: Error while initialising OIDC provider 'oidc-adfs'
 systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
```

**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: matrix_domain
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: matrix_homeserver_generic_secret_key
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: devture_traefik_config_certificatesResolvers_acme_email
devture_traefik_config_entrypoint_web_secure_enabled: false
matrix_synapse_admin_enabled: true
matrix_synapse_allow_public_rooms_over_federation: false
matrix_synapse_federation_enabled: false
matrix_server_fqn_element: matrix_server_fqn_element
matrix_server_fqn_matrix: matrix_server_fqn_matrix
ip_range_blacklist: []
matrix_synapse_ext_encryption_disabler_enabled: true
matrix_synapse_ext_encryption_disabler_download_url: https://raw.githubusercontent.com/digitalentity/matrix_encryption_disabler/cdc37a07441acb7c2>
matrix_synapse_ext_encryption_disabler_deny_encryption_for_users_of:
  - "{{ matrix_domain }}"
matrix_synapse_ext_encryption_disabler_deny_encryption_for_rooms_of:
  - "{{ matrix_domain }}"
matrix_synapse_ext_encryption_disabler_patch_power_levels: false
matrix_synapse_ext_encryption_config: "{{ matrix_synapse_ext_encryption_config_yaml | from_yaml }}"
matrix_synapse_ext_encryption_config_yaml: >
  deny_encryption_for_users_of: {{
  matrix_synapse_ext_encryption_disabler_deny_encryption_for_users_of | to_json
  }}

  deny_encryption_for_rooms_of: {{ matrix_synapse_ext_encryption_disabler_deny_encryption_for_rooms_of | to_json }}

  patch_power_levels: {{ matrix_synapse_ext_encryption_disabler_patch_power_levels | to_json }}
jitsi_enabled: false
matrix_playbook_docker_installation_enabled: false
matrix_coturn_enabled: false
devture_postgres_enabled: false
matrix_synapse_database_host: matrix_synapse_database_host
matrix_synapse_database_user: matrix_synapse_database_user
matrix_synapse_database_password: matrix_synapse_database_password
matrix_synapse_database_database: matrix_synapse_database_database
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
      - idp_id: adfs
        idp_name: "ADFS"
        client_id: "client_id"
        client_secret: "client_secret"
        scopes: ["openid", "profile", "email"]
        issuer: "https://issuer.url"
        user_mapping_provider:
         config:
          localpart_template: "{% raw %}{{ user.email.split('@')[0] }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
          email_template: "{% raw %}{{ user.email }}{% endraw %}"


```
Any input would be greatly appreciated. 

**Matrix Server:**
 - OS: [e.g. Ubuntu 21.04]
 - Architecture [e.g. amd64, arm32, arm64]

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

**Client (please complete the following information):**

**Additional context**
