### ISSUE TITLE
1-on-1 DM calls do not work.

### ISSUE THREAD

**Issue by MidnightSlicer** [spantaleev/matrix-docker-ansible-deploy#2909]
**Describe the bug**
1-on-1 DM calls always leave the user on an infinite connecting screen. Several months ago it worked, but after changing nothing with the server on my end other than updating it it stopped working (I think it had something to do with Traefik? As you can see that is one of the things I added myself and that may have started it but I can't remember.). Note my server is on my home network, but I have tried both callers being in my house, both callers being out of my house, and one in one out. every interaction leaves me on an infinite connecting screen. 

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: [REDACTED]

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '[REDACTED]'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: '[REDACTED]'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: '[REDACTED]'

###---!!! START OF CUSTOM CONFIG !!!---###

###Implement Traefik###
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: [REDACTED]

###Implement Sliding Sync Proxy###
matrix_sliding_sync_enabled: true

###NTFY###
ntfy_enabled: true

###More Federation Settings###
matrix_synapse_allow_public_rooms_over_federation: true

###Shared Secret Auth###
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: '[REDACTED]'

###CLIENTS###
matrix_client_hydrogen_enabled: true
matrix_client_cinny_cnabled: true
matrix_client_schildichat_enabled: true

###JITSI###
#Fix Jitsi!
jitsi_enabled: true

jitsi_jicofo_auth_password: "[REDACTED]"
jitsi_jvb_auth_password: "[REDACTED]"
jitsi_jibri_recorder_password: "[REDACTED]"
jitsi_jibri_xmpp_password: "[REDACTED]"

jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=192.168.100.200"'

jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;

  config.disableAudioLevels = true;

  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 4;

jitsi_web_config_resolution_width_ideal_and_max: 480
jitsi_web_config_resolution_height_ideal_and_max: 240

jitsi_prosody_max_participants: 50
```

**Expected behavior**
The call should connect and stay connected.

**Matrix Server:**
 - OS: Ubuntu 22.04.3 LTS
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Additional context**

I think it may have something to do with Coturn. I looked at my Coturn config file on the server in /matrix/coturn/turnserver.conf and this is what I saw:

```
use-auth-secret
static-auth-secret=9bbc3605-efb8-5e9c-9b23-79dc177381c2
realm=turn.matrix.[My domain]

min-port=49152
max-port=49172
external-ip=[My name @ my domain]  <--- this part is really confusing me

log-file=stdout
pidfile=/var/tmp/turnserver.pid
userdb=/var/tmp/turnserver.db

no-cli

cert=/certificate.crt
pkey=/privatekey.key
no-tlsv1
no-tlsv1_1

prod

no-tcp-relay

no-rfc5780

no-stun-backward-compatibility

response-origin-only-with-rfc5780


no-multicast-peers

denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255                                                            
denied-peer-ip=172.16.0.0-172.31.255.255                                                              
denied-peer-ip=192.0.0.0-192.0.0.255                                                                  
denied-peer-ip=192.0.2.0-192.0.2.255                                                                  
denied-peer-ip=192.88.99.0-192.88.99.255                                                              
denied-peer-ip=192.168.0.0-192.168.255.255                                                            
denied-peer-ip=198.18.0.0-198.19.255.255                                                              
denied-peer-ip=198.51.100.0-198.51.100.255                                                            
denied-peer-ip=203.0.113.0-203.0.113.255                                                              
denied-peer-ip=240.0.0.0-255.255.255.255                                                              
denied-peer-ip=::1                                                                                    
denied-peer-ip=64:ff9b::-64:ff9b::ffff:ffff                                                           
denied-peer-ip=::ffff:0.0.0.0-::ffff:255.255.255.255                                                  
denied-peer-ip=100::-100::ffff:ffff:ffff:ffff                                                         
denied-peer-ip=2001::-2001:1ff:ffff:ffff:ffff:ffff:ffff:ffff                                          
denied-peer-ip=2002::-2002:ffff:ffff:ffff:ffff:ffff:ffff:ffff                                         
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff                                         
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff 
```

I wonder if the denied peer IPs are causing issues? I also wonder about the setting for external IP (external-ip=<my name>@<my domain>). 

Any help is appreciated! Thank you!
