### ISSUE TITLE
matrix-registration-bot fails to install

### ISSUE THREAD

**Issue by MorpheusMXML** [spantaleev/matrix-docker-ansible-deploy#2919]
**Describe the bug**
When trying to install the matrix-registration-bot via the documentation and the recommendet configuration the playbook interrupts with this error:

```
TASK [custom/matrix-bot-matrix-registration-bot : Ensure matrix-registration-bot repository is present on self-build] *******************************************************************
fatal: [matrix.vida4ever.de]: FAILED! => changed=false
  cmd: /usr/bin/git checkout --force 1.3.0
  msg: Failed to checkout 1.3.0
  rc: 1
  stderr: |-
    error: pathspec '1.3.0' did not match any file(s) known to git
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

without really knowing what this value actually refers to i tried reverting to the latest commited value before that `latest` then the installation goes through but fails when checking if the bot service is running.

I also tried to add the `v` to the `1.3.0` to match the `v1.3.0` Tag in the Bots repo and the installation seems to work.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: xxxxxx

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: "xxxxxx"

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: "xxxxxxx"

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: "xxxxxx"

matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_synapse_admin_enabled: true
matrix_coturn_turn_external_ip_address: xxxxx

############################################################################################################
#TELEGRAM BRIDGE API STUFF
###########################################################################################################
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: xxxx
matrix_mautrix_telegram_api_hash: xxx

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: xxxx

#############################################################################################
#Prometheus + Grafana Metrics + Performance Dashboard
############################################################################################

prometheus_enabled: true

# You can remove this, if unnecessary.
prometheus_node_exporter_enabled: true

# You can remove this, if unnecessary.
prometheus_postgres_exporter_enabled: true

# You can remove this, if unnecessary.
matrix_prometheus_nginxlog_exporter_enabled: true

grafana_enabled: true

grafana_anonymous_access: false

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
grafana_default_admin_user: xxxxx

# Changing the password subsequently won't work.
grafana_default_admin_password: xxxxxx!

##################################################################################
#    ETHERPAD
##################################################################################
etherpad_enabled: true

# Uncomment below to enable the admin web UI
etherpad_admin_username: xxxx
etherpad_admin_password: xxxxx!

##################################################################################
# REMINDER BOT
##################################################################################
matrix_bot_matrix_reminder_bot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_matrix_reminder_bot_matrix_user_id_localpart: bot.matrix-reminder-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_reminder_bot_matrix_user_password: xxxxxxxx

# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/Berlin

#################################################################################
#  TOKEN AUTHENTICATION
#################################################################################
matrix_bot_matrix_registration_bot_enabled: true

#By default, the playbook will set use the bot with a username like
## this: `@bot.matrix-registration-bot:DOMAIN`.
# To use a different username, uncomment & adjust the variable.
matrix_bot_matrix_registration_bot_matrix_user_id_localpart: bot.registration-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_registration_bot_bot_password: xxxxx

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true

#################################################################################
#  MAUBOT CONFIG
#################################################################################
matrix_bot_maubot_enabled: true
matrix_bot_maubot_admins:
  -xxxx:xxxxx

```

run playbook with `setup-all, start` 

**Expected behavior**
installation should work and bot should be installed

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture aarch64 (Oracle Free Server)
