### ISSUE TITLE
registration on element. subdomain isn't working

### ISSUE THREAD

**Issue by nebocamin** [spantaleev/matrix-docker-ansible-deploy#2957]
**Describe the bug**
if you have open registration and go to element.yourdomain and try to register.
the email with validation is coming.
the validation link will not work.the site shows success, but the user remains unregistered

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_synapse_registrations_require_3pid: ['email']
#matrix_synapse_account_threepid_delegates_email: true
matrix_synapse_enable_registration: true
```
