### ISSUE TITLE
ChatGPT bot is leaving room due to "missing room key"

### ISSUE THREAD

**Issue by ZenKyma** [spantaleev/matrix-docker-ansible-deploy#3027]
**Describe the bug**
After setting up ChatGPT-bot, the bot immediately leaves the room after posting
```
Room key error. I will leave the room, please reinvite me!
```

`journalctl -fu matrix-bot-chatgpt` returns:
```
GMT [ERROR] [MatrixClientLite] Decryption error on !xHWwMdQSEmqAdXZYUk:synkosmos.org $<<CENSORED>> [Error: decryption failed because the room key is missing] {
  code: 'GenericFailure'
}
GMT [ERROR] [index] Failed decryption event!
```
The room is encrypted and my session is verified (even though many bridge bot sessions are unverified).

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_bot_chatgpt_enabled: true
matrix_bot_chatgpt_data_path: "/mnt/storage/chatgpt"

# Obtain a new API key from https://platform.openai.com/account/api-keys
matrix_bot_chatgpt_openai_api_key: 'XXX'

# This is the default username
matrix_bot_chatgpt_matrix_bot_username_localpart: 'chatgpt'

# Matrix access token (from bot user above)
# see: https://webapps.stackexchange.com/questions/131056/how-to-get-an-access-token-for-element-riot-mat>
matrix_bot_chatgpt_matrix_access_token: 'XXX'

# Configuring the system promt used, needed if the bot is used for special tasks.
# More information: https://github.com/mustvlad/ChatGPT-System-Prompts
matrix_bot_chatgpt_matrix_bot_prompt_prefix: 'Instructions:\nYou are ChatGPT, a large language model trained by OpenAI.'

# Matrix Configurable Settings Defaults (optional)
matrix_bot_chatgpt_matrix_default_prefix: "!gpt "  # MATRIX_DEFAULT_PREFIX= Leave prefix blank to reply to all messages, trailing space matters
matrix_bot_chatgpt_matrix_default_prefix_reply: false  # MATRIX_DEFAULT_PREFIX_REPLY=
```

**Expected behavior**
ChatGPT bot staying in room and replying to requests.

**Matrix Server:**
 - OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-89-generic x86_64)

**Client:**
 Element and Cinny
