### ISSUE TITLE
Synapse admin "server communication error"

### ISSUE THREAD

**Issue by mrtshoot** [spantaleev/matrix-docker-ansible-deploy#3032]
**Describe the bug**
When I wanted to activate the diactivated user again I got the "Server Communication Error" and 400 bad request.
the related api call with PUT method was https://matrix.[DOMAIN_NAME]/_synapse/admin/v2/users/%40[USERNAME]%3A[DOMAIN_NAME]

My `vars.yml` file looks like this:

```yaml
---
matrix_domain: ********
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '**************************'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: '**************'
devture_postgres_connection_password: '****************************'
matrix_synapse_max_upload_size_mb: 10000
matrix_user_verification_service_enabled: true
matrix_user_verification_service_uvs_access_token: "*******************"
matrix_synapse_workers_enabled: true
matrix_synapse_admin_enabled: true
matrix_coturn_enabled: true
# matrix_coturn_turn_external_ip_address: "********"
matrix_registration_enabled: true
matrix_registration_admin_secret: "****************"

jitsi_enabled: true
# jitsi_hostname: "jitsi.{{ matrix_domain }}"
jitsi_enable_auth: true
jitsi_auth_type: matrix
jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
  config.disableAudioLevels = true;
  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 4;
jitsi_web_config_resolution_width_ideal_and_max: 480
jitsi_web_config_resolution_height_ideal_and_max: 240

prometheus_enabled: false
prometheus_node_exporter_enabled: false
prometheus_postgres_exporter_enabled: false
grafana_enabled: false
grafana_anonymous_access: false
grafana_default_admin_user: "admin"
grafana_default_admin_password: "**********"

matrix_client_element_enabled: true

devture_traefik_config_log_level: DEBUG
devture_traefik_dashboard_enabled: false
devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
devture_traefik_dashboard_basicauth_enabled: false
devture_traefik_dashboard_basicauth_user: admin
devture_traefik_dashboard_basicauth_password: "**********"

matrix_client_hydrogen_enabled: false
matrix_server_fqn_hydrogen: "hydrogen.{{ matrix_domain }}"

matrix_client_cinny_enabled: false
matrix_server_fqn_cinny: "cinny.{{ matrix_domain }}"

ntfy_enabled: true
matrix_server_fqn_ntfy: "ntfy.{{ matrix_domain }}"
```

when I want to reactivate the deactivated user I get an error server communication error and it is deactivated again.

**Matrix Server:**
 - OS: [e.g. Ubuntu 22.04]
 - Architecture [e.g. amd64]

**Client:**
 - Device: [e.g. MacBook]
 - Browser [e.g. chrome]
