### ISSUE TITLE
matrix-prometheus-postgres-exporter pg_ls_waldir permission denied error

### ISSUE THREAD

**Issue by joecool1029** [spantaleev/matrix-docker-ansible-deploy#3039]
**Describe the bug**

Dec 13 18:41:02 xwaretech.net matrix-postgres[32910]: 2023-12-13 18:41:02.352 UTC [111] STATEMENT:
Dec 13 18:41:02 xwaretech.net matrix-postgres[32910]:                         SELECT
Dec 13 18:41:02 xwaretech.net matrix-postgres[32910]:                                 COUNT(*) AS segments,
Dec 13 18:41:02 xwaretech.net matrix-postgres[32910]:                                 SUM(size) AS size
Dec 13 18:41:02 xwaretech.net matrix-postgres[32910]:                         FROM pg_ls_waldir()
Dec 13 18:41:02 xwaretech.net matrix-postgres[32910]:                         WHERE name ~ '^[0-9A-F]{24}$'
Dec 13 18:41:02 xwaretech.net matrix-prometheus-postgres-exporter[35638]: ts=2023-12-13T18:41:02.352Z caller=collector.go:199 level=error
 msg="collector failed" name=wal duration_seconds=0.028922192 err="pq: permission denied for function pg_ls_waldir"

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
prometheus_enabled: true
prometheus_node_exporter_enabled: true
prometheus_postgres_exporter_enabled: true
grafana_enabled: true
matrix_synapse_metrics_enabled: true
```

**Expected behavior**
Expect to not see these errors.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - amd64

**Additional context**
Looks to be this issue: https://github.com/bitnami/charts/issues/20247 just not sure on best way to resolve issue.
