### ISSUE TITLE
New Signal bridge implementation does not use custom name

### ISSUE THREAD

**Issue by Progrsam** [spantaleev/matrix-docker-ansible-deploy#3088]
**Describe the bug**
Since the new update, the mautrix-signal-bridge does not take the variable matrix_mautrix_signal_appservice_bot_username to change the Username of the bridge.  

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_appservice_bot_username: "my_signal_bot_username"

matrix_mautrix_signal_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true

```

**Expected behavior**
The signal  bridge should use the custom name. Instead the bridge uses the default signalbot name in roles/custom/matrix-bridge-mautrix-signal/templates/config.yaml.j2 in line 61. 

Before update to go bridge:
```yaml
    # The unique ID of this appservice.
    id: signal
    # Username of the appservice bot.
    bot_username: {{ matrix_mautrix_signal_appservice_bot_username|to_json }}
    # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
    # to leave display name/avatar as-is.
    bot_displayname: Signal bridge bot
    bot_avatar: mxc://maunium.net/wPJgTQbZOtpBFmDNkiNEMDUp
    # Appservice bot details.
```

After:

```yaml
    bot:
        # Username of the appservice bot.
        username: signalbot # <-- Changing this to the older version works for me
        # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
        # to leave display name/avatar as-is.
        displayname: signal bridge bot
        avatar: mxc://maunium.net/wPJgTQbZOtpBFmDNkiNEMDUp
```

**Matrix Server:**
 - OS: Ubuntu
 - Architecture amd64

**My solution**
Changing the username: signalbot back to username: {{ matrix_mautrix_signal_appservice_bot_username|to_json }}
