### ISSUE TITLE
MatchingServerName

### ISSUE THREAD

**Issue by vengefulpunk** [spantaleev/matrix-docker-ansible-deploy#3116]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: darktundra.xyz

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'REPLACED'

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: 'webmaster@wpdevenv.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'REPLACED'

matrix_synapse_admin_enabled: true

matrix_mailer_sender_address: "matrix@darktundra.xyz"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "REPLACED"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "REPLACED"
matrix_mailer_relay_auth_password: "REPLACED"


# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.

# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''
# Enable generation of `/.well-known/matrix/support`.
# This needs to be enabled explicitly for now, because MSC 1929 is not yet accepted.
matrix_well_known_matrix_support_enabled: true

# Homeserver admin contacts as per MSC 1929 https://github.com/matrix-org/matrix-spec-proposals/pull/1929
matrix_homeserver_admin_contacts:
  - matrix_id: "@admin1:{{ matrix_domain }}"
    email_address: webmaster@wpdevenv.com
    role: admin
  - matrix_id: "@admin2:{{ matrix_domain }}"
    email_address: webmaster@darktundra.xyz
    role: admin
  - email_address: webmaster@wpdevenv.com
    role: security

matrix_homeserver_support_url: "https://support.darktundra.xyz"

matrix_synapse_allow_public_rooms_over_federation: true

matrix_synapse_federation_enabled: true

etherpad_enabled: true

prometheus_enabled: true

# You can remove this, if unnecessary.
prometheus_node_exporter_enabled: true

# You can remove this, if unnecessary.
prometheus_postgres_exporter_enabled: true

# You can remove this, if unnecessary.
matrix_prometheus_nginxlog_exporter_enabled: true

grafana_enabled: true

grafana_anonymous_access: false

# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
grafana_default_admin_user: "grafanaadmin"

# Changing the password subsequently won't work.
grafana_default_admin_password: "REPLACED"

matrix_bot_matrix_reminder_bot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_matrix_reminder_bot_matrix_user_id_localpart: bot.matrix-reminder-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_reminder_bot_matrix_user_password: REPLACED

# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: America/Denver


allow_public_rooms_without_auth: true
allow_public_rooms_over_federation: true
```

**Matrix Server:**
 - OS: Ubuntu 22.04
 - amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- on a standalone container
-version 2.16

**Problem description**:

Receiving a MatchingServerName error on https://federationtester.matrix.org/#matrix.darktundra.xyz

looking in /matrix/synapse/config/homeserver.yaml 

config: null
server_name: darktundra.xyz
signing_key_path: /data/matrix.darktundra.xyz.signing.key

Describe what you're doing, what you expect to happen and what happens instead here.
I am not sure where it is getting that from as the onlything that is not matrix.darktundra.xyz in the config is for matrix_domain
