### ISSUE TITLE
matrix-static-files doesn't use matrix_playbook_reverse_proxyable_services_additional_network

### ISSUE THREAD

**Issue by EorlBruder** [spantaleev/matrix-docker-ansible-deploy#3122]
**Describe the bug**
I'm using the playbook with an external traefik. The network name for that traefik is `traefik_proxy`. I also want to serve the well-known-files on the base domain.

Starting the playbook like this, leads to a gateway timeout. After a bit of investigation I figured out, that the matrix-static-files-service sets the network to "traefik" instead of "traefik_proxy". 

Other urls (element. and matrix.) are served as expected.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
"matrix_playbook_reverse_proxy_type": "other-traefik-container"
"matrix_playbook_reverse_proxyable_services_additional_network": "traefik_proxy"
"matrix_static_files_container_labels_base_domain_enabled": true
```

Start the playbook and then try opening the base-domain. It will run into a gateway-timeout. Same goes for the .well-known-files.

**Expected behavior**

The files under the base-domain should be served.

**Matrix Server:**
 - OS: Debian12
 - Architecture amd64

**Additional context**

Looking into the code, the container seems to take its network from `matrix_static_files_container_network`.  In the group_vars this is set from `matrix_playbook_reverse_proxy_container_network` (if `matrix_playbook_reverse_proxy_type` is set). 

That variable is set [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ecb5591743d1cc8e76194606fe5a2b30a49e1085/group_vars/matrix_servers#L25). As you can see, it'll be hardcoded as "traefik" if devture_traefik isn't active. Instead it probably should be derived from `matrix_playbook_reverse_proxyable_services_additional_network`.
