### ISSUE TITLE
matrix-synapse.service fails with variable matrix_synapse_media_store_path

### ISSUE THREAD

**Issue by ZelChief** [spantaleev/matrix-docker-ansible-deploy#3134]
**Describe the bug**

`matrix-synapse.service` can't start with variable `matrix_synapse_media_store_path`.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.com
matrix_base_data_path: "/srv/matrix"
matrix_synapse_media_store_path: "/srv/data"
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '87ynd8n7fyv'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_entrypoint_web_secure_enabled: false
```

After install:

```bash
$ sudo journalctl -xeu matrix-synapse.service
Jan 26 03:04:24 matrix matrix-synapse[9190]: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /srv/matrix/synapse/storage
Jan 26 03:04:24 matrix systemd[1]: matrix-synapse.service: Control process exited, code=exited, status=1/FAILURE
```

And in `/srv/matrix/synapse`

```bash
root@matrix:/srv/matrix/synapse# ls -la
total 23
drwxr-x---  5 matrix matrix    6 Jan 26 02:47 .
drwxr-x--- 15 matrix matrix   15 Jan 26 02:52 ..
drwxr-x---  2 matrix matrix    3 Jan 26 02:47 bin
drwxr-x---  2 matrix matrix    5 Jan 26 02:47 config
drwxr-x---  2 matrix matrix    2 Jan 26 02:45 ext
-rw-r--r--  1 root   root   7026 Jan 26 02:47 labels
```

Folder `matrix_synapse_media_store_path` exists:

```bash
root@matrix:/srv# ls -la
total 21
drwxr-xr-x  4 root   root    4 Jan 26 02:45 .
drwxr-xr-x 17 root   root   23 Jan 26 02:42 ..
drwxr-x---  2 matrix matrix  2 Jan 26 02:45 data
drwxr-x--- 15 matrix matrix 15 Jan 26 02:52 matrix
```

But folder `matrix_synapse_media_store_path` is empty

```bash
root@matrix:/srv/data# ls -la
total 1
drwxr-x--- 2 matrix matrix 2 Jan 26 02:45 .
drwxr-xr-x 4 root   root   4 Jan 26 02:45 ..
```

If I remove `matrix_synapse_media_store_path`, works without fails.
