### ISSUE TITLE
Which `traefik` docker labels for pointing to an additional webserver?

### ISSUE THREAD

**Issue by elindgren** [spantaleev/matrix-docker-ansible-deploy#3140]
Hi! I want to use the included `traefik` reverse proxy to also handle requests to an additional webserver I'm running in a docker container on the same server as all the other services. I followed [this section of the docs](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-traefik.md#reverse-proxying-another-service-behind-traefik) where, if I understand correctly, I can add my service to `traefik` simply by specifying the correct labels for my docker service. See the configuration I use in my `docker-compose.yaml` below.

My service can join the `traefik` docker network just fine, but when I access `https://subdomain.myserver.org` I get a 404 not found. I suspect I've misconfigured the `traefik` labels, specifically with regards to the `traefik` router name (it's probably not `myrouter` as I've used 😆), but I don't know what it should be. Anyone that can help a struggling hobbyist out? 😅 

#### docker-compose.yaml

```yaml
version: "3"
services:
  webserver:
    image: webserver:latest
    restart: always
    ports:
      - "4173:4173"
    build:
       context: .
       labels:
         - traefik.http.routers.myrouter.rule=Host(`subdomain.myserver.org`) # enable trafik reverse proxy
         - traefik.http.routers.myrouter.tls=true              # enable tls via reverse proxy
         # Tell Traefik to use the port 4173 to connect to `my-container`
         - traefik.http.services.my-service.loadbalancer.server.port=4173

networks:
  default:
    name: traefik
    external: true  # requires the traefik network from docker-ansible-deploy to have been created


```
