### ISSUE TITLE
Working Matrix install broken after trying to update! Help!!

### ISSUE THREAD

**Issue by drelephant** [spantaleev/matrix-docker-ansible-deploy#3146]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: sitename.org

# The Matrix homeserver software to install.
# See:
#  - `roles/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'secret'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
#matrix_ssl_lets_encrypt_support_email: 'revoked@gmail.com'
devture_traefik_config_certificatesResolvers_acme_email: 'redacted@gmail.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
#matrix_postgres_connection_password: 'secret'
devture_postgres_connection_password: 'secret'

#matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_static_files_container_labels_base_domain_enabled: true


matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: 'redacted@gmail.com'
```

**Matrix Server:**
 - OS: Ubuntu 20.04.6 LTS
 - Architecture amd64

**Ansible:**

I think Ansible is working.

`ansible --version`
```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.17 (default, Jun  6 2023, 20:10:10) [GCC 9.4.0]. This
feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.12]
  config file = /home/redacted/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/redacted/.local/lib/python3.7/site-packages/ansible
  ansible collection location = /home/redacted/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/redacted/.local/bin/ansible
  python version = 3.7.17 (default, Jun  6 2023, 20:10:10) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = False
```

**Problem description**:

I just tried to update my working but probably very out of date matrix install, but now I've broken things and now it isn't working.

Here's what I did:
ran `git pull`
installed [Prebuilt-MPR](https://docs.makedeb.org/prebuilt-mpr/getting-started/#setting-up-the-repository)
installed `just` - `sudo apt install just`
did `just roles`
ran `just setup-all`, fixing variables in my `inventory/host_vars/sitename/vars.yml` as it kept failing with errors:

changed `matrix_ssl_lets_encrypt_support_email` to `devture_traefik_config_certificatesResolvers_acme_email`

changed `matrix_postgres_connection_password` to `devture_postgres_connection_password`

changed `matrix_nginx_proxy_base_domain_serving_enabled` to `matrix_static_files_container_labels_base_domain_enabled`

After reading [this about changing to traefik](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#how-do-i-explicitly-switch-to-traefik-right-now)
I added the line `matrix_playbook_reverse_proxy_type: playbook-managed-traefik`
and added my email as `devture_traefik_config_certificatesResolvers_acme_email:`

It looks like it was mostly able to update, but now
`just setup-all` , `just stop-all` and `just start-all` now fail at the end with this error:
```
TASK [galaxy/systemd_service_manager : Ensure systemd is reloaded] **********************************************
s_push: parser stack overflow
fatal: [sitename.org]: FAILED! =>
  msg: |-
    The conditional check 'devture_systemd_service_manager_services_list_to_work_with | length > 0' failed. The error was: An unhandled exception occurred while templating '{{ devture_system
d_service_manager_services_list }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ devture_systemd_service_manager
_services_list_auto + devture_systemd_service_manager_services_list_additional }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occu
rred on ({{ devture_systemd_service_manager_services_list_auto + devture_systemd_service_manager_services_list_additional }}): can only concatenate str (not "list") to str

    The error appears to be in '/home/redacted/matrix-docker-ansible-deploy/roles/galaxy/systemd_service_manager/tasks/restart_specified.yml': line 3, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - when: devture_systemd_service_manager_services_list_to_work_with | length > 0
      ^ here

PLAY RECAP ******************************************************************************************************
sitename.org : ok=336  changed=4    unreachable=0    failed=1    skipped=521  rescued=0    ignored=0

```
I'm not sure how to proceed, can anyone help me?
