### ISSUE TITLE
Can't create users - ERROR! Received 500 Internal Server Error

### ISSUE THREAD

**Issue by Kuphi** [spantaleev/matrix-docker-ansible-deploy#3152]
**Describe the bug**
Can't create user using:
```
docker exec matrix-synapse register_new_matrix_user -u "username" -p "password" -c /data/homeserver.yaml --admin http://localhost:8008
```
or 
```
ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=username password=password admin=no' --tags=register-user
```
respectively.

Output of the latter is:
```
[...]
TASK [custom/matrix-synapse : Register user] *****************************************************************************************************************************
fatal: [matrix.domain.com]: FAILED! => changed=false 
  cmd:
  - /matrix/synapse/bin/register-user
  - user
  - password
  - '0'
  delta: '0:00:03.281327'
  end: '2024-02-03 12:00:24.398932'
  msg: non-zero return code
  rc: 1
  start: '2024-02-03 12:00:21.117605'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Sending registration request...
    ERROR! Received 500 Internal Server Error
  stdout_lines: <omitted>

PLAY RECAP ***************************************************************************************************************************************************************
matrix.domain.com            : ok=7    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '******'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: 'traefikmatrix@domain.com'
devture_postgres_connection_password: '******'
matrix_synapse_admin_enabled: true
devture_playbook_help_container_retries_delay: 9
devture_playbook_help_container_retries_count: 9
#I have a slow 1CPU server, thus:
devture_systemd_service_manager_up_verification_delay_seconds: 180
```

**Expected behavior**
Can create users without manual adjustments.

**Matrix Server:**
 - OS: Debian 12
 - Architecture: amd64
