### ISSUE TITLE
Latest change to static website serving is disabling static website serving

### ISSUE THREAD

**Issue by jalemann** [spantaleev/matrix-docker-ansible-deploy#3153]
Docs and changelog for serving a static website on base domain state this code:

```yaml
# Enable base-domain serving
matrix_static_files_container_labels_base_domain_enabled: true

# Prevent the default index.html file from being installed
matrix_static_files_file_index_html_enabled: false

# Disable the automatic redirectin of `https://DOMAIN/` to `https://matrix.DOMAIN/`.
# This gets automatically enabled when you disable `matrix_static_files_file_index_html_enabled`, as we're doing above.
matrix_static_files_container_labels_base_domain_enabled: false
```

Maybe I misunderstood something but this seems weird because `matrix_static_files_container_labels_base_domain_enabled` is set to `true` to enable serving a website on the base domain but then set to `false` to not redirect from base domain to matrix.domain.

Doesn't it also disable serving on the base domain?
It did when I tried using the variables above.
However, leaving the `matrix_static_files_container_labels_base_domain_enabled: false` out of my config (so using the config from before), still works as it did before and doesn't redirect the domain to matrix.domain.
