### ISSUE TITLE
Synapse Worker Metrics exposed at wrong path since Traefik migration

### ISSUE THREAD

**Issue by davidmehren** [spantaleev/matrix-docker-ansible-deploy#3154]
**Describe the bug**
The documentation [states](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-prometheus-grafana.md?plain=1#L89C146-L89C321):

> the playbook will also automatically expose all Synapse worker threads' metrics to `https://matrix.DOMAIN/metrics/synapse/worker/ID`, where `ID` corresponds to the worker `id`

But since the migration to Traefik this does not seem to be the case anymore.
The worker containers have labels like
``"traefik.http.routers.matrix-synapse-worker-generic-0-metrics.rule": "Host(`matrix.kif.rocks`) && Path(`/metrics/synapse/generic-worker-0`)"``, which misses the `worker` subpath.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
# A bunch of stuff omitted, the relevant settings are:

matrix_synapse_metrics_enabled: true
matrix_synapse_metrics_proxying_enabled: true
matrix_metrics_exposure_enabled: true

matrix_metrics_exposure_http_basic_auth_enabled: true
matrix_metrics_exposure_http_basic_auth_users: <redacted>
```

**Expected behavior**
Metrics should be available at the documented place or the documentation should be adjusted and the change announced.

**Matrix Server:**
 - OS: Debian 12
 - Architecture: amd64
