### ISSUE TITLE
 matrix-traefik.service doesn't start - node: insecure

### ISSUE THREAD

**Issue by Kuphi** [spantaleev/matrix-docker-ansible-deploy#3156]
**Describe the bug**
 matrix-traefik.service doesn't start
 Error occurs at:
```
 ExecStart=/usr/bin/env docker start --attach matrix-traefik
 2024/02/04 18:05:33 command traefik error: field not found, node: insecure
```
 
**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'secret'
devture_postgres_connection_password: 'password'
matrix_client_element_enabled: false
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '127.0.0.1:81'
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port: '127.0.0.1:8449'
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
    forwardedHeaders:
    insecure: true
    trustedIPs: ['99.99.99.99']
matrix_synapse_admin_enabled: true
devture_playbook_help_container_retries_delay: 9
devture_playbook_help_container_retries_count: 9
```

Running ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start --ask-become-pass
results in:
```
TASK [galaxy/systemd_service_manager : Fail if service isn't detected to be running] ***************************
skipping: [matrix.domain.com] => (item=matrix-container-socket-proxy.service) 
failed: [matrix.domain.com] (item=matrix-traefik.service) => changed=false 
  ansible_loop_var: item
  item: matrix-traefik.service
  msg: matrix-traefik.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-traefik.service` and `journalctl -fu matrix-traefik.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `devture_systemd_service_manager_up_verification_delay_seconds` variable. See `/home/user/matrix-docker-ansible-deploy/roles/galaxy/systemd_service_manager/defaults/main.yml` for more details about that.
skipping: [matrix.domain.com] => (item=matrix-postgres.service) 
skipping: [matrix.domain.com] => (item=matrix-exim-relay.service) 
skipping: [matrix.domain.com] => (item=matrix-coturn.service) 
skipping: [matrix.domain.com] => (item=matrix-synapse.service) 
skipping: [matrix.domain.com] => (item=matrix-static-files.service) 
skipping: [matrix.domain.com] => (item=matrix-synapse-admin.service) 
skipping: [matrix.domain.com] => (item=matrix-coturn-reload.timer) 

PLAY RECAP *****************************************************************************************************
matrix.domain.com           : ok=331  changed=5    unreachable=0    failed=1    skipped=519  rescued=0    ignored=0   
```

**Expected behavior**
Traefik should start.

**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64

**Additional context**
config of /etc/nginx/conf.d/matrix.conf:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # TODO: add/remove services and their subdomains if you use/don't use them
    # this example is using hosting something on the base domain and an element web client, so domain.com and element.domain.com are listed in addition to matrix.domain.com
    # if you don't use those, you can remove them
    # if you use e.g. dimension on dimension.domain.com, add dimension.domain.com to the server_name list
    server_name matrix.domain.com;

    location / {
        # note: do not add a path (even a single /) after the port in `proxy_pass`,
        # otherwise, nginx will canonicalise the URI and cause signature verification
        # errors.
        proxy_pass http://localhost:81;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;

        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 50M;
    }

    # TODO: adapt the path to your ssl certificate for the domains listed on server_name
    ssl_certificate /etc/letsencrypt/live/matrix.domain.com/fullchain.pem; # managed by Certbot
    # TODO: adapt the path to your ssl certificate for the domains listed on server_name
    ssl_certificate_key /etc/letsencrypt/live/matrix.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# settings for matrix federation
server {
    # For the federation port
    listen 8448 ssl http2 default_server;
    listen [::]:8448 ssl http2 default_server;

    server_name matrix.domain.com;

    location / {
        proxy_pass http://localhost:8449;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;

        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 50M;
    }
    # TODO: adapt the path to your ssl certificate for the domains listed on server_name
    ssl_certificate /etc/letsencrypt/live/matrix.domain.com/fullchain.pem; # managed by Certbot
    # TODO: adapt the path to your ssl certificate for the domains listed on server_name
    ssl_certificate_key /etc/letsencrypt/live/matrix.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# ensure using https
# TODO: remove server blocks that you don't use / add server blocks for domains you do use
server {
    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name domain.com;
    listen 80;
    return 404; # managed by Certbot
}

server {
    if ($host = matrix.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name matrix.domain.com;
    listen 80;
    return 404; # managed by Certbot
}
```

**Comment by Kuphi** [comment]
Might be relevant:
In the file /etc/nginx/conf.d/domain.com.conf I added the following:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name domain.com;

    access_by_lua_file /usr/share/ssowat/access.lua;

    include /etc/nginx/conf.d/acme-challenge.conf.inc;

    location ^~ '/.well-known/ynh-diagnosis/' {
        alias /var/www/.well-known/ynh-diagnosis/;
    }
    
    location ^~ '/.well-known/autoconfig/mail/' {
        alias /var/www/.well-known/domain.com/autoconfig/mail/;
    }
    
    location /.well-known/matrix {
        proxy_pass https://matrix.domain.com/.well-known/matrix;
        proxy_set_header X-Forwarded-For $remote_addr;
    proxy_ssl_server_name on;
    }
    
    location / {
        return 301 https://$host$request_uri;
    }
    
    include /etc/nginx/conf.d/yunohost_http_errors.conf.inc;

    access_log /var/log/nginx/domain.com-access.log;
    error_log /var/log/nginx/domain.com-error.log;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name domain.com;

    include /etc/nginx/conf.d/security.conf.inc;

    ssl_certificate /etc/yunohost/certs/domain.com/crt.pem;
    ssl_certificate_key /etc/yunohost/certs/domain.com/key.pem;
    
    location ^~ '/.well-known/autoconfig/mail/' {
        alias /var/www/.well-known/domain.com/autoconfig/mail/;
    }
    
    location /.well-known/matrix {
        proxy_pass https://matrix.domain.com/.well-known/matrix;
        proxy_set_header X-Forwarded-For $remote_addr;
    proxy_ssl_server_name on;
    }

    access_by_lua_file /usr/share/ssowat/access.lua;

    include /etc/nginx/conf.d/domain.com.d/*.conf;

    include /etc/nginx/conf.d/yunohost_sso.conf.inc;
    include /etc/nginx/conf.d/yunohost_admin.conf.inc;
    include /etc/nginx/conf.d/yunohost_api.conf.inc;
    include /etc/nginx/conf.d/yunohost_http_errors.conf.inc;

    access_log /var/log/nginx/domain.com-access.log;
    error_log /var/log/nginx/domain.com-error.log;
}
```

**Comment by Kuphi** [comment]
Worth mentioning: It was already running and the server was accessible via 443, synapse-admin as well. But via 8448 it wasn't accessible. Dunno what exactly I changed, but Traefik doesn't start anymore.

**Comment by Kuphi** [comment]
The reason why this didn't work is the wrong formatting:
```
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
    forwardedHeaders:
    insecure: true
    trustedIPs: ['99.99.99.99']
```

but it should be:
```
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
    insecure: true
    trustedIPs: ['99.99.99.99']
```

2 spaces in front of forwardedHeaders: and
4 spaces in front of the following two lines.
