### ISSUE TITLE
Matrix federation API returns '404 page not found'

### ISSUE THREAD

**Issue by ZelChief** [spantaleev/matrix-docker-ansible-deploy#3167]
**Describe the bug**
Local IP of server is 192.168.1.26. If I run:

```bash
$ curl -H 'Host: matrix.domain.com' http://192.168.1.26:8449
404 page not found
```

I conclude that the Matrix federation  is not working. Others service are running without any errors.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.com
matrix_base_data_path: "/srv/matrix"
matrix_synapse_storage_path: "/srv/synapse-storage"
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'rkfaoIdPKp*****'


matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: '81'
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
devture_traefik_config_entrypoint_web_forwardedHeaders_trustedIPs: '37.***.**.122'
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port: '8449'
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
    insecure: true
    trustedIPs: ['37.***.**.122']


devture_postgres_connection_password: 'DElWHnlkPU0dyyx6E******'

# Jitsu
# https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md
jitsi_enabled: true
jitsi_enable_auth: true
jitsi_enable_guests: false
jitsi_auth_type: matrix

matrix_user_verification_service_enabled: true
matrix_user_verification_service_uvs_access_token: 'Hl7pAf5wZf3fdvwK6iD4RTfP********'

jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
  config.disableAudioLevels = true;
  config.channelLastN = 4;

jitsi_web_config_resolution_width_ideal_and_max: 720
jitsi_web_config_resolution_height_ideal_and_max: 480
jitsi_prosody_max_participants: 10

matrix_homeserver_federation_enabled: true
matrix_synapse_allow_public_rooms_over_federation: false
matrix_federation_public_port: '8449'

matrix_synapse_admin_enabled: true
#matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true

```

**Expected behavior**

**Matrix Server:**
 - OS: Debian 12
 - Architecture: amd64

**Ansible:**
There is no problem:
```bash
PLAY RECAP ****************************************************************************************
matrix.domain.com: ok=231  changed=16   unreachable=0    failed=0    skipped=323  rescued=0    ignored=0 
```
