### ISSUE TITLE
Postgres 14 to 16 update fails. 

### ISSUE THREAD

**Issue by FSG-Cat** [spantaleev/matrix-docker-ansible-deploy#3180]
**Describe the bug**
Synapse refuses to work post Postgres 14 to 16 upgrade with 0 logs being able to be located that provide any information what so ever.

**To Reproduce**
My `vars.yml` file looks like this: 

Workers Enabled, Postgres password set and that should be it that touches Synapse and its postgres behavior. 

As to how to reproduce it well try to upgrade from 14 to 16 with a database that has been used and Synapse seems to be unhappy.

**Expected behavior**
That it works ofc. 

**Matrix Server:**
 - OS: Debian 12
 - Architecture amd64

**Comment by altsalt** [comment]
I've had a similar struggle, but think that my issue is related to not having enough drive space to store three versions of the database. Will keep an eye on this issue, whether it ends up being the same issue or a different one.

**Comment by spantaleev** [comment]
I've justed tested this against a Debian 12 VM with a `vars.yml` file that looks like this:

```yml
---

matrix_domain: example.com

matrix_homeserver_implementation: synapse
matrix_homserver_federation_enabled: false
matrix_homeserver_generic_secret_key: 'test'

matrix_synapse_workers_enabled: true

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_config_certificatesResolvers_acme_email: ''

# We need this for Debian 12 due to a conflict with some `time-daemon` package
devture_timesync_installation_enabled: false

devture_postgres_connection_password: 'test'

# TODO - remove after the initial installation, so upgrading would be possible
devture_postgres_container_image_latest: "{{ devture_postgres_container_image_v14 }}"
```

This makes a clean installation with Postgres pinned to v14. I've explicitly enabled Synapse workers to replicate your setup.

After the initial installation, I created some Synapse users manually.

I then removed the `devture_postgres_container_image_latest` override from `vars.yml` and ran `upgrade-postgres`. During the upgrade, all other containers were stopped (`docker ps` only showed `matrix-postgres` and `matrix-postgres-import` running). The upgrade to Postgres v16 (current latest at the time of this writing) was successful and my Synapse database still seems to contain my users, etc.

---

So, I'm not sure what's going on in your case and for others that have reported similar issues recently, but I can't reproduce the problem.
