### ISSUE TITLE
Authorization via login/password for Coturn

### ISSUE THREAD

**Issue by ZelChief** [spantaleev/matrix-docker-ansible-deploy#3191]
[Coturn](https://github.com/coturn/coturn) server will not work with `static-auth-secret` under NAT as a TURN server. You can find information about this issue here:

1. https://github.com/coturn/coturn/issues/162#issuecomment-322460614
2. https://github.com/coturn/coturn/issues/933#issuecomment-1203830697

But if configure in `/etc/turnserver.conf` static login and password, Coturn will work as turn server under NAT.
```yml
lt-cred-mech
user=turnuser:secret
```

**Describe the solution you'd like**
Can you add а variable to [matrix-coturn](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-coturn/defaults/main.yml) to setup `lt-cred-mech` and to disable `static-auth-secret`?

**Comment by ZelChief** [comment]
@spantaleev can you show the way to setup login and password for Coturn?

**Comment by ZelChief** [comment]
In [homeserver.yaml.j2](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/63b945dc1acdf5d1f872bd9aadd0d416196db6e1/roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2#L1271) there is necessary variables:

```yml
# The Username and password if the TURN server needs them and
# does not use a token
#
turn_username: "TURNSERVER_USERNAME"
turn_password: "TURNSERVER_PASSWORD"
```

Maybe there is a way to use them for external Coturn server?
