### ISSUE TITLE
Conference Calls Using Jitsi Instead of Element Call UI

### ISSUE THREAD

**Issue by patrickelam** [spantaleev/matrix-docker-ansible-deploy#3198]
**Playbook Configuration**:

I'm running the playbook against a VM on my LAN. I am using Nginx Proxy Manager as a proxy in front of the machine (and other hosted services). matrix.domain, matrix.domain:8448, and element.domain are forwarded appropriately and are working. All associated (I think, based on what the matrix-coturn docker exposes) turn ports (3478,5349,49152-49172) are forwarded from my firewall to the VM. I also commented out (perhaps erroneously) the LAN IP list items from `matrix_coturn_denied_peer_ips` in `roles/custom/matrix-coturn/defaults/main.yml`.

At the base domain, I had to add the following to the Advanced->Custom Nginx Configuration section in order to get .well-known to work, as the documented way (proxying to matrix.domain) caused a circular routing issue.

```
location /.well-known/matrix/server {
    return 200 '{"m.server": "matrix.domain.com:8448"}';
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
}

location /.well-known/matrix/client {
    return 200 '{
        "m.homeserver": {
            "base_url": "https://matrix.domain.com"
        },
        "org.matrix.msc3575.proxy": {
            "url": "https://matrix.domain.com/sliding-sync"
        }
    }'; 
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
}
```

My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'password'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_traefik_container_web_host_bind_port: 'lan_ip:81'
matrix_playbook_service_host_bind_interface_prefix: 'lan_ip:'
devture_traefik_config_entrypoint_web_forwardedHeaders_insecure: true
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port: 'lan_ip:8449'
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
    insecure: true
devture_traefik_config_certificatesResolvers_acme_email: ''
devture_postgres_connection_password: 'password'
matrix_coturn_turn_external_ip_address: ''
matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: one-of-each
matrix_synapse_admin_enabled: true
matrix_sliding_sync_enabled: true
```

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture amd64

**Ansible:**
core 2.16.3

**Problem description**:

When I create a room and then start a video call, a jitsi widget pops up. I've gone and selected to join the beta for video calling, and it *kinda* works with 1:1 calling if one client is outside the LAN. I really want to use the new video calling without Jitsi, but I'm not able to, and I'm not sure why. I'm still getting my head around the Matrix architecture, but is there another component that I need? Is there something that's just misconfigured? 

**Additional context**
The group call feature combined with [oidc](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3108) is the last step for me to start using matrix a lot more heavily.

Thanks!
