### ISSUE TITLE
matrix-dendrite.service service fails to start when whatsapp bridge is enabled 

### ISSUE THREAD

**Issue by inknos** [spantaleev/matrix-docker-ansible-deploy#3199]
**Describe the bug**
When running `just setup-all` the matrix-dendrite container fails to start if matrix whatsapp bridge is enabled.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
matrix_domain: xxx.xxx

matrix_homeserver_implementation: dendrite
matrix_dendrite_media_store_path: /mnt/nas/dendrite-media

matrix_static_files_container_labels_base_domain_enabled: true

matrix_homeserver_generic_secret_key: 'xxx'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: 'aaa@bbb.c'

devture_postgres_connection_password: 'xxx'

ntfy_enabled: true

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'xxx'

matrix_sliding_sync_enabled: true

matrix_mautrix_whatsapp_enabled: true

```

Use the vars.yml, run `just setup-all`

```log
failed: [matrix.snag.social] (item={'name': 'matrix-dendrite.service', 'priority': 1000, 'groups': ['matrix', 'homeservers', 'dendrite']}) => changed=false                                                                                                                                               
  ansible_loop_var: item                                                                                                                             
  item:                                                                                                                                              
    groups:                                                                                                                                              - matrix                                                                                                                                         
    - homeservers                                                                                                                                    
    - dendrite                                                                                                                                           name: matrix-dendrite.service                                                                                                                    
    priority: 1000                                                                                                                                   
  msg: |-                                                                                                                                            
    Unable to start service matrix-dendrite.service: Job for matrix-dendrite.service failed because the control process exited with error code.      
    See "systemctl status matrix-dendrite.service" and "journalctl -xe" for details.
```

**Expected behavior**
All should be up and running

**Matrix Server:**
 - OS: Debian 11.7
 - x86_64

**Playbook version**
```log
# git log
commit ac24b9f20db8ff211590a5f09fe15d460e76a522 (origin/master, origin/HEAD)
Merge: 3d337dc1 c375d888
Author: Slavi Pantaleev <slavi@devture.com>
Date:   Thu Feb 22 09:13:16 2024 +0200

    Merge pull request #3197 from spantaleev/renovate/halfshot-matrix-hookshot-5.x
    
    chore(deps): update halfshot/matrix-hookshot docker tag to v5.2.1
```

**Additional context**

Investigation.
I changed few lines in the file `/etc/systemd/system/matrix-dendrite.service` to preserve the container.

```
...
ExecStartPre=/usr/bin/env docker create \
#                        --rm \
                        --name=matrix-dendrite \
#                        --log-driver=none \
                        --user=997:1001 \
                        --cap-drop=ALL \
...
```

Then I can see this in the logs

```
# docker logs matrix-dendrite                                                                                 
time="2024-02-22T12:51:42Z" level=fatal msg="Invalid config file: open /matrix-mautrix-whatsapp-registration.yaml: no such file or directory"        
```
