### ISSUE TITLE
Ansible: `matrix-synapse-reverse-proxy-companion.service` is not detected running after `just setup-all`

### ISSUE THREAD

**Issue by pm-McFly** [spantaleev/matrix-docker-ansible-deploy#3269]
**Describe the bug**
After running `setup-all` just command to update the server, Ansible keeps telling that `matrix-synapse-reverse-proxy-companion.service` is not running although when manually checking, the service is correctly started and running.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
matrix_playbook_docker_installation_enabled: true
matrix_playbook_migration_debian_signedby_migration_enabled: true
matrix_domain: server.tld
matrix_admin: "@admin:{{ matrix_domain }}"
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'secret'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_static_files_container_labels_base_domain_enabled: true
devture_traefik_config_certificatesResolvers_acme_email: 'email'
devture_postgres_connection_password: 'pass'
matrix_coturn_systemd_required_services_list: ['docker.service']

#
## Synapse
#
matrix_synapse_report_stats: true
matrix_synapse_ext_synapse_auto_accept_invite_enabled: true
matrix_synapse_ext_synapse_auto_accept_invite_accept_invites_only_direct_messages: true
matrix_synapse_auto_compressor_enabled: true
matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: specialized-workers

#
## Monitoring
#
prometheus_enabled: true
grafana_enabled: true
grafana_anonymous_access: false
grafana_default_admin_user: "admin"
grafana_default_admin_password: "pass"
prometheus_node_exporter_enabled: true
prometheus_node_exporter_container_labels_traefik_enabled: true
prometheus_postgres_exporter_enabled: true
prometheus_postgres_exporter_container_labels_traefik_enabled: true
matrix_metrics_exposure_enabled: true
matrix_synapse_metrics_proxying_enabled: true
matrix_prometheus_nginxlog_exporter_enabled: true
matrix_media_repo_metrics_enabled: true

#
## ma1sd
#
matrix_ma1sd_enabled: true

#
## Synapse Admin UI
#
matrix_synapse_admin_enabled: true

#
## Shared Secret Auth
#
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'secret'

#
## Element
#
matrix_client_element_themes_enabled: true
matrix_client_element_default_theme: 'dark'

#
## Bridges - Global
#
matrix_bridges_encryption_enabled: true
matrix_bridges_relay_enabled: true

#
## Bridge - Discord
#
matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_version: 'latest'

#
## Bridge - Telegram
#
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_version: 'latest'
matrix_mautrix_telegram_api_id: 'id'
matrix_mautrix_telegram_api_hash: 'hash'
matrix_mautrix_telegram_bot_token: 'token'

#
## Bridge - Whatsapp
#
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_version: 'latest'
matrix_mautrix_whatsapp_bridge_relay_admin_only: false

#
## Bridge - Facebook
#
matrix_mautrix_meta_messenger_enabled: true
matrix_mautrix_meta_messenger_bridge_encryption_allow: true
matrix_mautrix_meta_messenger_bridge_encryption_default: true

#
## Bridge - Instagram
#
matrix_mautrix_meta_instagram_enabled: true
matrix_mautrix_meta_instagram_bridge_encryption_allow: true
matrix_mautrix_meta_instagram_bridge_encryption_default: true

#
## Bridge - signal
#
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_version: 'latest'
matrix_mautrix_signal_bridge_relay_enabled: true
matrix_mautrix_signal_bridge_relay_admin_only: false

#
## sliding proxy
#
matrix_sliding_sync_enabled: true

# vim:ft=yaml
```

**Expected behavior**
Service `matrix-synapse-reverse-proxy-companion` to be correctly detected running if so.

**Matrix Server:**
 - OS: Debian 12
 - Architecture: amd64
 - CPUs: 16$HOME
 - RAM: 16Gb

**Ansible:**
Running on my laptop, Debian 12
```
# ansible --version
ansible [core 2.16.2]
  config file = $HOME/$REPO/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = $HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = $HOME/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] ($HOME/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```
