### ISSUE TITLE
Sliding sync host name mismatch

### ISSUE THREAD

**Issue by Daniel15** [spantaleev/matrix-docker-ansible-deploy#3272]
**Describe the bug**
When I try to enable sliding sync in the Element web UI, I get this error:

> proxyHealthCheck: client using `https://matrix.example.com` but server is as `http://matrix-synapse:8008`

![image](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/91933/ca15e1cc-e1a8-4bfc-8f94-9c9ddbbae61d)

and it doesn't let me continue.

If I hit `https://matrix.example.com/sliding-sync/client/server.json`, it returns:
```json
{"server":"http://matrix-synapse:8008","version":"0.99.15 (bbb886e)"}
```

Do I need to somehow change that server field to match? How do I do that?

**To Reproduce**
My `vars.yml` file looks like this:
```yaml
---
matrix_domain: staging.example.com

matrix_server_fqn_matrix: matrix.example.com
matrix_server_fqn_element: element.example.com
matrix_sliding_sync_enabled: true

matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '<removed>'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: 'ssl@example.com'

devture_postgres_connection_password: '<removed>'
```

**Expected behavior**
Sliding sync should work

**Matrix Server:**
 - OS: Debian 12.5
 - Architecture amd64
