### ISSUE TITLE
Ansible overwrites /etc/docker/daemon.json

### ISSUE THREAD

**Issue by z3ky** [spantaleev/matrix-docker-ansible-deploy#3285]
**Describe the bug**
Running ` ansible-playbook -K -i inventory/hosts setup.yml --tags=setup-all,start` overwrites `/etc/docker/daemon.json` with

```
{
    "experimental": false,
    "ip6tables": false
}
```

**To Reproduce**
- pull the latest version of the master branch
- makr roles
-  `ansible-playbook -K -i inventory/hosts setup.yml --tags=setup-all,start`

```yaml

matrix_domain: xxx
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'xxx'
devture_traefik_config_certificatesResolvers_acme_email: 'xxx'
devture_postgres_connection_password: 'xxx='

matrix_synapse_admin_enabled: true

matrix_coturn_enabled: false

matrix_homeserver_container_network: 'matrix-net'
matrix_monitoring_container_network: 'matrix-net'
matrix_addons_container_network: 'matrix-net'

matrix_playbook_reverse_proxy_type: other-traefik-container
matrix_playbook_reverse_proxyable_services_additional_network: matrix-net
matrix_playbook_reverse_proxy_hostname: traefik
devture_traefik_certs_dumper_ssl_dir_path: "xxx"
devture_traefik_config_certificatesResolvers_acme_name: xxx
devture_traefik_config_entrypoint_web_secure_name: websecure

matrix_synapse_database_password: "xxx"
matrix_synapse_database_database: "xxx"

matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
    - idp_id: keycloak
      idp_name: "SSO"
      issuer: "xxx"
      client_id: "matrix"
      client_secret: "xxx"
      scopes: ["openid", "profile"]
      user_mapping_provider:
        config:
          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
          email_template: "{% raw %}{{ user.email }}{% endraw %}"
      backchannel_logout_enabled: false

matrix_synapse_enable_registration: false
matrix_synapse_password_config_localdb_enabled: false
matrix_synapse_federation_enabled: false

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'xxx'
matrix_synapse_ext_password_provider_shared_secret_auth_com_devture_shared_secret_auth_support_enabled: true

matrix_client_element_registration_enabled: false
matrix_client_element_configuration_extension_json: |
  {
    "sso_redirect_options": {
        "immediate": true
    }
  }

matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_database_engine: postgres
matrix_mautrix_whatsapp_database_username: 'xxx'
matrix_mautrix_whatsapp_database_password: 'xxx'
matrix_mautrix_whatsapp_bridge_encryption_allow: true
matrix_mautrix_whatsapp_configuration_extension_yaml: |
  bridge:
    history_sync:
      max_initial_conversations: 10

matrix_client_element_themes_enabled: true
matrix_client_element_themes_repository_url: https://github.com/aaronraimist/element-themes
matrix_client_element_themes_repository_version: master

matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_bridge_encryption_allow: true
matrix_mautrix_signal_database_username: 'xxx'
matrix_mautrix_signal_database_password: 'xxx'

matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: xxx
matrix_mautrix_telegram_api_hash: "xxx"
matrix_mautrix_telegram_database_username: 'xxx'
matrix_mautrix_telegram_database_password: 'xxx'
matrix_mautrix_telegram_bridge_encryption_allow: true
matrix_mautrix_telegram_database_engine: 'postgres'
matrix_mautrix_telegram_configuration_extension_yaml: |
  max_initial_member_sync: 100
  sync_direct_chats: true

exim_relay_sender_address: "xxx"
exim_relay_relay_use: true
exim_relay_relay_host_name: "xxx"
exim_relay_relay_host_port: 25
exim_relay_relay_auth: false


matrix_client_hydrogen_enabled: true

matrix_bot_postmoogle_enabled: false
matrix_bot_postmoogle_ssl_path: "xxx"
matrix_bot_postmoogle_tls_cert: "xxx"
matrix_bot_postmoogle_tls_key: "xxx"

matrix_bot_postmoogle_noencryption: false
matrix_bot_postmoogle_password: "xxx"
matrix_bot_postmoogle_database_username: 'xxx'
matrix_bot_postmoogle_database_password: 'xxx'
matrix_bot_postmoogle_database_engine: 'postgres'
matrix_bot_postmoogle_admins: 
  - "xxx"

matrix_dimension_enabled: true
matrix_dimension_database_username: 'xxx'
matrix_dimension_database_password: 'xxx'
matrix_dimension_admins:
  - "xxx"
matrix_dimension_access_token: "xxx"
matrix_dimension_database_engine: 'postgres'

matrix_ma1sd_enabled: true
matrix_ma1sd_matrixorg_forwarding_enabled: false
matrix_ma1sd_database_engine: 'postgres'
matrix_ma1sd_database_username: 'xxx'
matrix_ma1sd_database_password: 'xxx'

```

**Expected behavior**
No changes of /etc/docker/daemon.json

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- run on the server itself
-  2.13.6
