### ISSUE TITLE
devture_traefik_ssl_dir_enabled: true Not creating /matrix/traefik/config Directory

### ISSUE THREAD

**Issue by NassemKa** [spantaleev/matrix-docker-ansible-deploy#3292]
**Describe the bug**
devture_traefik_ssl_dir_enabled: true Not creating /matrix/traefik/config Directory.
I am using self signed certificate that i generate to test this playbook on local lan, in the doc it mentioned to add
devture_traefik_ssl_dir_enabled: true 
to create /matrix/traefik/config Directory but doesn't seems to be working.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: home.xyz
#
# Condiguring Well Known
matrix_static_files_container_labels_base_domain_enabled: true
# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse
#
# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'secret-key'
#
# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'secret password'

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''
#
# matrix admin console enable install
matrix_synapse_admin_enabled: true
#
# install ntfy
ntfy_enabled: true
ntfy_hostname: 'ntfy.home.xyz'
# Uncomment and change to inject additional configuration options.
matrix_server_fqn_ntfy: "ntfy.{{ matrix_domain }}"
ntfy_configuration_extension_yaml: |
  log_level: DEBUG
  ntfy_self_check_validate_certificates: false
#
# jitsi install
jitsi_enabled: true
jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=172.24.80.75"'
#
#grafana enable
prometheus_enabled: true
grafana_enabled: true
grafana_anonymous_access: false
# This has no relation to your Matrix user id. It can be any username you'd like.
# Changing the username subsequently won't work.
grafana_default_admin_user: "admin"
# Changing the password subsequently won't work.
grafana_default_admin_password: "password"
#
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
#
# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: 'test@home.local'
# Disable ACME / Let's Encrypt support.
devture_traefik_config_certificatesResolvers_acme_enabled: false
# Disabling ACME support (above) automatically disables the creation of the SSL directory.
# Force-enable it here, because we'll add our certificate files there.
#
devture_traefik_ssl_dir_enabled: true

devture_traefik_configuration_extension_yaml: |
  providers:
    file:
      filename: /config/certificates.yml
      watch: true
#
aux_file_definitions:
  # Create the privkey.pem file on the server by
  # uploading a file from the computer where Ansible is running.
  - dest: "{{ devture_traefik_ssl_dir_path }}/privkey.pem"
    src: /home/ubuntu/projects/matrix-docker-ansible-deploy/ssl/privkey.pem
    # Alternatively, comment out `src` above and uncomment the lines below to provide the certificate content inline.
    # Note the indentation level.
    # content: |
    #   FILE CONTENT
    #   HERE
#
  # Create the cert.pem file on the server
  # uploading a file from the computer where Ansible is running.
  - dest: "{{ devture_traefik_ssl_dir_path }}/cert.pem"
    src: /home/ubuntu/projects/matrix-docker-ansible-deploy/ssl/cert.pem
    # Alternatively, comment out `src` above and uncomment the lines below to provide the certificate content inline.
    # Note the indentation level.
    # content: |
    #   FILE CONTENT
    #   HERE
#
  # Create the custom Traefik configuration.
  # The `/ssl/..` paths below are in-container paths, not paths on the host (/`matrix/traefik/ssl/..`). Do not change them!
  - dest: "{{ devture_traefik_config_dir_path }}/certificates.yml"
    content: |
      tls:
        certificates:
          - certFile: /ssl/cert.pem
            keyFile: /ssl/privkey.pem
        stores:
          default:
            defaultCertificate:
              certFile: /ssl/cert.pem
              keyFile: /ssl/privkey.pem
#White list local IP to make push notificton work
matrix_synapse_configuration_extension_yaml: |
  ip_range_whitelist:
    - '172.24.80.0/24'
# Etherpad
etherpad_enabled: true

# Uncomment below to enable the admin web UI
etherpad_admin_username: admin
etherpad_admin_password: password
```

**Expected behavior**
The playbook should create /matrix/traefik/config Directory

**Matrix Server:**
 - OS: Ubuntu 22.04.4 LTS
 - Architecture  amd64

**Ansible:**
- Ansible run on the Matrix server itsel
-  Ansible version : ansible [core 2.16.5]

**Error log when running this playbook**
```bash
TASK [galaxy/auxiliary : Ensure AUX files are created] **********************************************************************************************************************************************************
failed: [matrix.home.xyz] (item=/matrix/traefik/ssl/privkey.pem) => changed=false 
  ansible_loop_var: item
  checksum: 4917c478605647a57e04f5a390956b9ed4c0f0fe
  item:
    dest: /matrix/traefik/ssl/privkey.pem
    src: /home/ubuntu/projects/matrix-docker-ansible-deploy/ssl/privkey.pem
  msg: Destination directory /matrix/traefik/ssl does not exist
failed: [matrix.home.xyz] (item=/matrix/traefik/ssl/cert.pem) => changed=false 
  ansible_loop_var: item
  checksum: dd3414805da92df7f434d8e815c628969c3ef6d2
  item:
    dest: /matrix/traefik/ssl/cert.pem
    src: /home/ubuntu/projects/matrix-docker-ansible-deploy/ssl/cert.pem
  msg: Destination directory /matrix/traefik/ssl does not exist
failed: [matrix.home.xyz] (item=/matrix/traefik/config/certificates.yml) => changed=false 
  ansible_loop_var: item
  checksum: 50550a5ace0de7a63f286a5da5bbd00a9cea5d2c
  item:
    content: |-
      tls:
        certificates:
          - certFile: /ssl/cert.pem
            keyFile: /ssl/privkey.pem
        stores:
          default:
            defaultCertificate:
              certFile: /ssl/cert.pem
              keyFile: /ssl/privkey.pem
    dest: /matrix/traefik/config/certificates.yml
  msg: Destination directory /matrix/traefik/config does not exist
PLAY RECAP ******************************************************************************************************************************************************************************************************
matrix.home.xyz            : ok=226  changed=95   unreachable=0    failed=1    skipped=313  rescued=0    ignored=0 
```
