### ISSUE TITLE
Unified Push (NextPush) Notifications not working

### ISSUE THREAD

**Issue by Wave6677** [spantaleev/matrix-docker-ansible-deploy#3305]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
#---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: mydomain.tld

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'googoogaagaa'

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
#matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_reverse_proxy_type: other-traefik-container

# Uncomment and adjust if your Traefik container is on another network
matrix_playbook_reverse_proxy_container_network: jame

# Adjust to point to your Traefik container
matrix_playbook_reverse_proxy_hostname: traefik

devture_traefik_certs_dumper_ssl_dir_path: "/traefik/certs"

# Uncomment and tweak the variable below if the name of your federation entrypoint is different
# than the default value (matrix-federation).
# matrix_federation_traefik_entrypoint_name: matrix-federation
# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: 'matrix@mydomain.tld'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'googoogaagaa'

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''
exim_relay_sender_address: "matrix@mydomain.tld"
exim_relay_relay_use: true
exim_relay_relay_host_name: "mail.mydomain.tld"
exim_relay_relay_host_port: 587
exim_relay_relay_auth: true
exim_relay_relay_auth_username: "googoogaagaa"
exim_relay_relay_auth_password: "googoogaagaa!"
matrix_bot_matrix_registration_bot_enabled: true

# By default, the playbook will set use the bot with a username like this: `@bot.matrix-registration-bot:DOMAIN`.
# To use a different username, uncomment & adjust the variable below:
# matrix_bot_matrix_registration_bot_matrix_user_id_localpart: bot.matrix-registration-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_registration_bot_bot_password: googoogaagaa

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true
matrix_synapse_admin_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: googoogaagaa
jitsi_enabled: true

# Uncomment and adjust if you need to use another hostname
# jitsi_hostname: "jitsi.{{ matrix_domain }}"

# Uncomment and possible adjust if you'd like to host under a subpath
# jitsi_path_prefix: /jitsi
etherpad_enabled: true

# Uncomment below to enable the admin web UI
# etherpad_admin_username: admin
# etherpad_admin_password: some-password
#matrix_mautrix_facebook_enabled: true
#matrix_mautrix_facebook_configuration_extension_yaml: |
#  bridge:
#    permissions:
#      'googoogaagaa:mydomain.tld': admin
#    encryption:
#      allow: true
#      default: true
#matrix_mautrix_instagram_enabled: true
matrix_admin: "googoogaagaa:mydomain.tld"
#matrix_mautrix_instagram_configuration_extension_yaml: |
#  bridge:
#    encryption:
#      allow: true
#      default: true
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: googoogaagaa
matrix_mautrix_telegram_api_hash: googoogaagaa
matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_bridge_permissions: |
  {{
    {'*': 'relay', matrix_mautrix_discord_homeserver_domain: 'user',
    '@googoogaagaa:matrix.org': 'user'}
    | combine({matrix_admin: 'admin'} if matrix_admin else {})
  }}

matrix_mautrix_signal_enabled: true
matrix_mx_puppet_steam_enabled: true
matrix_mx_puppet_steam_provisioning_whitelist:
  - "@.*:{{ matrix_domain | regex_escape }}"
  - '@googoogaagaa:matrix.org'
matrix_synapse_auto_compressor_enabled: true
matrix_sliding_sync_enabled: true
matrix_beeper_linkedin_enabled: true
matrix_beeper_linkedin_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
matrix_appservice_discord_enabled: true
matrix_appservice_discord_client_id: "googoogaagaa"
matrix_appservice_discord_bot_token: "googoogaagaa"
matrix_synapse_configuration_extension_yaml: |
  use_appservice_legacy_authorization: true
matrix_appservice_discord_bridge_enableSelfServiceBridging: true
matrix_bot_maubot_enabled: true
matrix_bot_maubot_admins:
  - googoogaagaa: googoogaagaa
matrix_media_repo_enabled: true
# (optional) Turned off by default
# matrix_media_repo_metrics_enabled: true
matrix_client_cinny_enabled: true
backup_borg_enabled: false
#backup_borg_location_repositories:
#backup_borg_storage_encryption_passphrase: 
#backup_borg_ssh_key_private: |
matrix_mautrix_meta_instagram_enabled: true
matrix_mautrix_meta_instagram_bridge_permissions_default:
  '*': relay
  'mydomain.tld': user
  '@googoogaagaa7:matrix.org': user
  'googoogaagaa:mydomain.tld': admin
matrix_mautrix_meta_messenger_enabled: true
matrix_mautrix_meta_messenger_bridge_permissions_default:
  '*': relay
  'mydomain.tld': user
  '@googoogaagaa7:matrix.org': user
  'googoogaagaa:mydomain.tld': admin
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_bridge_relay_enabled: true
matrix_mautrix_whatsapp_bridge_relay_admin_only: false
matrix_mautrix_whatsapp_bridge_permissions: |
  {{
    {'*': 'relay', matrix_mautrix_whatsapp_homeserver_domain: 'user',
    '@googoogaagaa:matrix.org': 'user'}
    | combine({matrix_admin: 'admin'} if matrix_admin else {})
  }}

```

**Matrix Server:**
 - OS: Fedora 39
 - Architecture amd64

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

**Client (please complete the following information):**
 - Device: Google Pixel 6
 - OS: CalyxOS
 - Browser Mull 124.2.0/Element 1.6.12 /ElementX 0.4.6

**Additional context**
I asked in the matrix room first so I'm going to copy paste the message I sent there
Hi, I'm having some trouble with push notifications for my server and I was wondering if Anyone could help me out here. Its an android only issue, and it happens on devices without Google services which are either using UnifiedPush through NextPush or using Background Synchronization. The devices are failing to get any kind of push notifications unless the app is running on the screen, currently open. Otherwise, I get no notifications for new messages at all. I dont have ntfy enabled in playbook because I'm using NextPush, does ntfy need to be enabled for UP to work or is there a separate issue?
