### ISSUE TITLE
Self-signed certificates in external services

### ISSUE THREAD

**Issue by Hedgehog57** [spantaleev/matrix-docker-ansible-deploy#331]
Hello!

Thanks for a perfect playbook.

I am stuck with one thing and don't know what to do. We have AD LDAP servers and want to communicate with then by LDAPS. After configuring mxisd and synapse we cannot login in the system because of LDAPS certificate errors (self-signed certificates).
Changing to LDAP and disabling TLS allow us to pass authorization in synapse.

When it is installed on standart system w/o docker i can do one two things

1. add CA certificates to openssl and this will work in python
2. disable certification validation in python (bad idea, i know)

But what can we do in docker? Only make a fork of synapse image and modify dockerfile? Or there is some mechanism i didn't find?

Will much appreciate for any ideas.

**Comment by spantaleev** [comment]
You could make your own Synapse image and use that one. But you'd need to keep it updated, which is a bit annoying.

Another, possibly better, option might be to prepare the certificates directory on the host and mount it in the Synapse container (to `/etc/ssl` or wherever it needs to be). You can use the `matrix_synapse_container_additional_volumes` or `matrix_synapse_container_extra_arguments` variables to do that. You can read the documentation about those variables in `roles/matrix-synapse/defaults/main.yml`. Doing that, you'd be using the latest image (as defined by the playbook) and won't need to worry about keeping anything in sync.

**Comment by daudo** [comment]
Reawakening this a bit old post, as we've been hit by this issue as well.

The problem is not with the Synapse but the mxisd image (that has reached EOL btw, see https://github.com/kamax-matrix/mxisd/blob/master/EOL.md#end-of-life-notice).

mxisd is a Java application, so the "right" way to do it is to populate Java's keystore accordingly.

Are you interested in a PR for the mxisd role?

**Comment by spantaleev** [comment]
We know it's EOL and are considering adding [ma1sd](https://github.com/ma1uta/ma1sd) as an alternative. See #333.

If you've got time and would like to fix things for mxisd, it would probably be useful in the future for the ma1ds role as well. A pull request would be welcome! :)

**Comment by razzeee** [comment]
trying to use `matrix_synapse_container_additional_volumes` as @spantaleev recommended, I'm running into the cert not being enrolled I think?

At least when I curl the endpoint from inside of the docker container, it's not happy.

So I've tried running this, which fails:

```sh
$ update-ca-certificates
Updating certificates in /etc/ssl/certs...
/usr/sbin/update-ca-certificates: 101: cannot create /etc/ssl/certs/ca-certificates.crt.new: Read-only file system
```

But mounts with `docker container inspect` seem fine to me?

```yml
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/matrix/synapse/config",
                    "Target": "/data",
                    "ReadOnly": true
                },
                {
                    "Type": "bind",
                    "Source": "/matrix/synapse/storage",
                    "Target": "/matrix-media-store-parent",
                    "BindOptions": {
                        "Propagation": "slave"
                    }
                },
                {
                    "Type": "bind",
                    "Source": "/home/matrix-deploy/root-cert/",
                    "Target": "/usr/local/share/ca-certificates/"
                },
                {
                    "Type": "bind",
                    "Source": "/matrix/hookshot/registration.yml",
                    "Target": "/hookshot-registration.yml",
                    "ReadOnly": true
                }
            ],

```
