### ISSUE TITLE
Failed services are not detected as stopped

### ISSUE THREAD

**Issue by Geosearchef** [spantaleev/matrix-docker-ansible-deploy#3318]
**Describe the bug**
I wanted to update my installation from July 2023 to the current version. After reading through the changelog and adapting a few variables, everything seemed to work smoothly.

When trying to remove matrix-synapse-reverse-proxy-companion.service, the playbook froze and didn't continue. The same occured with the mautrix-facebook and and mautrix-whatsapp services.

Looking at the systemd, it seems those services didn't terminate with an exit code of 0 and were marked as failed by systemd.
Clearing this using `systemctl reset-failed [service]` and rerunning the playbook resolved the issue. 

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: matrix.xxxx
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: ''
devture_postgres_connection_password: ''

matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: matrixserver@domain.de

matrix_synapse_allow_public_rooms_over_federation: false

matrix_client_element_themes_enabled: true

matrix_static_files_container_labels_base_domain_enabled: true
matrix_static_files_file_index_html_enabled: false

matrix_synapse_admin_enabled: true

matrix_registration_enabled: true
matrix_registration_admin_secret: ""

# ---------------------
# shared secret auth - requried for double puppeting
# ---------------------
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: abcabcabc

jitsi_enabled: false

matrix_mautrix_telegram_enabled: false
matrix_mautrix_telegram_api_id: 1234567
matrix_mautrix_telegram_api_hash: 1234567
matrix_mautrix_telegram_bot_token: 123456789
matrix_mautrix_telegram_configuration_extension_yaml: |
  ...

matrix_mautrix_whatsapp_enabled: false
matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true
    enable_status_broadcast: false
    relay:
      enabled: true
    permissions:
      ...

matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true

matrix_mautrix_facebook_enabled: false
matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    permissions:
      ...

```

This occured during the transition from a nginx based setup to the native-traefik setup.

**Expected behavior**
The playbook should proceed removing the service after it failing on stop, as it is due for removal anyway.

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture: x86_64

**Ansible:**
Ansible is running on a different machine.
```
ansible [core 2.16.6]
  config file = None
  configured module search path = ['/home/geosearchef/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/geosearchef/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/geosearchef/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

**Additional context**
I'm currently also hitting a problem with the playbook sometimes not being able to verify the successful completion of a task. I randomly hangs on:

```
TASK [custom/matrix-static-files : Ensure matrix-static-files container image is pulled]

TASK [custom/matrix-registration : Ensure matrix-registration image is pulled]

TASK [custom/matrix-synapse-reverse-proxy-companion : Ensure matrix-synapse-reverse-proxy-companion.service is stopped]

TASK [galaxy/synapse : Ensure synapse container network is created]

TASK [galaxy/postgres : Ensure Postgres container network is created]
```

Even when those tasks have already been successful. Not sure if this is related though. I also noticed that these are all Docker specific tasks.
