### ISSUE TITLE
Ensure Postgres systemd service installed - ansible_processor_nproc'' is undefined

### ISSUE THREAD

**Issue by Silfer2024** [spantaleev/matrix-docker-ansible-deploy#3334]
Hello ... SOS....

**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: blabla.de

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'rdKx7483838rU^Vnj&F#gt6'

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: 'blabla@blabla.de'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'HAdWHr@WHt8T9VfE0815'

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''

```

**Matrix Server:**
 - Debian 11
 - amd64

**Problem description**:

Hello community, unfortunately I get the following error when installing:

`TASK [galaxy/postgres : Ensure Postgres systemd service installed] **********************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: {{ devture_postgres_postgres_process_extra_arguments_auto + devture_postgres_postgres_process_extra_arguments_custom }}: ["-c 'max_connections={{ devture_postgres_max_connections|int }}'", "-c 'shared_buffers={{ (devture_postgres_shared_buffers|int/1024)|int }}MB'", "-c 'effective_cache_size={{ (devture_postgres_effective_cache_size|int/1024)|int }}MB'", "-c 'maintenance_work_mem={{ (devture_postgres_maintenance_work_mem|int/1024)|int }}MB'", "-c 'checkpoint_completion_target={{ devture_postgres_checkpoint_completion_target }}'", "-c 'wal_buffers={{ (devture_postgres_wal_buffers|int/1024)|int }}MB'", "-c 'default_statistics_target={{ devture_postgres_default_statistics_target|int }}'", "-c 'random_page_cost={{ devture_postgres_random_page_cost }}'", "-c 'effective_io_concurrency={{ devture_postgres_effective_io_concurrency|int }}'", "-c 'work_mem={{ devture_postgres_work_mem|int }}kB'", "-c 'huge_pages={{ devture_postgres_huge_pages }}'", "-c 'min_wal_size={{ (devture_postgres_min_wal_size|int/1024)|int }}MB'", "-c 'max_wal_size={{ (devture_postgres_max_wal_size|int/1024)|int }}MB'", "-c 'max_worker_processes={{ devture_postgres_max_worker_processes|int }}'", "-c 'max_parallel_workers={{ devture_postgres_max_parallel_workers|int }}'", "-c 'max_parallel_workers_per_gather={{ devture_postgres_max_parallel_workers_per_gather|int }}'", "-c 'max_parallel_maintenance_workers={{ devture_postgres_max_parallel_maintenance_workers|int }}'"]: {{ 64 if devture_postgres_work_mem_raw|int <= 64 else devture_postgres_work_mem_raw|int }}: {{ ((devture_postgres_memtotal_kb|int - devture_postgres_shared_buffers|int)/(devture_postgres_max_connections|int*3))/devture_postgres_max_parallel_workers_per_gather|int }}: {{ (4 if ansible_processor_nproc/2 > 4 else ansible_processor_nproc|int/2) | round(0, 'ceil') | int }}: 'ansible_processor_nproc' is undefined
fatal: [matrix.schreibnoma.de]: FAILED! => changed=false
  msg: 'AnsibleUndefinedVariable: {{ devture_postgres_postgres_process_extra_arguments_auto + devture_postgres_postgres_process_extra_arguments_custom }}: ["-c ''max_connections={{ devture_postgres_max_connections|int }}''", "-c ''shared_buffers={{ (devture_postgres_shared_buffers|int/1024)|int }}MB''", "-c ''effective_cache_size={{ (devture_postgres_effective_cache_size|int/1024)|int }}MB''", "-c ''maintenance_work_mem={{ (devture_postgres_maintenance_work_mem|int/1024)|int }}MB''", "-c ''checkpoint_completion_target={{ devture_postgres_checkpoint_completion_target }}''", "-c ''wal_buffers={{ (devture_postgres_wal_buffers|int/1024)|int }}MB''", "-c ''default_statistics_target={{ devture_postgres_default_statistics_target|int }}''", "-c ''random_page_cost={{ devture_postgres_random_page_cost }}''", "-c ''effective_io_concurrency={{ devture_postgres_effective_io_concurrency|int }}''", "-c ''work_mem={{ devture_postgres_work_mem|int }}kB''", "-c ''huge_pages={{ devture_postgres_huge_pages }}''",
    "-c ''min_wal_size={{ (devture_postgres_min_wal_size|int/1024)|int }}MB''", "-c ''max_wal_size={{ (devture_postgres_max_wal_size|int/1024)|int }}MB''", "-c ''max_worker_processes={{ devture_postgres_max_worker_processes|int }}''", "-c ''max_parallel_workers={{ devture_postgres_max_parallel_workers|int }}''", "-c ''max_parallel_workers_per_gather={{ devture_postgres_max_parallel_workers_per_gather|int }}''", "-c ''max_parallel_maintenance_workers={{ devture_postgres_max_parallel_maintenance_workers|int }}''"]: {{ 64 if devture_postgres_work_mem_raw|int <= 64 else devture_postgres_work_mem_raw|int }}: {{ ((devture_postgres_memtotal_kb|int - devture_postgres_shared_buffers|int)/(devture_postgres_max_connections|int*3))/devture_postgres_max_parallel_workers_per_gather|int }}: {{ (4 if ansible_processor_nproc/2 > 4 else ansible_processor_nproc|int/2) | round(0, ''ceil'') | int }}: ''ansible_processor_nproc'' is undefined'
`

I followed the instructions exactly. I've been having this error for hours and can't find a solution.
I'm already grateful for your help.

Greets Silfer
