### ISSUE TITLE
Federation issue + possible fix

### ISSUE THREAD

**Issue by Black616Angel** [spantaleev/matrix-docker-ansible-deploy#3335]
**Describe the bug**
Federation on our server was not correctly working due to the .well-known-files returning a 404 error on the main domain.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
# general
matrix_domain: matrix-cyb.org
matrix_homeserver_implementation: synapse

# A secret used to protect access keys issued by the server. You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "secret"
matrix_ma1sd_enabled: false
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_sliding_sync_enabled: true

# A shared secret (between Coturn and Synapse) used for authentication. You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "secret"

matrix_synapse_admin_enabled: true
# shared secret
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "secret"


# federation
matrix_homeserver_federation_enabled: true
matrix_synapse_allow_public_rooms_over_federation: true

# traefik
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: secret@example.com

#Postgres
devture_postgres_connection_password: 'secret'

# telegram
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: 2255250
matrix_mautrix_telegram_api_hash: hash(not really)

#signal
matrix_mautrix_signal_enabled: true

# whatsapp
matrix_mautrix_whatsapp_enabled: true

# facebook
matrix_mautrix_facebook_enabled: true

# hangouts
matrix_mautrix_hangouts_enabled: true

# static-files
matrix_static_files_container_http_host_bind_port: 8443
matrix_static_files_environment_variable_server_port: 8080

# jitsi
jitsi_enabled: true
jitsi_jicofo_component_secret: secret
jitsi_jicofo_auth_password: secret
jitsi_jvb_auth_password: secret
jitsi_jibri_recorder_password: secret
jitsi_jibri_xmpp_password: secret
jitsi_enable_auth: true
jitsi_enable_guests: true
jitsi_prosody_auth_internal_accounts:
  - username: "jitsi-admin"
    password: "secret"

jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
    config.disableAudioLevels = true;
    config.channelLastN = 4;

jitsi_web_config_resolution_width_ideal_and_max: 1280
jitsi_web_config_resolution_height_ideal_and_max: 720
```

**Expected behavior**
The URL https://matrix-cyb.org/.well-known/matrix/server should return a file and not the URL matrix.DOMAIN/... 
with the current setup static files is designed in a way, that publicizes these files under matrix.DOMAIN, which borks federation.

**Additional context**
Okay, now to my supposed fix:
in the file /group_vars/matrix_servers
replace line 5166:
```yaml
matrix_static_files_container_labels_well_known_matrix_endpoint_traefik_hostname: "{{ matrix_server_fqn_matrix }}"
```

with 
```yaml
matrix_static_files_container_labels_well_known_matrix_endpoint_traefik_hostname: "{{ matrix_domain }}"
```

I can make this a new PR, but this is such a small fix, and I don't even know, if it is up to the matrix-specs, but it did work for our server to re-federate with the 3+ servers we regularly chat with.
