### ISSUE TITLE
Synapse server occasionally suddenly unresponsive

### ISSUE THREAD

**Issue by Vincent-appinco** [spantaleev/matrix-docker-ansible-deploy#3343]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: REDACTED
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: REDACTED
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: REDACTED
devture_postgres_connection_password: REDACTED
matrix_synapse_workers_enabled: true
matrix_synapse_admin_enabled: true
matrix_synapse_presence_enabled: false
etherpad_enabled: false
```

**Matrix Server:**
- Hetzner CAX11 ARM 4GB 2vCPU node with Debian
- There's in total only 3 users on the server with little to no activity

**Problem description**:

For a good amount of time everything ran perfectly smoothly with no issues whatsoever without updating. Recently however all of the sudden the synapse server would become unresponsive and all connected clients would be disconnected. Rebooting the server solved it for some time until it happens more and more often. I didn't see any signs of malicious intrusion or rogue processes so I updated to latest version and experience the same issue still. Usually I notice the CPU/disk exploding when this happens but believe I've seen the issue on normal CPU/disk load as well.

How can I find out what's causing this and/or what is recommended to solve this?

![image](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/125973996/48c3d132-e266-4d1a-9050-dabbc0542a8f)

![image](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/125973996/a60ad983-b3fd-41d4-822f-cdeb48366365)
