### ISSUE TITLE
Enabling matrix-media-repo for an arm64 server results in the wrong architecture being installed

### ISSUE THREAD

**Issue by churipputori** [spantaleev/matrix-docker-ansible-deploy#3349]
**Describe the bug**
When installing matrix-media-repo on an arm64 server, the playbook will install the amd64 image instead of the arm64 image. Journalctl shows this log:
```
systemd[1]: Starting Matrix media-repo...
matrix-media-repo[1432888]: WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
matrix-media-repo[1432888]: 88d562d3dd0ef9b4b73b0af695ed3c3ad0d9de900eb0eff16b7256f83786ceac
systemd[1]: Started Matrix media-repo.
matrix-media-repo[1432909]: exec /usr/local/bin/media_repo: exec format error
systemd[1]: matrix-media-repo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: matrix-media-repo.service: Failed with result 'exit-code'.
```
**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: <private>
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: <private>
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: <private>
devture_postgres_connection_password: <private>
devture_postgres_backup_enabled: true
matrix_static_files_container_labels_base_domain_enabled: true
matrix_synapse_admin_enabled: true
matrix_synapse_allow_public_rooms_over_federation: false
matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: little-federation-helper
matrix_sliding_sync_enabled: true
matrix_media_repo_enabled: true
matrix_bot_matrix_registration_bot_enabled: true
matrix_bot_matrix_registration_bot_bot_password: <private>
matrix_synapse_enable_registration: true
matrix_synapse_registration_requires_token: true
matrix_mautrix_discord_enabled: false
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: <private>
devture_systemd_service_manager_up_verification_delay_seconds: 120
```

Run `just setup-all`, wait for it to complete, then run `journalctl -fu matrix-media-repo.service`

**Expected behavior**

**Matrix Server:**
 - OS: Ubuntu 22.04.4 LTS
 - Architecture: arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible: another computer (Debian 12, amd64)
- what version of Ansible you're running: 2.16.7
