### ISSUE TITLE
Wechat bot will not respond

### ISSUE THREAD

**Issue by Korben57** [spantaleev/matrix-docker-ansible-deploy#3352]
**Describe the bug**
The WeChat bot will only respond on a DM, but will reply with:

🔒 This bridge has not been configured to support encryption

If you message it on a NON encrypted room (not DM) it refuses to respond at all

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: XXXXX.au

matrix_homeserver_implementation: synapse

matrix_homeserver_generic_secret_key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

devture_traefik_config_certificatesResolvers_acme_email: 'XXXXXXXXXX@gmail.com'

devture_postgres_connection_password: 'XXXXXXX'

matrix_synapse_admin_enabled: true

matrix_sliding_sync_enabled: true

matrix_bot_maubot_enabled: true
matrix_bot_maubot_admins:
  - k: XXXXXXXXX

matrix_static_files_container_labels_base_domain_enabled: true

matrix_wechat_enabled: true
```

**Expected behavior**
Add WeChat bot, try to create a non encrypted room, message bot, don't get reply

**Matrix Server:**
 - OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-107-generic x86_64)

**Additional context**

This screenshot is the DM

![DM](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/131165103/de6a58e8-a0ea-4b33-9faf-593f12d91565)

This is a standard room without encryption

![Room created without Encryption](https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/131165103/1c00fcb2-c11e-4cbd-83d4-4c04f5152e88)

The bot is an Admin in both rooms
