### ISSUE TITLE
Federation not working/ 404 Page not found / Playbook Error 

### ISSUE THREAD

**Issue by DeansTagLab** [spantaleev/matrix-docker-ansible-deploy#3355]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
Paste your vars.yml file here.

matrix_domain: chatprivat.de
matrix_static_files_container_labels_base_domain_enabled: false
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
devture_traefik_config_certificatesResolvers_acme_email: '****'

devture_traefik_dashboard_enabled: true
devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
devture_traefik_dashboard_basicauth_enabled: true
devture_traefik_dashboard_basicauth_user: test
devture_traefik_dashboard_basicauth_password: test

matrix_synapse_federation_enabled: true
matrix_coturn_turn_static_auth_secret: '****'
matrix_synapse_macaroon_secret_key: '****'

matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"

devture_postgres_connection_password: '****'

#Matrix Registration Bot
matrix_bot_matrix_registration_bot_enabled: true

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_registration_bot_bot_password: '****'

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true

# Matrix Mail
exim_relay_sender_address: "****"
exim_relay_relay_use: true
exim_relay_relay_host_name: "****"
exim_relay_relay_host_port: 587
exim_relay_relay_auth: true
exim_relay_relay_auth_username: "****"
exim_relay_relay_auth_password: "****"


# Synapse Admin
matrix_synapse_admin_enabled: true


# Synapse Shared Secret
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: ****


# Add Whatsapp
matrix_mautrix_whatsapp_enabled: true
```

**Matrix Server:**
 - OS: Ubuntu 18.04
 - Architecture [x64]
 - VPS Cloud Server

**Ansible:**
If your problem appears to be with Ansible, tell us:
- Ansible is running on a virtual server at home
- Ubuntu 20.04
- Ansibel: Core 2.11.9
- python version = 3.8.10
- jinja version = 3.1.2

**Problem description**:

My federation to other server isn't working any more.
Also trying to open my base domain gives me a 404 page not found error.
The same for the federation tester.

When running my playbook I'm getting the following error:

```
s_push: parser stack overflow
fatal: [matrix.chatprivat.de]: FAILED! =>
  msg: |-
    The conditional check 'devture_systemd_service_manager_services_list_to_work_with | length > 0' failed. The error was: An unhandled exceptce_manager_services_list }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templ_auto + devture_systemd_service_manager_services_list_additional }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Uneystemd_service_manager_services_list_auto + devture_systemd_service_manager_services_list_additional }}): can only concatenate str (not "list"

    The error appears to be in '/home/matrixadmin/matrix-docker-ansible-deploy/roles/galaxy/systemd_service_manager/tasks/restart_specified.ym
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - when: devture_systemd_service_manager_services_list_to_work_with | length > 0
      ^ here

PLAY RECAP ***********************************************************************************************************************************
 
```

Hope someone has any idea
