### ISSUE TITLE
Importing an existing Postgres database from another installation

### ISSUE THREAD

**Issue by Podolyan98** [spantaleev/matrix-docker-ansible-deploy#3356]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: localhost
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'password'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: 'example@example.com'
devture_traefik_config_entrypoint_web_secure_enabled: false
devture_postgres_connection_password: '12345'
devture_postgres_container_image_latest: "{{ devture_postgres_container_image_v14 }}"
```

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Ansible: 2.16.6

**Problem description**:

I'm trying to restore a Postgres 14 dump:

```
just run-tags import-postgres \
--extra-vars=server_path_postgres_dump=/home/alex/matrix/matrix/postgres-backup/data/last/synapse-20240504-000000.sql.gz \
--extra-vars=postgres_default_import_database=synapse
```

But there was an error:

```
TASK [galaxy/postgres : Note about Postgres importing alternative] *************************************************************************************************************************************************
ok: [localhost] => (item=Importing Postgres database using the following command: `/usr/bin/env docker run --rm --name matrix-postgres-import --log-driver=none --user=998:1001 --cap-drop=ALL --network=matrix-postgres --env-file=/matrix/postgres/env-postgres-psql --mount type=bind,src=/home/alex/matrix/matrix/postgres-backup/data/last/synapse-20240504-000000.sql.gz,dst=/synapse-20240504-000000.sql.gz,ro --entrypoint=/bin/sh docker.io/postgres:14.10-alpine -c "set -o pipefail && cat /synapse-20240504-000000.sql.gz | gunzip | grep -vE '^(CREATE|ALTER) ROLE \"?(matrix|synapse)\"?(;| WITH)' | grep -vE '^CREATE DATABASE \"?(matrix|synapse)\"?\s' | psql -b -v ON_ERROR_STOP=1 -h matrix-postgres --dbname=synapse"`. If this crashes, you can stop Postgres (`systemctl stop matrix-postgres`), delete its existing data (`rm -rf /matrix/postgres/data/*`), start it again (`systemctl start matrix-postgres`) and manually run the above import command directly on the server.)

TASK [galaxy/postgres : Perform Postgres database import] **********************************************************************************************************************************************************
ASYNC FAILED on localhost: jid=j686047333300.50053
fatal: [localhost]: FAILED! => changed=false
  ansible_job_id: j686047333300.50053
  cmd:
  - /usr/bin/env
  - docker
  - run
  - --rm
  - --name
  - matrix-postgres-import
  - --log-driver=none
  - --user=998:1001
  - --cap-drop=ALL
  - --network=matrix-postgres
  - --env-file=/matrix/postgres/env-postgres-psql
  - --mount
  - type=bind,src=/home/alex/matrix/matrix/postgres-backup/data/last/synapse-20240504-000000.sql.gz,dst=/synapse-20240504-000000.sql.gz,ro
  - --entrypoint=/bin/sh
  - docker.io/postgres:14.10-alpine
  - -c
  - set -o pipefail && cat /synapse-20240504-000000.sql.gz | gunzip | grep -vE '^(CREATE|ALTER) ROLE "?(matrix|synapse)"?(;| WITH)' | grep -vE '^CREATE DATABASE "?(matrix|synapse)"?\s' | psql -b -v ON_ERROR_STOP=1 -h matrix-postgres --dbname=synapse
  delta: '0:00:06.567299'
  end: '2024-06-07 09:26:02.157598'
  failed_when_result: true
  finished: 1
  msg: non-zero return code
  rc: 3
  results_file: /root/.ansible_async/j686047333300.50053
  start: '2024-06-07 09:25:55.590299'
  started: 1
  stderr: |-
    ERROR:  schema "public" already exists
    STATEMENT:  CREATE SCHEMA public;
  stderr_lines: <omitted>
  stdout: |-
    SET
    SET
    SET
    SET
    SET
     set_config
    ------------

    (1 row)

    SET
    SET
    SET
    SET
  stdout_lines: <omitted>
```

I also tried repeating the import, but it didn't help:

```
sudo systemctl stop matrix-postgres
sudo rm -rf /matrix/postgres/data/*
sudo systemctl start matrix-postgres
just run-tags setup-postgres
```
