### ISSUE TITLE
Jitsi playbook don't change meet.element.io

### ISSUE THREAD

**Issue by ZelChief** [spantaleev/matrix-docker-ansible-deploy#3358]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: mydomain.com
matrix_base_data_path: "/srv/matrix"
matrix_synapse_storage_path: "/srv/synapse-storage"
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'rkfao********'

matrix_registration_enabled: false

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# Ensure that public urls use https
matrix_playbook_ssl_enabled: true

jitsi_enabled: true

jitsi_enable_auth: true
jitsi_auth_type: matrix

jitsi_web_stun_servers:
- stun:coturn.mydomain.com:3478

jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=192.168.1.**"'


jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
  config.disableAudioLevels = true;
  config.channelLastN = 4;

jitsi_web_config_resolution_width_ideal_and_max: 720
jitsi_web_config_resolution_height_ideal_and_max: 480
jitsi_prosody_max_participants: 10

matrix_coturn_authentication_method: lt-cred-mech

matrix_coturn_tls_enabled: true
#matrix_coturn_turn_static_auth_secret: 'f4105******'
matrix_coturn_turn_external_ip_address: "146.*******"
matrix_synapse_turn_uris:
- turns:coturn.mydomain.com?transport=udp
- turns:coturn.mydomain.com?transport=tcp
- turn:coturn.mydomain.com?transport=udp
- turn:coturn.mydomain.com?transport=tcp

```

**Matrix Server:**
 - OS: Debian 12
 - Architecture: amd64

**Problem description**:

Element clients (web, macOS, iOS) still using https://meet.element.io. Is there [the way to configuring Element to use your self-hosted Jitsi server](https://github.com/element-hq/element-web/blob/develop/docs/jitsi.md)?
