### ISSUE TITLE
Playbook fails with "unrecognized arguments" when upgrading to synapse 1.110 on task custom/matrix-user-creator

### ISSUE THREAD

**Issue by baskinsy** [spantaleev/matrix-docker-ansible-deploy#3393]
**Describe the bug**
After today's git pull to upgrade to synapse 1.110, playbook fails on 

```
TASK [custom/matrix-user-creator : Ensure Synapse user registered - bot.matrix-registration-bot]
```

with this error:

```
fatal: [matrix.example.com]: FAILED! => changed=false 
  cmd:
  - /usr/bin/env
  - docker
  - exec
  - matrix-synapse
  - register_new_matrix_user
  - -u
  - bot.matrix-registration-bot
  - -p
  - XXXXXXXXXXXXX
  - -c
  - /data/homeserver.yaml
  - --admin
  - --exists-ok
  - http://localhost:8008
  delta: '0:00:01.596653'
  end: '2024-07-04 09:37:37.505576'
  msg: non-zero return code
  rc: 2
  start: '2024-07-04 09:37:35.908923'
  stderr: |-
    usage: register_new_matrix_user [-h] [-u USER] [-p PASSWORD] [-t USER_TYPE]
                                    [-a | --no-admin]
                                    (-c CONFIG | -k SHARED_SECRET)
                                    [server_url]
    register_new_matrix_user: error: unrecognized arguments: --exists-ok
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
  ```

**To Reproduce**
My `vars.yml` file looks like this and has no change since the last successful run.

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: example.com

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse
matrix_base_data_path: "/mnt/HC_Volume_28526776/matrix"

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'XXXXXXXXXXXXXX'

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: 'mail@example.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'XXXXXXXXX'

# Enable synapse admin
matrix_synapse_admin_enabled: true

# Enable dimension integration
matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@dimension:example.com"
matrix_dimension_access_token: "XXXXXXXXXXXX"

# Enable registration bot
matrix_bot_matrix_registration_bot_enabled: true
#By default, the playbook will set use the bot with a username like 
## this: `@bot.matrix-registration-bot:DOMAIN`.
# To use a different username, uncomment & adjust the variable.
# matrix_bot_matrix_registration_bot_matrix_user_id_localpart: bot.matrix-registration-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_registration_bot_bot_password: XXXXXXXXXXXXXXX

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true

exim_relay_sender_address: "matrix@example.com"
exim_relay_relay_use: true
exim_relay_relay_host_name: "smtp.example.com"
exim_relay_relay_host_port: 587
exim_relay_relay_auth: true
exim_relay_relay_auth_username: "postmaster@mg.example.com"
exim_relay_relay_auth_password: "XXXXXXXXXXXXXXX"

# Enable matrix to skype bridge
matrix_go_skype_bridge_enabled: false

# Enable matrix to whatsapp bridge
matrix_mautrix_whatsapp_enabled: true

# Postgresql tunning
devture_postgres_process_extra_arguments: [
  "-c shared_buffers=256MB",
  "-c effective_cache_size=768MB",
  "-c effective_io_concurrency=200",
  "-c random_page_cost=1.1",
  "-c min_wal_size=1GB",
  "-c max_wal_size=4GB",
  "-c max_connections=200",
  "-c maintenance_work_mem=64MB",
  "-c checkpoint_completion_target=0.9",
  "-c wal_buffers=7864kB",
  "-c default_statistics_target=100",
  "-c work_mem=655kB",
]

# Maubot enable and config
matrix_bot_maubot_enabled: true
matrix_bot_maubot_admins:
  - user: XXXXXXXX
matrix_bot_maubot_initial_password: XXXXXXXXXXX

# Switch to traefic as reverse proxy
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# Enable Telemetry
matrix_synapse_report_stats: true

# Enable Shared Secret Auth
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: XXXXXXXXXXXXX
# Enable Sliding Sync Proxy
matrix_sliding_sync_enabled: true

# Enable Synapse auto compressor
matrix_synapse_auto_compressor_enabled: true

# Enable matrix bot chatgpt
#matrix_bot_chatgpt_enabled: true

# Obtain a new API key from https://platform.openai.com/account/api-keys
#matrix_bot_chatgpt_openai_api_key: ''

# This is the default username
#matrix_bot_chatgpt_matrix_bot_username_localpart: 'bot.chatgpt'

# Matrix access token (from bot user above)
# see: https://webapps.stackexchange.com/questions/131056/how-to-get-an-access-token-for-element-riot-matrix
#matrix_bot_chatgpt_matrix_access_token: 'XXXXXXXXXXXXXXXXX'

# Configuring the system promt used, needed if the bot is used for special tasks.
# More information: https://github.com/mustvlad/ChatGPT-System-Prompts
#matrix_bot_chatgpt_matrix_bot_prompt_prefix: 'Instructions:\nYou are ChatGPT, a large language model trained by OpenAI.'

# (Optional) You can change the api url to use another (OpenAI-compatible) API endpoint
#matrix_bot_chatgpt_reverse_proxy: https://example.com

# Enable Mautrix Discord
matrix_mautrix_discord_enabled: false

# Enable ma1sd Identity Server
matrix_ma1sd_enabled: true

# Enable Instagram bridging via Mautrix Meta
matrix_mautrix_meta_instagram_enabled: true
matrix_mautrix_meta_instagram_bridge_permissions_default:
  '*': relay
  example.com: user
  '@user:example.com': admin
matrix_mautrix_meta_instagram_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true

# Enable Messenger bridging via Mautrix Meta
matrix_mautrix_meta_messenger_enabled: true
matrix_mautrix_meta_messenger_bridge_permissions_default:
  '*': relay
  example.com: user
  '@user:example.com': admin
matrix_mautrix_meta_messenger_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
```

1. git pull to fetch latest playbook
2. just roles
3. just setup-all

Playbook fails with the above message

**Expected behavior**

Playbook should finish with success, registration bot is installed long time ago and working as expected. No change to the configuration.

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- Workstation with Opensuse Tumbleweed, ansible installed from packages
- what version of Ansible you're running (see `ansible --version`) -- ansible [core 2.16.8]

**Additional context**

No changes to vars.yml since last success, only pull to get the synapse version change.
