### ISSUE TITLE
Need help using the meta plugin

### ISSUE THREAD

**Issue by ghost** [spantaleev/matrix-docker-ansible-deploy#3396]
Hello, I have been using the matrix-facebook and matrix-instagram plugins.

However now they don't really work anymore so I have been trying to use the new meta plugin.

I have this vars setup:

```yaml
    # Facebook Messenger
    matrix_mautrix_facebook_enabled: false
    #matrix_mautrix_facebook_configuration_extension_yaml: |
    #  bridge:
    #    encryption:
    #      allow: true
    #      default: true
    # Google Chat
    matrix_mautrix_googlechat_enabled: true
    
    # Instagram 
    matrix_mautrix_instagram_enabled: false
    
    # Twitter
    matrix_mautrix_twitter_enabled: true
    
    # Signal
    matrix_mautrix_signal_enabled: true
    
    # Linkedin
    matrix_beeper_linkedin_enabled: true
    
    # IRC
    matrix_heisenbridge_enabled: true
    
    # meta instagram
    matrix_mautrix_meta_instagram_enabled: true

    # meta messenger
    matrix_mautrix_meta_messenger_enabled: true
```

And I would like to know what I am doing wrong as when I run `just setup-all` I still have the `facebook-bot` present but I can not use it, it does not respond to the `help` command.

Let me know if you have any useful tips. Thank you very much
