### ISSUE TITLE
Add docs on how to properly download media_store for Mac users

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#34]

**Comment by aaronraimist** [comment]
Or add a new doc that explains how to `rsync -a -P /path_to_backup/media_store/ /matrix/synapse/storage/media-store/ --ignore-existing` and a new script that basically just runs

```
- name: Ensure media store permissions are correct (generic case)
  file:
    path: "{{ matrix_synapse_media_store_path }}"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
    recurse: yes
  when: "not matrix_s3_media_store_enabled"
```
