### ISSUE TITLE
Synapse Workers with Sliding Sync resulting in broken Client API

### ISSUE THREAD

**Issue by throny** [spantaleev/matrix-docker-ansible-deploy#3429]
**Describe the bug**
When having a setup with either [specialized or generic workers](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-synapse.md), the client API endpoint seems to fail. I did not test with federation-only workers yet, but I guess, they should work.

I tried to include all relevant config entries. Let me know, if there's something missing, but my yml is quite extensive.
**To Reproduce**
```yaml
matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: specialized-workers
matrix_sliding_sync_enabled: true 
matrix_playbook_reverse_proxy_type: other-traefik-container
matrix_playbook_reverse_proxy_hostname: traefik
devture_traefik_certs_dumper_ssl_dir_path: "/containers/traefik/letsencrypt"
matrix_federation_traefik_entrypoint_name: web-secure
matrix_static_files_container_labels_base_domain_enabled: true
# change federation to 443
matrix_synapse_http_listener_resource_names: ["client","federation","openid"]
matrix_federation_public_port: 443
matrix_synapse_federation_port_enabled: false

```

**Expected behavior**
A running Sliding Sync proxy with workers enabled.

**Matrix Server:**
 - OS: Ubuntu 22.04 LTS
 - Architecture amd64

**Additional context**
If you agree that this might be a bug, I already adjusted the documentation in my [PR](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3428)
