### ISSUE TITLE
Default Configuration File Error and Cross-Site Access Issue with Etherpad Integration in Jitsi Meet

### ISSUE THREAD

**Issue by glycerinevaseline** [spantaleev/matrix-docker-ansible-deploy#3471]
**Describe the bug**
I am currently running independent instances of Synapse, Jitsi, and Etherpad on my server.

My Etherpad is hosted at ether.<matrix.domain>, and Jitsi Meet is at jitsi.<matrix.domain>.

Firstly, there was an issue in the configuration file where the default value of `etherpad_base_url ` had an extra '/' at the end, which caused a 404 error when trying to open a shared document in Jitsi Meet to access Etherpad.

After manually correcting the etherpad_base_url to the correct URL, Jitsi Meet was able to access Etherpad properly, but I encountered the following error:
![image](https://github.com/user-attachments/assets/aca72051-f47d-4daf-bd98-e63d35085cf4)

How should I modify the Traefik or Etherpad configuration file to enable correct access to Etherpad from within Jitsi Meet?

**To Reproduce**

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: [REDACTED]

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: [REDACTED]

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: [REDACTED]

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: [REDACTED]

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''


matrix_playbook_docker_installation_enabled: false

exim_relay_enabled: false
matrix_ma1sd_enabled: false
matrix_coturn_enabled: false
matrix_homeserver_federation_enabled: false
matrix_synapse_admin_enabled: true

matrix_synapse_auto_compressor_enabled: true
matrix_synapse_auto_compressor_calendar: "*-*-* 20:00:00"
matrix_synapse_auto_join_rooms: [REDACTED]
matrix_synapse_log_level: "INFO"
matrix_synapse_storage_sql_log_level: "INFO"
matrix_synapse_root_log_level: "INFO"

jitsi_enabled: true
jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;
  config.disableAudioLevels = true;
  config.channelLastN = 4;
jitsi_web_config_resolution_width_ideal_and_max: 1920
jitsi_web_config_resolution_height_ideal_and_max: 1080

jitsi_enable_auth: true
jitsi_enable_guests: true
jitsi_prosody_auth_internal_accounts:
  - username: [REDACTED]
    password: [REDACTED]

matrix_dimension_enabled: true
matrix_dimension_admins:
  - "@dimension:{{ matrix_domain }}"
  - "@admin:{{ matrix_domain }}"
  - "@nx8s:{{ matrix_domain }}"
matrix_dimension_access_token: [REDACTED]

etherpad_enabled: true
etherpad_base_url: "https://etherpad.[REDACTED]"
etherpad_admin_username: [REDACTED]
etherpad_admin_password: [REDACTED]
```

When I remove `etherpad_base_url: "https://etherpad.[REDACTED]"`, the embedded Etherpad in Jitsi Meet reports a 404 error because the concatenated URL is incorrect and does not exist at all.

**Expected behavior**
I hope to avoid manually defining this option and have the embedded Etherpad in Jitsi Meet work correctly with the default settings, without encountering cross-site access issues.
And I received such a prompt in `configuring-playbook-etherpad.md`.
> When enabled together with the Jitsi audio/video conferencing system (see [our docs on Jitsi](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/2a35ad5a0ab6a2feb2da33ef1c63b73c9b3debe2/docs/configuring-playbook-jitsi.md)), it will be made available as an option during the conferences.
However, there's no mention of anything related to Etherpad in `configuring-playbook-jitsi.md`, which is quite confusing. I hope that more explanations can be added to the docs.
**Matrix Server:**
 - OS: [Debian 12.6]
 - Architecture [amd64]
