### ISSUE TITLE
Mautrix whatsapp and telegram bots not  working

### ISSUE THREAD

**Issue by proudhon** [spantaleev/matrix-docker-ansible-deploy#3497]
**Describe the bug**
Mautrix whatsapp and telegram bots won't work as expected.
whatsapp bot answers "This bridge has not been configured to support encryption"
telegram bot won't answer.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: [REDACTED]

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: [REDACTED]

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: [REDACTED]

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: [REDACTED]

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''
#
matrix_appservice_double_puppet_enabled: true
matrix_client_element_enabled: false
matrix_synapse_admin_enabled: true
matrix_synapse_container_labels_public_client_synapse_admin_api_enabled: true
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: [REDACTED]
matrix_mautrix_telegram_api_hash: [REDACTED]
matrix_mautrix_telegram_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
    permissions:
      [REDACTED]: admin

matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
    permissions:
      [REDACTED]: admin

matrix_sliding_sync_enabled: true

```

**Expected behavior**
The bot answers with the basic help and authentication prompt.

**Matrix Server:**
 - OS: Debian 12
 - Architecture amd64

**Additional context**
