### ISSUE TITLE
Outdated client when trying to login whatsApp bridge bot

### ISSUE THREAD

**Issue by Geckon01** [spantaleev/matrix-docker-ansible-deploy#3505]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: ***
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '***'
matrix_ssl_lets_encrypt_support_email: '***'
matrix_postgres_connection_password: '***'
matrix_ma1sd_enabled: true
matrix_synapse_admin_enabled: true
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_mautrix_discord_enabled: true
matrix_synapse_enable_registration: true
matrix_synapse_enable_registration_captcha: true
matrix_synapse_recaptcha_public_key: '***'
matrix_synapse_recaptcha_private_key: '***'
matrix_synapse_max_upload_size_mb: 500
matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_whatsapp_bridge_relay_enabled: true
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: '***'
matrix_mautrix_telegram_api_hash: '***'
```
Note: I've used "***" here to hide my sensetive data, actually in my vars.yml there some keys here and other data.

**Matrix Server:**
 - OS: Debian 11
 - Architecture amd64

**Problem description**:

I've used manual [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-whatsapp.md) to set up WhatsApp bridge. But after i use command `login` the bot tell me: 

> Failed to log in: outdated client. The bridge must be updated to continue.
I've also tried to update services how it is described [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md), but nothing changed.
