### ISSUE TITLE
Config for Signal doesn't change the Name

### ISSUE THREAD

**Issue by mr8tom** [spantaleev/matrix-docker-ansible-deploy#3510]
**Describe the bug**
The disyplayed Name of the Contacts seems not to be customizable with the syntax in the given config. I tried many versions. I looked at the config at the signal github, looks different there. No "...{% endraw %}"

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
[...]
matrix_mautrix_signal_enabled: true
#matrix_mautrix_signal_version: "0.4.3"
#matrix_mautrix_signal_version: "latest"
#encryption
matrix_mautrix_signal_bridge_encryption_allow: true
matrix_mautrix_signal_bridge_encryption_default: true
matrix_mautrix_signal_bridge_personal_filtering_spaces: false
#matrix_mautrix_signal_relaybot_enabled: false
#global_permissions?
permissions:
  '*': relay
  xxx.xx: user
matrix_mautrix_signal_configuration_extension_yaml: |
  netqork:
    use_contact_avatars: true
    displayname_template: "{% raw %}{{or .ContactName .ProfileName .PhoneNumber}} _sg{% endraw %}"
  bridge:
    permissions:
      'xxx@xxx.xx': admin
  matrix:
    delivery_receipts: true
```

**Expected behavior**
Change the Display Name according to the config. But it stays with the Profile Name

**Matrix Server:**
 - OS: [e.g. Ubuntu 22.04]
- Architecture :x86_64
