### ISSUE TITLE
Title for Rooms in Signal is empty

### ISSUE THREAD

**Issue by mr8tom** [spantaleev/matrix-docker-ansible-deploy#3552]
Describe the bug
In my last ticket I solved my problem to disyplay a custom Name of the Contacts #3510 . 
Now my Problem is, that the changed Name only works for the contact.

The Avatar + the Name of the Signal-Room stays empty. With other chatbots this works (wa, tg, meta-insta) with a similar configuration. I asked in mautrix/signal for support but didn't get an answer (https://github.com/mautrix/signal/issues/548).

My vars.yml file looks like this:

```
[...]
matrix_mautrix_signal_enabled: true
#matrix_mautrix_signal_version: "0.4.3"
#matrix_mautrix_signal_version: "latest"
#encryption
matrix_mautrix_signal_bridge_encryption_allow: true
matrix_mautrix_signal_bridge_encryption_default: true
matrix_mautrix_signal_bridge_personal_filtering_spaces: false
#matrix_mautrix_signal_relaybot_enabled: false
#global_permissions?
permissions:
  '*': relay
  xxx.xx: user
matrix_mautrix_signal_configuration_extension_yaml: |
  network:
    use_contact_avatars: true
    displayname_template: "{% raw %}{{or .ContactName .ProfileName .PhoneNumber}} _sg{% endraw %}"
  bridge:
    permissions:
      'xxx@xxx.xx': admin
  matrix:
    delivery_receipts: true
  bridge:
    private_chat_portal_meta: true
```

I also tryed to force the handling by forcing "private_chat_portal_meta: true"

Expected behavior
Avatar + Contact Name should also be used for the room, not only for the Contact.

Thannks for suggestion :)
