### ISSUE TITLE
Use Jitsi on lab feature Video Rooms instead of Element Call

### ISSUE THREAD

**Issue by ilterugur** [spantaleev/matrix-docker-ansible-deploy#3583]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: example.com

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: "secret-key"

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
traefik_config_certificatesResolvers_acme_email: "name@example.com"

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
postgres_connection_password: "secret-password"

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''

matrix_homeserver_federation_enabled: false
# This stops the federation port on the Synapse side (normally `matrix-synapse:8048` on the container network).
# matrix_synapse_federation_port_enabled: false

# This stops the federation port on the synapse-reverse-proxy-companion side (normally `matrix-synapse-reverse-proxy-companion:8048` on the container network).
# matrix_synapse_reverse_proxy_companion_federation_api_enabled: false

matrix_client_element_room_directory_servers: []
# Branding of Element
matrix_client_element_brand: "Example Chat"

matrix_client_element_welcome_logo_link: "https://example.com"

matrix_client_element_default_country_code: "TR"

matrix_client_element_default_theme: "dark"

matrix_server_fqn_element: "chat.example.com"

matrix_dimension_enabled: true

matrix_dimension_access_token: secrettoken

matrix_dimension_admins:
  - "@admin:{{ matrix_domain }}"

exim_relay_enabled: false

matrix_synapse_admin_enabled: true
```

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture: amd64

**Problem description**:

On default matrix homeserver, "experimental lab feature" Video Rooms are running on Jitsi but on my own homeserver, it is trying to run through Element Call (I guess)
Element Call is not working on my homeserver. I am using Jitsi instead on "normal" rooms. 
How can I get Jitsi running on video rooms, like default homeserver?
