### ISSUE TITLE
"User is undefined" when setting up MAS with upstream OIDC (Authentik)

### ISSUE THREAD

**Issue by wjbeckett** [spantaleev/matrix-docker-ansible-deploy#3645]
**Describe the bug**
I am attempting to setup MAS with ansible (utilising the spantaleev playbook). After configuring the playbook and my upstream oidc (Authentik) and rubbing the playbook to set it up, I get an error saying User is undefined. This is referring to the claim template from what I can tell.
It doesn't matter what I place in the localpart template, it seems that the template is not evaluated at all. So whatever is in the template, it comes back with "undefined".

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_authentication_service_config_upstream_oauth2_providers:
  - id: 01HFRQFT5QFMJFGF01P7JAV2ME
    human_name: Authentik
    issuer: "https://auth.REDACTED.org/application/o/mas/"
    client_id: "REDACTED"
    client_secret: "REDACTED"
    scope: "openid profile email"
    claims_imports:
      localpart:
        action: require
        template: "{{ user.preferred_username }}"
      displayname:
        action: suggest
        template: "{{ user.name }}"
      email:
        action: suggest
        template: "{{ user.email }}"
        set_email_verification: always
```
**Expected behavior**
Ansible deployment should complete and MAS should be setup.

**Additional context**
[{''id'': ''01HFRQFT5QFMJFGF01P7JAV2ME'', ''human_name'': ''Authentik'', ''issuer'': ''https://auth.REDACTED/application/o/mas/'', ''client_id'': ''REDACTED'', ''client_secret'': ''REDACTED'', ''scope'': ''openid profile email'', ''claims_imports'': {''localpart'': {''action'': ''require'', ''template'':
''{{ user.preferred_username }}''}, ''displayname'': {''action'': ''suggest'', ''template'': ''{{ user.name }}''}, ''email'': {''action'': ''suggest'', ''template'': ''{{ user.email }}'', ''set_email_verification'': ''always''}}}]: ''user'' is undefined. ''user'' is undefined'
