### ISSUE TITLE
Traefik Dashboard 404

### ISSUE THREAD

**Issue by IrealiTY** [spantaleev/matrix-docker-ansible-deploy#3683]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
matrix_domain: mydomain.com
matrix_homeserver_implementation: synapse
matrix_synapse_admin_enabled: true

matrix_client_cinny_enabled: true
matrix_server_fqn_cinny: "chat.{{ matrix_domain }}"

matrix_homeserver_generic_secret_key: 'xxx'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

traefik_dashboard_enabled: true
traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
traefik_dashboard_basicauth_enabled: true
traefik_dashboard_basicauth_user: aaa
traefik_dashboard_basicauth_password: xxx
traefik_config_accessLog_enabled: true
traefik_config_log_level: DEBUG

traefik_config_certificatesResolvers_acme_email: 'my@mail.com'

postgres_connection_password: 'xxx'

matrix_synapse_federation_enabled: false

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: 'xxx'

ntfy_enabled: true


 # Discord
matrix_mautrix_discord_enabled: true

# Telegram
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: 1111
matrix_mautrix_telegram_api_hash: xxxx
matrix_mautrix_telegram_filter_mode: whitelist

# WhatsApp
matrix_mautrix_whatsapp_enabled: true
matrix_synapse_configuration_extension_yaml: |
  experimental_features:
    msc2716_enabled: true
matrix_mautrix_whatsapp_configuration_extension_yaml:
  bridge:
    history_sync:
      backfill: true
    sync_direct_chat_list: true
matrix_mautrix_whatsapp_bridge_enable_status_broadcast: false

# Facebook Messenger
matrix_mautrix_facebook_enabled: true

# Google Chat
matrix_mautrix_googlechat_enabled: false

# Instagram 
matrix_mautrix_instagram_enabled: true

# Twitter
matrix_mautrix_twitter_enabled: false

# Signal
matrix_mautrix_signal_enabled: true

# Skype
matrix_go_skype_bridge_enabled: true

# IRC
matrix_heisenbridge_enabled: false


matrix_appservice_double_puppet_enabled: true
matrix_media_repo_generate_signing_key: true

#Disable not needed
matrix_coturn_enabled: false
exim_relay_enabled: false
```

**Matrix Server:**
 - OS:  Ubuntu 24.04.1 LTS 
 - Architecture: aarch64

**Ansible:**
ansible [core 2.16.10]

**Problem description**:
I want to check the Traefik dashboard at matrix.mydomain.com/dashboard, but after entering the user and password set in the .yaml i'm just getting a 404 error.

**Additional context**
it seems some Let's encrypt certs are not being refreshed too? not sure if it could be related, if I type in matrix.mydomain.com it transfers me to element.mydomain.com and that one is expired?
