### ISSUE TITLE
Unhandled templating exceptions on install

### ISSUE THREAD

**Issue by Samonitari** [spantaleev/matrix-docker-ansible-deploy#372]
Hi!

I will start with clearly stating - I am on unsupported linux distribution: openSUSE Leap 15.1
However, as I am quite the newbie regarding Ansible, any help would be appreciated.

#### Setup details
 * Ansible version: 2.9.4
 * Python version: 3.6.10

I had to hack `roles/matrix-base/tasks/server_base/setup.yml`
I changed this
`-    name: "{{ 'ntpd' if ansible_os_family == 'RedHat' else 'ntp' }}"`
to this
`+    name: "{{ 'ntpd' if ( ansible_os_family == 'RedHat' else 'systemd-timesyncd' }}"`
or this
`+    name: "{{ 'ntpd' if ( ansible_os_family == 'RedHat' or ansible_os_family == 'Suse' ) else 'ntp' }}"`
Does the playbook really need the server-side of the ntp protocol?
Setup has the same error with ntpd, so at least it is not the cause of **this** error...

#### Error
I get an error message at: 
```
TASK [matrix-bridge-mautrix-facebook : Ensure mautrix-facebook config.yaml installed

fatal: [matrix.meszaros-szegi.cloud]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ 
matrix_mautrix_facebook_configuration_yaml|from_yaml|combine(matrix_mautrix_facebook_configuration_extension, recursive=True) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ matrix_mautrix_facebook_configuration_extension_yaml|from_yaml if matrix_mautrix_facebook_configuration_extension_yaml|from_yaml is mapping else {} }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ matrix_mautrix_facebook_configuration_extension_yaml|from_yaml if matrix_mautrix_facebook_configuration_extension_yaml|from_yaml is mapping else {} }}): a string or stream input is required"}
```

#### Config
I think I don't have any funny thing going in my config:
```
matrix_domain: xyz.xyz
matrix_coturn_turn_static_auth_secret: "..."
matrix_synapse_macaroon_secret_key: "..."
matrix_riot_web_enabled: false
matrix_nginx_proxy_enabled: false
matrix_nginx_poxy_proxy_matrix_nginx_status_enabled: true
matrix_ssl_retrieval_method: none
matrix_mautrix_facebook_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "..."

matrix_synapse_configuration_extension_yaml: |
    enable_group_creation: true
    group_creation_prefix: "unofficial/"

matrix_mautrix_facebook_configuration_extension_yaml: |
     bridge:
         community_template: "unofficial/facebook_{localpart}={server}"

matrix_mailer_sender_address: "matrix-server@xyz.xyz"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "mail.xyz.xyz"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "matrix-server@xyx.xyx
matrix_mailer_relay_auth_password: "..."
```

#### Tried solution
Removed all customization from config -> didn't help.
As I run a nextcloud and mailserver docker-composed setup with cron'd cert-renewal, I am trying to reuse the already existing components. I voted for separating DB from the mailserver's though, as it seemed sane this way.
Removing all configuration customization did not help.

If I config out the facebook-bridge, I get the same templating error at:
`TASK [matrix-synapse : Ensure Synapse homeserver config installed]`
Seems to me that these are the first occurances of `to_nice_yaml` usage that playbook hits.
Tried adding `width` parameter to `to_nice_yaml`, but it didn't help.

Thanks for your great work, BTW:
Krisztián

**Comment by spantaleev** [comment]
Are you sure the indentation of `matrix_synapse_configuration_extension_yaml` and `matrix_mautrix_facebook_configuration_extension_yaml` is correct?

As for ntp, we probably don't strictly need to install it and could let people do it themselves, if they wish. Since keeping accurate time is likely important for Matrix federation, we do install it though.

**Comment by Samonitari** [comment]
Thanks for the tip, will check it out!

> As for ntp, we probably don't strictly need to install it and could let people do it themselves, if they wish. Since keeping accurate time is likely important for Matrix federation, we do install it though.

Sorry, I didn't make it clear.
I agree, that in case of any(thing's) server instance, keeping accurate time should be a bare minimum!
Although installed, `ntpd` isn't enabled by default in SUSE for a reason.
`systemd-timesyncd` is the one used for keeping the time accurate. The latter doesn't support being an ntp-server though, which in turn keeps it more simple. `timedatectl set-ntp true` controls this service behind the curtains, as far as I can tell...
If I get it to work, I wouldn't mind making a PR for SUSE related things. But that's a different story.

**Comment by Samonitari** [comment]
Okay, I am officially lost.

> Are you sure the indentation of matrix_synapse_configuration_extension_yaml and matrix_mautrix_facebook_configuration_extension_yaml is correct?

I think they are correct, I mean the install fails even if I don't override anything.
So should `roles/matrix-bridge-mautrix-facebook/defaults/main.yml` indentation match with what if I don't override anything? That file seems like the culprit to me

**Comment by spantaleev** [comment]
If you're not using custom override variables, what you see as defaults in that file should be okay.

There's lots of people using this bridge (myself included), and we're not observing any problems.

My custom overrides are like this, by the way:

```yaml
matrix_synapse_configuration_extension_yaml: |
  enable_group_creation: true
  group_creation_prefix: "unofficial/"

matrix_mautrix_facebook_enabled: true
matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    community_template: "unofficial/facebook_{localpart}={server}"
```
