### ISSUE TITLE
baibot and postmoogle don't work on IPv6-only host

### ISSUE THREAD

**Issue by nolith** [spantaleev/matrix-docker-ansible-deploy#3764]
**Describe the bug**

My homeserver is IPv6 only, the machine is dualstack but only ipv6 is public and part of my DNS entry.

Both baibot and postmoogle fail to boot because they resolve my matrix.example.com to IPv6 no have no way to reach it.

I had to add the following lines to my vars to trick the services into resolve the homeserver address using the local address

```yaml
matrix_postmoogle_container_extra_arguments:
  - "--add-host='{{matrix_server_fqn_matrix}}:{{ansible_default_ipv4.address}}'"
matrix_bot_baibot_container_extra_arguments:
  - "--add-host='{{matrix_server_fqn_matrix}}:{{ansible_default_ipv4.address}}'"
```

**To Reproduce**

``matrix_server_fqn_matrix`` must only have an IPv6 entry, no ipv4

My `vars.yml` file looks like this:

```yaml
---
matrix_domain: redacted
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: "{{ lookup('env', 'matrix_homeserver_generic_secret_key') }}"
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
traefik_config_certificatesResolvers_acme_email: 'redacted'
postgres_connection_password: "{{ lookup('env', 'postgres_connection_password') }}"
matrix_sliding_sync_enabled: true
matrix_admin: "@alessio:{{ matrix_domain }}"
matrix_appservice_double_puppet_enabled: true
matrix_bridges_encryption_enabled: true
matrix_bridges_encryption_default: true
matrix_static_files_container_labels_base_domain_enabled: true


matrix_bot_baibot_enabled: true
matrix_bot_baibot_config_user_password: "{{ lookup('env', 'matrix_bot_baibot_config_user_password') }}"

matrix_bot_baibot_config_user_encryption_recovery_passphrase: "{{ lookup('env', 'matrix_bot_baibot_config_user_encryption_recovery_passphrase') }}"
matrix_bot_baibot_config_persistence_session_encryption_key: "{{ lookup('env', 'matrix_bot_baibot_config_persistence_session_encryption_key') }}"
matrix_bot_baibot_config_persistence_config_encryption_key: "{{ lookup('env', 'matrix_bot_baibot_config_persistence_config_encryption_key') }}"

matrix_bot_baibot_config_initial_global_config_user_patterns:
  - "@alessio:{{ matrix_bot_baibot_config_homeserver_server_name }}"

matrix_bot_baibot_config_agents_static_definitions_openai_enabled: true
matrix_bot_baibot_config_agents_static_definitions_openai_config_api_key: "{{ lookup('env', 'matrix_bot_baibot_config_agents_static_definitions_openai_config_api_key') }}"
matrix_bot_baibot_config_initial_global_config_handler_catch_all: static/openai


matrix_postmoogle_enabled: true
matrix_postmoogle_password: "{{ lookup('env', 'matrix_postmoogle_password') }}"


```

**Expected behavior**

baibot and postmoogle starts.

I forgot to take the exact error of postmoogle, but for baibot the error in the logs is this one

> Nov 10 13:25:10 matrix matrix-bot-baibot[774446]: Error: Error creating a new login session: Error recovering encryption keys: Failed to recover with an unknown error: Failed to recover with an unknown error: SecretStorage(Sdk(Http(Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("matrix.REDACTED")), port: None, path: "/_matrix/client/v3/user/@baibot:REDACTED/account_data/m.secret_storage.default_key", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" })) }))))

**Matrix Server:**
 - OS: Debian 12
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Additional context**

**Comment by nolith** [comment]
I'm trying other options like setting 

```yaml
docker_daemon_options:
  experimental: true
  ipv6: true
  ip6tables: true
  fixed-cidr-v6: "REDACTED::/64" # get something from https://simpledns.plus/private-ipv6
```

With this I was able to remove the baibot extra hosts

```yaml
matrix_bot_baibot_container_extra_arguments:
  - "--add-host='{{matrix_server_fqn_matrix}}:{{ansible_default_ipv4.address}}'"
```

But could not do the same for postmoogle, I have the impression that the software only works with ipv4
