### ISSUE TITLE
.well-known client requests time out behind nginx reverse-proxy

### ISSUE THREAD

**Issue by shade-belisar** [spantaleev/matrix-docker-ansible-deploy#3794]
**Describe the bug**
When running matrix behind an nginx reverse-proxy and setting up the /.well-known/matrix location according to the [documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md#option-3-setting-up-reverse-proxying-of-the-well-known-files-from-the-base-domains-server-to-the-matrix-server), some requests hang for a long time on "old SSL session ID is stale, removing". This leads to the playbooks self-check failing on the following task:
```
TASK [custom/matrix-static-files : Check .well-known on the identity hostname] ***
fatal: [matrix.<my.url>]: FAILED! => changed=false 
  content: ''
  elapsed: 30
  msg: 'Status code was -1 and not [200]: Connection failure: The read operation timed out'
  redirected: false
  status: -1
  url: https://<my.url>/.well-known/matrix/client
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_domain: <my.url>
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '<my_secret>'
traefik_config_certificatesResolvers_acme_email: '<my@email>'
postgres_connection_password: '<my_password>'
matrix_synapse_admin_enabled: true
matrix_registration_enabled: true
matrix_registration_admin_secret: "<my_other_secret>"
matrix_coturn_turn_udp_max_port: 49200
matrix_ma1sd_enabled: true
matrix_synapse_auto_join_rooms: ["#main:<my.url>"]
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
traefik_config_entrypoint_web_secure_enabled: false
traefik_container_web_host_bind_port: '127.0.0.1:81'
traefik_config_entrypoint_web_forwardedHeaders_insecure: true
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port: '127.0.0.1:8449'
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_http3_enabled: false
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
    insecure: true
```

I ran the playbook with the vars.yaml specified above. Then I set up my nginx with the following site config:
```
server {

        root /var/www/<my.url>;

        index index.html;

        server_name <my.url>;

        location /.well-known/matrix {
                proxy_pass https://matrix.<my.url>/.well-known/matrix;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_ssl_server_name on;
        }

        location / {
                try_files $uri $uri/ =404;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<my.url>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<my.url>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```
Finally I run the playbook self-check with `ansible-playbook -i inventory/hosts setup.yml --tags=self-check -K` and get the error mentioned above. I also tried running the requests via curl `curl https://bielefeldt.berlin/.well-known/matrix/server -v --trace-time`. This sometimes hangs at "old SSL session ID is stale, removing" for exactly one minute.
```
09:30:05.638067 * old SSL session ID is stale, removing
09:31:05.659899 * TLSv1.2 (IN), TLS header, Supplemental data (23):
```
Interestingly, this error does not appear everytime, but only every couple of requests from the same client. The curl requests can absolutely go through within split seconds, at which point the same log entry looks like this
```
09:33:44.232521 * old SSL session ID is stale, removing
09:33:44.233790 * TLSv1.2 (IN), TLS header, Supplemental data (23):
```
Even the playbooks self-check can partially work. This task message is from the exact same run as the error message mentioned above:
```
TASK [custom/matrix-static-files : Report working .well-known on the identity hostname] ***
ok: [matrix.<my.url>] => 
  msg: 'well-known for Client Discovery (/.well-known/matrix/client) is configured correctly for `<my.url>` (checked endpoint: `https://<my.url>/.well-known/matrix/client`)'
```

**Expected behavior**
I expected the requests to go through in a timely fashion, especially since requests going directly to matrix.<my.url>/.well-known/matrix never shows this problem.

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture amd64

**Additional context**
My setup for the matrix-domain specific site in nginx is as follows. Since this never throws said error I tried to use the same settings in my <my.url> config for /.well-known/matrix/ as for the location / in this playbook, but to no avail.
```
server {
    listen 443 ssl;

    listen [::]:443 ssl;

    server_name matrix.<my.url> element.<my.url>;

    location / {
        proxy_pass http://localhost:81;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;

        client_max_body_size 50M;

        add_header Alt-Svc 'h3=":443"; ma=86400';
    }

    ssl_certificate /etc/letsencrypt/live/<my.url>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<my.url>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 8448 ssl default_server;

    listen [::]:8448 ssl default_server;

    server_name matrix.<my.url>;

    location / {
        proxy_pass http://localhost:8449;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;

        client_max_body_size 50M;

        add_header Alt-Svc 'h3=":8448"; ma=86400';
    }
    ssl_certificate /etc/letsencrypt/live/<my.url>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<my.url>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = matrix.<my.url>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name matrix.<my.url>;
    listen 80;
    return 404; # managed by Certbot
}

server {
    if ($host = element.<my.url>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name element.<my.url>;
    listen 80;
    return 404; # managed by Certbot
}
```
