### ISSUE TITLE
Self-building of matrix-client-schildichat fails: path to webpack.config.js cannot be specified

### ISSUE THREAD

**Issue by luixxiul** [spantaleev/matrix-docker-ansible-deploy#3831]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_client_schildichat_container_image_self_build: true
matrix_client_schildichat_container_image_self_build_repo: "https://github.com/SchildiChat/schildichat-desktop.git"
# Controls whether to patch webpack.config.js when self-building, so that building can pass on low-memory systems (< 4 GB RAM):
# - https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1357
# - https://github.com/element-hq/element-web/issues/19544
matrix_client_schildichat_container_image_self_build_low_memory_system_patch_enabled: "{{ ansible_memtotal_mb < 4096 }}"

matrix_client_schildichat_version: v1.11.86-sc.0.test.0

matrix_client_schildichat_data_path: "{{ matrix_base_data_path }}/client-schildichat"
matrix_client_schildichat_docker_src_files_path: "{{ matrix_client_schildichat_data_path }}/docker-src"
```

It was specified following `roles/custom/matrix-client-element/defaults/main.yml` as an example.

`v1.11.86-sc.0.test.0` was released here: https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.86-sc.0.test.0

**Matrix Server:**
 - OS: Ubuntu 21.04
 - Architecture: amd64

**Ansible:**

**Problem description**:

I tried to self-build SchildiChat Web client based on the latest pre-release to try it out.
````
TASK [custom/matrix-client-schildichat : Patch webpack.config.js to support building on low-memory (<4G RAM) devices] ***
fatal: [matrix.progressiv.dev]: FAILED! => changed=false 
  msg: Destination /matrix/client-schildichat/docker-src/webpack.config.js does not exist !
  rc: 257
````

With the error message I changed `matrix_client_schildichat_docker_src_files_path` to `{{ matrix_client_schildichat_data_path }}/docker-src/element-web` (where webpack.config.js should exist) and ran the setup command, but it did not find `/matrix/client-schildichat/docker-src/element-web/webpack.config.js` because the file moved to `/matrix/client-schildichat/docker-src/element-web/element-web/webpack.config.js` for a reason which I do not know.

So I changed `matrix_client_schildichat_docker_src_files_path` to  `{{ matrix_client_schildichat_data_path }}/docker-src/element-web/element-web` and ran the setup command again, and it failed again with the error message as below:

````
TASK [custom/matrix-client-schildichat : Patch webpack.config.js to support building on low-memory (<4G RAM) devices] ***
fatal: [matrix.progressiv.dev]: FAILED! => changed=false 
  msg: Destination /matrix/client-schildichat/docker-src/element-web/element-web/webpack.config.js does not exist !
  rc: 257
````

Any pointer to proceed with self-building would be appreciated.

**Client (please complete the following information):** irrelevant

**Additional context**
Since the repository structure of https://github.com/SchildiChat/schildichat-desktop was greatly changed, the role might need update as well, maybe?
