### ISSUE TITLE
matrix registration bot broken - 404 on request to closed matrix.mydomain.here/_synapse/admin/ endpoints

### ISSUE THREAD

**Issue by grigoriy-a** [spantaleev/matrix-docker-ansible-deploy#3898]
**Describe the bug**
The matrix registration bot is broken - it gets 404 on its requests to now closed matrix.example.com/_synapse/admin/ endpoints (as I understand from change logs, these endpoints were once opened, and now are closed).
I confirm this with curl from my local machine.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_bot_matrix_registration_bot_enabled: true
matrix_bot_matrix_registration_bot_bot_password: xxx
matrix_synapse_enable_registration: true
matrix_synapse_registration_requires_token: true
```
I installed everything using the quick setup guide. Then I added the registration bot. No other finetunings.
"Help" command works, bot gives answers. Then I asked the bot to create token or list tokens - every time I get error from bot
List command's error response is more verbose - it says "The registration api returned 404: Not Found for GET: https://matrix.mydomain.here/_synapse/admin/v1/registration_tokens"

**Expected behavior**
I expected the bot to work.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture amd64

**Ansible:**
No problems with Ansible

**Client:**

**Additional context**
Since the /_synapse/admin/ endpoints are closed from outside, I would guess line 23 in "roles/custom/matrix-bot-matrix-registration-bot/defaults/main.yml" file should be changed
<img width="619" alt="image" src="https://github.com/user-attachments/assets/02b1003b-1787-484d-aed1-d964f94a3129" />
