### ISSUE TITLE
Traefik managed by you - on a different host?

### ISSUE THREAD

**Issue by Handrail9** [spantaleev/matrix-docker-ansible-deploy#3905]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: mydomain.tld

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'abcde'

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: other-traefik-container

# Uncomment and adjust if your Traefik container is on another network
#matrix_playbook_reverse_proxy_container_network: 

# Adjust to point to your Traefik container
matrix_playbook_reverse_proxy_hostname: 192.168.2.2:8080

traefik_certs_dumper_ssl_dir_path: "/mnt/certs/"

# Uncomment and tweak the variable below if the name of your federation entrypoint is different
# than the default value (matrix-federation).
# matrix_federation_traefik_entrypoint_name: matrix-federation

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
#devture_traefik_config_certificatesResolvers_acme_email: ''

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
postgres_connection_password:  'abcde'

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''

# Enable Jitsi
jitsi_enabled: true

# Uncomment and adjust if you need to use another hostname
# jitsi_hostname: "jitsi.{{ matrix_domain }}"

# Uncomment and possible adjust if you'd like to host under a subpath
# jitsi_path_prefix: /jitsi
jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=192.168.2.2"'

# Use an alternative email server
exim_relay_sender_address: "matrix@mydomain.tld"
exim_relay_relay_use: true
exim_relay_relay_host_name: "mail.mydomain.tld"
exim_relay_relay_host_port: 587
exim_relay_relay_auth: true
exim_relay_relay_auth_username: "abcde"
exim_relay_relay_auth_password: "abcde"

# Enable cinny
matrix_client_cinny_enabled: true

# Enable double puppeting for bridges
matrix_appservice_double_puppet_enabled: true

# Enable Synapse Admin
matrix_synapse_admin_enabled: true

# Enable Mautrix Discord bridge
matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_bridge_permissions: |
  {{
    {'*': 'relay', matrix_mautrix_discord_homeserver_domain: 'user',
    | combine({matrix_admin: 'admin'} if matrix_admin else {})
  }}

# Enable Mautrix Slack Bridge
matrix_mautrix_slack_enabled: true

# Enable What'sApp Bridge
matrix_mautrix_whatsapp_enabled: true

# Enable Instagram Bridge
matrix_mautrix_meta_instagram_enabled: true
matrix_mautrix_meta_instagram_bridge_permissions_default:
  '*': relay
  'mydomain.tld': user

# Enable Facebook Messenger bridge
matrix_mautrix_meta_messenger_enabled: true
matrix_mautrix_meta_messenger_bridge_permissions_default:
  '*': relay
  'mydomain.tld': user

# Enable Signal Bridge
matrix_mautrix_signal_enabled: true

# Enable Steam Bridge
matrix_mx_puppet_steam_enabled: true
matrix_mx_puppet_steam_provisioning_whitelist:
  - "@.*:{{ matrix_domain | regex_escape }}"

# Enable Linkedin Bridge
matrix_beeper_linkedin_enabled: true
matrix_beeper_linkedin_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true

# Enable Twitter Bridge
matrix_mautrix_twitter_enabled: true

# Enable RemindMe Bot
#matrix_bot_matrix_reminder_bot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_matrix_reminder_bot_matrix_user_id_localpart: bot.matrix-reminder-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_reminder_bot_matrix_user_password: "abcde"

# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: US/New_York

# Enable Registration Bot
matrix_bot_matrix_registration_bot_enabled: true

# By default, the playbook will set use the bot with a username like this: `@bot.matrix-registration-bot:DOMAIN`.
# To use a different username, uncomment & adjust the variable below:
# matrix_bot_matrix_registration_bot_matrix_user_id_localpart: bot.matrix-registration-bot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_matrix_registration_bot_bot_password: "abcde"

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true

# Enable Maubot
matrix_bot_maubot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_maubot_login: bot.maubot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`
matrix_bot_maubot_initial_password:  "abcde"

matrix_bot_maubot_admins:
  - abcde: "abcde"

# Enable auto compression
matrix_synapse_auto_compressor_enabled: true

# Enable sliding sync
matrix_sliding_sync_enabled: false

# Disable /etc/docker/daemon.json from being overwritten
matrix_playbook_docker_installation_enabled: false

# Add server to IP Range Whitelist
matrix_synapse_configuration_extension_yaml: |
  ip_range_whitelist:
    - '192.168.2.2'
    - '192.168.2.4'
    - '192.168.2.8'

```

**Matrix Server:**
 - OS: Fedora Server 41
 - Architecture amd64

**Problem description**:
I was wondering if it's possible to have the traefik managed by you configuration if traefik is on a seperate host/machine/VM? My configuration works when traefik is on the same machine, but I am trying to virtualize more of my containers so one docker container crashing doesn't take down my whole homelab. If need-be I can probably put Matrix and traefik in the same VM, but I was trying to get traefik by itself to avoid all my services being taken down if anything in the traefik VM takes the VM down. (Not saying that Matrix is unstable or would cause that to happen, most of my crashes are probably user error)
