### ISSUE TITLE
Remote access to media files is broken when using multiple workers

### ISSUE THREAD

**Issue by Marx1st** [spantaleev/matrix-docker-ansible-deploy#3918]
**Describe the bug**
Remote access to media files is broken when using multiple workers. Remote user get an error message when accessing the file and the log shows a 404 http error.

`Jan 03 12:01:20 synapse matrix-traefik[1365431]: 176.126.240.157 - - [03/Jan/2025:12:01:20 +0000] "GET /_matrix/federation/v1/media/download/BPrmGmkQSCsZSViBIWxERZUi?timeout_ms=20000 HTTP/1.1" 404 59 "-" "-" 380167 "matrix-synapse-reverse-proxy-companion-public-federation-api@docker" "http://172.24.0.54:8048" 1ms
Jan 03 12:01:20 synapse matrix-traefik[1365431]: 176.126.240.157 - - [03/Jan/2025:12:01:20 +0000] "GET /_matrix/media/v3/download/xxxx.com/BPrmGmkQSCsZSViBIWxERZUi?allow_remote=false&timeout_ms=20000&allow_redirect=true HTTP/1.1" 404 45 "-" "-" 380168 "matrix-synapse-reverse-proxy-companion-public-federation-api@docker" "http://172.24.0.54:8048" 3ms
`

**To Reproduce**
Enable more then one worker like below and post media to a federated room. Access room with remote account.

Our custom worker's preset looks like this:

```
  buw:
    room_workers_count: 4
    sync_workers_count: 4
    client_reader_workers_count: 2
    federation_reader_workers_count: 6
    generic_workers_count: 0
    pusher_workers_count: 2
    federation_sender_workers_count: 6
    media_repository_workers_count: 2
    appservice_workers_count: 2
    user_dir_workers_count: 2
    background_workers_count: 4
    stream_writer_events_stream_workers_count: 6
    stream_writer_typing_stream_workers_count: 1
    stream_writer_to_device_stream_workers_count: 1
    stream_writer_account_data_stream_workers_count: 1
    stream_writer_receipts_stream_workers_count: 1
    stream_writer_presence_stream_workers_count: 1
```

**Expected behavior**

When posting media files to a federated room, all members should be able to view those files, even when they have accounts on remote servers.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture: amd64

**Client:**
all clients
