### ISSUE TITLE
Self-Check Failing Despite Successful Setup with External Reverse Proxy

### ISSUE THREAD

**Issue by xelayz** [spantaleev/matrix-docker-ansible-deploy#3959]
Hello 👋

**Problem description**:

I run "ansible-playbook -i inventory/hosts setup.yml --tags=install-all,start" on the matrix container and everything looks good. Then I run the "self check" and will get the following error. I just don’t get it. In the beginning, I didn’t fully read the docs and thought I could set up Traefik normally and then route everything through Nginx. However, that caused issues with TLS. So, I followed everything from the docs. I can now access https://matrix.domain.com/_matrix/client/versions without any issues. But the self-check still fails. I’m really desperate and don’t know what to do anymore. I must have overlooked something... maybe someone here can find the mistake? This would be great...

```yaml
TASK [custom/matrix-synapse : Check Matrix Client API] **********************************************************************************************************************************************************************************************************************************************************************
fatal: [matrix.domain.com -> 127.0.0.1]: FAILED! => changed=false
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>'
  redirected: false
  status: -1
  url: https://matrix.domain.com/_matrix/client/versions
...ignoring

TASK [custom/matrix-synapse : Fail if Matrix Client API not working] ********************************************************************************************************************************************************************************************************************************************************
fatal: [matrix.domain.com]: FAILED! => changed=false
  msg: 'Failed checking Matrix Client API is up at `matrix.domain.com` (checked endpoint: `https://matrix.domain.com/_matrix/client/versions`). Is Synapse running? Is port 443 open in your firewall? Full error: {''redirected'': False, ''url'': ''https://matrix.domain.com/_matrix/client/versions'', ''status'': -1, ''elapsed'': 0, ''changed'': False, ''failed'': True, ''msg'': ''Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>''}'

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************
matrix.domain.com          : ok=7    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=1

root@Matrix:~/matrix-docker-ansible-deploy#
```

**Matrix Server:**
 - OS: Ubuntu 24.04
 - Architecture: amd64

**Setup:**
- Host (192.168.100.1)
- Container (Nginx) on Host (192.168.100.101)
- Container (Matrix) on Host (192.168.100.105)

**Configurations**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user IDs for your server will be of the form (`@alice:example.com`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.example.com", see `matrix_server_fqn_matrix`).
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
matrix_domain: domain.com

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
#  - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
#
# By default, we use Synapse, because it's the only full-featured Matrix server at the moment.
#
# Note that the homeserver implementation of a server will not be able to be changed without data loss.
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred. You can create one with a command like `pwgen -s 64 1`.
matrix_homeserver_generic_secret_key: '123'

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
atrix_playbook_reverse_proxy_type: playbook-managed-traefik

# Ensure that public urls use https
matrix_playbook_ssl_enabled: true

# Disable the web-secure (port 443) endpoint, which also disables SSL certificate retrieval.
# This has the side-effect of also automatically disabling TLS for the matrix-federation entrypoint
# (by toggling `matrix_federation_traefik_entrypoint_tls`).
traefik_config_entrypoint_web_secure_enabled: false

# If your reverse-proxy runs on another machine, consider using `0.0.0.0:81`, just `81` or `SOME_IP_ADDRESS_OF_THIS_MACHINE:81`
traefik_container_web_host_bind_port: '0.0.0.0:81'

# We bind to `127.0.0.1` by default (see above), so trusting `X-Forwarded-*` headers from
# a reverse-proxy running on the local machine is safe enough.
# If you're publishing the port (`traefik_container_web_host_bind_port` above) to a public network interface:
# - remove the `traefik_config_entrypoint_web_forwardedHeaders_insecure` variable definition below
# - uncomment and adjust the `traefik_config_entrypoint_web_forwardedHeaders_trustedIPs` line below
traefik_config_entrypoint_web_forwardedHeaders_insecure: true
# traefik_config_entrypoint_web_forwardedHeaders_trustedIPs: ['IP-ADDRESS-OF-YOUR-REVERSE-PROXY']

# Expose the federation entrypoint on a custom port (other than port 8448, which is normally used publicly).
#
# We bind to `127.0.0.1` by default (see above), so trusting `X-Forwarded-*` headers from
# a reverse-proxy running on the local machine is safe enough.
#
# If your reverse-proxy runs on another machine, consider:
# - using `0.0.0.0:8449`, just `8449` or `SOME_IP_ADDRESS_OF_THIS_MACHINE:8449` below
# - adjusting `matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom` (below) - removing `insecure: true` and enabling/configuring `trustedIPs`
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port: '0.0.0.0:8449'

# Disable HTTP/3 for the federation entrypoint.
# If you'd like HTTP/3, consider configuring it for your other reverse-proxy.
#
# Disabling this also sets `matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port_udp` to an empty value.
# If you'd like to keep HTTP/3 enabled here (for whatever reason), you may wish to explicitly
# set `matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port_udp` to something like '127.0.0.1:8449'.
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_http3_enabled: false

# Depending on the value of `matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port` above,
# this may need to be reconfigured. See the comments above.
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
   trustedIPs: ['192.168.100.101']

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
# traefik_config_certificatesResolvers_acme_email: 'matrix@domain.com'

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
postgres_connection_password: '123'

# By default, we configure coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''

matrix_client_element_enabled: false

```

My `inventory/hosts` file looks like this:

```yaml
[matrix_servers]
matrix.domain.com ansible_host="host public IP" ansible_ssh_user=root ansible_connection=local
```

My `iptables rules (network interface: Host)` file looks like this:

```yaml
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p tcp --dport 80 -j DNAT --to 192.168.100.101:80                                # 101-Webserver
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p tcp --dport 443 -j DNAT --to 192.168.100.101:443                              # 101-Webserver TLS

        post-up iptables -t nat -A PREROUTING -i vmbr0 -p udp --dport 8448 -j DNAT --to 192.168.100.101:8448                            # 101-Webserver Matrix Federation UDP
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p tcp --dport 8448 -j DNAT --to 192.168.100.101:8448                            # 101-Webserver Matrix Federation TCP
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p udp --dport 3478 -j DNAT --to 192.168.100.105:3478                            # 105-Matrix TURN/STUN UDP
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p tcp --dport 3478 -j DNAT --to 192.168.100.105:3478                            # 105-Matrix TURN/STUN TCP
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p udp --dport 5349 -j DNAT --to 192.168.100.105:5349                            # 105-Matrix TURN/STUN UDP
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p tcp --dport 5349 -j DNAT --to 192.168.100.105:5349                            # 105-Matrix TURN/STUN TCP
        post-up iptables -t nat -A PREROUTING -i vmbr0 -p udp --dport 49152:49172 -j DNAT --to 192.168.100.105                          # 105-Matrix WebRTC Media
```

My `Nginx config` file looks like this:

```yaml
# domain.com
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name domain.com;

    root /var/www/domain.com/domain.com;
    index index.html index.htm index.php;

    access_log /var/log/nginx/domains/domain.com.log combined;
    error_log  /var/log/nginx/domains/domain.com.error.log error;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/matrix {
        proxy_pass http://192.168.100.105:81/.well-known/matrix;  # Weiterleitung zur Matrix-VM
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_server_name on;

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;
    }

    location ~* \.(png|jpg|jpeg|gif|ico|woff|otf|ttf|eot|svg|txt|pdf|docx?|xlsx?|js|css)$ {
        access_log off;
        log_not_found off;
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public";
        add_header Vary "Accept-Encoding";
    }

    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name domain.com;

    return 301 https://$host$request_uri;
}

# matrix.domain.com

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name matrix.domain.com;

    ssl_certificate /etc/letsencrypt/live/matrix.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matrix.domain.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://192.168.100.105:81;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 50M;
        add_header Alt-Svc 'h3=":443"; ma=86400';

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;
    }
}

server {
    if ($host = matrix.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name matrix.domain.com;
    listen 80;
    return 404; # managed by Certbot
}

server {
    listen 8448 ssl;
    listen [::]:8448 ssl;

    server_name matrix.domain.com;

    ssl_certificate /etc/letsencrypt/live/matrix.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matrix.domain.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://192.168.100.105:8449;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 50M;
        add_header Alt-Svc 'h3=":8448"; ma=86400';

        access_log /var/log/nginx/matrix.access.log;
        error_log /var/log/nginx/matrix.error.log;
    }
}
```

**Additional context**
Thank you very much in advance. The playbook is really great. I’ve successfully used it before, but not with an external reverse proxy.
