### ISSUE TITLE
Maubot dependencies not installed

### ISSUE THREAD

**Issue by circle3451** [spantaleev/matrix-docker-ansible-deploy#4011]
**Describe the bug**
Im trying to install a python dependency for a maubot im working on. Do you know how to do this? i tried doing this 

```yaml
matrix_bot_maubot_container_image_customizations_dockerfile_body_custom: | 
RUN pip install supabase
```
and this
```yaml
matrix_bot_maubot_container_image_customizations_dockerfile_body_custom: | 
RUN apk install py3-supabase
```
and this
```yaml
matrix_bot_maubot_container_image_customizations_dockerfile_body_custom: |
  RUN apk add --no-cache py3-supabase
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---

matrix_domain: xxx.xxx

matrix_homeserver_implementation: synapse

matrix_homeserver_generic_secret_key: 'xxx'

matrix_playbook_reverse_proxy_type: playbook-managed-traefik
traefik_config_entrypoint_web_secure_enabled: false
traefik_config_certificatesResolvers_acme_enabled: true

matrix_static_files_container_labels_base_domain_enabled: true
matrix_static_files_container_labels_base_domain_traefik_path_prefix: /.well-known/matrix
matrix_federation_public_port: 'xxx'
# Ensure that public urls use https
matrix_playbook_ssl_enabled: true
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
    insecure: true
    trustedIPs: ['xxx.xxx.xxx.xxx']
    
traefik_config_entrypoint_web_forwardedHeaders_trustedIPs: ['xxx.xxx.xxx.xxx']

traefik_config_certificatesResolvers_acme_email: 'xxx@xxx.xxx'
matrix_synapse_container_labels_additional_labels: |
  traefik.http.routers.matrix-synapse-federation-api.tls.domains.main="xxx.xxx"
  traefik.http.routers.matrix-synapse-federation-api.tls.domains.sans="*.xxx.xxx"
matrix_federation_traefik_entrypoint_tls: false

postgres_connection_password: 'xxx'

matrix_coturn_turn_external_ip_address: 'x.x.x.x'

######################################### Bridges
matrix_admin: "@xxx:{{ matrix_domain }}"

matrix_heisenbridge_enabled: true

# set owner (optional)
matrix_heisenbridge_owner: "@xxx:xxx.xxx"

# to enable identd on host port 113/TCP (optional)
matrix_heisenbridge_identd_enabled: true

matrix_mautrix_signal_enabled: true

matrix_mautrix_meta_messenger_enabled: true

matrix_mautrix_meta_instagram_enabled: true

matrix_mautrix_meta_messenger_configuration_extension_yaml: |
  bridge:
    personal_filtering_spaces: true
    permissions:
      '@xxx:{{ matrix_domain }}': admin
  encryption:
    allow: true
    default: true

matrix_mautrix_meta_instagram_configuration_extension_yaml: |
  bridge:
    personal_filtering_spaces: true
    permissions:
      '@xxx:{{ matrix_domain }}': admin
  encryption:
    allow: true
    default: true

matrix_mautrix_discord_enabled: true

matrix_mautrix_whatsapp_enabled: true

matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: "xxx"
matrix_mautrix_telegram_api_hash: "xxx"

# #############SYNAPSE
matrix_synapse_max_upload_size_mb: 100
matrix_synapse_auto_compressor_enabled: true

# Enables registration
matrix_synapse_enable_registration: true

# Restrict registration to users with a token
matrix_synapse_registration_requires_token: true

matrix_appservice_double_puppet_enabled: true

matrix_synapse_admin_enabled: true  

matrix_bot_maubot_enabled: true

# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_maubot_login: bot.maubot

# Generate a strong password for the bot. You can create one with a command like `pwgen -s 64 1`.
matrix_bot_maubot_initial_password: "xxxx"

matrix_bot_maubot_admins:
  - xxx: "xxx"

matrix_bot_maubot_container_image_customizations_dockerfile_body_custom: |
  RUN apk add --no-cache py3-supabase

```

**Expected behavior**
I expected maubot to be able run an instance of a bot that has the dependency of the python supabase module.
https://pypi.org/project/supabase/
https://supabase.com/docs/reference/python/start?queryGroups=platform&platform=pip

I entered the maubot docker container and none of the docker files seemed to have been updated.

**Matrix Server:**
 - OS: [Debian 6.1.124-1 (2025-01-12) x86_64]
 - Architecture [amd64,]
