### ISSUE TITLE
Support `ident` server on matrix-appservice-irc

### ISSUE THREAD

**Issue by sergiodj** [spantaleev/matrix-docker-ansible-deploy#4178]
Hi,

Realistically, IRC networks (like Libera.Chat) will require admins running matrix-appservice-irc to also provide an `ident` server accompanying it.  The bridge software has support for a built-in `ident` server; all one has to do is to enable it:

```yaml
ircService:
  ident:
    address: 0.0.0.0
    enabled: true
    port: 113
...
```

However, there's no easy way to adjust Traefik and make it listen to the correct external port and then route the requests to the container.  It'd be great if the container supported labels so that we could at least implement our own routers/entrypoints for this.
