### ISSUE TITLE
TASK [galaxy/ntfy : Allow anonymous write access for push messages] FAILED (fatal / ignoring...)

### ISSUE THREAD

**Issue by UehgxEQbFiw4Tlw8** [spantaleev/matrix-docker-ansible-deploy#4183]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
Paste your vars.yml file here.
Make sure to remove any secret values before posting your vars.yml file publicly.

matrix_domain: example.com
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'secret'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_systemd_docker_base_ipv6_enabled: true
postgres_connection_password: 'secret'
matrix_client_element_enabled: false
matrix_synapse_user_directory_search_all_users: true
matrix_synapse_admin_enabled: false
# If the above set to false, uncomment the following line, for security (?):
matrix_synapse_container_labels_public_client_synapse_admin_api_enabled:  false
# See CHANGELOG.md on 2024-11-08 for explanation
matrix_static_files_file_matrix_client_property_cc_etke_synapse_admin_enabled: false
matrix_synapse_usage_exporter_enabled: true
matrix_synapse_federation_enabled: false
prometheus_enabled: true
prometheus_node_exporter_enabled: true
prometheus_postgres_exporter_enabled: true
grafana_enabled: true
grafana_hostname: grafana.example.com
grafana_anonymous_access: false
grafana_default_admin_user: "xxx"
grafana_default_admin_password: "secret"
traefik_dashboard_enabled: true
traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
traefik_dashboard_basicauth_enabled: true
traefik_dashboard_basicauth_user: xxx
traefik_dashboard_basicauth_password: secret
ntfy_enabled: true
ntfy_global_topic_limit: x
ntfy_visitor_subscription_limit: y
ntfy_credentials:
  - username: user1
    password: pw1
    admin: true
  - username: user2
    password: pw2
    admin: false
matrix_coturn_turn_static_auth_secret: "secret"
```

**Matrix Server:**
 - OS: RaspberryPi OS
 uname -a
Linux hostname 6.6.74+rpt-rpi-2712 1 SMP PREEMPT Debian 1:6.6.74-1+rpt1 (2025-01-27) aarch64 GNU/Linux

**Ansible:**
If your problem appears to be with Ansible, tell us:

I don't think, but, just in case... 

- where you run Ansible — on another computer (Ubuntu 24.04 LTS, standard installation, up-to-date)
- what version of Ansible you're running (see `ansible --version`):
ansible [core 2.16.3]
  config file = /home/user/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

**Problem description**:
Enabling authentication with:

ntfy_credentials:
  - username: user1
    password: pw1
    admin: true
  - username: user2
    password: pw2
    admin: false

in my vars.yml from a previously unprotected ntfy produces the error:

TASK [galaxy/ntfy : Allow anonymous write access for push messages] ****************************************************
fatal: [matrix.example.com]: FAILED! => {"changed": true, "cmd": ["/usr/bin/env", "sh", "-c", "/usr/bin/env docker run \\\n--rm \\\n--user=999:1001 \\\n--mount type=bind,src=/matrix/ntfy/config,dst=/etc/ntfy,ro \\\n--mount type=bind,src=/matrix/ntfy/data,dst=/data \\\n--network none \\\ndocker.io/binwiederhier/ntfy:v2.11.0 \\\n access * up* write-only"], "delta": "0:00:00.230374", "end": "2025-03-15 13:33:21.195637", "msg": "non-zero return code", "rc": 1, "start": "2025-03-15 13:33:20.965263", "stderr": "too many arguments, please check 'ntfy access --help' for usage details", "stderr_lines": ["too many arguments, please check 'ntfy access --help' for usage details"], "stdout": "", "stdout_lines": []}
...ignoring

password pw1 and pw2 above in the configuration have been generated with pwgen -s XX.

Thanks for help!

Best
M.

**Additional context**
