### ISSUE TITLE
mautrix bridge fails to connect to homeserver in most default config

### ISSUE THREAD

**Issue by hermannsblum** [spantaleev/matrix-docker-ansible-deploy#4193]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---

matrix_domain: hermannblum.net

matrix_homeserver_implementation: dendrite

matrix_homeserver_generic_secret_key: ''

devture_systemd_docker_base_ipv6_enabled: true

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

postgres_connection_password: ''

matrix_appservice_double_puppet_enabled: true

matrix_client_element_enabled: false

matrix_mautrix_slack_enabled: true

matrix_static_files_container_labels_base_domain_enabled: true

```

**Matrix Server:**
 - OS: Ubuntu 24.04
 - Architecture amd64

**Problem description**:

I have a problem getting mautrix bridges in a fresh setup to work. This is potentially related to #4182 , who reports a similar issue. I completely reinstalled my server to make sure it is no setup issue and run with the most vanilla config possible. Still, I get the following error in the syslog of mautrix-slack:

`
Mar 17 18:10:44 ubuntu matrix-mautrix-slack[70957]: 2025-03-17T18:10:44.057Z ERR Failed to connect to homeserver, retrying in 10 seconds... error="failed to GET /_matrix/client/versions: HTTP 404"
`

Manually checking, there is `https://matrix.hermannblum.net/_matrix/client/versions` available, but `https://hermannblum.net/_matrix/client/versions` indeed returns 404, so it seems the bridge does not query the correct subdomain. However, I am not even sure where to configure this? Should this not be the default?
