### ISSUE TITLE
404 accessing element.server.com (after ipv6 implementation)

### ISSUE THREAD

**Issue by darkblue69** [spantaleev/matrix-docker-ansible-deploy#4199]
@spantaleev hello, can u explain pls how to deprecate all changes with ipv6?
I don't have Ipv6 in my network,and it won't appear)
i have added this `devture_systemd_docker_base_ipv6_enabled: true` to my **vars.yaml**, so matrix-element-client is unhealthy for now(
I have deleted this option from **vars.yaml,** and restarted playbook, deleted networks. but matrix-client-element is not responding (404 eror) can u help me pls?)
When i start playbook without this devture_systemd_docker_base_ipv6_enabled: true everything going well, but element web doesn't work(  (wget: can't connect to remote host (127.0.0.1): Connection refused)
Here is my **vars.yaml**
```
---
matrix_domain: server.com

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse
matrix_registration_admin_secret: ""
matrix_synapse_admin_enabled: true
# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: ''

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
#traefik_config_certificatesResolvers_acme_email: 'achich@business-car.ru'
matrix_admin: '@some_email'
matrix_bot_baibot_enabled: true
# Uncomment and adjust this part if you'd like to use a username different than the default
# matrix_bot_baibot_config_user_mxid_localpart: baibot

# Generate a strong password here. Consider generating it with `pwgen -s 64 1`.
# If you'd like to change this password subsequently, see the details below.
matrix_bot_baibot_config_user_password: ''

# An optional passphrase to use for backing up and recovering the bot's encryption keys.
# You can use any string here. Consider generating it with `pwgen -s 64 1`.
#
# If set to null, the recovery module will not be used and losing your session/database
# will mean you lose access to old messages in encrypted room.
# It's highly recommended that you configure this to avoid losing access to encrypted messages.
#
# Changing this subsequently will also cause you to lose access to old messages in encrypted rooms.
# For details about changing this subsequently or resetting, see `defaults/main.yml` in the baibot role.
matrix_bot_baibot_config_user_encryption_recovery_passphrase: ''

# An optional secret for encrypting the bot's session data (see `matrix_bot_baibot_data_path`).
# This must be 32-bytes (64 characters when HEX-encoded).
# Generate it with: `openssl rand -hex 32`
# Set to null or empty to avoid using encryption.
# Changing this subsequently requires that you also throw away all data (see `matrix_bot_baibot_data_path`)
matrix_bot_baibot_config_persistence_session_encryption_key: ''

# An optional secret for encrypting bot configuration stored in Matrix's account data.
# This must be 32-bytes (64 characters when HEX-encoded).
# Generate it with: `openssl rand -hex 32`
# Set to null or empty to avoid using encryption.
# Changing this subsequently will make you lose your configuration.
matrix_bot_baibot_config_persistence_config_encryption_key: ''
# MATRIX TUNE
#Synapse's presence feature which tracks which users are online and which are offline can use a lot of processing power. 
matrix_synapse_presence_enabled: true
matrix_synapse_caches_global_factor: 0.4
# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
postgres_connection_password: ''
#Jitsi
jitsi_enabled: true
#Jitsi Making your Jitsi server work on a LAN
jitsi_jvb_container_extra_arguments:
  - '--env "JVB_ADVERTISE_IPS=local ip,ext ip"'
jitsi_web_stun_servers:
- stun:ext ip:3478
#Jitsi tune video
jitsi_web_custom_config_extension: |
  config.enableLayerSuspension = true;

  config.disableAudioLevels = true;

  // Limit the number of video feeds forwarded to each client
  config.channelLastN = 30;

#jitsi_web_config_resolution_width_ideal_and_max: 480
#jitsi_web_config_resolution_height_ideal_and_max: 240
#jitsi_jvb_container_colibri_ws_host_bind_port: '127.0.0.1:9090'
#jitsi_jvb_custom_config_extension: |


matrix_registration_enabled: false
# Enables grafana web interface for viewing metrics in 
# prometheus
grafana_enabled: true
# Disables anonymous access to grafana
grafana_anonymous_access: false
# Sets default credentials for grafana access
grafana_default_admin_user: "adm"
grafana_default_admin_password: ""
# Enable prometheus which is a time series database for 
# holding metrics
prometheus_enabled: true
# Addon to prometheus that collects generic system 
# information such as CPU, memory, filesystem, and even 
# system temperatures
prometheus_node_exporter_enabled: true

# Addon to prometheus that collects metrics about postgres
prometheus_postgres_exporter_enabled: true
# You can remove this, if unnecessary.
prometheus_nginxlog_exporter_enabled: true
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

#matrix_bot_chatgpt_enabled: false
#etherpad_enabled: false
# Switch to the domain used for Matrix services (`matrix.DOMAIN`),
# so we won't need to add additional DNS records for Etherpad.
#etherpad_hostname: "{{ matrix_server_fqn_matrix }}"


postgres_backup_enabled: true
postgres_backup_base_path: "/mnt/backup/postgres-backup"
postgres_backup_data_path: "/mnt/backup/data"
postgres_backup_keep_months: 3
matrix_synapse_federation_enabled: false

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
matrix_bot_baibot_config_agents_static_definitions_custom:
  # This agent will use the GPT 3.5 model and will only support text-generation,
  # even though the `openai` provider could support other features (e.g. image-generation).
  - id: llama3.1:8b-agent
    provider: openai
    config:
        base_url: http://uri:11434/v1
        api_key: ""
        text_generation:
          model_id: "llama3.1"
          prompt: "You are a brief, but helpful bot called bai bot."
          temperature: 1.0
          max_response_tokens: 4096
          max_context_tokens: 16385
        speech_to_text: null
        text_to_speech: null
        image_generation: null
#
matrix_synapse_auto_accept_invites_enabled: true

# Default settings below. Uncomment and adjust if necessary.
# matrix_synapse_auto_accept_invites_only_for_direct_messages: false
# matrix_synapse_auto_accept_invites_only_from_local_users: false

# If workers are enabled, you may delegate usage to a specific worker.
# matrix_synapse_auto_accept_invites_worker_to_run_on: 'matrix-synapse-worker-generic-0'
matrix_synapse_workers_enabled: false
#matrix_synapse_workers_preset: specialized-workers
server_notices:
  system_mxid_localpart: notices
  system_mxid_display_name: "Element Admin"
#   system_mxid_avatar_url: "mxc://server.com/oumMVlgDnLYFaPVkExemNVVZ"
  room_name: "Element Admin"

# Adjust this to your room ID
#matrix_bot_honoroit_roomid: "!room.server.com"
matrix_client_element_themes_enabled: true
#matrix_alertmanager_receiver_enabled: true

# Controls whether container networks will be created with IPv6 support.
#
# If you also have IPv6 support on your server/network and AAAA DNS records pointing to the server,
# enabling this will effectively give you full public IPv6 connectivity (powered by NAT66).
#
# We recommend leaving this enabled even if you don't currently have IPv6 connectivity on your server/network.
# This way, once you eventually get IPv6 connectivity, you won't have to change anything (besides DNS records).
#
# Flipping this setting later on requires manual work (stopping services, deleting and recreating all container networks).
#
# In the future, this setting will likely default to `true`, so if you really want IPv6 disabled, explicitly set this to `false`.
#
# People managing Docker themselves and running an older Docker version will need additional configuration.
#
# Learn more in `docs/configuring-ipv6.md`.
#devture_systemd_docker_base_ipv6_enabled: true
#matrix_playbook_docker_installation_daemon_options_custom:
#  default-address-pools: [
#    { "base": "172.17.0.0/16", "size": 16 },
#    { "base": "172.18.0.0/16", "size": 16 },
#    { "base": "172.19.0.0/16", "size": 16 },
#    { "base": "172.20.0.0/16", "size": 16 },
#    { "base": "172.21.0.0/16", "size": 16 },
#    { "base": "172.22.0.0/16", "size": 16 },
#    { "base": "172.23.0.0/16", "size": 16 },
#    { "base": "172.24.0.0/16", "size": 16 },
#    { "base": "172.25.0.0/16", "size": 16 },
#    { "base": "172.26.0.0/16", "size": 16 },
#    { "base": "fe80::/64", "size": 64 }
#  ]
#  fixed-cidr-v6: "fe80::/64"
#matrix_playbook_docker_installation_enabled: false
```

Need ur help, thx
