### ISSUE TITLE
Traefik is using a lot of RAM and occasionally restarts.

### ISSUE THREAD

**Issue by vnavalianyi** [spantaleev/matrix-docker-ansible-deploy#4228]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: 
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: ''
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
traefik_config_certificatesResolvers_acme_email: ''
traefik_version: v3.3.1
traefik_config_log_level: WARN
postgres_connection_password: ''
matrix_synapse_admin_enabled: true
matrix_coturn_turn_static_auth_secret: ''
matrix_homeserver_generic_secret_key: ''
matrix_homeserver_federation_enabled: false
# matrix_sliding_sync_enabled: true

postgres_backup_enabled: true

prometheus_enabled: true
prometheus_node_exporter_enabled: true
prometheus_postgres_exporter_enabled: true
grafana_enabled: true
grafana_anonymous_access: false
grafana_default_admin_user: ""
grafana_default_admin_password: ""

matrix_synapse_usage_exporter_enabled: true

backup_borg_enabled: true
backup_borg_location_repositories:
 - ssh:./repo
backup_borg_storage_encryption_passphrase: ""
backup_borg_ssh_key_private: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  -----END OPENSSH PRIVATE KEY-----

backup_borg_storage_archive_name_format: backup-borg-{now:%Y-%m-%d-%H%M%S}
backup_borg_retention_keep_hourly: 0
backup_borg_retention_keep_daily: 7
backup_borg_retention_keep_weekly: 4
backup_borg_retention_keep_monthly: 12
backup_borg_retention_keep_yearly: 2
```

**Matrix Server:**
 - OS: Ubuntu 24.10"
 - Architecture: amd64
 - Cloud: DigitalOcean

**Problem description**:
Hi, my Traefik is using a lot of RAM and occasionally restarts and users get error:
❗ Some of your messages were not sent
You can select all or individual messages to retry or delete

**Additional context**

![Image](https://github.com/user-attachments/assets/a0b20e49-f9ec-4b61-b678-663254b53f79)

![Image](https://github.com/user-attachments/assets/e59f1447-83fc-4b18-bc74-9fc97d8c356c)
