### ISSUE TITLE
Cannot access Element via prefix path anymore

### ISSUE THREAD

**Issue by sergiodj** [spantaleev/matrix-docker-ansible-deploy#4250]
**Describe the bug**

Hello,

I've upgraded my deployment using the latest commit today (b35289cae) and now I can't access my Element client anymore.

I run the client inside a path prefix (`https://example.com/element`), and upon checking the Traefik labels they seem OK.

I went down a rabbit hole trying to find what's wrong, and I found that:

- I can ping but I can't connect to `http://matrix-client-element:8080` inside the Traefik container.
- I can't access `http://localhost:8080` inside the Element container.
- The nginx process doesn't seem to be listening to port 8080 inside the Element container.

I can see that the file `/etc/nginx/templates/default.conf.template` has references to `ELEMENT_WEB_PORT`:

```
~ $ cat /etc/nginx/templates/default.conf.template 
server {
    listen       ${ELEMENT_WEB_PORT};
    listen  [::]:${ELEMENT_WEB_PORT};
    server_name  localhost;
...
```

but `/etc/nginx/nginx.conf` doesn't (and it doesn't refer to the template file either).  Not sure if this is expected, though.

Here's what I have in my `vars.yaml` pertaining to Element:

```yaml
# Enable element
matrix_client_element_enabled: true
matrix_client_element_hostname: "matrix.example.com"
matrix_client_element_path_prefix: "/element"
matrix_client_element_default_theme: "dark"
matrix_client_element_themes_enabled: true
# Don't redirect main domain to element.
matrix_synapse_container_labels_public_client_root_redirection_url: ""
matrix_client_element_room_directory_servers: ['matrix.org', 'matrix.debian.social', 'matrixrooms.info']
```

I don't have any proof, but I'm thinking that maybe e65d198841b4bcd84224fae9c739bdd71c8537eb is the culprit here.

I'm happy to provide more info if needed.  Thanks.
