### ISSUE TITLE
"Insufficient capacity" when joining video room

### ISSUE THREAD

**Issue by INNKCake** [spantaleev/matrix-docker-ansible-deploy#4281]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
matrix_domain: server-name.org

matrix_homeserver_implementation: synapse

#Configure workers
matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: one-of-each
matrix_synapse_report_stats: false
matrix_homeserver_federation_enabled: true

#Configure element-web
matrix_client_element_default_country_code: "redacted"
matrix_client_element_themes_enabled: true
matrix_client_element_themes_repository_url: "https://github.com/aaronraimist/element-themes.git"

#Enable double-puppeting for bridges (https://docs.mau.fi/bridges/general/double-puppeting.html)
matrix_appservice_double_puppet_enabled: true

#Add admin webgui
matrix_synapse_admin_enabled: true

#Shared secret
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "redacted"

#Enabled bridges
matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_logging_level: 'debug'

matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: 'redacted'
matrix_mautrix_telegram_api_hash: 'redacted'

matrix_element_call_enabled: true

matrix_synapse_enable_registration: true
matrix_synapse_registration_requires_token: true

matrix_homeserver_generic_secret_key: 'redacted'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
matrix_playbook_ssl_enabled: true
traefik_config_entrypoint_web_secure_enabled: false
traefik_container_web_host_bind_port: '127.0.0.1:81'
traefik_config_entrypoint_web_forwardedHeaders_insecure: true

matrix_playbook_public_matrix_federation_api_traefik_entrypoint_host_bind_port: '127.0.0.1:8449'
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_http3_enabled: false
matrix_playbook_public_matrix_federation_api_traefik_entrypoint_config_custom:
  forwardedHeaders:
    insecure: true
  # trustedIPs: ['IP-ADDRESS-OF-YOUR-REVERSE-PROXY']

devture_systemd_docker_base_ipv6_enabled: true

postgres_connection_password: 'redacted'

exim_relay_sender_address: "redacted"
exim_relay_relay_use: true
exim_relay_relay_host_name: "redacted"
exim_relay_relay_host_port: 587
exim_relay_relay_auth: true
exim_relay_relay_auth_username: "redacted"
exim_relay_relay_auth_password: "redacted"

```
**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture arm64

**Problem description**:
Hello,

When I'm trying to join a video room, *Insufficient capacity* error appears moments after joining and server kicks me out.

![Image](https://github.com/user-attachments/assets/7ce8ce75-7174-4768-953d-f06337ff1460)

The same happens if I try to video-call another user in private messages. Audio-only works fine. Interestingly though, if I select Legacy option for video-call in Element Desktop, it works fine. 
From Element Android app I'm able to join a video room , but it creates a call via Jitsi, and it's not accessible from other clients (Element Web and Element Desktop). (Maybe I need to update an app on Android)

Logs for matrix-livekit-jwt-service shows requests:
```
Apr 27 21:22:00 servername matrix-livekit-jwt-service[4547]: 2025/04/27 21:22:00 Request from 172.25.0.6:59500 at "vector://vector"
Apr 27 21:22:00 servername matrix-livekit-jwt-service[4547]: 2025/04/27 21:22:00 Got user info for @username:servername
```

Logs for matrix-livekit-server empty besides startup info(expected behavior?)
Logs for coturn show nothing if I try to connect to video room, but works as expected when I'm calling in private messages.

`.well-known` both for matrix.server-name.org and server-name.org are equal:
```
{
    "cc.etke.synapse-admin": {
        "asManagedUsers": [
            "^@discordbot:server\\-name\\.org$",
            "^@discord_[0-9]+:server\\-name\\.org$",
            "^@telegrambot:server\\-name\\.org$",
            "^@telegram_[a-zA-Z0-9]+:server\\-name\\.org$",
        ],
        "menu": [],
        "restrictBaseUrl": [
            "https://matrix.server-name.org"
        ]
    },
    "m.homeserver": {
        "base_url": "https://matrix.server-name.org"
    },
    "org.matrix.msc4143.rtc_foci": [
        {
            "livekit_service_url": "https://matrix.server-name.org/livekit-jwt-service",
            "type": "livekit"
        }
    ]
}
```
I assume I'm missing something in configuration of livekit/element-call, but honestly I can't tell at this point.
