### ISSUE TITLE
truying to add exter config for ntfy

### ISSUE THREAD

**Issue by cchalifo999** [spantaleev/matrix-docker-ansible-deploy#4282]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
#enable: Ntfy server
ntfy_enabled: true
ntfy_hostname: ntfy.cchalifo.net
ntfy_auth_default_access: 'deny-all'
ntfy_enable_login: 'true'
```

**Matrix Server:**
 - OS: manjaro
 - Architecture  amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible — e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

**Client (please complete the following information):**

**Additional context**
