### ISSUE TITLE
[Feat] Provide cron job for backing up database

### ISSUE THREAD

**Issue by abeluck** [spantaleev/matrix-docker-ansible-deploy#429]
I imagine many users would like to have automatic backups of the database available.

Ideally the postgres role could also provide a script and cron job that performs the backup. It could be controlled with a few simple variables, here are some suggested defaults:

```yaml
matrix_postgres_backup_enabled: true
matrix_postgres_backup_location: /matrix/postgres/backups
matrix_postgres_backup_cron_schedule: @daily
```
Then when combined with a backup tool like borg, tarsnap, or even rsync, it would be dead simple to ensure the matrix deployment is backed up.

Obviously large deployments might have perf issues with daily backups, but I suspect they should be/are using external an postgres server anyways.
