### ISSUE TITLE
Enable public registration for new users doesn't work since MAS migration

### ISSUE THREAD

**Issue by piipouzusaki** [spantaleev/matrix-docker-ansible-deploy#4349]
Hi everyone,

I have a problem since migrating from Synapse to MAS.
User login is functional. However, I can't reactivate registration via Synapse. I get this error message saying “Registration cannot be enabled when OAuth delegation is enabled”.

After searching, I saw that the MSC3824 and MCS2966 are mandatory for operation, but I couldn't find how to do it.

Is this normal and a known bug?
Or have I done something wrong in the configuration?

Thanks in advance for your help.

**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
valkey_enabled: false
#
# Example value: example.com
matrix_domain: example.com

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse
#postgres_managed_databases_postgres_start_wait_timeout_seconds: 45
# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'onwoivnweowinoivwneowinvwoivnevwdecoirv4oivnodinvinwovneworivn'

matrix_authentication_service_enabled: true

# Generate this encryption secret with: `openssl rand -hex 32`
matrix_authentication_service_config_secrets_encryption: '23ck43f34ieck34f2eci24fwievc24f2iev2if2wriv24firv3vi3rie3vir34irec3i4'


matrix_authentication_service_config_upstream_oauth2_providers:
  - id: 01JVQNAY1P5BWRA613Y1S32EVS
    synapse_idp_id: oidc-SMINE
    issuer: "https://mine.test.net/"
    human_name: "SMINE Mail"
    client_id: "sdc33234f34"
    client_secret: "f34fffvrv34fe3cwef35g3g3ig3u5gfi3g34ke"
    authorization_endpoint: "https:/mine.test.net.net/oauth/authorize"
    token_endpoint: "https:/mine.test.net.net/oauth/token"
    userinfo_endpoint: "https:/mine.test.net.net/oauth/profile"
    token_endpoint_auth_method: client_secret_post
    scope: "profile"
    claims_imports:
      subject:
        template: "username"
      displayname:
        action: suggest
        template: "{% raw %}{{ user.displayName }}{% endraw %}"
      email:
        action: force
        template: "{% raw %}{{ user.username }}{% endraw %}"

# When migrating an existing homeserver to Matrix Authentication Service, uncomment the line below.
# Learn more about the migration process in the "Marking an existing homeserver for migration" section below.
# For brand-new installations which start directly on MAS, this line can be removed.
matrix_authentication_service_migration_in_progress: false

# Change the default hostname and path prefix
#matrix_authentication_service_hostname: mine.test.net
#matrix_authentication_service_path_prefix: /

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
postgres_connection_password: 'we;mcrverveowew#3fwevdw2@1rpvepdv3@rf34'

#matrix_synapse_workers_enabled: true
#matrix_synapse_workers_preset: one-of-each

matrix_synapse_configuration_extension_yaml: |
  server_notices:
    system_mxid_localpart: notices
    system_mxid_display_name: "Server Notices"
    system_mxid_avatar_url: "mxc://example.com/oumMVlgDnLYFaPVkExemNVVZ"
    room_name: "Server Notices"
  user_directory:
    enabled: true
    search_all_users: true



#matrix_synapse_oidc_enabled: true
#
#matrix_synapse_oidc_providers:
#    - idp_id: SMINE_Mail
#      discover: false
#      issuer: "https:/mine.test.net.net/"
#      idp_name: "SMINE Mail"
#      client_id: "sdc33234f34"
#      client_secret: "f34fffvrv34fe3cwef35g3g3ig3u5gfi3g34ke"
#      scopes: ["profile"]
#      authorization_endpoint: "https:/mine.test.net.net/oauth/authorize"
#      token_endpoint: "https:/mine.test.net.net/oauth/token"
#      userinfo_endpoint: "https:/mine.test.net.net/oauth/profile"
#      user_profile_method: "userinfo_endpoint"
#      client_auth_method: "client_secret_post"
#      skip_verification: true
#      allow_existing_users: true
#      user_mapping_provider:
#        config:
#            subject_claim: "username"
#            display_name_template: "{% raw %}{{ user.displayName }}{% endraw %}"
#            email_template: "{% raw %}{{ user.username }}{% endraw %}"



#A vérifier pour Admin
matrix_synapse_admin_enabled: true

#matrix_synapse_enable_registration: true

matrix_synapse_federation_enabled: false
matrix_synapse_federation_port_enabled: false


matrix_registration_enabled: true
# Generate a strong secret here. You can create one with a command like `pwgen -s 64 1`.
matrix_registration_admin_secret: "w23d2e23f42f3ef23r1fc3ref34ofv3ro3fj34v30343jf20fj3f4f0wjerv34"

exim_relay_sender_address: "noreply@smine.net"
exim_relay_relay_use: true
exim_relay_relay_host_name: "mine.test.net"
exim_relay_relay_host_port: 587
exim_relay_relay_auth: true
exim_relay_relay_auth_username: "noreply@smine.net"
exim_relay_relay_auth_password: "wecwecfce1fe!3fec3"

matrix_synapse_registrations_require_3pid:
 - email
matrix_synapse_autocreate_auto_join_rooms: false

matrix_static_files_container_labels_base_domain_enabled: true


#postgre backup
postgres_backup_enabled: true
postgres_backup_schedule: "@daily"
postgres_backup_keep_days: 2
postgres_backup_base_path: "{{ matrix_base_data_path }}/postgres-backup"

# DB Version: 14
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 8 GB
# CPUs num: 3
# Connections num: 1000
# Data Storage: ssd



postgres_process_extra_arguments: [
  "-c max_connections=1000",
  "-c shared_buffers=3GB",
  "-c effective_cache_size=9GB",
  "-c maintenance_work_mem=768MB",
  "-c checkpoint_completion_target=0.9",
  "-c wal_buffers=16MB",
  "-c default_statistics_target=100",
  "-c random_page_cost=1.1",
  "-c effective_io_concurrency=200",
  "-c work_mem=5242kB",
  "-c huge_pages=off",
  "-c min_wal_size=1GB",
  "-c max_wal_size=4GB",
  "-c max_worker_processes=6",
  "-c max_parallel_workers_per_gather=3",
  "-c max_parallel_workers=6",
  "-c max_parallel_maintenance_workers=3",
]


prometheus_enabled: true
prometheus_node_exporter_enabled: true
  #grafana_enabled: true
  #grafana_anonymous_access: false
  #grafana_default_admin_user: "adm_stats_smine"
  #grafana_default_admin_password: "cwec#42ecwv3SEV4ceq"

#matrix_synapse_ext_password_provider_shared_secret_auth_enabled: false
#matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "8absuYhojNebGlVp2VYSi1Y2azqa7Qm8Iwo0IWKzIxIvyjDfN4rMPC2wnVRUXWNS"


# Enable the Element Call frontend UI to allow standalone use of Element Call.
# Enabling this also auto-enables the Matrix RTC stack.
matrix_rtc_enabled: true

matrix_sliding_sync_enabled: true

matrix_playbook_reverse_proxy_type: playbook-managed-traefik

matrix_appservice_double_puppet_enabled: true
#matrix_playbook_docker_installation_enabled: false
#matrix_mautrix_signal_enabled: true
matrix_synapse_container_labels_public_client_synapse_admin_api_enabled: true
```

**Matrix Server:**
 - OS: Debian 12
 - Architecture amd64

**Problem description**:

I have a problem since migrating from Synapse to MAS.
User login is functional. However, I can't reactivate registration via Synapse. I get this error message saying “Registration cannot be enabled when OAuth delegation is enabled”.

After searching, I saw that the MSC3824 and MCS2966 are mandatory for operation, but I couldn't find how to do it.

Is this normal and a known bug?
Or have I done something wrong in the configuration?

Thanks in advance for your help.

**Comment by spantaleev** [comment]
You may be able to enable the experimental features for these MSCs in Synapse, using the following configuration:

```yml
matrix_synapse_configuration_extension_yaml:
  experimental_features:
    msc_2966_enabled: true
    msc_3824_enabled: true
```

For other experimental features, we have dedicated variables (e.g. `matrix_synapse_experimental_features_msc2409_to_device_messages_enabled`) in `roles/custom/matrix-synapse/defaults/main.yml` which are also wired into `roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2`, but for MSC3824 and MCS2966 we don't yet have such variables, so you need to resort to using `matrix_synapse_configuration_extension_yaml`.

Having dedicated variables not only makes it easier to enable additional experimental features, but also allows the playbook to auto-enable certain features when certain components are installed.

Here's an example: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/312b4826f01751080f440bd15d01a1d819d98546/group_vars/matrix_servers#L4946-L4952

------

All that said, searching through the [Synapse](https://github.com/element-hq/synapse/) source code and looking at https://github.com/element-hq/synapse/blob/v1.130.0/synapse/config/experimental.py **there doesn't seem to be anything about MSC2966 or MSC3824 there, so the above configuration won't do anything**.

It appears that these features are either no longer experimental today (so there's no flag for enabling them), or these MSCs are about things implemented elsewhere (e.g. on the MAS side, not on the Synapse side). Perhaps something needs to be enabled or otherwise-configured elsewhere.
