### ISSUE TITLE
Email addresses/phone numbers do not show up in the Settings tab

### ISSUE THREAD

**Issue by schopenhauer** [spantaleev/matrix-docker-ansible-deploy#503]
The issue has already been reported in the following [bug report](https://github.com/vector-im/riot-web/issues/13033#) logged in the `riot-web` repo.

Potential solution would be to add the ACAO directive to the reverse proxy - to be tested.

```
add_header Access-Control-Allow-Origin *;
```

**Comment by ns130291** [comment]
Adding the header in the reverse proxy (in my case haproxy) solves the CORS error in the browser but doesn't help with the `405 Method Not Allowed` error. 
I guess the header isn't set when this error occurs as all other responses from the identity module have `Access-Control-Allow-Origin: *` set.

**Comment by t2d** [comment]
running with `-t self-check` doesn't report any problems but this issue persists

**Comment by 0x46616c6b** [comment]
Maybe that is related to #511. If `ma1sd` not configured with enabled `v2` api prefix Riot reports a problem with CORS (405 Method not allowed).

**Comment by ns130291** [comment]
with the new change I'm no longer getting the 405 error, but now it says `401 Unauthorized`

**Comment by rootuser** [comment]
I can confirm that the actual release fixes the CORS header problem.
Alas I have issues with ma1sd instead; 

The identity server is requested for 3PIDs, but fails with the followin error (from the Javascript console:)

> Unable to reach identity server at https://matrix.myserver.de to check for 3PIDs bindings in Settings
> Error: Unsupported identity server: bad response

Do you think that would be fixed in the new ma1sd release with v2 enabled?

**Comment by spantaleev** [comment]
You can try the ma1sd RC by putting this in your `vars.yml` file:

```yaml
matrix_ma1sd_docker_image: "ma1uta/ma1sd:2.4.0-rc1"
```

Let us know if it helps! If not, you can report the issue at the [ma1sd](https://github.com/ma1uta/ma1sd) repository.

**Comment by rootuser** [comment]
Thanks for your reply!

I did try it but, alas, to no avail. I will report the bug.

**Comment by spantaleev** [comment]
Bug seems to be reported here: https://github.com/ma1uta/ma1sd/issues/48

**Comment by jmastr** [comment]
@spantaleev ma1sd v2.4.0 is now released, but the bug is still present. I can confirm this error:
```
Unable to reach identity server at https://matrix.trust2core.rocks to check for 3PIDs bindings in Settings
```

On a side note: if I switch from my Identity Server to https://vector.im, it gives me an error saying that it cannot delete the data on my Identity Server because it is not reachable.

**Comment by jmastr** [comment]
For me solution was to add this to ma1sd config:
```
hashing:
  enabled: true # enable or disable the hash lookup MSC2140 (default is false)
  pepperLength: 20 # length of the pepper value (default is 20)
  rotationPolicy: per_requests # or `per_seconds` how often the hashes will be updating
  hashStorageType: sql # or `in_memory` where the hashes will be stored
  algorithms:
    - none   # the same as v1 bulk lookup
    - sha256 # hash the 3PID and pepper.
  delay: 2m # how often hashes will be updated if rotation policy = per_seconds (default is 10s)
  requests: 10 # how many lookup requests will be performed before updating hashes if rotation policy = per_requests (default is 10)
```
https://github.com/ma1uta/ma1sd/blob/master/docs/MSC2140_MSC2134.md#hash-lookup
