### ISSUE TITLE
Matrix & Discord-Bridge UX / Integration: Allow bridging of discord guilds to matrix communities

### ISSUE THREAD

**Issue by jdreichmann** [spantaleev/matrix-docker-ansible-deploy#561]
The mx-puppet-discord bridge support bridging guilds to matrix communities, but need `enable_group_creation: true` in the homeserver.yaml, currently controlled by `matrix_synapse_enable_group_creation`.

The mx-puppet-discord bridge further needs `bridge.enableGroupSync=true` in the config in order to bridge guilds from discord into a matrix community.

See: https://github.com/Sorunome/mx-puppet-bridge#group-mapping

**Comment by izissise** [comment]
As a temporary workaround, it can achieve using yaml extension, 

As an example, here is what I have in my host_var file:

```
# Allow group creation from bridges
matrix_synapse_configuration_extension_yaml: |
  enable_group_creation: true
  group_creation_prefix: ""

matrix_mx_puppet_discord_configuration_extension_yaml: |
  bridge:
    enableGroupSync: true

matrix_mx_puppet_slack_configuration_extension_yaml: |
  bridge:
    enableGroupSync: true
```
