### ISSUE TITLE
Option to clean old media-store files

### ISSUE THREAD

**Issue by AlwaysLivid** [spantaleev/matrix-docker-ansible-deploy#584]
I run my Matrix instance on a Raspberry Pi 4 with very limited space, and most of the old files/thumbnails are unnecessary to me.

It'd be great to have a Playbook integration that would allow you to either clean **all** of these files safely, or, alternatively, **depending on how old they are**.

**Comment by Broglah1** [comment]
has anyone worked out how to do this yet?

**Comment by aaronraimist** [comment]
Synapse has admin APIs for deleting remote and local media. https://github.com/matrix-org/synapse/blob/master/docs/admin_api/media_admin_api.md

Note that once you delete local media it is gone forever. Remote media can most likely be fetched again in the future from the remote server (unless they have deleted their local media).

**Comment by spantaleev** [comment]
This is now supported. Synapse gained a native `media_retention` setting, and the playbook exposes it through these variables in your `vars.yml`:

```yaml
# Delete local media (uploads by your own users) older than this
matrix_synapse_media_retention_local_media_lifetime: 90d

# Delete cached remote media (downloaded from other homeservers) older than this
matrix_synapse_media_retention_remote_media_lifetime: 14d
```

Both are disabled by default. Once set, Synapse periodically deletes media older than the configured lifetime on its own, so no extra playbook tooling or cron job is needed. Note that deleted local media is gone for good, while remote media can usually be re-fetched from the origin server.

For one-off manual cleanup, Synapse's [media admin APIs](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html) remain an option, as mentioned above.

Closing as implemented. If you find a gap that these settings do not cover, feel free to comment and we can reopen.
