### ISSUE TITLE
user_consent / configuration of homerserver.yaml.j2

### ISSUE THREAD

**Issue by CodingAnonymous** [spantaleev/matrix-docker-ansible-deploy#600]
I want to configure the user_consent. Therefore I uncommented the following code inside the `homeserver.yaml.j2`:
```
user_consent:
  template_dir: res/templates/privacy
  version: 1.0
  server_notice_content:
    msgtype: m.text
    body: >-
      To continue using this homeserver you must review and agree to the
      terms and conditions at %(consent_uri)s
  send_server_notice_to_guests: True
  block_events_error: >-
    To continue using this homeserver you must review and agree to the
    terms and conditions at %(consent_uri)s
  require_at_registration: False
  policy_name: Privacy Policy
```

I'm not sure wether `homeserver.yaml.j2` is the correct place to put this so I tried it with `matrix_synapse_configuration_extension_yaml` but didn't find a working example for this command.

I'll get following error after running the playbook with the configuration above:
`{"ansible_loop_var": "item", "changed": false, "item": "matrix-synapse", "msg": "matrix-synapse was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-synapse` and `journalctl -fu matrix-synapse` on the server to investigate."}`

Where should I put the user_consent code? Could somebody give me a working example?

How should I create the template_dir? I found this link with an example: https://github.com/matrix-org/synapse/tree/master/docs/privacy_policy_templates/en
But I'm not sure wether I should copy this complete directory inside into the directory  `config/res/templates/privacy` with `template_dir: res/templates/privacy` or only a single file? Please help me!

**Comment by spantaleev** [comment]
You're supposed to use `matrix_synapse_configuration_extension_yaml`, yes.

An example would be:

```yaml
matrix_synapse_configuration_extension_yaml: |
  user_consent:
    template_dir: res/templates/privacy
    version: 1.0
    server_notice_content:
      msgtype: m.text
      body: >-
        To continue using this homeserver you must review and agree to the
        terms and conditions at %(consent_uri)s
    send_server_notice_to_guests: True
    block_events_error: >-
      To continue using this homeserver you must review and agree to the
      terms and conditions at %(consent_uri)s
    require_at_registration: False
    policy_name: Privacy Policy
```

Not sure about the template paths though. Perhaps those files don't have some defaults in Synapse and you need to define them manually?

If so, you can put files in `/matrix/synapse/config/...`, which later gets mounted to `/data` (within the container). Make sure the files are owned by the `matrix` user and group, so that they're readable inside the container.
