### ISSUE TITLE
Cannot compile element-web on arm64

### ISSUE THREAD

**Issue by AlwaysLivid** [spantaleev/matrix-docker-ansible-deploy#604]
# Error log

```
TASK [matrix-client-element : Ensure Element Docker image is built] **********************************************************************************
fatal: [matrix.livid.pw]: FAILED! => {"changed": false, "msg": "Error building vectorim/riot-web - code: 134, message: The command '/bin/sh -c yarn --network-timeout=100000 install' returned a non-zero code: 134, logs: ['Step 1/18 : FROM node:10 as builder', '\\n', ' ---> 5bc5b1f1e265\\n', 'Step 2/18 : ARG USE_CUSTOM_SDKS=false', '\\n', ' ---> Using cache\\n', ' ---> 06f13181a65b\\n', 'Step 3/18 : ARG REACT_SDK_REPO=\"https://github.com/matrix-org/matrix-react-sdk.git\"', '\\n', ' ---> Using cache\\n', ' ---> 8210ce4e24f1\\n', 'Step 4/18 : ARG REACT_SDK_BRANCH=\"master\"', '\\n', ' ---> Using cache\\n', ' ---> a7c73774b58b\\n', 'Step 5/18 : ARG JS_SDK_REPO=\"https://github.com/matrix-org/matrix-js-sdk.git\"', '\\n', ' ---> Using cache\\n', ' ---> 22406f438873\\n', 'Step 6/18 : ARG JS_SDK_BRANCH=\"master\"', '\\n', ' ---> Using cache\\n', ' ---> e9ae0f707508\\n', 'Step 7/18 : RUN apt-get update && apt-get install -y git dos2unix', '\\n', ' ---> Using cache\\n', ' ---> dc18747d3bae\\n', 'Step 8/18 : WORKDIR /src', '\\n', ' ---> Using cache\\n', ' ---> c11b5a845432\\n', 'Step 9/18 : COPY . /src', '\\n', ' ---> 05655d55c20d\\n', 'Step 10/18 : RUN dos2unix /src/scripts/docker-link-repos.sh && bash /src/scripts/docker-link-repos.sh', '\\n', ' ---> Running in 3fffb44009cf\\n', '\\x1b[91mdos2unix: converting file /src/scripts/docker-link-repos.sh to Unix format...\\n\\x1b[0m', '\\x1b[91m++ git rev-parse --abbrev-ref HEAD\\n\\x1b[0m', '\\x1b[91m+ BRANCH=HEAD\\n\\x1b[0m', 'skipping react-sdk and js-sdk installs: USE_CUSTOM_SDKS is false\\n', \"\\x1b[91m+ '[' false == false ']'\\n+ '[' HEAD == develop ']'\\n+ '[' false == false ']'\\n+ echo 'skipping react-sdk and js-sdk installs: USE_CUSTOM_SDKS is false'\\n+ exit 0\\n\\x1b[0m\", 'Removing intermediate container 3fffb44009cf\\n', ' ---> c1dcc5fd5108\\n', 'Step 11/18 : RUN yarn --network-timeout=100000 install', '\\n', ' ---> Running in 8ae18faf5d01\\n', '\\x1b[91mAborted (core dumped)\\n\\x1b[0m', 'Removing intermediate container 8ae18faf5d01\\n']"}
```

## Steps to reproduce
- Set `matrix_client_element_enabled` as `true` under `vars.yml`. (Optional, enabled by default)
- `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start -k -K`

**Comment by fadecaps** [comment]
I have run into this issue previously, and my solution is for before the change from riot-web, but should still fix this issue. Need to pass the actual path to the pkgconfig to the docker build command.
--

I have been able to fix this bug with edits to `roles/matrix-riot-web/tasks/setup_riot_web.yml`

The only necessary change is to make sure that `PKG_CONFIG_PATH` is passed to the `docker_image` task using the build args command.
```
- name: Ensure Riot Web Docker image is built
  docker_image:
    name: "{{ matrix_riot_web_docker_image }}"
    source: build
    build:
      args:
        PKG_CONFIG_PATH: "/usr/lib/aarch64-linux-gnu/pkgconfig"
      dockerfile: Dockerfile
      path: "{{ matrix_riot_web_docker_src_files_path }}"
      pull: yes
  when: "matrix_riot_web_enabled|bool and matrix_riot_web_container_image_self_build"
```
