### ISSUE TITLE
"matrix-nginx-proxy" starts even if matrix_nginx_proxy_enable is set to false, when synapse_admin is enabled

### ISSUE THREAD

**Issue by bachrc** [spantaleev/matrix-docker-ansible-deploy#637]
So I want to provide my own Nginx (as the documentation permits it here : https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md )

But every time I launch the playbook, even if I sat my `matrix_nginx_proxy_enable` to false (following the option 1 in the documentation I previously linked) : the `matrix-nginx-proxy` container is started, exposing its ports. Blocking me from exposing MY Nginx. 

Here is my configuration :

```yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# Example value: example.com
matrix_domain: dessert.coffee

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: bachrc@dessert.coffee

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "mysecret"

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "mysecret"

matrix_nginx_proxy_enable: false
matrix_nginx_proxy_ssl_protocols: "TLSv1.2"
matrix_ssl_retrieval_method: none

matrix_synapse_admin_enabled: true

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: mysecret

#matrix_synapse_ext_spam_checker_synapse_simple_antispam_enabled: true

matrix_mautrix_whatsapp_enabled: true
matrix_mautrix_facebook_enabled: true
```

And I'm quite lost, because I didn't do anything exotic. So it seems weird. My server is Debian 9, vanilla.

Thanks in advance
