### ISSUE TITLE
[Signal bridge] E2BE doesn't seem to work

### ISSUE THREAD

**Issue by tchapi** [spantaleev/matrix-docker-ansible-deploy#806]
I get: `Your message was not bridged: the bridge hasn't received the decryption keys. If this error keeps happening, try restarting your client.`

![Screenshot 2021-01-22 at 13 38 56](https://user-images.githubusercontent.com/1944007/105491855-52a13800-5cb7-11eb-86ad-82925c464eef.png)

I have no clue if it is a missing configuration on my side or if I'm supposed to do something else.

Here is the relevant configuration I used :

```
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "TEST"

matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
```

Thanks a lot !

**Comment by tchapi** [comment]
NB: I have the exact same behaviour with the Telegram bridge

**Comment by spantaleev** [comment]
Asking in the Signal/Telegram rooms (or issues) may be better. Let us know if we need some playbook adjustments to make this work.

**Comment by tchapi** [comment]
Thanks for your quick answer @spantaleev — and thanks for your great work on these playbooks !

**Comment by tchapi** [comment]
Hi @spantaleev 

It seems that the playbook might need a little fix for the registration files for the Telegram and the Signal bridge. See https://github.com/tulir/mautrix-signal/issues/43#issuecomment-767496745 for more details

It doesn't look that difficult to implement and would be nice to have the 2BE2 feature that works on these two bridges by default.

Do you think that it's feasible on your side ?
Thanks a lot for your time !
BR

**Comment by theCalcaholic** [comment]
FYI: This seems to apply to all mautrix bridges

**Comment by spantaleev** [comment]
Seems like it requires manual action?

Fortunately, it only affects people who enable encryption to the bridge, the point of which is dubious/pointless.. Unless I miss something. ... but... layered security, I guess.

Still, we should fix it.. We can easily adjust our registration files. The question is.. perhaps we need to adjust the installation instructions as well..? Should we complicate things for everyone or just for the people who enable encryption?

**Comment by theCalcaholic** [comment]
@spantaleev The point of E2B encryption is hosting your own bridge while using someon else's home server. That's what most of the users of my bridges do

**Comment by tchapi** [comment]
@tulir mentions that "This playbook brings its own registration file instead of having the bridge generate one, that file has not applied the workaround mentioned in the wiki. Even the latest versions of Synapse are broken (matrix-org/synapse#5758), so the workaround is still required."

So it seems that we would need to let the playbook generate the registration file, then adjust it if we need, if I understand correctly ? I admit that I'm pretty confused as to how to apply the workaround TBH

**Comment by spantaleev** [comment]
You can apply it right now by:
- either manually editing the registration file on the server (bad idea; it will get overwritten by the playbook on the next run)
- *or* by modifying the registration file template that the playbook uses (better)

The playbook reads a template file into this variable: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/07f1ea24eed34ceb6b2bc3d155335e34914b1f77/roles/matrix-bridge-mautrix-signal/defaults/main.yml#L91

Here's the template: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/07f1ea24eed34ceb6b2bc3d155335e34914b1f77/roles/matrix-bridge-mautrix-signal/templates/registration.yaml.j2

You can define it all inline in your `vars.yml` file though:

```yaml
matrix_mautrix_signal_registration_yaml: |
  #jinja2: lstrip_blocks: "True"
  id: signal
  as_token: "{{ matrix_mautrix_signal_appservice_token }}"
  hs_token: "{{ matrix_mautrix_signal_homeserver_token }}"
  namespaces:
      users:
      - exclusive: true
        regex: '^@signal_.+:{{ matrix_mautrix_signal_homeserver_domain|regex_escape }}$'
      aliases:
      - exclusive: true
        regex: '^#signal_.+:{{ matrix_mautrix_signal_homeserver_domain|regex_escape }}$'
  url: {{ matrix_mautrix_signal_appservice_address }}
  sender_localpart: signalbot
  rate_limited: false
```

.. and modify that.

You can also modify the template and contribute your changes to us.. However, I'm still unsure whether and how we should act on it, given that manual action is required. And that it only affects a few people.

Seems like as soon as the Synapse bug (https://github.com/matrix-org/synapse/pull/5758) is resolved, we won't need some of these hacks anymore.

**Comment by tulir** [comment]
I don't think the synapse devs are interested in fixing bugs, so you should just apply the workaround for everyone. The manual action is probably not required anymore.

**Comment by tchapi** [comment]
@spantaleev, @tulir, again, let me reiterate a big thanks for your work on these subjects and the time you take to answer the community.

I'm forking this repo right now so I can make these change and make a PR asap

**Comment by spantaleev** [comment]
@tchapi, oh, sorry! I already discussed this with @tulir in our support room and made the changes myself.

Please give it a test!

**Comment by spantaleev** [comment]
f6097fb was a little broken, so I had to fix it up in e3290d8bc.

**Comment by tchapi** [comment]
No worries, you're faster than me 🥇 I'm testing this right now

**Comment by tchapi** [comment]
There's a little typo in the Telegram conf — one line removed instead of another. See my comments here: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/f6097fbba1fb1367bf18946f652cbbe79665233a

**Comment by spantaleev** [comment]
Fixed! Thanks! It should be good now

**Comment by theCalcaholic** [comment]
Thanks, everyone! That's great news :smiley:

**Comment by pimeys** [comment]
Thank you everybody. In the end I needed to clean the whole signal bridge from my server and reinstall. Just took some minutes of watching the text flow and some sql deleting the database until it started working. Now I have all messages nicely encrypted.

**Comment by luixxiul** [comment]
@pimeys 

> Thank you everybody. In the end I needed to clean the whole signal bridge from my server and reinstall. Just took some minutes of watching the text flow and some sql deleting the database until it started working. Now I have all messages nicely encrypted.

Mind letting me know how to delete and reinstall the signal bridge? Thanks!

**Comment by pimeys** [comment]
@luixxiul sure

First thing is to `logout` from your Signal session through the bot. I also deleted all my signal chats from Element, but I don't know is this necessary. 

Then, just comment out signal stuff from your `vars.yml`, deploy and stop the services:

```bash
> ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,stop
```

Ssh into your matrix server, connect to the database:

```bash
> /usr/local/bin/matrix-postgres-cli
```

In the database, delete the signal database and the user:

```sql
DROP DATABASE matrix_mautrix_signal;
DROP ROLE matrix_mautrix_signal;
```

Take away the comments from your `vars.yml` Signal setup. If not yet there, add the encryption configuration:

```yaml
matrix_mautrix_signal_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
```

Deploy and start the services:

```bash
> ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
```

When finished, the last thing (regarding the manual) should be to register the bot. I don't really know is this needed or if the playbook does it already, but it doesn't hurt to do this anyhow. First you need to cat the file `/matrix/mautrix-signal/bridge/registration.yaml` from the server. Get the value for `as_token`, and then from your `localhost` register the bot:

```bash
> curl -H "Authorization: Bearer <TOKEN>" -d '{"username": "signalbot"}' -X POST "https://<matrix_host>/_matrix/client/r0/register?kind=user"
```

Now just `link` your device through the signal bot and you should be ready to go.
