### ISSUE TITLE
3PID Login via LDAP Auth

### ISSUE THREAD

**Issue by RickStinson** [spantaleev/matrix-docker-ansible-deploy#856]
Hi,
i just installed everything, but 3PID Login is not working
- Login via samaccountname is working
- Searching for ldap user in element is working
- Login via E-Mail is not working
- profiles are not prefilled with mail and displayname

I read this manual: https://github.com/ma1uta/ma1sd/blob/master/docs/stores/ldap.md

What i'm missing? 
This is my LDAP configuration:

```
matrix_ma1sd_configuration_extension_yaml: |
  ldap:
    enabled: true
    connection:
      host: 10.11.12.13
      tls: false
      port: 389
      bindDn: cn=matrixaduser,ou=sub,DC=domain,DC=com
      bindPassword: 1234
      baseDNs: ['ou=sub,DC=domain,DC=com']
    attribute:
      uid:
        type: uid
        value: sAMAccountName
      name: 'cn'
      threepid:
        email:
          - 'mail'
        msisdn:
          - 'telephoneNumber'
```

Syslog says:  synapse.handlers.auth - 982 - WARNING - POST-27 - unknown 3pid identifier medium email, address 'my@mail.com'
