### ISSUE TITLE
Problem with domains: .promo, .wtf, .lib, .services and others etc.

### ISSUE THREAD

**Issue by m4rkell** [spantaleev/matrix-docker-ansible-deploy#860]
Found the following problem:
1. I used a non-standard domain, different from com, org and others. I took a thematic: promo, lib, wtf and etc. but i have error any time when start install.
When using the domains .promo, .wtf, and others, **when starting the installation, an error related** to the code in the file immediately appeared:

/roles/matrix-base/tasks/sanity_check.yml 

I had to delete these lines so that the installation would continue without errors.

```
- name: (Deprecation) Catch and report renamed settings
  fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'host_specific_hostname_identity', 'new': 'matrix_domain'}
    - {'old': 'hostname_identity', 'new': 'matrix_domain'}
    - {'old': 'hostname_matrix', 'new': 'matrix_server_fqn_matrix'}
    - {'old': 'hostname_riot', 'new': 'matrix_server_fqn_element'}
    - {'old': 'matrix_server_fqn_riot', 'new': 'matrix_server_fqn_element'}

- name: Fail if required variables are undefined
  fail:
    msg: "The `{{ item }}` variable must be defined and have a non-null value"
  with_items:
    - matrix_domain
    - matrix_server_fqn_matrix
    - matrix_server_fqn_element
  when: "item not in vars or vars[item] is none"
```

2. **When installing Dimension, there were problems**, the service did not turn on, all the time in the widget settings it was suggested to use the standard vector server. (install  from manual https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-dimension.md)
In the config, I added the url of the installed demises server like this:

```
matrix_dimension_integrations_ui_url: "https://dimension.example.com/element"
matrix_dimension_integrations_rest_url: "https://dimension.example.com/api/v1/scalar"
matrix_dimension_integrations_widgets_urls: ["https://dimension.example.com/widgets"]
matrix_dimension_integrations_jitsi_widget_url: "https://dimension.example.com/widgets/jitsi"
```

The server was displayed and started working in chats.
**Next there is a problem in the room with encryption**, when entering the Dimension settings, he writes that the integration is not encrypted, but the room is encrypted.

I think this is a bug. Domains are different, you need a more universal check.
