### ISSUE TITLE
matrix-reminder-bot: Unable to remove the reminder bot

### ISSUE THREAD

**Issue by MichaelSasser** [spantaleev/matrix-docker-ansible-deploy#887]
## Reproduce:
1. Use 41fd52f32730b77a416afe18851eb54b520ac719 (current `master` as of Fri, 19 Feb 2021 01:08:31 +0000)
2. Install reminder-bot with super secure password:

```yaml
matrix_bot_matrix_reminder_bot_enabled: true
matrix_bot_matrix_reminder_bot_matrix_user_id_localpart: reminderbot
matrix_bot_matrix_reminder_bot_matrix_user_password: pasword1
matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/Berlin
```

3. Remove the lines above from the host vars file
4. Deploy with tags: `all,start`
5. See error below:

```console
TASK [matrix-bot-matrix-reminder-bot : Ensure matrix-matrix-reminder-bot is stopped] ***
fatal: [matrix.myhost.tld]: FAILED! => changed=false
  msg: 'Could not find the requested service matrix-matrix-reminder-bot: host'
```

The Same error will occur, when only changing `matrix_bot_matrix_reminder_bot_enabled` to `false` and leaving in the rest.
If I enable the bot again, the playbook runs just fine (but will leave the bot "installed" as expected).

---

Thanks for the fine work, you and the other contributors did an amazing job!
