### ISSUE TITLE
User_directory not working

### ISSUE THREAD

**Issue by Unsourire** [spantaleev/matrix-docker-ansible-deploy#919]
I have installed the application with the  following configuration :
```
matrix_domain: xxx.xx
matrix_ssl_lets_encrypt_support_email: "admin@xx.xx"
matrix_coturn_turn_static_auth_secret: "xxxxxxxxxxxxx"
matrix_synapse_macaroon_secret_key: "xxxxxxxxx"
matrix_postgres_connection_password: "xxxxxxxxxxxxx"
matrix_synapse_admin_enabled: true

#multiconnexion
matrix_synapse_workers_enabled: true

#disable feder  tion
matrix_synapse_federation_enabled: false
#matrix_synapse_federation_port_enabled: false
matrix_nginx_proxy_proxy_matrix_federation_api_enabled: false

#ssl-certificates
matrix_nginx_proxy_enabled: false
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_base_domain_serving_enabled: true

matrix_synapse_enable_registration: true
matrix_synapse_retention_enabled: true
matrix_synapse_retention_default_policy_min_lifetime: 1d
matrix_synapse_retention_default_policy_max_lifetime: 2y
matrix_synapse_retention_allowed_lifetime_min: 1d
matrix_synapse_retention_allowed_lifetime_max: 2y
matrix_synapse_retention_purge_jobs_longest_max_lifetime: 3d
matrix_synapse_retention_purge_jobs_longest_max_lifetime_interval: 1d
matrix_synapse_retention_purge_jobs_shortest_max_lifetime: 3d
matrix_synapse_retention_purge_jobs_shortest_max_lifetime_interval: 1d
matrix_synapse_configuration_extension_yaml: |
  user_consent:
    policy_name: Privacy Policy
    template_dir: /data/res/templates/privacy
    version: 1.0
    form_secret: "ai1U]r1i"
  user_directory:
    enabled: true
    search_all_users: true
```
I use my own nginx web server, for the configuration i used the one include in the configuration folder.
I had in the configuration for allowing user search the following line in the configuration file :
```
user_directory:
    enabled: true
    search_all_users: true
```
When i want to search for a user, nothing is showed.
What do i have to insert for allowing the user_directory?
