### ISSUE TITLE
Reverse-proxying /.well-known/matrix/server with Traefik

### ISSUE THREAD

**Issue by gcaillaut** [spantaleev/matrix-docker-ansible-deploy#928]
Hi,

First, I’d like to thanks all the people who contributed to this project. Thank you all :)

So, here’s my issue.
I’m serving my matrix instance using this Ansible playbook and Traefik. Everything works like a charm, except that I can’t find a way to serve ` /.well-known/matrix/server`.

Let’s suppose that my matrix domain is mydomain.com. Then `matrix.mydomain.com/ /.well-known/matrix/server` serves the json file I expect. But I’d like this file to be served at, obviously, `mydomain.com/.well-known/matrix/server`.

I tried several configuration (well, only two).

First configuration:

```yaml
http:
  routers:
    matrix-federation:
      entryPoints:
        - websecure
      rule: Host(`mydomain.com`) && PathPrefix(`/.well-known/matrix`)
      service: matrix-federation
      # I also tried to use with the following
      # service: matrix-nginx-proxy@docker
      tls:
        certResolver: letsencrypt
        domains:
          - main: "mydomain.com"

  services:
    matrix-federation:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://matrix.mydomain.com
```

Second configuration, I’m trying to redirect the client on the right URL. It’s workish but I’m pretty sure it’s not the right solution…

```yaml
http:
  routers:
    matrix-federation:
      entryPoints:
        - websecure
      rule: Host(`mydomain.com`) && PathPrefix(`/.well-known/matrix`)
      service: noop@internal
      middlewares:
        - matrix-federation-redirect
      tls:
        certResolver: letsencrypt
        domains:
          - main: "mydomain.com"

  middlewares:
    matrix-federation-redirect:
      redirectRegex:
        regex: "^https://example.com/(.*)"
        replacement: "https://matrix.example.com/${1}"
```

But nothing work… And I can’t find documentation for this setup :(
Au secours !

**Comment by hungrymonkey** [comment]
May I ask how you serve your main website? Are you hosting your website statically like cloudflair or amazon s3 bucket? You can configure the s3 endpoint with the configuration below

https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html

```
[
    {
        "Condition": {
            "KeyPrefixEquals": ".well-known/matrix/client"
        },
        "Redirect": {
            "HostName": "matrix.domain.com",
            "Protocol": "https",
            "ReplaceKeyWith": ".well-known/matrix/client"
        }
    },
    {
        "Condition": {
            "KeyPrefixEquals": ".well-known/matrix/server"
        },
        "Redirect": {
            "HostName": "matrix.domain.com",
            "Protocol": "https",
            "ReplaceKeyWith": ".well-known/matrix/server"
        }
    }
]
```

**Comment by MTRNord** [comment]
Not sure how much this helps but this is what I do https://dashboard-new.nordgedanken.dev/dashboard/#/http/routers/well-known@file

(not the config on purpose as a) I use toml and b) mine is a bit messy on the code side)

**Comment by GaaH** [comment]
Thank you, I checked your configuration and I was able to solve my problem. Actually it was quite simple:

```yaml
http:
  routers:
    matrix-federation:
      entryPoints:
        - websecure
      rule: Host(`example.com`) && PathPrefix(`/.well-known/matrix/`)
      service: matrix-nginx-proxy@docker
      middlewares:
        - matrix-federation-headers
      tls:
        certResolver: letsencrypt
        domains:
          - main: "example.com"

  middlewares:
    matrix-federation-headers:
      headers:
        customRequestHeaders:
          Host: matrix.example.com
          # Not sur if the following is required
          X-Forwwarded-Host: matrix.example.com
        customResponseHeaders:
          Content-Type: application/json
```

But now I have other problems. Element is having CORS errors and is not able to reach my matrix domain. I tried adding `--label "traefik.http.middlewares.matrix-nginx-proxy.headers.accesscontrolalloworigin=*"` in both `matrix_nginx_proxy_container_extra_arguments` and `matrix_synapse_container_extra_arguments` (in vars.yml), but it doesn’t work… Any clue on how to fix this?
